### ISSUE TITLE
Redesign how to handle global/parent scope variables

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1059]
## Current State

Currently we have an ASR pass that determines which variables are being accessed from the parent scope, and hands over this information to the LLVM backend in forms of internal compiler data structures (not via ASR). The LLVM backend then uses this information to create global structs with the correct context to handle the access to parent scope variables.

This has two issues:

1. handing over information separately from ASR is not a clean design; all the information should be passed as ASR; The justification in this case is that the ASR pass is only used by the backend, to help it figure out some information. But that means the ASR is badly designed: it should be designed in such a way so that the backend only needs a single pass to generate correct code.

2. It makes the backend more complex.

## Better Design

First, we will add a new member to Function called "capture", which will store all parent scope variables that the function accesses, to make this explicit.

Then we will create two ASR passes, which implement this feature in two different ways, each has pros and cons, and the backend or user can choose.

### ASR pass global context

This ASR pass would do the equivalent of what we currently do in the backend, but it would do it at the ASR level explicitly. So it would promote all captured variables into global structs at ASR level. The backends would then not need to do anything special; the only feature they would need is to access a global function, but nothing else (no worry about nested scopes).

This pass doesn't require access to all the source code.

An example from minpack:

```diff
--- a/examples/example_primes.f90
+++ b/examples/example_primes.f90
@@ -5,6 +5,8 @@ public dp
 
 integer, parameter :: dp=kind(0d0)
 
+! here we will create a "global" module variable to handle the "expr" handover
+
 end module
 
 module find_fit_module
@@ -47,8 +49,7 @@ n = size(pars)
 allocate(wa(m*n + 5*n + m))
 call lmdif1(fcn, m, n, pars, fvec, tol, info, iwa, wa, size(wa))
 if (info /= 1) stop "failed to converge"
-
-contains
+end subroutine
 
 subroutine fcn(m, n, x, fvec, iflag)
 integer, intent(in) :: m, n, iflag
@@ -59,8 +60,6 @@ fvec(1) = iflag
 fvec = data_y - expr(data_x, x)
 end subroutine
 
-end subroutine
-
 end module
```

### ASR pass promote captured arguments into regular arguments

This is pass would promote all captured arguments into actual arguments; this pass requires access to all the code stack that contains the given callback, and it would extend all declaration and callsite with those arguments. If there are multiple callbacks with different arguments, then this ASR pass must decide whether to duplicate code, or do a superset of all arguments. The big advantage of this pass is that it doesn't access any global variables or state, every function becomes "pure", so potentially faster and thread safe. The downside is that you must have access to all the code, and it might be potentially harder to implement. We should implement this pass, but we will choose between this pass and the previous pass, the user can select using a command line option, or something like that.

**Comment by Smit-create** [comment]
In order to make the current approach of `nested_vars` more generalized we can follow the 1st design with the following modifications:
1. Add an argument: bool `save_nested_call_out_context` in Function ASR node.
2. Add an argument: symbol* `nested_required_globals` in the Module ASR node.
3. Add an argument: symbol* `nested_functions` in the Function ASR node.
4. Add an argument: ASR::ttype* `nested_vars_types` in the Function ASR node.

The above modifications and reimplementing the `nested_vars` pass to be ASR explicit will solve the generalizing issues.

What do you think @certik?

**Comment by certik** [comment]
The 1st design would work like this. Starting point:
```fortran
module find_fit_module

! This module contains a general function find_fit() for a nonlinear least
! squares fitting. The function can fit any nonlinear expression to any data.

use minpack, only: lmdif1
use types, only: dp
implicit none
private
public find_fit

contains

subroutine find_fit(data_x, data_y, expr, pars)
! Fits the (data_x, data_y) arrays with the function expr(x, pars).
! The user can provide any nonlinear function 'expr' depending on any number of
! parameters 'pars' and it must return the evaluated expression on the
! array 'x'. The arrays 'data_x' and 'data_y' must have the same
! length.
real(dp), intent(in) :: data_x(:), data_y(:)
interface
    function expr(x, pars) result(y)
    use types, only: dp
    implicit none
    real(dp), intent(in) :: x(:), pars(:)
    real(dp) :: y(size(x))
    end function
end interface
real(dp), intent(inout) :: pars(:)

real(dp) :: tol, fvec(size(data_x))
integer :: iwa(size(pars)), info, m, n
real(dp), allocatable :: wa(:)

tol = sqrt(epsilon(1._dp))
m = size(fvec)
n = size(pars)
allocate(wa(m*n + 5*n + m))
call lmdif1(fcn, m, n, pars, fvec, tol, info, iwa, wa, size(wa))
if (info /= 1) stop "failed to converge"

contains

subroutine fcn(m, n, x, fvec, iflag)
integer, intent(in) :: m, n, iflag
real(dp), intent(in) :: x(n)
real(dp), intent(out) :: fvec(m)
! Suppress compiler warning:
fvec(1) = iflag
fvec = data_y - expr(data_x, x)
end subroutine

end subroutine

end module
```
And the ASR->ASR pass would transform this into:
```fortran
module @lcompilers_fcn_context

real(dp) :: @data_x(:), @data_y(:)
interface
    function expr_t(x, pars) result(y)
    use types, only: dp
    implicit none
    real(dp), intent(in) :: x(:), pars(:)
    real(dp) :: y(size(x))
    end function
end interface
procedure(expr_t) :: @expr

end module

module find_fit_module

! This module contains a general function find_fit() for a nonlinear least
! squares fitting. The function can fit any nonlinear expression to any data.

use minpack, only: lmdif1
use types, only: dp
implicit none
private
public find_fit

contains

subroutine find_fit(data_x, data_y, expr, pars)
! Fits the (data_x, data_y) arrays with the function expr(x, pars).
! The user can provide any nonlinear function 'expr' depending on any number of
! parameters 'pars' and it must return the evaluated expression on the
! array 'x'. The arrays 'data_x' and 'data_y' must have the same
! length.
use @lcompilers_fcn_context, only: @data_x, @data_y, @expr
real(dp), intent(in) :: data_x(:), data_y(:)
interface
    function expr(x, pars) result(y)
    use types, only: dp
    implicit none
    real(dp), intent(in) :: x(:), pars(:)
    real(dp) :: y(size(x))
    end function
end interface
real(dp), intent(inout) :: pars(:)

real(dp) :: tol, fvec(size(data_x))
integer :: iwa(size(pars)), info, m, n
real(dp), allocatable :: wa(:)

tol = sqrt(epsilon(1._dp))
m = size(fvec)
n = size(pars)
allocate(wa(m*n + 5*n + m))
@data_x = data_x
@data_y = data_y
@expr = expr
call lmdif1(fcn, m, n, pars, fvec, tol, info, iwa, wa, size(wa))
! In this case these are intent(in), so they cannot be modified, but in general we would have to do:
data_x = @data_x
data_y = @data_y
if (info /= 1) stop "failed to converge"
end subroutine

subroutine fcn(m, n, x, fvec, iflag)
use @lcompilers_fcn_context, only: @data_x, @data_y, @expr
integer, intent(in) :: m, n, iflag
real(dp), intent(in) :: x(n)
real(dp), intent(out) :: fvec(m)
! Suppress compiler warning:
fvec(1) = iflag
fvec = @data_y - @expr(@data_x, x)
end subroutine

end module
```

**Comment by certik** [comment]
The first approach "ASR pass global context" has now been implemented in https://github.com/lfortran/lfortran/pull/1464 and https://github.com/lfortran/lfortran/pull/1523 thanks to @Smit-create, thank you!

The second approach "ASR pass promote captured arguments into regular arguments" might possibly even be implemented as a pass that takes the result of the current "nested_functions" pass, so global variables in a module, and tries to promote the global variables into explicit function arguments. We can think about this and do this much later, the current design is very good, it unblocked us.

**Comment by certik** [comment]
See also https://github.com/lfortran/lfortran/issues/1510#issuecomment-1500968593 about eliminating some of the copies to and from globals.

**Comment by certik** [comment]
The nested functions work pretty well now, so I am going to close this issue as fixed.

We can much later implement lifting the global variables into function arguments, I created a dedicated issue for this at https://github.com/lfortran/lfortran/issues/1906.
