### ISSUE TITLE
Parser: allow a program without the program line

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1076]
The main two tests are:
```
print *, "OK"
end
```
and
```
print *, "OK"
end program
```

The rest I think will start working, but we should test, including:
```
      subroutine sub (); end subroutine; integer i
      end program
```
and
```
      subroutine sub (); end subroutine; integer i
      end
```

**Comment by certik** [comment]
The first test gives:
```console
$ lfortran --show-ast c.f90
(TranslationUnit [(Print 0 () [(String "OK")] ()) end])
```
It treats "end" as a variable. The second test gives:
```console
$ lfortran --show-ast d.f90 --indent
syntax error: Token 'end program' is unexpected here
 --> d.f90:2:1
  |
2 | end program
  | ^^^^^^^^^^^ 
```

**Comment by certik** [comment]
People keep hitting this bug, so I am rising it to high priority.

To get started on a fix, let's do the following: If the last AST node after parsing is an "end" expression (we have to skip any modules / procedures after the "end" correctly), simply insert "program test" at the beginning (after all procedures / modules) and reparse.

This is slow, but should fix most of these issues that people hit. The best would be to figure this out in the Bison parser, but I have not figured out how. We can also try in the tokenizer. The fixed-form tokenizer doesn't have this problem, since it is a recursive descent parser, but it is also slow.

**Comment by certik** [comment]
I think if we can parse this reasonably robustly, then that should be good enough for now:
```fortran
subroutine x
end subroutine

call y
end

subroutine y
print *, "x"
end subroutine
```
The AST prints:
```console
$ lfortran --show-ast a.f90
(TranslationUnit
    [(Subroutine
        x
        []
        []
        ()
        (TriviaNode
            []
            [(EndOfLine)
            (EndOfLine)]
        )
        []
        []
        []
        []
        []
        []
    )
    (SubroutineCall
        0
        y
        []
        []
        []
        ()
    )
    end
    (Subroutine
        y
        []
        []
        ()
        ()
        []
        []
        []
        []
        [(Print
            0
            ()
            [(String
                "x"
            )]
            ()
        )]
        []
    )]
)
```
One option is to use "fmt", but we would still need to somehow locate the place to insert "program main". Or probably more robust is to traverse this AST and find the first non-subroutine non-module statement, and use its location information to find the line, then take the original source code and insert it there.

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lfortran/lfortran/pull/1750 seems to be more of a temporary fix. In the longer term, I think we might need to incorporate supporting programs without program line in the LFortran grammar. Since, LFortran supports interactive execution which needs the interactive grammar, I think we would have conflicts between the interactive grammar and the regular grammar when trying to support programs without program line.

One of the ways to solve it could be to have different parsers for interactive execution and regular execution. As discussed with Dr. Ondrej, the drawback here is that it doubles our testing efforts as both the parsers/grammars need to be thoroughly tested.

It seems one of the ways to distinguish between regular grammar/parsing and interactive grammar/parsing could be to have dummy (lookahead) keyword in the LFortran grammar for interactive rules.

For example:
```bash
$ git diff
diff --git a/src/lfortran/fortran_evaluator.cpp b/src/lfortran/fortran_evaluator.cpp
index 76153c31c..dd3229791 100644
--- a/src/lfortran/fortran_evaluator.cpp
+++ b/src/lfortran/fortran_evaluator.cpp
@@ -76,9 +76,10 @@ Result<FortranEvaluator::EvalResult> FortranEvaluator::evaluate(
 #ifdef HAVE_LFORTRAN_LLVM
     EvalResult result;
 
+    const std::string code = "[" + code_orig + "]";
     // Src -> AST
     Result<LFortran::AST::TranslationUnit_t*> res = get_ast2(
-        code_orig, lm, diagnostics);
+        code, lm, diagnostics);
     LFortran::AST::TranslationUnit_t* ast;
     if (res.ok) {
         ast = res.result;
diff --git a/src/lfortran/parser/parser.yy b/src/lfortran/parser/parser.yy
index 83ab8ba69..abae0232e 100644
--- a/src/lfortran/parser/parser.yy
+++ b/src/lfortran/parser/parser.yy
@@ -562,7 +562,7 @@ void yyerror(YYLTYPE *yyloc, LCompilers::LFortran::Parser &p,
 %precedence UMINUS
 %right "**"
 
-%start units
+%start lfortran_grammar
 
 %%
 
@@ -575,6 +575,34 @@ void yyerror(YYLTYPE *yyloc, LCompilers::LFortran::Parser &p,
 
 // Higher %dprec means higher precedence
 
+lfortran_grammar
+    : regular_grammar
+    | interactive_grammar
+    ;
+
+regular_grammar
+    : units
+    ;
+
+interactive_grammar
+    : "[" interactive_rules "]"
+    ;
+
+interactive_rules
+    : module
+    | submodule
+    | block_data
+    | subroutine
+    | procedure
+    | function
+    | use_statement
+    | implicit_statement
+    | var_decl
+    | statement
+    | expr sep
+    ;
+
+
 units
     : units script_unit  %dprec 9  { RESULT($2); }
     | script_unit        %dprec 10 { RESULT($1); }
@@ -589,11 +617,6 @@ script_unit
     | subroutine
     | procedure
     | function
-    | use_statement
-    | implicit_statement
-    | var_decl
-    | statement          %dprec 7
-    | expr sep           %dprec 8
     ;
 
 // ----------------------------------------------------------------------------
```

**Comment by certik** [comment]
This is now fixed by https://github.com/lfortran/lfortran/pull/1750, all the above examples should work now.
