### ISSUE TITLE
"Check Production codes with LFortran" failing on `main` branch

### ISSUE THREAD

**Issue by czgdp1807** [lfortran/lfortran#1082]
Please see https://github.com/lfortran/lfortran/actions/runs/3643105944/jobs/6150968034. This is affecting other PRs as well. I don't know how to fix it.

cc: @certik

**Comment by certik** [comment]
I know. I think GFortran got updated, and it now fails to compile SciPy. We either have to find the correct command line option, or just disable the gfortran line.

**Comment by Smit-create** [comment]
Should we try with this `-fallow-argument-mismatch`?
