### ISSUE TITLE
[SciPy] ASR verify pass error

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1085]
```fortran
      DOUBLE PRECISION FUNCTION dinvnr(p,q)

      DOUBLE PRECISION r2pi
      PARAMETER (r2pi=0.3989422804014326D0)
      DOUBLE PRECISION nhalf
      PARAMETER (nhalf=-0.5D0)

      DOUBLE PRECISION dennor,x

      dennor(x) = r2pi*exp(nhalf*x*x)


      END
```
The above code when compiled using `lfortran --fixed-form --implicit-typing --allow-implicit-interface --show-asr /home/pranavchiku/scipy/scipy/special/cdflib/dinvnr2.f` throws the following error

```
ASR verify pass error: ASR verify: Function dennor depends on exp@dexp but isn't found in its dependency list.
  --> /home/pranavchiku/scipy/scipy/special/cdflib/dinvnr2.f:10:7
   |
10 |       dennor(x) = r2pi*exp(nhalf*x*x)
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ failed here
```

**Comment by gptsarthak** [comment]
Running ```(base) sarthak@pop-os:~/scipy/scipy/special/cdflib$ lfortran --show-asr --fixed-form --implicit-typing --implicit-interface dinvnr.f``` produces the ASR for me.
I assume your ```dinvnr2.f``` file is just a copy of the ```dinvnr.f``` file.
I tried running the minimal code you provided but it gave me ```AssertFailed: t.cur < end``` error.

**Comment by Pranavchiku** [comment]
The error you reported is assert failure while parsing, it is generating ASR for me in both fixed and free form.
