### ISSUE TITLE
Implement ``present``

### ISSUE THREAD

**Issue by czgdp1807** [lfortran/lfortran#1111]
As far as I know ``present`` is a feature for functions in Fortran source code (i.e., `Source` ABI) and is applicable to optional arguments. So I list the following approaches for implementing it in LFortran,

1. **Pass bits for each optional argument** - Consider the function is `f(a, b, c)` where `b` and `c` are specified as optional arguments. So we will write an ASR pass which will convert `f(a, b, c)` to `f(a, b, is_b_present, c, is_c_present)` where `is_b_present` and `is_c_present` are simply the bits which will be `true` if the associated argument is present and `false` if not. And inside the function body calls like `present(b)` will be replaced by `is_b_present`. The calls to function `f` will also be modified accordingly. Like `f(a, b)` will become, `f(a, b, true, c, false)`. Everything will be done at ASR level, no modifications in any of the backends. This is the same pattern as `pass_array_by_data` so we have the infrastructure for this already.
2. **Pass arguments by pointer and set non-present to nullptr** - In this approach we don't touch the ASR, just in LLVM backend, convert calls like `f(a, b)` to `f(a, b, nullptr)` and whenever we encounter `present(c)`, replace it with `c == nullptr`. This approach depends on the fact we pass argument by pointers.

In my opinion first approach is robust and adds the feature to all the backends simultaneously (so I favour it). The second approach is limited to LLVM backend and also very risky (because of the nullptr checks and involvement of nullptr brings the risk of frequent segmentation faults as well).

**Comment by czgdp1807** [comment]
cc: @certik

**Comment by certik** [comment]
I thought we already use a pointer in ASR to determine if the argument is present for a function call.

The first approach seems cleaner, so you can go ahead and try it.
