### ISSUE TITLE
Can lfortran generate LLVM IR or not？

### ISSUE THREAD

**Issue by if362005** [lfortran/lfortran#1114]
Can lfortran generate the files which is same as **.ll or **.bc ?

**Comment by Thirumalai-Shaktivel** [comment]
Yup, you can use `--show-llvm` option to show the llvm IR:
```console
$ lfortran --show-llvm a.f90
```
To write into a file use:
```console
$ lfortran --show-llvm a.f90 > a.ll
```

**Comment by certik** [comment]
@if362005 thanks for the question. As @Thirumalai-Shaktivel answered with examples, the answer is yes, LFortran can generate LLVM IR.
