### ISSUE TITLE
Compile modern Minpack

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1241]
Repository: https://github.com/fortran-lang/minpack/

Repository used at CI: https://github.com/Pranavchiku/modern_minpack

Main file: https://github.com/fortran-lang/minpack/blob/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/src/minpack.f90

Tests: https://github.com/fortran-lang/minpack/tree/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/test

We already support the legacy Minpack (https://github.com/lfortran/lfortran/issues/512), and to compile the modernized version we just have to implement a few missing features, it does not seem it will be very complicated. 

### AST -> ASR
- [x] #1246 
- [x] https://github.com/lfortran/lfortran/issues/1247
- [x] #1259
- [x] #1262
-----
### ASR -> LLVM
- [x] #1265 
- [x] #1266
- [x] #1293
- [x] #1445

-----
### Compilation progress
* [x] `minpack_module` to `.mod` file (no LLVM)
* [x] [tests](https://github.com/fortran-lang/minpack/tree/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/test) ( AST  -> ASR )
* [ ] [test_hybrd.f90](https://github.com/fortran-lang/minpack/blob/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/test/test_hybrd.f90) to a binary (ASR->LLVM)
     * [x] #1312 ( AST -> ASR )
     * [x] #1316 ( ASR -> LLVM )
     * [x] #1347 ( ASR -> LLVM )
     * [x] #1349 ( ASR -> LLVM )
     * [x] #1353 ( ASR -> LLVM )
     * [x] #1358 ( ASR -> LLVM )
     * [ ] #1362 ( ASR -> LLVM )
     * [x] #1369 ( ASR -> LLVM )
     * [ ] #1563
     * [x] #1564
* [x] [example_hybrd.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_hybrd.f90)
   - [Output Gist](https://gist.github.com/Pranavchiku/b34b2ecb3de3b06a9b7b64e4296b1789)
* [x] [example_hybrd1.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_hybrd1.f90)
   - [Output Gist](https://gist.github.com/Pranavchiku/199fd383ac5bca5c875e78c363001e61)
* [x] [example_lmdif1.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_lmdif1.f90)
   - [Output gist](https://gist.github.com/Pranavchiku/c9d727ba1f77037465f16b275c19279c)
   * [x] #1395  
   * [x] #1402
* [x] [example_lmder1.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_lmder1.f90)
   * [x] Using diff in [comment](https://github.com/lfortran/lfortran/issues/1241#issuecomment-1492855351): [output_gist](https://gist.github.com/Pranavchiku/60006c297f6e05d491b16f21f21ed06e)
   * [x] #1150 
* [ ] [example_primes.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_primes.f90)
   * [x] #1477
   * [x] #1486 
   * [x] #1488 
   * [ ] #1506
   * [x] #1516
   * [x] #1518 
   * [x] #1522
   * [x] #1555
   * [ ] #1556
   * [x] #1559
   * [ ] #1573

--------

* [ ] Write a blog post, together with Legacy minpack: https://github.com/lfortran/lfortran/issues/512

**Comment by Pranavchiku** [comment]
With #1261, and using some workarounds for #1246, #1247 we get [minpack.f90]( https://github.com/fortran-lang/minpack/blob/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/src/minpack.f90) compile to ASR.

**Comment by certik** [comment]
Awesome, that's easier than I thought, let's keep pushing until it fully works.

**Comment by Pranavchiku** [comment]
With #1297, lfortran compiles [minpack.f90]( https://github.com/fortran-lang/minpack/blob/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/src/minpack.f90)  to LLVM!

**Comment by Pranavchiku** [comment]
With workaround for #1312, all [modern_minpack/tests](https://github.com/fortran-lang/minpack/tree/c0b5aea9fcd2b83865af921a7a7e881904f8d3c2/test) compile to ASR!

**Comment by certik** [comment]
@jacobwilliams almost done!

**Comment by certik** [comment]
@Pranavchiku very good!

#1370 is merged, so we just have three small workarounds, I am not worried about those.

Let's focus on correct results now. Do the examples run and do they differ from GFortran?

**Comment by Pranavchiku** [comment]
> Do the examples run and do they differ from GFortran?

I will have to check that, focusing on examples now.

**Comment by Pranavchiku** [comment]
3 out of 5 tests compile without any workarounds, [example_lmder1.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_lmder1.f90) uses intrinsic `any` which compiles using a small workaround. [example_primes.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_primes.f90) is a bit tricky, looking into it now.

**Comment by Pranavchiku** [comment]
Output of [example_hybrd.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_hybrd.f90) align GFortran bit by bit!

**Comment by certik** [comment]
Can you post output of gfortran and lfortran, into a gist and link it here for reference?

**Comment by Pranavchiku** [comment]
> GFortran

```console
example_hybrd
     FINAL L2 NORM OF THE RESIDUALS  0.1192636D-07

     NUMBER OF FUNCTION EVALUATIONS        14

     EXIT PARAMETER                         1

     FINAL APPROXIMATE SOLUTION

      -0.5706545D+00 -0.6816283D+00 -0.7017325D+00
      -0.7042129D+00 -0.7013690D+00 -0.6918656D+00
      -0.6657920D+00 -0.5960342D+00 -0.4164121D+00
```

> LFortran

```console
$ lfortran --implicit-typing --implicit-interface /home/pranavchiku/Desktop/minpack/examples/example_hybrd.f90
FINAL L2 NORM OF THE RESIDUALS 1.19263583475980921e-08 NUMBER OF FUNCTION EVALUATIONS 14 EXIT PARAMETER 1 FINAL APPROXIMATE SOLUTION

-5.70654511600659053e-01
-6.81628342291230593e-01
-7.01732452563471165e-01
-7.04212940083752348e-01
-7.01369047627288800e-01
-6.91865643379914186e-01
-6.65792012154689195e-01
-5.96034201280816633e-01
-4.16412062998471999e-01
```

**Comment by Pranavchiku** [comment]
Output of [example_hybrd1.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_hybrd1.f90) aligns too!

**Comment by Pranavchiku** [comment]
> GFortran

```console
example_hybrd1
     FINAL L2 NORM OF THE RESIDUALS  0.1192636D-07

     EXIT PARAMETER                         1

     FINAL APPROXIMATE SOLUTION

      -0.5706545D+00 -0.6816283D+00 -0.7017325D+00
      -0.7042129D+00 -0.7013690D+00 -0.6918656D+00
      -0.6657920D+00 -0.5960342D+00 -0.4164121D+00
```

> LFortran

```console
$ lfortran --implicit-typing --implicit-interface /home/pranavchiku/Desktop/minpack/examples/example_hybrd1.f90
FINAL L2 NORM OF THE RESIDUALS 1.19263583475980921e-08 EXIT PARAMETER 1 FINAL APPROXIMATE SOLUTION

-5.70654511600659053e-01
-6.81628342291230593e-01
-7.01732452563471165e-01
-7.04212940083752348e-01
-7.01369047627288800e-01
-6.91865643379914186e-01
-6.65792012154689195e-01
-5.96034201280816633e-01
-4.16412062998471999e-01
```

**Comment by certik** [comment]
Can you post exact instructions how you compile it? Let me try it myself.

**Comment by Pranavchiku** [comment]
For `example_hybrd.f90` it looks like this assuming you are in `minpack/examples/` directory
```sh
gfortran -c ../src/minpack.f90
gfortran -c example_hybrd.f90 -I.
gfortran example_hybrd.o minpack.o -o example_hybrd -I.
./example_hybrd
```

**Comment by certik** [comment]
Perfect. Which exact branch (commit) of Minpack do you use? I think we still need some workarounds in the Minpack source code.

**Comment by Pranavchiku** [comment]
Actually all changes are on my local device, if you want I can push it all up on fork?

**Comment by certik** [comment]
Yes, please fork the repository and push it into your own fork/branch. Then send instructions and I'll try it.

**Comment by Pranavchiku** [comment]
https://github.com/Pranavchiku/modern_minpack
You may use this, I directly cloned the repository so I was unable to push changes to fork hence made a new repo with instructions on compilation in readme, I hope it helps.

**Comment by certik** [comment]
Perfect, will try soon. Btw, `--implicit-typing --implicit-interface` shouldn't be needed for the modern code.

**Comment by Pranavchiku** [comment]
With #1424 output of LFortran and GFortran aligns for [example_lmdif1.f90](https://github.com/fortran-lang/minpack/blob/main/examples/example_lmdif1.f90)! Here is the [Output gist](https://gist.github.com/Pranavchiku/c9d727ba1f77037465f16b275c19279c)

**Comment by certik** [comment]
Here is how to compile it:
```console
$ git clone https://github.com/Pranavchiku/modern_minpack.git
$ cd modern_minpack
$ git checkout 02ceb93e0d63fab9166122c0da4a5156ad521d7c
$ lfortran -c ./src/minpack.f90 -o minpack.o
$ lfortran examples/example_hybrd.f90
$ lfortran examples/example_hybrd1.f90
$ lfortran examples/example_lmdif1.f90
$ lfortran test/test_hybrd.f90 
```
There are some issues such as the file `test/test_hybrd.f90` has some empty program at the end, which is not there in the upstream minpack.

**Comment by certik** [comment]
One can compile using fpm as follows:
```
$ FPM_FC=lfortran fpm build
minpack.f90                            done.
libminpack.a                           done.
example_hybrd.f90                      done.
example_hybrd1.f90                     done.
example_lmder1.f90                     done.
example_lmdif1.f90                     done.
example_hybrd
[hang]
```
I had to remove some files that we can't compile yet. The last file hangs, because `fpm` executes:
```
 + lfortran  -I./include  build/lfortran_521640BEBB1444E2/minpack/examples_example_hybrd.f90.o build/lfortran_521640BEBB1444E2/minpack/libminpack.a -o build/lfortran_521640BEBB1444E2/example/example_hybrd
```
Which launches the interactive shell. I think we have to improve our main driver to call a linker here.

**Comment by Pranavchiku** [comment]
> There are some issues such as the file test/test_hybrd.f90 has some empty program at the end, which is not there in the upstream minpack

Aah yes, I might have forgot to remove it.

**Comment by certik** [comment]
We can setup a CI to test what already works.

Let's see if we can change the code with some workarounds so that it fully compiles and runs correctly for all examples. We might be very close.

Then we will focus on fixing the individual bugs and removing the workarounds.

**Comment by Pranavchiku** [comment]
With the following diff I am able to get output bit to bit aligned with GFortran: [output_gist](https://gist.github.com/Pranavchiku/60006c297f6e05d491b16f21f21ed06e)
```diff
diff --git a/examples/example_lmder1.f90 b/examples/example_lmder1.f90
index 4c5642f..916b805 100644
--- a/examples/example_lmder1.f90
+++ b/examples/example_lmder1.f90
@@ -13,11 +13,32 @@ integer :: info
 real(wp) :: tol, x(n), fvec(m), fjac(m,n)
 integer :: ipvt(n)
 real(wp) :: wa(lwa)
+integer :: iflag, i
+real(wp) :: xp(n), fvecp(m), err(m)
 
 ! The following starting values provide a rough fit.
 x = [1.0_wp, 1.0_wp, 1.0_wp]
+fvec = 1.0_wp
+
+! call check_deriv()
+
+call chkder(m, n, x, fvec, fjac, m, xp, fvecp, 1, err)
+iflag = 1
+call fcn(m, n, x, fvec, fjac, m, iflag)
+iflag = 2
+call fcn(m, n, x, fvec, fjac, m, iflag)
+iflag = 1
+call fcn(m, n, xp, fvecp, fjac, m, iflag)
+call chkder(m, n, x, fvec, fjac, m, xp, fvecp, 2, err)
+
+write(nwrite, '(a)') 'Derivatives check (1.0 is correct, 0.0 is incorrect):'
+write(nwrite,'(1p,(5x,3d15.7))') err
+do i = 1, size(err)
+    if (abs(err(i)-1.0_wp) > epsilon(1.0_wp)) then
+        error stop 'Derivative check failed'
+    end if
+end do
 
-call check_deriv()
```

**Comment by certik** [comment]
Excellent, let's commit it to your repository and update CI to run this test. Also add tests in the form `if ((abs(x)-34.4) > 1e-15) error stop`.

**Comment by certik** [comment]
TODO:
* [ ] Let's figure out clean workaround commits in the w2 branch (https://github.com/Pranavchiku/modern_minpack/tree/w2) to get `example_primes.f90` working.
* [ ] Let's figure out clean workaround commits for `test/test_hybrd.f90`

**Comment by certik** [comment]
@jacobwilliams, I think we have it:
```console
$ git clone https://github.com/fortran-lang/minpack
$ cd minpack
$ lfortran -c src/minpack.f90
$ lfortran examples/example_hybrd.f90
FINAL L2 NORM OF THE RESIDUALS 1.19263583475980921e-08 NUMBER OF FUNCTION EVALUATIONS 14 EXIT PARAMETER 1 FINAL APPROXIMATE SOLUTION

-5.70654511600659053e-01
-6.81628342291230593e-01
-7.01732452563471165e-01
-7.04212940083752348e-01
-7.01369047627288800e-01
-6.91865643379914186e-01
-6.65792012154689195e-01
-5.96034201280816633e-01
-4.16412062998471999e-01
$ lfortran examples/example_lmder1.f90
Derivatives check (1.0 is correct, 0.0 is incorrect):
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00
1.00000000000000000e+00

FINAL L2 NORM OF THE RESIDUALS 9.06359603390466673e-02 EXIT PARAMETER 1 FINAL APPROXIMATE SOLUTION

8.24105765758333941e-02
1.13303665347150440e+00
2.34369463894115393e+00
$ lfortran examples/example_lmdif1.f90
FINAL L2 NORM OF THE RESIDUALS 9.06359603390476665e-02 EXIT PARAMETER 1 FINAL APPROXIMATE SOLUTION

8.24105772024121969e-02
1.13303667706272582e+00
2.34369461611932239e+00
$ lfortran examples/example_hybrd1.f90 
FINAL L2 NORM OF THE RESIDUALS 1.19263583475980921e-08 EXIT PARAMETER 1 FINAL APPROXIMATE SOLUTION

-5.70654511600659053e-01
-6.81628342291230593e-01
-7.01732452563471165e-01
-7.04212940083752348e-01
-7.01369047627288800e-01
-6.91865643379914186e-01
-6.65792012154689195e-01
-5.96034201280816633e-01
-4.16412062998471999e-01
```

We still need to harden it and get more examples and tests working. But it clearly works.

**Comment by certik** [comment]
I am going to close this issue, we test it at CI. If there are any bugs, we'll open new issues for this.
