### ISSUE TITLE
Bug in private

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1249]
```fortran
module foo1
private
end module

module foo2
real :: y = 2
end module

program test
use foo2
print *, y
end program
```
This gives:
```console
 $ lfortran y.f90
semantic error: Variable 'y' is not declared
  --> y.f90:11:10
   |
11 | print *, y
   |          ^ 'y' is undeclared
```
And the reason is that the first "private" sets the private visitor flag, but then it does not get reset in the module "foo2", so "y" ends up being private and does not (correctly) get imported by `use foo2`.

The fix is to reset the private flag to be the default public for the module foo2, and this example should compile and run.

**Comment by Pranavchiku** [comment]
"y" should be private right? 
and in implementation it every time checks if its "access" is "Public" for every variable, if yes then adds as an external symbol.

**Comment by Pranavchiku** [comment]
>And the reason is that the first "private" sets the private visitor flag, but then it does not get reset in the module "foo2", so "y" ends up being private and does not (correctly) get imported by use foo2.

In #1245, I checked if `Variable_t->m_access = Public` if yes, then declare ut as external symbol, else don't. Problem here is that while declaration of module "y" is treated as private variable, but if I am correct then it must be declared as "Public".  Fixing it will work.

**Comment by certik** [comment]
"y" in `foo2` should be public (the default).
