### ISSUE TITLE
The converted f90 code shows error The function result on the lhs of the assignment at (1) must have the pointer attribute.

### ISSUE THREAD

**Issue by xichaoqiang** [lfortran/lfortran#1301]
The f code can convert to f90 code. But it can't compile by gfortran.
 
[phs3sQx-HoV.zip](https://github.com/lfortran/lfortran/files/10732168/phs3sQx-HoV.zip)
![image](https://user-images.githubusercontent.com/30900789/218735005-5d48ab0f-d094-4306-b38f-c16723642f8b.png)

**Comment by xichaoqiang** [comment]
My lfortran version is download from anaconda. Is there any new version can fix this problem?

**Comment by certik** [comment]
@xichaoqiang thanks for the bug report! Can you please try the latest version from master? If you want to help get this fixed sooner, here are the steps:

* [ ] see if this error happen in the latest master
* [ ] if so, create a minimal reproducible example

We'll then take it from there and fix it.

**Comment by xichaoqiang** [comment]
@certik It seems the convert parameter line is too long, exceeding the length of 132.

If I add & to split the long line into short lines. It works well.

**Comment by certik** [comment]
@xichaoqiang thanks for figuring it out! If you discover any other issues, please report them.
