### ISSUE TITLE
WASM: one array generics example does not work

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1332]
Everything is now fixed, except one example, the first bug here:

* https://github.com/lfortran/lfortran/issues/1294#issuecomment-1430149634

And there is a work in progress PR to fix it at https://github.com/lfortran/lfortran/pull/1306

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lfortran/lfortran/blob/e87adb8273bba0a825c308426ab45797370c8a37/integration_tests/CMakeLists.txt#L674-L683

I think all the template examples work with the `wasm` backend. Dr. Ondrej, is this issue safe to close?
