### ISSUE TITLE
Lfortran allows redefinition of loop variable unlike Gfortran 

### ISSUE THREAD

**Issue by faze-geek** [lfortran/lfortran#1342]
```
program for_loop_example
  implicit none
  integer :: i

  do i = 1, 10
    write(*,*) i
    i=i+1
  end do

end program for_loop_example
```
Such an increment is not allowed inside the loop in ` Gfortran`
```
(lf) faze-geek@DESKTOP-497JDCU:~/lfortran/lfortran$ gfortran try.f90  && ./a.out
try.f90:7:9:

    5 |   do i = 1, 10
      |              2
    6 |     write(*,*) i
    7 |     i=i+1
      |         1
Error: Variable ‘i’ at (1) cannot be redefined inside loop beginning at (2)

(lf) faze-geek@DESKTOP-497JDCU:~/lfortran/lfortran$ ./src/bin/lfortran try.f90
1
3
5
7
9
```

**Comment by faze-geek** [comment]
Not familiar well with `Fortran` but could find online that ` do i = 1, 10, 2` is the only method of incrementing allowed (unless another variable is involved I guess). So should it be expected of `Lfortran` too ?

**Comment by kargl** [comment]
11.1.7 DO construct
    ...
    11.1.7.4.3 The execution cycle
     ...
     (3) The iteration count, if any, is decremented by one. The DO variable, if any, is incremented by the
          value of the incrementation parameter m3.

      Except for the incrementation of the DO variable that occurs in step (3), the DO variable shall neither
      be redefined nor become undefined while the DO construct is active.

**Comment by certik** [comment]
Thanks for reporting it. Yes, we have to fix it. So far we've been mostly focusing on valid Fortran code, so there will be quite a few error messages that we have to catch and report.

**Comment by Pranavchiku** [comment]
This can be fixed during AST->ASR conversion, by iterating over assignments present in DoLoop statement prior to creation of DoLoop and checking if assignment->target == DoLoopVariable, then throw erro.

**Comment by certik** [comment]
The above example now gives:
```console
$ lfortran try.f90 
semantic error: Assignment to loop variable `i` is not allowed
 --> try.f90:7:5
  |
7 |     i=i+1
  |     ^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```
Thanks @Pranavchiku for fixing it!
