### ISSUE TITLE
Failed to build fpm

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1343]
I am setting up the CI for fpm.

I am trying to reproduce how to build fpm from scratch using LFortran and so far I can't figure it out. I am using the latest LFortran master (fe6a46df8b564ef4f2607c8684b1723674cf46bc):
```console
git clone https://github.com/fortran-lang/fpm.git
cd fpm
git checkout f8c901c00d8575f17a01bb995d9ba5864ff9426f
FPM_FC=lfortran fpm build --flag="--cpp"
```
This gives:
```
filesystem_utilities.c                 done.
fpm_strings.f90                        done.
fpm_backend_console.f90                done.
iscygpty.c                             done.
isatty.c                               done.
constants.f90                          done.
version.f90                            done.
token.f90                              done.
M_CLI2.F90                             done.
error.f90                              done.
error.f90                              done.
datetime.f90                           failed.
[ 16%] Compiling...
semantic error: The LHS character len=1 and the RHS character len=10 are not equal.
   --> build/dependencies/toml-f/src/tomlf/datetime.f90:113:4
    |
113 |    character(*, tfc), parameter :: num = "0123456789"
    |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

I tried different versions of LFortran and fpm. This has been working for me though, but I don't know how.

**Comment by certik** [comment]
I see, one must use an older version of toml:
```diff
--- a/fpm.toml
+++ b/fpm.toml
@@ -8,7 +8,7 @@ copyright = "2020 fpm contributors"
 [dependencies]
 [dependencies.toml-f]
 git = "https://github.com/toml-f/toml-f"
-rev = "aee54c5a480d623af99828c76df0447a15ce90dc"
+rev = "e8c52cce1253d3c8956af4d6c571b3cce583b265"
 
 [dependencies.M_CLI2]
 git = "https://github.com/urbanjost/M_CLI2.git"
```
This compiles.

**Comment by czgdp1807** [comment]
Use, https://github.com/czgdp1807/fpm/tree/lfortran_stf. I have been using this locally for development purposes.

**Comment by certik** [comment]
I created a new branch from a recent version of fpm, just downgraded `toml-f` to an older version that compiles with LFortran, now everything works. I enabled it at the CI: #1344.

Everything is fine, I got really worried that we badly regressed. But it's just newer `toml-f` that has some things we don't support yet, but since the older one works and fpm works with it, I think we don't have to worry.

**Comment by awvwgk** [comment]
Just seeing this issue now, we are upgrading TOML Fortran in fpm since we need some of the features for supporting the registry. So downgrading TOML Fortran is not a long term option for LFortran support with the latest versions of fpm anymore.

**Comment by certik** [comment]
Yes, we will have to support the newest toml-f, but I think the best for us is to get one given version of fpm+dependencies to fully compile. Then go from there and fix up any newer versions.
