### ISSUE TITLE
Implement intrinsic `allocated`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1353]
```fortran
program test_hybrd

    implicit none
    real,dimension(:),allocatable :: fvec

    if (allocated(fvec)) deallocate(fvec)

    contains
end program test_hybrd
```

> LFortran

```console
$ lfortran a.f90 --show-llvm
code generation error: Intrinsic 'allocated' not implemented yet and compile time value is not available.


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed)
```

**Comment by Pranavchiku** [comment]
I am planning to implement it, I have a design that goes as follows
* Maintain a vector to track all assignments `std::vector<ASR::expr_t*> allocated_vars`
* When encountering `allocated(xx)`, check if expr `xx` is present in `allocated_vars`, if yes then set value to true, else false.

**Comment by certik** [comment]
Allocated is a runtime feature. You need to check if the pointer is null, then it is not allocated, otherwise it is allocated. And we must initialize the pointer to null.

**Comment by Pranavchiku** [comment]
Okay, got it! I will try to build something on it.
