### ISSUE TITLE
WASM: Simple array assignment errors

### ISSUE THREAD

**Issue by fxcoudert** [lfortran/lfortran#1366]
Running in browser [LFortran](https://lfortran.org/) ([c969e0bc3](https://github.com/lfortran/lfortran/commit/c969e0bc3))

```
program main
    implicit none
    real :: x(2)
    x = [0.1, 0.1]
    print *, x
end program main
```

gives

```
CompileError: WebAssembly.Module doesn't validate: F64PromoteF32 value type mismatch, in function at index 2
ERROR: The code could not be executed. Either there is a runtime error or there is an issue at our end.
```

Replacing the assignment with `x = 0.1` gives another error:

```
CompileError: WebAssembly.Module doesn't validate: set_local to type F32 expected I32, in function at index 2
ERROR: The code could not be executed. Either there is a runtime error or there is an issue at our end.
```

**Comment by certik** [comment]
This is a WASM bug, the WASM backend is not as advanced as our main LLVM backend, where the above works:
```
$ lfortran a.f90 
1.00000001e-01
1.00000001e-01

```

**Comment by Shaikh-Ubaid** [comment]
The example shared here https://github.com/lfortran/lfortran/issues/1366#issue-1601469411 seems to work at https://dev.lfortran.org/.

>Replacing the assignment with x = 0.1 gives another error:

Yes, we have to fix this.
