### ISSUE TITLE
Incorrect handling of exit statements inside block

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1402]
```fortran
program main
    implicit none
    integer :: i, j
    test: block
        outer : do
            i = i + 1
            inner : do
                j = j + 1
                if (j == 5) then
                    print *, j
                    exit inner
                end if
            end do inner
            print *, "out of inner loop"
            if (i == 2) then
                print *, i
                exit outer
            end if
        end do outer
        print *, "out of outer loop"
    end block test
    print *, "out of test block"
end program
```

> LFortran
```console
$ lfortran a.f90 
5
out of test block
```

**Comment by certik** [comment]
We have to fix this. A separate issue is if the exit is exiting an outer block (#1414).

**Comment by certik** [comment]
I would fix this particular issue in the backend: I would keep track what the "inner most" statement is, whether block or (nested) do loop. Then I would exit that one. We might need to use a stack.

**Comment by certik** [comment]
Maybe maintain a stack, put blocks and do loops into it, and for each item keep the label it should jump to.

**Comment by certik** [comment]
Let's introduce ExitBlock, and decouple blocks and do loops completely. In the frontend, we recognize if we are exiting a block, and insert ExitBlock. We should rename Exit to ExitLoop.

**Comment by Pranavchiku** [comment]
I have made progress on it, decouple `visit_Block` and `visit_Exit` using `visit_ExitBlock`, the given case should pass once #1420 gets merged and will open up PR after that.
