### ISSUE TITLE
implicit function return type is not handled

### ISSUE THREAD

**Issue by fxcoudert** [lfortran/lfortran#1472]
```
module m
contains
   function f()
   end
end
```

gives `semantic error: Return type not specified`

This is incorrect, in the absence of a `implicit none`, `f` is implicitly `real`

**Comment by Pranavchiku** [comment]
I am able to reproduce. The log is as follows
```console
$ lfortran a.f90 --implicit-typing --implicit-interface
semantic error: Return type not specified
 --> a.f90:3:5 - 4:8
  |
3 |        function f()
  |        ^^^^^^^^^^^^...
...
  |
4 |        end
  | ...^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by fxcoudert** [comment]
Another case of implicit that is not handled:

```
MODULE EXAMPLE_MODULE
   IMPLICIT NONE
   INTERFACE
      FUNCTION FUN (I)
        INTEGER FUN
      END FUNCTION FUN
   END INTERFACE
END MODULE EXAMPLE_MODULE
```

where `I` is implicitly declared (and it is integer because of its name). This is allowed because the `IMPLICIT NONE` is in scope for the module, but not for the interface.

Another case also allowed is derived-types in implicit:

```
PROGRAM TEST
  IMPLICIT TYPE(FOO)(A-Z)
  TYPE FOO
    INTEGER X, Y
  END TYPE

  Z = FOO(42, 1)
  PRINT *, Z%X, Z%Y
END
```

This is valid and should output "42 1"

**Comment by certik** [comment]
@fxcoudert thanks for reporting these! We'll get them fixed.
