### ISSUE TITLE
With --implicit-typing, the "implicit none" does not apply to interfaces

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1499]
Currently I think we apply the "implicit none" to the whole module, but it does not actually apply to interfaces, according to the standard.

Let's write some test cases that use implicit typing in interfaces while having "implicit none" at the module level, that compile with gfortran but fail with `lfortran --implicit-typing`. Then fix it.

**Comment by Pranavchiku** [comment]
This code should give error as `x` has no implicit typing, but LFortran considers `x` as real. This happens because during AST to ASR conversion we populate `implicit_dictionary` at begining of `visit_Function` and `visit_Subroutine`. 
```fortran
module implicit_typing_module
implicit none

contains
subroutine sub1()
    x = 1
end subroutine sub1
end module implicit_typing_module

program main
end program main
```

> GFortran

```console
$ gfortran ./tests/temp.f90  && ./a.out
./tests/temp.f90:6:5:

    6 |     x = 1
      |     1
Error: Symbol ‘x’ at (1) has no IMPLICIT type
```

> LFortran

```console
$ lfortran ./tests/temp.f90 --implicit-typing
```

**Comment by Pranavchiku** [comment]
We are not checking `implicit none` statements when `--implicit-typing` flag is used, for example:
```fortran
subroutine sub1()
implicit none
x = 1
print *, x
end subroutine sub1

program main
    call sub1()
end program main
```

```console
$ lfortran ./tests/temp2.f90 --implicit-typing
1.00000000e+00
(lf) pranavchiku@pranavchiku-Yoga-Slim-7-14IIL05:~/lfortran$ gfortran ./tests/temp2.f90 && ./a.out
./tests/temp2.f90:3:1:

    3 | x = 1
      | 1
Error: Symbol ‘x’ at (1) has no IMPLICIT type
```

**Comment by gxyd** [comment]
Now for the above program:
```f90
subroutine sub1()
implicit none
x = 1
print *, x
end subroutine sub1

program main
    call sub1()
end program main
```

I get a semantic error on compilation with LFortran (irrespective of whether `--implicit-typing` is specified or not)
