### ISSUE TITLE
Array assignment bug

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1512]
```fortran
program array_assignment
implicit none
real :: x(3), fvec(15)
x = 1
fvec = x(1)
print *, fvec
end program
```
This gives with the latest master:
```console
$ gfortran array_assignment.f90 && ./a.out && lfortran array_assignment.f90
   1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000       1.00000000    
1.00000000e+00
1.00000000e+00
1.00000000e+00
-1.66597175e+20
1.40129846e-45
1.40129846e-45
4.20389539e-45
1.40129846e-45
1.00000000e+00
1.00000000e+00
1.00000000e+00
-1.66597175e+20
1.40129846e-45
1.40129846e-45
4.20389539e-45
```

**Comment by certik** [comment]
The `array_op` pass produces:
```
                        [(=
                            (ArrayItem
                                (Var 2 fvec)
                                [(()
                                (Var 2 __1_t)
                                ())]
                                (Real 4 [])
                                RowMajor
                                ()
                            )
                            (ArrayItem
                                (Var 2 x)
                                [(()
                                (Var 2 __1_v)
                                ())]
                                (Real 4 [])
                                RowMajor
                                ()
                            )
                            ()
                        )
```
which is wrong, as it is an equivalent of `fvec(:) = x(:)` which cannot even be done (wrong sizes), and should not be done anyway.

**Comment by certik** [comment]
@czgdp1807 I wonder if we should explicitly cast the scalar on RHS (`x(1)`) to an array (I think it's called "broadcasting"). That way the assignment is assigning an array to an array, and things become more clear.

**Comment by czgdp1807** [comment]
I think casting a scalar to an array would be a good idea because we have enough information in `fvec = x(1)` into a do loop. In fact we already do it for `Var` and `StructInstanceMember` but `ArrayItem` case is not handled yet (which I will do today).

Regarding "broadcasting" in general can also be done by converting to loops and iterating the array operands in the right manner. For example if you are adding, `a(2, 3)` with `b(2)` and then storing it in `c(2, 3)` then you don't need to convert `b(2)` to `b_broadcasted(2, 3)` (extra memory overhead) you can just do,

```fortran
do i = 1, 2
    do j = 1, 3
        c(i, j) = a(i, j) + b(i)
    end do
end do
```

**Comment by certik** [comment]
(Note that `b_broadcasted(2, 3)` has no memory overhead, it just represents the operation, it is not necessarily a copy.)
