### ISSUE TITLE
Value not assigned to nested variable in nested_vars pass 

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1530]
I guess it is reason for #1529.
```fortran
program main
implicit none
real :: x, fvec(5)                
x = 1.0                    
! call fcn(x, fvec)  
call check_deriv()              
print *, fvec

contains

    subroutine check_deriv()
    print *, "check_deriv x: ", x
    call fcn(x, fvec)
    end subroutine check_deriv 

    subroutine fcn(x, fvec)    
    real, intent(in) :: x
    real, intent(out) :: fvec(5)  
    fvec = x                                                  
    end subroutine fcn
 
end program

```

> GFortran

```console
$ gfortran ./tests/temp.f90 && ./a.out
 check_deriv x:    1.00000000    
   1.00000000       1.00000000       1.00000000       1.00000000       1.00000000   
```

> LFortran

```console
$ lfortran ./tests/temp.f90
check_deriv x:  0.00000000e+00
0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00 
```

**Comment by czgdp1807** [comment]
This issue is irrelevant. Actual problem is https://github.com/lfortran/lfortran/issues/1529#issuecomment-1501403731

**Comment by Pranavchiku** [comment]
I am not sure if this can be irrelevant because the code states same thing as [1529/comment](https://github.com/lfortran/lfortran/issues/1529#issuecomment-1501403731)

**Comment by czgdp1807** [comment]
The actual bug is copying to and from statements ending up in wrong places. However, we can use the above example as a test case.

**Comment by certik** [comment]
> The actual bug is copying to and from statements ending up in wrong places.

I think these statements are correct, the bug is probably somewhere else.

**Comment by czgdp1807** [comment]
These statements are correct but probably they are in the wrong places in our examples. I will need to investigate more while fixing it.

**Comment by HarshitaKalani** [comment]
I guess this can be closed as it works with the latest main. The test for the same is also added too.
