### ISSUE TITLE
Fix line & column numbers

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#159]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/8

Propagate them into the AST and write tests.

**Comment by lucifer1004** [comment]
This should have been solved @certik

**Comment by certik** [comment]
Yes, I think this is solved. The location information is part of AST and ASR nodes, and it is tested by our "tests/errors" tests. It could (and should!) be tested more systematically, but that's a separate issue, so we can close this one.
