### ISSUE TITLE
Using module variables as dimensions in function arguments

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1642]
Here is a minimal reproducible example that compiles with GFortran:
```fortran
module test_module_dim
implicit none
integer :: nx

contains

subroutine f(x)
real, intent(in) :: x(nx)
end subroutine

end module
```
and fails with LFortran:
```console
$ lfortran a.f90 
ASR verify pass error: ASR verify: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
  --> a.f90:7:1 - 10:1
   |
 7 |    subroutine f(x)
   |    ^^^^^^^^^^^^^^^...
...
   |
10 |    
   | ...^ failed here
```
But I don't understand the semantics of this yet, or if it is even valid Fortran. It is however used in SNAP here: https://github.com/lanl/SNAP/blob/e7ab43dfb0c16419d9a42d756141d5957ac526fc/src/geom.f90#L257, so we need to address this one way or the other.

I also asked here: https://fortran-lang.discourse.group/t/using-module-variables-as-dimensions-in-function-arguments/5742

**Comment by certik** [comment]
Here is an executable example that works:
```fortran
program test_module_dim
implicit none
integer :: nx

! Segfaults at runtime, due to `nx` not being initialized
!call f([1, 2])

! Works:
nx = 2
call f([1, 2])
nx = 3
call f([1, 2, 3])

contains

subroutine f(x)
integer, intent(in) :: x(nx)
print *, size(x)
print *, x
end subroutine

end program
```
It prints:
```console
$ gfortran a.f90 && ./a.out 
           2
           1           2
           3
           1           2           3
```

**Comment by certik** [comment]
It looks like GFortran, ifort, ifx and Flang can compile this, based on this: https://godbolt.org/z/3c7G6vqzq. So we should as well.

**Comment by certik** [comment]
I think one simple option is to treat it as `integer, intent(in) :: x(:)` at the type level. That should take care of most of our issues. In the symbol table we can still reference the module variable.

**Comment by czgdp1807** [comment]
I think this can be achieved as follows,

```fortran
module test_module_dim
implicit none
integer :: nx = 10
integer :: x(10)

call f(x)

contains

subroutine f(x)
real, intent(in) :: x(nx)
end subroutine

end module
```

can be transformed to,

```fortran
module test_module_dim
implicit none
integer :: nx
integer :: x(10)

call f(x, nx)

contains

subroutine f(x, nx)
integer, intent(in) :: nx
real, intent(in) :: x(nx)
end subroutine

end module
```

**Comment by czgdp1807** [comment]
Also, I think this can be done via ASR pass. Doing directly in ASR can lead to loosing the originality of the input code.

**Comment by czgdp1807** [comment]
@Thirumalai-Shaktivel I would work on it.

**Comment by certik** [comment]
ASR pass is usually the way to go, however in this case I think it's problematic: if we do not call this ASR pass that I would argue the initial ASR is incorrect --- the `nx` should never point to the parent symbol table.

In other words, ASR should not be allowed to represent this feature. I don't think we want it. Consequently, ASR verify should reject it. So we could still write it as some kind of a pass to run in AST->ASR before verify gets called, but it might be simpler to just recognize this case in AST->ASR, and construct some workaround, whether `integer, intent(in) :: x(:)` or `subroutine f(x, nx)`, either would work.
