### ISSUE TITLE
c_int64_t is missing in c_iso_binding module

### ISSUE THREAD

**Issue by kargl** [lfortran/lfortran#1672]
```
 subroutine foo
   use iso_c_binding
   integer(c_int64_t) i
   i = 42
   print *, 42
end subroutine foo

% ~/lfortran/work/bin/lfortran -c a.f90
semantic error: Variable 'c_int64_t' is not declared
 --> a.f90:3:12
  |
3 |    integer(c_int64_t) i
  |            ^^^^^^^^^ 'c_int64_t' is undeclared


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

**Comment by kargl** [comment]
You can add `c_long_double` to list of missing symbols.

**Comment by certik** [comment]
Thanks @kargl. It should work now. I returned `-1` for `c_long_double`, since we don't support 128bit floats yet. Are you using it for the 80 bit double (https://en.wikipedia.org/wiki/Extended_precision#x86_extended_precision_format) ? GFortran seems to return 8, the same as double precision. So maybe we can do the same.

**Comment by kargl** [comment]
> Thanks @kargl. It should work now. I returned `-1` for `c_long_double`, since we don't support 128bit floats yet. Are you using it for the 80 bit double (https://en.wikipedia.org/wiki/Extended_precision#x86_extended_precision_format) ? GFortran seems to return 8, the same as double precision. So maybe we can do the same.

On FreeBSD, `c_long_double` is 10, which is `real(10)` and a 80-bit Intel extended double type.  What operating system are you testing on with gfortran and what version of gfortran?  If `c_long_double` is 8, this suggest that the C compiler has `sizeof(double) == sizeof(long double)`.

**Comment by certik** [comment]
I am using GFortran 11.3.0 on Apple M1 (arm64). I compiled it via Spack from source code. So I think returning -1 for now is the best, since we don't support real(10) yet. We'll implement it later, as well as quadruple precision that we don't support either yet.
