### ISSUE TITLE
Emit a warning for "real*4 x"

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1680]
Right now we compile `real*4 x` without any warning. Instead, we should give a warning that one should use `real(4) x` (or `real(4) :: x`). 

Also, I think we should also give a warning that one should not use `real(4)`, but rather `real(sp)` (or equivalent), since the number 4 is compiler dependent.

**Comment by HarshitaKalani** [comment]
The AST for all the cases come out to be same. I was searching for the correct location in parser.cpp. Am I going in the right direction?

**Comment by Thirumalai-Shaktivel** [comment]
Yup, you are almost on the right track.
I think we have to make the changes in `parser.yy`. See for `var_decl` for declaration grammar rules.
See: https://gitlab.com/lfortran/lfortran/-/merge_requests/1519/diffs for references on how to add warnings.

**Comment by HarshitaKalani** [comment]
Hey @Thirumalai-Shaktivel, I could locate `var_decl` but feel that it is a little tricky to understand. Can you please give some more idea on how to do that?
I proceeded this way: https://github.com/lfortran/lfortran/pull/2094
