### ISSUE TITLE
Compilation failure due to presence of pass attribute in type-bound procedure declaration

### ISSUE THREAD

**Issue by difference-scheme** [lfortran/lfortran#1685]
Let's see whether you guys are truly "agile". :-)

I am trying to get a modern Fortran code base to compile with LFortran and have hit the following bug. The code below doesn't compile, because LFortran is offended by the (superfluous, but allowed by the standard) `pass` attribute to the type-bound procedure statement:

```
module test

   private

   type, abstract :: tester
   contains
      procedure(testing), deferred, pass :: testing
   end type tester

   abstract interface
      subroutine testing()
      end subroutine testing
   end interface
   
end module test

```
After removal of the `pass` attribute, the example compiles.

If you can get this bug fixed within a few days, I'll send you more bug reports.

**Comment by certik** [comment]
@difference-scheme thanks! I modified your test slightly so that it compiles with gfortran and then added it to our test suite.

I am sure there are tons of bugs regarding classes, so go ahead and report them all, we'll fix them one by one.

**Comment by difference-scheme** [comment]
Thanks, you were quicker than me! 

I realized later, that I had forgotten to add the passed-object dummy argument to the abstract interface of the subroutine (I had reduced the original test case too much, to figure out where exactly LFortran crashed).

But this also shows that there's another bug in the semantic checks, because when deleting the `pass` attribute, LFortran accepted the code as valid, whereas it wasn't. I will open a separate issue for that.

**Comment by certik** [comment]
Yes. There are tons of bugs related to invalid code, but those are lower priority. We will of course fix all those eventually (with beautiful error messages), but first I am focusing on compiling valid code, that's the absolutely highest priority.
