### ISSUE TITLE
compile program not starting with "program" statement

### ISSUE THREAD

**Issue by Beliavsky** [lfortran/lfortran#1691]
At https://dev.lfortran.org/ , 

```
program main
print*,"hello"
end program
```
compiles and runs, as does

```
program main
print*,"hello"
end
```
but
```
print*,"hello"
end program
```

does not, nor does

```
print*,"hello"
end
```

Gfortran compiles and runs all of these. It looks like LFortran has trouble with programs not starting with "program".

**Comment by Shaikh-Ubaid** [comment]
related https://github.com/lfortran/lfortran/issues/1076
