### ISSUE TITLE
Possible regression for type-bound procedures with the nopass attribute

### ISSUE THREAD

**Issue by difference-scheme** [lfortran/lfortran#1712]
So far I've been running lfortran as compiled from tarball lfortran-0.19.0-27-g967178c3e.tar.gz. 

I've now switched to compiling the latest lfortran source directly from this github repository. 
Unfortunately, now the following module fails to compile, that was compiling before:
```
module regressed

   private
   
   type, public, abstract :: AbsType
   contains
      procedure(method), deferred, nopass :: method
   end type AbsType

   abstract interface
      pure function method() result(n)
         integer :: n
      end function method
   end interface

end module regressed
```
Here's the error message:
```
semantic error: Passed object dummy argument does not match function argument
 --> regressed.f90:7:7
  |
7 |       procedure(method), deferred, nopass :: method
  |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```
It seems to expect a passed object dummy argument, although the method is declared with the `nopass` attribute. Can someone confirm whether this regressed? Thanks.

**Comment by certik** [comment]
I can confirm that the latest master has this bug. However, the previous case was for a `pass` attribute, the test is here: https://github.com/lfortran/lfortran/blob/4d1aeac17805b8abbd36c097769a15861414fd95/integration_tests/class_06.f90 and it still works (we run it in our testsuite). We currently don't have a single test for `nopass`, so I think if it was working before, it was an accident. We have to implement it.

**Comment by difference-scheme** [comment]
@certik Ok, thanks for the confirmation.

I think that's all I can do for you right now. I'll check back on your progress sometime later, to see whether we'll be closer to get this modern Fortran code base to compile.

**Comment by certik** [comment]
Awesome, thanks @difference-scheme, we appreciate all your bug reports. I'll ping you once we fix them all.
