### ISSUE TITLE
Possible regression with intrinsic functions

### ISSUE THREAD

**Issue by difference-scheme** [lfortran/lfortran#1725]
It seems that the present main branch of the repository fails to compile code that makes use of several of Fortran's intrinsic functions (the problem seems not to be restricted merely to the real intrinsic; It's used here just as an example):
```
program test

   integer, parameter :: n = 10
   real(8) :: float

   float = real(n)
   
end program test

```
Error message:
```
semantic error: Module 'lfortran_intrinsic_builtin' not declared in the current source and the modfile was not found
 --> test.f90:6:12
  |
6 |    float = real(n)
  |            ^^^^^^^ 

```

**Comment by Shaikh-Ubaid** [comment]
It seems to work for me on the present `main` branch.

```bash
$ cat examples/expr2.f90      
program test

    integer, parameter :: n = 10
    real(8) :: float

    float = real(n)
    print *, float
end program test
$ lfortran examples/expr2.f90 
1.00000000000000000e+01
```

**Comment by difference-scheme** [comment]
@Shaikh-Ubaid Thanks for checking! 

I'll then need to do again a git pull, and a recompile. I will report afterwards if the problem persists on my side. Might actually be a compilation setup issue.

**Comment by difference-scheme** [comment]
I have downloaded a new git clone of the repository, and the problem is gone now. 

Seems that my previous lfortran binary was possibly out of sync with the main branch after all. Sorry for the false alarm. You may close this issue now.
