### ISSUE TITLE
CI: add a test for warnings turned errors

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1759]
In both Debug and Release mode. Right now we are getting a lot of warning messages, especially in Release mode.

**Comment by Shaikh-Ubaid** [comment]
@certik, please, could you share an example of warning turned error?

**Comment by certik** [comment]
We just have to pass `-Werror` into the build and build Debug and Release to check both, since in Release we have more warnings caused by asserts being turned off. In fact we already do it here: https://github.com/lfortran/lfortran/blob/cfd48ed755b5d0fbe115a4c0d8e93afaab0e36b6/.github/workflows/CI.yml#L699, so we might just enable this for the Release builds as well.
