### ISSUE TITLE
Implement multidimensional explicit-shape arrays

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#177]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/51

Such arrays are implemented by simply passing a pointer to the data (no array descriptor as in https://gitlab.com/lfortran/lfortran/-/issues/50 is needed) and the size/shape of such arrays is either known at compile time or at function invocation time.

Initial 1D implementation has been implemented in https://gitlab.com/lfortran/lfortran/-/merge_requests/123.

TODO:

* [ ] Allow to infer the size of the array from a function argument (e.g., `integer, intent(in) :: a(n)`).
* [ ] Implement multidimensional array support
* [ ] Fix all corner cases

Explicit-shape arrays are easy to implement, and after this issue is fixed, it will allow people to start writing numerical algorithms using LFortran.

The assumed-shape arrays (https://gitlab.com/lfortran/lfortran/-/issues/50) are more powerful, but also more difficult to implement, and so they will be implemented after this issue is fixed.

**Comment by lucifer1004** [comment]
Can this be closed @certik

**Comment by certik** [comment]
I think that's done.
