### ISSUE TITLE
Possibility of race condition in Integration tests due to FAST tests

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#1825]
The failure in LLVM 15:
```
[ 44%] Built target modules_02_FAST
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: read_int64: String is too short for deserialization.
make[2]: *** [CMakeFiles/modules_22.dir/build.make:75: CMakeFiles/modules_22.dir/modules_22.f90.o] Error 1
```
Is typically caused by duplicate module. Ah, I wonder if the FAST test has a race condition on the module name? CC @Shaikh-Ubaid. I think it does.

_Originally posted by @certik in https://github.com/lfortran/lfortran/issues/1818#issuecomment-1591372754_

**Comment by Shaikh-Ubaid** [comment]
>I wonder if the FAST test has a race condition on the module name? CC @Shaikh-Ubaid. I think it does.

While supporting the FAST tests, I did think that there could be a possibility of race conditions for modules as they would be shared with the non-fast executions of the same tests. It seems there is. I think its time to fix it.

**Comment by certik** [comment]
Another failure: https://github.com/lfortran/lfortran/actions/runs/5350542283/jobs/9703278181


@Shaikh-Ubaid will you have time to fix this? I think the easiest to fix is to build the fast tests in another directory.

**Comment by Shaikh-Ubaid** [comment]
>@Shaikh-Ubaid will you have time to fix this? I think the easiest to fix is to build the fast tests in another directory.

Yes, looking into it. It seems I am close.
