### ISSUE TITLE
[SciPy][cdflib]: visit_Entry() not implemented

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#1836]
```fortran
SUBROUTINE dzror()
print *, "in dzror"
ENTRY dstzr()
    print *, "in dztzr"
RETURN
END

program main
    print *, "Call dzror"
    call dzror()
    print *, "Call dstzr"
    call dstzr()
end program

```

> GFortran

```console
% gfortran a.f90 && ./a.out
 Call dzror
 in dzror
 in dztzr
 Call dstzr
 in dztzr
```

> LFortran

```console
% lfortran a.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: visit_Entry() not implemented
```

**Comment by Pranavchiku** [comment]
@certik , @czgdp1807 
If I understood it correctly, the above code translates to:
```fortran
subroutine dztzr()
    print *, "in dztzr"
end subroutine

SUBROUTINE dzror()
print *, "in dzror"
call dztzr()
END

program main
    print *, "Call dzror"
    call dzror()
    print *, "Call dstzr"
    call dztzr()
end program
```

**Comment by Pranavchiku** [comment]
> An ENTRY name used in a subroutine subprogram is treated like a subroutine and can be referenced with a CALL statement. Similarly, the ENTRY name used in a function subprogram is treated like a function and can be referenced as a function reference.


Source: https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn99/index.html

**Comment by Thirumalai-Shaktivel** [comment]
I think an `entry` statement is used as the alternative entry for the subroutines or functions.
So, in your case:
```f90
SUBROUTINE dzror()
print *, "in dzror"
ENTRY dstzr()
    print *, "in dztzr"
RETURN
END

program main
    print *, "Call dzror"
    call dzror()
    print *, "Call dstzr"
    call dstzr()
end program
```
I think we can consider it as a nested subroutine with all the statements executed based on the scope.
Here is another example, which can help you: https://github.com/lfortran/lfortran/blob/main/tests/entry1.f90

**Comment by certik** [comment]
I think `entry` is used at only a few places in SciPy. I think that is lower priority. But I think we are at the last few things for ASR, so why not. I think the way you implement it is as follows. Take this:
```fortran
 subroutine x(dummy) 
     print *, "Printed using subroutine call: ", dummy 
     dummy = 5 
     return 
     entry y(dummy) 
     print *, "Printed using entry statement: ", dummy 
     return 
 end subroutine 
```
And create two functions:
```fortran
 subroutine x(dummy) 
     print *, "Printed using subroutine call: ", dummy 
     dummy = 5 
     return 
     print *, "Printed using entry statement: ", dummy 
     return 
 end subroutine 

 subroutine y(dummy) 
     print *, "Printed using entry statement: ", dummy 
     return 
 end subroutine 
```

Where in the original function you simply remove all `entry` statements. In this case there was a "return" above "entry", but it doens't have to be there, in which case the execution would just continue. In the second function you ignore all statements above the entry. With multiple entries, you simply create a new function for each entry, ignoring all previous statements, and ignoring all subsequent entry lines for that function.

You keep all variable declarations. I think this might not be a complicated feature to implement. Let's only implement "entry" at the "top level" in the function -- so no "entry" inside an if statement or a loop. I think that's all we need for SciPy.

**Comment by Pranavchiku** [comment]
Yes, perfect! I am thinking the same.

**Comment by Pranavchiku** [comment]
```fortran
program entry1 
     real :: dummy 
     dummy = 10 
     call x(dummy) 
     call y(dummy) 
 end program 
  
 subroutine x(dummy) 
     print *, "Printed using subroutine call: ", dummy 
     dummy = 5 
     return 
     entry y(dummy) 
     print *, "Printed using entry statement: ", dummy 
     return 
 end subroutine 
```

I have implementation ready, but I have a doubt when we encounter `call y(dummy)` we don't have `y` present in symbol table so it will throw error
```console
% lfortran ./tests/entry1.f90 
semantic error: Function 'y' not found or not implemented yet (if it is intrinsic)
 --> ./tests/entry1.f90:5:5
  |
5 |     call y(dummy)
  |     ^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

**Comment by Pranavchiku** [comment]
This is not much trouble as 
```console
% lfortran ./integration_tests/entry_01.f90 --implicit-typing --implicit-interface             
Call dzror
in dzror
in dztzr
Call dstzr
in dztzr
```

**Comment by certik** [comment]
The symbol table visitor could put all the entries into the symbol table, so that it is there.

**Comment by Pranavchiku** [comment]
`entry` ia defined as `AST::stmt_t` so i guess we can't directly read it from symboltable visitor

**Comment by certik** [comment]
I meant you can put the Function into the symbol table, that corresponds to each "entry".

**Comment by Pranavchiku** [comment]
I do this thing in `visit_Entry()` present in `body_visitor`. I am not sure how will I do this in `symboltable_visitor`. The major trouble is at `symboltable_visitor` we will have to visit body of function to know about presence of `entry` statements.

**Comment by certik** [comment]
If needed, you might need to "scan" each function for "entry points", and if this is a performance hit, we can put it behind a compiler option (off by default).

**Comment by Pranavchiku** [comment]
This is doable, just will have to keep it under `--implicit-interface`.

**Comment by certik** [comment]
Or that, since people needing this will need `--implicit-interface` anyway.
