### ISSUE TITLE
GitHub Mirror: automatically close PRs with a nice message

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#185]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/64

Currently this repository is mirrored at GitHub automatically: https://github.com/lfortran/lfortran

Wiki, issues are all disabled. Unfortunately the GitHub PRs cannot be disabled, so we need to setup a bot that will automatically close any PRs that people might open (despite the repository description that this is a mirror), with a nice informative message to "please send this PR to https://gitlab.com/lfortran/lfortran".

We should try to use https://github.com/dessant/repo-lockdown, which does exactly that.

**Comment by lucifer1004** [comment]
This issue can be closed since the GitHub repo is now the main repo. @certik
