### ISSUE TITLE
Bug: allow length variables below the array definition

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#1853]
This:
```fortran
subroutine f(n, x)
real, intent(in) :: x(n)
integer, intent(in) :: n
end subroutine
```
Gives:
```console
$ lfortran a.f90 
semantic error: Variable 'n' is not declared
 --> a.f90:2:23
  |
2 | real, intent(in) :: x(n)
  |                       ^ 'n' is undeclared
```
But works with GFortran:
```console
$ gfortran -c a.f90  
$
```

**Comment by Smit-create** [comment]
Even this is an issue to consider:
```fortran
program a
    implicit none
    integer :: x(3) = [1, 2, 3]
    call f(3, x)

    contains
        subroutine f(n, x)
        integer, intent(in) :: x(n), n
        print *, x(1)
        end subroutine

end program
```

**Comment by Smit-create** [comment]
One way of fixing this is visiting all the `unit_decl2` and determining the order of their declaration in the first pass and then processing them. This approach has 2 issues:
1. The will be a repetition of this approach wherever we are having `visit_unit_decl2`.
2. Time complexity may increase as we will visit them twice to determine the order.

**Comment by certik** [comment]
I would do it just like we do now, but when we discover a variable in a dimension that has not been declared yet, we simply assume it has the right type and insert it into the symbol table, then we fill it in later.
