### ISSUE TITLE
Port to C++

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#188]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/70

Gradually we will port to C++ for speed and robustness. We will keep the same (or very similar) Python API, so that code that is written on top of the current LFortran does not have to change much (and also it allows us to make this move gradually), but the underlying compiler will eventually be in pure C++ as a standalone binary. Then we can also have wrappers to other languages.

**Comment by lucifer1004** [comment]
Can this be seen as fixed? @certik

**Comment by certik** [comment]
Thanks!
