### ISSUE TITLE
Refactor and Improve File read/write

### ISSUE THREAD

**Issue by Smit-create** [lfortran/lfortran#1931]
The current implementation uses the runtime `C` library for read/write operations. The implementation doesn't work properly as consider the following example:
```fortran
program fileops
    implicit none
    integer :: j, i
    j=11
    open(j, file="foo.txt")
    read(j, *) i
    close(j)
    print *, i

end program fileops
```
```
% cat foo.txt 
1023
```
The results differences are:
```
% lfortran a.f90 
1
% gfortran a.f90 && ./a.out 
        1023
```

Moreover, `lfortran` doesn't work at all when we have multiple lines and multiple read variables as it isn't able to recognize what cursor position to start with. We need to design a robust solution that works with every minimal read/write case.

Right now, this just works in helping the LLVM code-generation without any errors but would surely fail in LLVM binary testing as the variables would not contain the correct values at runtime.

**Comment by certik** [comment]
Isn't it enough to simply keep some struct in the C runtime library, and keep the state that way?
