### ISSUE TITLE
Comment in preprocessor lines cause syntax error

### ISSUE THREAD

**Issue by cphyc** [lfortran/lfortran#1945]
## Description of bug

Comments in preprocessor macros (`/* comment */` and `// comment`) lead to a syntax error.

Here is some code for reproduction:
```fortran
! File test.f90
program test
#ifdef SOMETHING
#endif // This should work

#define square(a) /* This should be ignored as well */ a * a 
	integer :: a = 10

    print*, square(a)
end program test
```

## Observed behaviour
The code above does not compile
```bash
$ lfortran --cpp test.f90 -o test
syntax error: End of file is unexpected here
  --> test.f90:10:1
   |
10 | 
   | ^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that must be fixed).
```

Note that removing the comments from the preprocessor allows the program to be compiled and runs fine.

## Expected behaviour
The code above should compile. E.g., with gfortran:
```bash
$ gfortran -cpp test.f90 -o test && ./test
100
```

## System information
- Lfortran version:
```$ lfortran --version
LFortran version: 0.19.0
Platform: Linux
Default target: x86_64-unknown-linux-gnu
```
- Linux x64

**Comment by certik** [comment]
@cphyc excellent, thanks for the bug report. It's bug in our preprocessor handling.

**Comment by Shaikh-Ubaid** [comment]
@certik To solve this, shall we remove comments before passing the `input` (user's source code) to `CPP Preprocessor`? Or do we need to handle the comments inside the `CPP Prepocessor`?

**Comment by certik** [comment]
As a first step we can ignore the comment. Later we can figure out how to pass in the comment into AST (like we do with other comments).
