### ISSUE TITLE
Segfaults when assigning to a slice of a member of derived type

### ISSUE THREAD

**Issue by cphyc** [lfortran/lfortran#1950]
# Minimal code for reproduction

### Case 1
The following codes segfault at compilation:
```fortran
program test
    type :: int_container
        integer, dimension(2) :: my_int
    end type
    integer :: my_int

    type(int_container) :: t
    my_int = 1
    t%my_int(:) = 1
end program
```

### Case 2
This one also causes a segfault (see working case below for a comparison)
```fortran
program test
    type :: int_container
        integer, dimension(2) :: my_int
    end type
    integer :: my_int

    type(int_container) :: t
    ! my_int = 1
    t%my_int(:) = 1
end program
```

### Case 3
Very interestingly, the following program causes a segfault at compilation
```fortran
program test
    type :: int_container
        integer :: my_int
    end type
    integer :: my_int

    type(int_container) :: t
    t%my_int(:) = 1
end program
```
but the following causes a `code generation error` instead
```fortran
program test
    type :: int_container
        integer :: my_int
    end type
    ! integer :: my_int

    type(int_container) :: t
    t%my_int(:) = 1
end program
```

# Compiling case
This compiles fine:
```fortran
program test
    type :: int_container
        integer, dimension(2) :: my_int
    end type
    ! integer :: my_int

    type(int_container) :: t
    t%my_int(:) = 1
end program
```

**Comment by certik** [comment]
Perfect, thank you. I think it is getting confused with a local variable having the same name. We need to fix it.

**Comment by Pranavchiku** [comment]
I see while checking `is_statement_function` we are using the variable name ( which is my_int ) in this case, and then searching in the current scope if any variable ( not array ) with a given name exists.
For this case, as we have the declaration `integer :: my_int` present, it confuses `t%my_int` with `my_int` and hence considers it as statement function which eventually leads to creating statement function and finally a segfault because of empty dimension_t

**Comment by Pranavchiku** [comment]
> Case 3: but the following causes a code generation error instead

```fortran 
program test
    type :: int_container
        integer :: my_int
    end type
    ! integer :: my_int

    type(int_container) :: t
    t%my_int(:) = 1
end program
```

> GFortran

```console
% gfortran a.f90&& ./a.out
a.f90:8:5:

    8 |     t%my_int(:) = 1
      |     1
Error: Unclassifiable statement at (1)
```

**Comment by certik** [comment]
The compilation bugs in this issue are all fixed.

@Pranavchiku I opened a new issue https://github.com/lfortran/lfortran/issues/2197 for the better error message.
