### ISSUE TITLE
Your Star History stops working

### ISSUE THREAD

**Issue by zaikunzhang** [lfortran/lfortran#1995]
I think you have encountered the same problem as me: 

https://github.com/star-history/star-history/issues/317

**Comment by certik** [comment]
Can you describe the problem? It seems to be working for me:

<img width="898" alt="Screen Shot 2023-07-18 at 9 05 28 AM" src="https://github.com/lfortran/lfortran/assets/20568/ddfad4d8-2eb0-4cb3-9919-248b9090cecb">

**Comment by zaikunzhang** [comment]
It works now.

**Comment by certik** [comment]
I notice that sometimes it doesn't load, but usually it works.
