### ISSUE TITLE
variable order

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2000]
https://github.com/certik/fastGPT/commit/c0c4d66cea37b0ea3f88a6eab666472ae0c5658e

**Comment by Smit-create** [comment]
Same issue as: https://github.com/lfortran/lfortran/issues/1853. This was fixed in #1907. @certik  Can you please verify?

**Comment by certik** [comment]
Perfect, it looks like it is fixed! I am updating the CI to not test this anymore, then we can close this.
