### ISSUE TITLE
Implement read() into an allocatable array

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2001]
https://github.com/certik/fastGPT/commit/824605b7366464baa53bfe6bf723654e26f80fad

**Comment by Smit-create** [comment]
I have attempted to fix this in #1925. Can you please review that? I/O with files is a known common issue that would need restructuring but at least generate a valid LLVM code.

**Comment by certik** [comment]
Perfect, that's the first step. Note that here we are reading a binary file:
```
open(newunit=u, file=filename, form="unformatted", access="stream", status="old")
```
Which just loads the data directly into the array, so it might be simpler to implement in the runtime library --- we just read it and copy the data to the array.

**Comment by certik** [comment]
@Smit-create Here is the current status as of the latest master (5c741a63286de1c190abfc488e300be75b500d1e):
```
warning: format string in read() is not implemented yet and it is currently treated as '*'
 --> /Users/ondrej/repos/fastGPT/main.f90:1:1
  |
1 | program gpt2
  | ^ treated as '*'

code generation error: Read function not implemented for: real[:, :]
```

**Comment by certik** [comment]
We need reading integer and real arrays (allocatable, but they are all pre-allocated) from a binary file.

**Comment by certik** [comment]
This is now fixed thanks to #https://github.com/lfortran/lfortran/pull/2036. Thank you so much @Shaikh-Ubaid for this fix.

There are more issues to fix, but I am going to close this issue as fixed. The other issues are medium priority.
