### ISSUE TITLE
Docs: The "Edit on GitLab" link is broken for notebook pages

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#201]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/89

For pages that are generated from a Jupyter notebook, the "Edit on GitLab" link is broken, because the corresponding MD file actually not saved in the repository. We could use `mknotebooks` after [this issue](https://github.com/greenape/mknotebooks/issues/4) is fixed.

We disabled the link for now (in https://gitlab.com/lfortran/lfortran/-/merge_requests/192), and after we fix this, we can enable it again.

**Comment by lucifer1004** [comment]
This issue can be closed. @certik

**Comment by certik** [comment]
Thanks!
