### ISSUE TITLE
indexing into integer array doesn't work

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2044]
```
function c2s(x) result(y)
integer(1), intent(in) :: x(:)
character(:), allocatable :: y
integer :: i
allocate(character(size(x)) :: y)
print *, "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
do i = 1, size(x)
    y(i:i) = char(int(x(i),4))
    print *, i, x(i)                     
end do
print *, "--------"
print *, x
print *, y
end function                                                        
```
Here the `x(i)` values are incorrect, but `x` prints correctly at the end. This function is called as:
```
c2s(decoder_txt(idx(i)+1:idx(i+1))
```
The slice probably makes it fail.

**Comment by certik** [comment]
The workaround is this:
```
function c2s(x) result(y)
integer(1), intent(in) :: x(:)
integer(1) :: xx(size(x))
character(:), allocatable :: y
integer :: i
xx = x
allocate(character(size(x)) :: y)
do i = 1, size(x)
    y(i:i) = char(int(xx(i),4))
end do
end function
```
It looks like the lower/upper bounds are not reset when entering the function. But the `xx = x` lines resets it, so everything works then.

**Comment by Smit-create** [comment]
Yeah, so I think the bug is in the `ArrayItem`. We have passed the pointer whose `LBound` and `UBound` are changed through a pass and so I think we should also replace all the `ArrayItem[i]` with `ArrayItem[i+LBound]`.

**Comment by certik** [comment]
I think ArrayItem is correct, but it's lowering to LLVM is incorrect --- or to be precise, I think LBound and UBound is incorrect, it should be 1..size(x), but it is not, I think it's reused from the argument. The lower bound resets to 1 when entering a function.

**Comment by Smit-create** [comment]
Here is the line that is the exact bug:
https://github.com/lfortran/lfortran/blob/8bfa5992eb03990800e8aec076e162e172c02705/src/libasr/codegen/llvm_array_utils.cpp#L506

It does the following:
```
Array[i-LowerBound]
```
Now this would not work if we changed `LBound` of an array while passing it through the call parameters.

Print works fine because it starts printing from `LBound` till `UBound`.
