### ISSUE TITLE
Passing A(:,i) as an argument fails

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2061]
Here is a minimal example:
```fortran
program test_arrays
real :: B(10,2)
B(:,1) = 1
B(:,2) = 2
print *, mysum(size(B,1), B(:,1))
print *, mysum(size(B,1), B(:,2))

contains

    real function mysum(n, A) result(r)
    integer, intent(in) :: n
    real, intent(in) :: A(n)
    integer :: i
    r = 0
    do i = 1, size(A)
        r = r + A(i)
    end do
    end function

end program
```
This gives:
```console
$ lfortran a.f90 
1.00000000e+01
1.00000000e+01
$ gfortran a.f90 && ./a.out 
   10.0000000    
   20.0000000    
```

Note that this does not happen if the array is declared as `A(:)` instead of `A(n)`. There are other variations of this bug, such as having a function hierarchy, a few accepting `A(:)` and eventually passing to `A(n)`.

**Comment by certik** [comment]
This code: https://github.com/lfortran/lfortran/blob/9b4da222c566ffab71f01716db1e0f9e181a5475/src/libasr/codegen/asr_to_llvm.cpp#L2019 doesn't seem to support higher rank than 1. That would explain why the above does not work.

**Comment by certik** [comment]
Here is the relevant part of the ASR that the LLVM sees:
```
                    (=>
                        (Var 2 __libasr__created__var__1__array_section_pointer_)                       (ArraySection
                            (Var 2 b)
                                (Var 2 b)
                                (IntegerConstant 1 (Integer 4))
                                (Integer 4)
                                LBound
                                (IntegerConstant 1 (Integer 4))
                            )
                            (ArrayBound
                                (Var 2 b)
                                (IntegerConstant 1 (Integer 4))
                                (Integer 4)
                                UBound
                                (IntegerConstant 10 (Integer 4))
                            )
                            (IntegerConstant 1 (Integer 4)))
                            (()
                            (IntegerConstant 2 (Integer 4))
                            ())]
                            (Array
                                (Real 4)
                                [(()
                                ())]
                                DescriptorArray
                            )
                            ()
                        )
                    )
                    (=
                        (Var 2 s)
                        (FunctionCall
                            2 mysum
                            ()
                            [((ArraySize
                                (Var 2 b)
                                (IntegerConstant 1 (Integer 4))
                                (Integer 4)
                                (IntegerConstant 10 (Integer 4))
                            ))
                            ((ArrayPhysicalCast
                                (Var 2 __libasr__created__var__1__array_section_pointer_)
                                DescriptorArray
                                PointerToDataArray
                                (Array
                                    (Real 4)
                                    [(()
                                    ())]
                                    PointerToDataArray
                                )
                                ()
                            ))]
                            (Real 4)
                            ()
                            ()
                        )
                        ()
                    )
```

**Comment by certik** [comment]
I think this happens in handle_array_section_association_to_pointer, it creates a new descriptor for the pointer and I wonder if it doesn't set the pointer to data correctly. Because in `visit_ArrayPhysicalCastUtil` I see
```
        if( m_new == ASR::array_physical_typeType::PointerToDataArray &&
            m_old == ASR::array_physical_typeType::DescriptorArray ) {
            if( ASR::is_a<ASR::StructInstanceMember_t>(*m_arg) ) {
                arg = LLVM::CreateLoad(*builder, arg);
            }
            tmp = LLVM::CreateLoad(*builder, arr_descr->get_pointer_to_data(arg));
```
Which just loads the pointer. I think that is correct, as long as the descriptor itself is correct, which leads me to believe the descriptor of the pointer is not correct.

**Comment by czgdp1807** [comment]
I see what's going on. The data pointer is perfectly fine. The problem is that `B(:, 2)` is passed by data, so the offsets doesn't get passed into `mysum`. If you do, `real, intent(in) :: A(:)` instead of `real, intent(in) :: A(n)` then it should work.

```fortran
program test_arrays
real :: B(10, 2)
B(:, 1) = 1
B(:, 2) = 2
print *, mysum(size(B, 1), B(:, 1))
print *, mysum(size(B, 1), B(:, 2))

contains

    real function mysum(n, A) result(r)
    integer, intent(in) :: n
    real, intent(in) :: A(:)
    integer :: i
    r = 0
    do i = 1, size(A)
        r = r + A(i)
    end do
    end function

end program
```

```zsh
(lf) 9:09:00:~/lfortran_project/lfortran % lfortran /Users/czgdp1807/lfortran_project/debug.f90            
1.00000000e+01
2.00000000e+01
```

**Comment by czgdp1807** [comment]
`((ArrayPhysicalCast (Var 2 __libasr__created__var__1__array_section_pointer_) DescriptorArray PointerToDataArray (Array (Real 4) [(() ())] PointerToDataArray) ()))]` is not possible when `offset` is not `0` because you need a descriptor to index `B(:, 2)` correctly inside a function.

**Comment by Shaikh-Ubaid** [comment]
Yes @czgdp1807 https://github.com/lfortran/lfortran/issues/2061#issuecomment-1647150678. Dr. Ondrej shared about it the  issue description

>Note that this does not happen if the array is declared as A(:) instead of A(n). There are other variations of this bug, such as having a function hierarchy, a few accepting A(:) and eventually passing to A(n).

**Comment by czgdp1807** [comment]
For now I would suggest to use the `A(:)` instead of `A(n)` workarounds. I can't think of an easy fix here because `B(:, 2)` and general cases like, `B(i:j, k)` can't be passed by just data pointer. You need the lower bounds, the upper bounds, the offset to index it correctly. One way is to just spot calls like,  

```fortran
print *, mysum(size(B, 1), B(:, 2))
```

and then duplicate `mysum` to accept `A(:)` instead of `A(n)`.

Also there will be cases like, 

```fortran
real, pointer :: Bp(:)
Bp => B(:, 2)
print *, mysum(size(B, 1), Bp)
```

Here `Bp` always needs a descriptor but since `mysum` accepts a data pointer so all the crucial indexing information like lower bounds, upper bounds and offsets never reach `mysum`.

**Comment by certik** [comment]
This will not work --- it will fail when calling C that requires a data pointer.

The solution is simple: `B(:,2)` can be passed as a data pointer easily. It is contiguous. And remember, you do not pass any lower and upper bounds into the function --- that is another huge bug that I had to workaround. Inside a function the lower bound is always 1 (unless specified otherwise inside the function), no matter what the lower bound was outside the function. The upper bound is simply the lower bound + size.

**Comment by certik** [comment]
> you need a descriptor to index B(:, 2) correctly inside a function.

You don't need a descriptor. You might need a temporary copy of the array if it is not contiguous (other Fortran compilers do that), but in fastGPT all the arrays are contiguous, I made sure of that.

Given this fact, do you recommend to simply update ArrayPhysicalCast to offset the data pointer by "offset" (that is part of the descriptor, if I understand it correctly)?

**Comment by czgdp1807** [comment]
> Given this fact, do you recommend to simply update ArrayPhysicalCast to offset the data pointer by "offset" (that is part of the descriptor, if I understand it correctly)?

Okay

**Comment by czgdp1807** [comment]
> And remember, you do not pass any lower and upper bounds into the function --- that is another huge bug that I had to workaround. Inside a function the lower bound is always 1 (unless specified otherwise inside the function), no matter what the lower bound was outside the function. The upper bound is simply the lower bound + size.

We will have to fix this by handling descriptor to descriptor array passing. Basically create a new descriptor and set its data pointer to the original one (+ the offset), fill the lower bounds and upper bounds correctly. Cleanest way to do this is to allow `ArrayPhysicalCast.old == ArrayPhysicalCast.new` when the physical type is `DescriptorArray`.

**Comment by certik** [comment]
Yes, exactly.
