### ISSUE TITLE
Licensing Information

### ISSUE THREAD

**Issue by bkmgit** [lfortran/lfortran#2097]
It would be helpful to indicate that some of the included software has licenses other than BSD-3-Clause:

- Apache License 2.0
   + [src/libasr/codegen/KaleidoscopeJIT.h](https://github.com/lfortran/lfortran/blob/main/src/libasr/codegen/KaleidoscopeJIT.h)
- MIT
   + [src/bin/tpl/whereami/whereami.cpp](https://github.com/lfortran/lfortran/blob/main/src/bin/tpl/whereami/whereami.cpp)
   + [src/bin/tpl/whereami/whereami.h](https://github.com/lfortran/lfortran/blob/main/src/bin/tpl/whereami/whereami.h)
   + [src/tests/doctest.h](https://github.com/lfortran/lfortran/blob/main/src/tests/doctest.h)

**Comment by certik** [comment]
Yes, we should put this into the LICENSE file. Good catch.
