### ISSUE TITLE
Emit warning for "complex*8"

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2104]
This can be a good first issue!

Issue reference: https://github.com/lfortran/lfortran/pull/1680
Refer: https://github.com/lfortran/lfortran/pull/2094 to resolve

**Comment by Pranavchiku** [comment]
@HarshitaKalani let's properly document what needs to  be done as it is a good first issue, you may improve the template provided below:

---
## Description
Add a warning whenever a variable is declared using the `complex*8` pattern.

## Minimal Code
```fortran
program main
    complex*8 :: x
end program
```

## Expected Outcome
```console
% lfortran a.f90
style suggestion: Use real(8) instead of real*8
 --> a.f90
  |
6 | complex*8 :: x
  | ^^^^^^ help: write this as 'complex(8)'
```

## Reference

PR: https://github.com/lfortran/lfortran/pull/2094

**Comment by HarshitaKalani** [comment]
Hey thanks. I'll take a note of this!

**Comment by HarshitaKalani** [comment]
@Pranavchiku can you please change 
```console
style suggestion: Use real(8) instead of real*8
```
to 
```console
style suggestion: Use complex(8) instead of complex*8
```
