### ISSUE TITLE
Emit warning for "logical*4"

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2105]
This can be a good first issue!

Issue reference: https://github.com/lfortran/lfortran/issues/1680
Refer: https://github.com/lfortran/lfortran/pull/2094 to resolve

**Comment by Pranavchiku** [comment]
Apply same as https://github.com/lfortran/lfortran/issues/2104#issuecomment-1667501520

**Comment by HarshitaKalani** [comment]
### Description
Add a warning whenever a variable is declared using the logical*4 pattern.

### Minimal Code
```
program main
    logical*4 :: x
end program
```

### Expected Outcome
```
% lfortran a.f90
style suggestion: Use logical(4) instead of logical*4
 --> a.f90
  |
6 | logical*4:: x
  | ^^^^^^ help: write this as 'logical(4)'
```

### Reference
PR: https://github.com/lfortran/lfortran/pull/2094
