### ISSUE TITLE
-x for x=0 does not return -0

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2138]
Minimal example:
```fortran
program sign_01
   real :: x
   x = -0.0
   print *, x
   x = -x
   print *, x
   x = -x
   print *, x
end program
```
behaves differently in GFortran and LFortran
```console
$ lfortran sign_01.f90 
-0.00000000e+00
0.00000000e+00
0.00000000e+00
$ gfortran sign_01.f90 && ./a.out
  -0.00000000    
   0.00000000    
  -0.00000000    
```

**Comment by certik** [comment]
This is due to the fact that we implement `-x` as `0-x` in the LLVM backend.

**Comment by Pranavchiku** [comment]
I feel I encountered this issue with SciPy: https://github.com/lfortran/lfortran/issues/2131#issuecomment-1674292575

**Comment by certik** [comment]
This might be fixed by https://github.com/lfortran/lfortran/pull/2186.

**Comment by Pranavchiku** [comment]
This works. I feel will have to revert #2133.

**Comment by certik** [comment]
The example now prints:
```
$ lfortran a.f90
-0.00000000e+00
0.00000000e+00
-0.00000000e+00
```
So it works.
