### ISSUE TITLE
CI: `llvmReAllocLHS` and `llvmUseLoopVariableAfterLoop` are not tested

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#2152]
The `integration_tests/CMakeLists.txt` backends `llvmReAllocLHS` and `llvmUseLoopVariableAfterLoop` are not tested at the CI.

**Comment by Pranavchiku** [comment]
`llvmUseLoopVariableAfterLoop` is tested at https://github.com/lfortran/lfortran/blob/main/integration_tests/CMakeLists.txt#L949

**Comment by Pranavchiku** [comment]
`llvmReAllocLHS` is tested at https://github.com/lfortran/lfortran/blob/main/integration_tests/CMakeLists.txt#L977

**Comment by Pranavchiku** [comment]
Ahh, I see, the tests with the given flags are not working on CI. Thanks for working on it, @Shaikh-Ubaid!

**Comment by certik** [comment]
Yep, we added a test without testing that it actually works. That's the danger of modifying the cmake. I think @Shaikh-Ubaid's approach will allow us to test more compiler flags without modifying the macros, thus hopefully things will keep working.
