### ISSUE TITLE
Print ASR after every pass

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2194]
It must print it after each pass and the very first ASR, *before* ASR verify is called, since it can fail.

Both in LPython and LFortran. This will greatly simplify debugging. This is quite urgent now, since I now hit this almost every day and so is everyone else.

**Comment by Thirumalai-Shaktivel** [comment]
This should only happen  when we pass some option like `--verbose`, right?

Also, I had a thought of printing the ASR along with the ASR verify fail.

**Comment by certik** [comment]
Yes, I would add a new option for this.
