### ISSUE TITLE
webpage: add a progress bar towards beta

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2290]
Right now it would be at 2/10, and it needs to get to 10/10. From here: https://www.hongkiat.com/blog/beautiful-progress-bars/ I like the designs 10, 33 and at https://www.template.net/design-templates/web-elements/progress-bar-design/ I like the second design. Using a green color seems good, and there should be visible 10 parts, and only 2/10 highlighted. Underneath we will list all the codes that we can compile, with links to the respective blog posts.

**Comment by Thirumalai-Shaktivel** [comment]
https://gitlab.com/lfortran/web/www.lfortran.org/-/merge_requests/100

**Comment by certik** [comment]
This is now fixed:
<img width="984" alt="Screen Shot 2023-09-03 at 2 51 12 PM" src="https://github.com/lfortran/lfortran/assets/20568/52b40a41-7cc4-4bc5-9743-3fb2a32f6f06">
