### ISSUE TITLE
Have all elements of an array in a single StringFormat expression while printing arrays

### ISSUE THREAD

**Issue by gptsarthak** [lfortran/lfortran#2344]
In ```print_arr.cpp```, right now we make a new ```print``` statement for every element for the array.
For more consistent formatting, we need to have all the elements of the array in a single ```print``` statement, more specifically a single ```StringFormat``` expression. How can we do that?
This is what we do right now:
https://github.com/lfortran/lfortran/blob/66e1814f51cfcaada54fb1a4ee9daf70dbb699f9/src/libasr/pass/print_arr.cpp#L56-L107

Please let me know if the description is not clear.

**Comment by certik** [comment]
Good question. Can you post here a minimal Fortran example showing the issue? Let's figure out a good solution.

**Comment by gptsarthak** [comment]
Since we pass the arguments one by one, we do not know the total number of arguments in ```lfortran_intrinsics.c```. Hence, we will not be able to print newlines correctly.
Example:
```fortran
program test
    integer :: x(10)
    x = 1
    print '(6(i6))', x
end
```
```console
(lf) $ lfortran examples/hi.f90
     1     1     1     1     1     1     1     1     1     1
(lf) $ gfortran examples/hi.f90 && ./a.out
     1     1     1     1     1     1
     1     1     1     1
```

**Comment by certik** [comment]
How about this:
```diff
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -297,7 +297,7 @@ expr
     | StringCompare(expr left, cmpop op, expr right, ttype type, expr? value)
     | StringOrd(expr arg, ttype type, expr? value)
     | StringChr(expr arg, ttype type, expr? value)
-    | StringFormat(expr fmt, expr* args, string_format_kind kind, ttype type, expr? value)
+    | StringFormat(expr fmt, expr* args, expr? packed_args string_format_kind kind, ttype type, expr? value)
 
     | CPtrCompare(expr left, cmpop op, expr right, ttype type, expr? value)
     | SymbolicCompare(expr left, cmpop op, expr right, ttype type, expr? value)
```
and we take the RHS and create a runtime sized array, and pass it as`packed_args` in StringFormat
