### ISSUE TITLE
Improvements to --dump-all-passes

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2350]
Things we should improve:

* [x]  The initial ASR must be printed
* [x]  prefix all passes with "pass_", so that one can remove them by "rm pass_*"
* [x]  Use Clojure comments for the top "ASR after applying the pass: nested_vars"
* [x] Remove the spurious:
``` console
$ lfortran --show-llvm --dump-all-passes a.f90
rm: pass_*: No such file or directory
Warning: old `pass_*` files are not removed!
```

**Comment by Thirumalai-Shaktivel** [comment]
Fixed here: https://github.com/lfortran/lfortran/pull/2353 & https://github.com/lfortran/lfortran/pull/2420
