### ISSUE TITLE
Return type ignored in function definitions

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#236]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/138

The `return_type` of functions is always none and the type of return variable defaults to `Integer` even after explicitly stating otherwise.
Even if I manually define the function or the variable as `real`, before or inside the function, it still remains as `Integer`.

**Comment by lucifer1004** [comment]
This should have been fixed. @certik

**Comment by certik** [comment]
Yes, this is fixed, thanks!
