### ISSUE TITLE
 Allow declaration of return type of functions like real*8 sqrt

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2398]
Reference: https://github.com/lfortran/lfortran/issues/2345
```lfortran 
program main
real*8 x, sqrt
x = sqrt(9d0)
print *, x
end program
```
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ gfortran a.f90 && ./a.out 
   3.0000000000000000     
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90
Internal Compiler Error: Unhandled exception
^C
```

**Comment by gptsarthak** [comment]
It will work if you use ```--implicit-interface```.
@certik shall we make it so that it does not need that option anymore?

**Comment by certik** [comment]
I missed the part that `sqrt` was declared as a variable. This definitely should not be allowed by default. However, LFortran must give a nice error message saying "`sqrt` was declared as a variable, it can't be called as a function".

**Comment by Pranavchiku** [comment]
I feel `real*8 sqrt` is indicating to use `dsqrt` i.e. return type will be double precision real number. we have a similar case for entry function, where `double precision :: a` denotes the return type of entry function.
```fortran
subroutine sub()
double precision :: a

entry a()
print *, "entry function"
return
end subroutine
```

**Comment by HarshitaKalani** [comment]
Closing with reference to #2395.
