### ISSUE TITLE
ADVANCE not working

### ISSUE THREAD

**Issue by jkd2016** [lfortran/lfortran#2413]
The following code does not compile on lfortran:

```
program test
implicit none

write(*,'("Hello ")',advance='NO')
write(*,'("world!")')

end program
```

and reports:

```
semantic error: ADVANCE= specifier must have value = YES or NO
```

The code works fine on Intel Fortran and GFortran.

**Comment by certik** [comment]
Thanks! The above code compiles with "NO" replaced by "no". This is easy to fix.

The other issue is that formatting in write is not implemented yet.

@gptsarthak, do you want to implement this? I think it would not be difficult.
