### ISSUE TITLE
[SciPy]: code generation error on passing external function to subroutine

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#2449]
Once #2446 is merged we get, 

```fortran
SUBROUTINE COBYLA (CALCFC)
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
EXTERNAL CALCFC
CALL COBYLB (CALCFC)
RETURN
END
SUBROUTINE COBYLB (CALCFC)
IMPLICIT DOUBLE PRECISION (A-H,O-Z)
EXTERNAL CALCFC
CALL CALCFC(CON)
RETURN
END
```

> LFortran

```console
% lfortran b.f90 --show-llvm --implicit-typing --implicit-interface
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @cobyla(double ()* %calcfc) {
.entry:
  call void @cobylb(double ()* %calcfc)
  br label %return

unreachable_after_return:                         ; No predecessors!
  br label %return

return:                                           ; preds = %unreachable_after_return, %.entry
  ret void
}

declare double @calcfc()

define void @cobylb(void (double*)* %calcfc) {
.entry:
  %con = alloca double, align 8
  call void %calcfc(double* %con)
  br label %return

unreachable_after_return:                         ; No predecessors!
  br label %return

return:                                           ; preds = %unreachable_after_return, %.entry
  ret void
}

declare void @calcfc.1(double*)
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
double ()* %calcfc
 void (double*)*  call void @cobylb(double ()* %calcfc)
```

**Comment by Pranavchiku** [comment]
This happens because `calcfc` in `cobylb` is expecting a function argument whereas, the `calcfc` passed from `call cobylb(calcfc)` does not contain a function argument.

**Comment by Pranavchiku** [comment]
One possible way to resolve this is whenever we update the template external function here at `CALL CALCFC(CON)` we may iterate over entire ASR and update `CALCFC` nodes. I do not find this method convincing, we might need to see if there can be any better way to handle external. 

cc @certik

**Comment by certik** [comment]
Looks like that only with `--implicit-interface` we should remember that the `CALCFC` node is implicit and will be updated as more information is recovered. Without `--implicit-interface` we will not bother (for faster compilation).

**Comment by certik** [comment]
Alternatively, we can treat it on a per function basis --- so the two `EXTERNAL CALCFC` will have different signatures, and in LLVM they will be two different names, so that they do not clash. But somehow pointing to the same C function. And the external function would have to be bind(c). That might work.

**Comment by certik** [comment]
We need to figure out if one of these works in LLVM:

* Either two different names `CALCFC1` and `CALCFC2` both pointing to the same C function `CALCFC`
* Or declaring `CALCFC` twice with two different interfaces

If one of these approaches work, then let's use it. If it doesn't work, then we need to reconcile the interface across the whole translation unit in ASR.

**Comment by certik** [comment]
With the latest main I am now getting:
```console
$ lfortran b.f90 --show-llvm --implicit-typing --implicit-interface
; ModuleID = 'LFortran'
source_filename = "LFortran"

define void @cobyla(void (double*)* %calcfc) {
.entry:
  call void @cobylb(void (double*)* %calcfc)
  br label %return

unreachable_after_return:                         ; No predecessors!
  br label %return

return:                                           ; preds = %unreachable_after_return, %.entry
  ret void
}

declare void @calcfc(double*)

define void @cobylb(void (double*)* %calcfc) {
.entry:
  %con = alloca double, align 8
  call void %calcfc(double* %con)
  br label %return

unreachable_after_return:                         ; No predecessors!
  br label %return

return:                                           ; preds = %unreachable_after_return, %.entry
  ret void
}

declare void @calcfc.1(double*)
```

**Comment by certik** [comment]
This now works and there is a test in `tests/external_02.f90`. So we can close this now.
