### ISSUE TITLE
CI: automatically build a docker image for the latest master

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2478]
And upload somewhere. Requested at https://fortran-lang.discourse.group/t/testing-lfortran-string-formatting/6543/7.

**Comment by ivan-pi** [comment]
Docker is also the preferred way of nightly builds for compilers in Compiler Explorer (see related issue #623): https://github.com/compiler-explorer/infra/blob/22d3367f3ffb13de82c5d66551a52de4ca2b1ef7/BuildingCompilers.md

**Comment by certik** [comment]
Excellent, let's set this up at our CI, to ensure the main branch always works, and then we can create a repository at Compiler Explorer as well for them to use.

**Comment by Pranavchiku** [comment]
If no one is on it, I may try exploring. I did a little research from https://www.docker.com/blog/how-to-build-and-test-your-docker-images-in-the-cloud-with-docker-hub/, the documentation is good.

**Comment by certik** [comment]
The docker image now builds, but not in Release mode. Given that the main requested reason was to make it easy to "use" LFortran, as opposed to develop, we need to build in Release mode: https://github.com/lfortran/lfortran/pull/4664.
