### ISSUE TITLE
LFortran needs a logo

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#248]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/161

We had some discussion about it at [Zulip](https://lfortran.zulipchat.com/).

But it is now becoming quite urgent to have a logo:

https://twitter.com/Mbussonn/status/1273827262001889283

**Comment by lucifer1004** [comment]
This can be closed. @certik

**Comment by certik** [comment]
Thanks!
