### ISSUE TITLE
SIMD in C backend

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2500]
The ASR of `tests/pragma2.f90`:
```fortran
program pragma2
!LF$ attributes simd :: A
real :: A(8)
A = 1
end program
```
is (after all ASR->ASR transformations):
```clojure
                    [(DoLoop
                        ()
                        ((Var 2 __1_t)
                        (ArrayBound
                            (Var 2 a)
                            (IntegerConstant 1 (Integer 4))
                            (Integer 4)
                            LBound
                            ()
                        )
                        (ArrayBound
                            (Var 2 a)
                            (IntegerConstant 1 (Integer 4))
                            (Integer 4)
                            UBound
                            ()
                        )
                        ())
                        [(=
                            (ArrayItem
                                (Var 2 a)
                                [(()
                                (Var 2 __1_t)
                                ())]
                                (Real 4)
                                RowMajor
                                ()
                            )
                            (Cast
                                (IntegerConstant 1 (Integer 4))
                                IntegerToReal
                                (Real 4)
                                ()
                            )
                            ()
                        )]
                    )]
```
And this currently generates:
```c
    for (__1_t=((int32_t)a->dims[1-1].lower_bound); __1_t<=((int32_t) a->dims[1-1].length + a->dims[1-1].lower_bound - 1); __1_t++) {
        a->data[(__1_t - a->dims[0].lower_bound)] = (float)(1);
    }
```
Instead, we need this to generate the vector code.

It seems we do not want to apply the vector -> loop transformation for SIMD, but rather keep it in vector form, as it will be easier to translate.

**Comment by certik** [comment]
Several issues:

* Array assignment `a = 1` must be represented as `(Assignment a Broadcast(1, (8,)))` (i.e., casting scalar 1 to an array constant)
* the `array_op` pass should not be applied to SIMD

**Comment by certik** [comment]
Here is the kind of C code that we need to generate:
```c
int main(int argc, char* argv[])
{
    float a __attribute__ (( vector_size(sizeof(float) * 8) )) = {1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0};
    float b __attribute__ (( vector_size(sizeof(float) * 8) )) = {2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0};
    float c __attribute__ (( vector_size(sizeof(float) * 8) )) = a + b;
    return 0;
}
```
One can create "vectors", and initialize them. And then do operations on them. One can also do:
```
    b = (float __attribute__ (( vector_size(sizeof(float) * 8) ))){} + 10;
    float c __attribute__ (( vector_size(sizeof(float) * 8) )) = a + b + 5;
```
as well as:
```
    b = (float __attribute__ (( vector_size(sizeof(float) * 8) ))){2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0};
```
This gives enough examples how to construct everything we need.

In ASR, we really need to now upgrade and represent "a = 1" using Broadcast and/or ArrayConstant. That way in the C backend the translation becomes easier.

**Comment by certik** [comment]
The semantics of these vector types in C is that you can't assign `a = 1`, so constants at the RHS of an assignment do not broadcast. However, you can do `a + b + 5`, or even `(float __attribute__ (( vector_size(sizeof(float) * 8) ))){} + 10`, so constants broadcast in binary operations.

**Comment by certik** [comment]
The next step is to represent these array operations properly in ASR --- we can't assign `a = 1`, but rather the RHS must be a SIMD array as well. Then it will be quite easy to generate the proper C code.

**Comment by Pranavchiku** [comment]
Can we close this, referring PR: #2517?

**Comment by certik** [comment]
I think so, the initial version is done. Now we need to extend it.
