### ISSUE TITLE
Implement ArrayBroadcast

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2503]
The array operation `a = 1` must be represented as `Assignment(a, ArrayBroadcast(1, shape=[8], value=ArrayConstant([1, 1, 1, 1, 1, 1, 1, 1])))`.

And `x + 4` must be represented as `RealBinOp(x, ArrayBroadcast(4, shape=[8], value=...))`.

The ArrayConstant should only be used for small arrays, say less than 256 for now. For bigger arrays it must be a runtime operation.

**Comment by czgdp1807** [comment]
I assume you want this node in the ASR directly and not via a ASR to ASR pass.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, we had discussed this before and created an issue in LPython / LFortran (but, I'm not able to find it right now)

**Comment by certik** [comment]
Yes, I think we need the node directly.

**Comment by certik** [comment]
Thank you @czgdp1807, great job!
