### ISSUE TITLE
Implement intrinsic `Trailz`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#2530]
```fortran
program main
print *, trailz(6)
end program
```

> GFortran

```console
% gfortran a.f90 && ./a.out
           1
```

Ref: https://gcc.gnu.org/onlinedocs/gcc-4.9.4/gfortran/TRAILZ.html

Implementation can follow following fortran function

```fortran
function trailz(n) result(result)
    integer :: n
    integer :: result
    result = 0
    do while (mod(n,2) == 0)
        n = n/2
        result = result + 1
    end do
end function
```

@Thirumalai-Shaktivel is it possible to call `mod` intrinsic in body of `trailz` intrinsic?

**Comment by Thirumalai-Shaktivel** [comment]
This always crossed my mind, but I didn't find an application to try it.
I think it's possible, you can do
```c
Mod::instantiate_Mod(al, loc, fn_scope, arg_types, return_type, new_args, 0);
```
It returns the function call and you can use it for further operations.
