### ISSUE TITLE
Pickle: print location information

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#257]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/175

There should be an optional argument to `pickle` to print location information. In the tests we either add new types like `ast-loc` and `asr-loc`, or we always print it in tests.

We have to test that it is correct, but for user information such as in the interactive mode, the location information makes things longer and less readable, so it should be optional.

**Comment by Shaikh-Ubaid** [comment]
>There should be an optional argument to pickle to print location information. In the tests we either add new types like ast-loc and asr-loc, or we always print it in tests.
>We have to test that it is correct, but for user information such as in the interactive mode, the location information makes things longer and less readable, so it should be optional.

We have json formats for AST and ASR which contains the location information. Does this issue seem fixed?

**Comment by certik** [comment]
I think that's good enough.
