### ISSUE TITLE
macOS Intel: missing "___isPlatformVersionAtLeast"

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2582]
https://github.com/conda-forge/lfortran-feedstock/pull/48#issuecomment-1751811444

```
2023-10-07T20:25:19.5552440Z Undefined symbols for architecture x86_64:
2023-10-07T20:25:19.5553840Z   "___isPlatformVersionAtLeast", referenced from:
2023-10-07T20:25:19.5590550Z       llvm::sys::fs::copy_file(llvm::Twine const&, llvm::Twine const&) in libLLVMSupport.a(Path.cpp.o)
2023-10-07T20:25:19.5593560Z       llvm::set_thread_priority(llvm::ThreadPriority) in libLLVMSupport.a(Threading.cpp.o)
2023-10-07T20:25:19.6313870Z ld: symbol(s) not found for architecture x86_64
```

This issue happens when compiling on x86_64 on macOS, but only happens on the "arm" cross-compilation runner. The x86_64 macOS runner succeeds, but it is using llvmdev =11.1.0, while the arm runner is using llvmdev =16.0.0.

**Comment by certik** [comment]
With LLVM 16, it happens on the regular macOS Intel runner also:
```
[ 90%] Linking CXX executable lfortran
Undefined symbols for architecture x86_64:
  "___isPlatformVersionAtLeast", referenced from:
      llvm::sys::fs::copy_file(llvm::Twine const&, llvm::Twine const&) in libLLVMSupport.a(Path.cpp.o)
      llvm::set_thread_priority(llvm::ThreadPriority) in libLLVMSupport.a(Threading.cpp.o)
  "_clonefile", referenced from:
      llvm::sys::fs::copy_file(llvm::Twine const&, llvm::Twine const&) in libLLVMSupport.a(Path.cpp.o)
  "_pthread_set_qos_class_self_np", referenced from:
      llvm::set_thread_priority(llvm::ThreadPriority) in libLLVMSupport.a(Threading.cpp.o)
ld: symbol(s) not found for architecture x86_64
```

**Comment by certik** [comment]
According to https://reviews.llvm.org/D90367:

> The __isPlatformVersionAtLeast routine is an implementation of if (@available) check
that uses the _availability_version_check API on Darwin that's supported on
macOS 10.15, iOS 13, tvOS 13 and watchOS 6.

and according to https://forum.openframeworks.cc/t/compile-error-on-vscode-undefined-symbols-for-architecture-x86-64/37529:

> So this seems to be an issue with lib curl which when built on macOS 11.0 ( which we need to do for arm64 ), relies on calls that only exist in Xcode 11 and newer. ( [see the discussion here 102](https://forum.openframeworks.cc/t/of-0-11-1-release-is-out/37359/7) )

**Comment by certik** [comment]
Latest status: https://github.com/conda-forge/lfortran-feedstock/pull/48#issuecomment-1752093867

**Comment by certik** [comment]
This is not a high-priority issue anymore. The workaround we use is to use LLVM 15 which works. This issue seems to be caused by LLVM and it appears wide spread. Here is the conda-forge issue to track this: https://github.com/conda-forge/llvmdev-feedstock/issues/244.

**Comment by Shaikh-Ubaid** [comment]
@certik I think this issue is solved, right?

**Comment by certik** [comment]
Yes, fixed by https://github.com/conda-forge/compiler-rt-feedstock/pull/89.
