### ISSUE TITLE
Implement intrinsic random_number

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#2591]
> Implement Intrinsic `random_number`

To implement this one can follow `generate_random_uniform` implementation
Refer: https://gcc.gnu.org/onlinedocs/gfortran/RANDOM_005fNUMBER.html
```fortran
program random_uniform_function
  implicit none
  real :: random_number

  ! Call the function to get a random number
  call generate_random_uniform(random_number)

  ! Print the generated random number
  print *, "Random Number:", random_number

contains

  subroutine generate_random_uniform(rand)
    implicit none
    real, intent(out) :: rand
    integer, parameter :: m = 2147483647 ! Modulus (2^31 - 1)
    integer, parameter :: a = 1664525    ! Multiplier
    integer, parameter :: c = 1013904223 ! Increment
    integer :: seed = 12345              ! Initial seed

    seed = mod(a * seed + c, m)
    rand = real(seed) / real(m)
  end subroutine generate_random_uniform

end program random_uniform_function
```
Required for: https://github.com/lfortran/lfortran/issues/2444

**Comment by certik** [comment]
Actually, this one is already implemented using the C runtime library, and I believe it even works for one number:
```fortran
$ cat a.f90 
real :: z
call random_number(z)
print *, z
end
```
This works:
```console
$ lfortran a.f90
7.37292051e-01
$ lfortran a.f90
7.37307727e-01
$ lfortran a.f90
7.37307727e-01
$ lfortran a.f90
7.37315536e-01
$ lfortran a.f90
7.37323344e-01
$ lfortran a.f90
7.37331212e-01
$ lfortran a.f90
7.37331212e-01
$ lfortran a.f90
7.37339020e-01
$ lfortran a.f90
7.37339020e-01
$ lfortran a.f90
7.37346828e-01
```
However this is not really random, so it needs to be fixed.

**Comment by Pranavchiku** [comment]
> Actually, this one is already implemented using the C runtime library, and I believe it even works for one number:

Yes, one approach: we can convert subroutine call for elemental intrinsic over array to doloops, but this needs modification in array_ops. Also, this is already handled for IntrinsicScalarFunction in array_op pass, hence I thought of implementing it as an intrinsic function

**Comment by certik** [comment]
Yes, it should be an intrinsic function, actually IntrinsicScalarSubroutine, since it's a statement, not an expression.

**Comment by Pranavchiku** [comment]
I guess we might need to introduce it in `asr.asdl`:
```diff
diff --git a/src/libasr/ASR.asdl b/src/libasr/ASR.asdl
index 5fc7e0247..879e29d99 100644
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -240,6 +240,8 @@ expr
             ttype type, expr? value, expr? dt)
     | IntrinsicScalarFunction(int intrinsic_id, expr* args, int overload_id,
             ttype? type, expr? value)
+    | IntrinsicScalarSubroutine(int intrinsic_id, expr* args, int overload_id,
+            ttype? type)
     | IntrinsicArrayFunction(int arr_intrinsic_id, expr* args, int overload_id,
             ttype? type, expr? value)
     | IntrinsicImpureFunction(int impure_intrinsic_id, expr* args, int overload_id,
```

**Comment by certik** [comment]
Yes, but not there in `expr`, but in `stmt`.

**Comment by certik** [comment]
I know. Ideally we could maybe piggyback on IntrinsicScalarFunction. For example, it could just return the array, and it would take the shape of the array as an argument.

But there is another problem --- the function is not deterministic, and strictly speaking it is not side-effect-free either.

So it would have to be IntrinsicScalarImpureFunction or something.

**Comment by HarshitaKalani** [comment]
This works with the latest main.
The example at the top (https://github.com/lfortran/lfortran/issues/2591#issue-1934495018) gives:
```console
$ lfortran a.f90 --no-warnings
Random Number: 4.08053696e-02
$ gfortran a.f90 && ./a.out
 Random Number:   4.08053696E-02
```

Even the numbers generated are indeed random now. Ref: https://github.com/lfortran/lfortran/issues/2591#issuecomment-1754555972 
```console
$ lfortran a.f90 
8.93648148e-01
$ lfortran a.f90 
7.57668078e-01
$ lfortran a.f90 
6.17273390e-01
$ lfortran a.f90 
8.27870965e-01
$ lfortran a.f90 
1.85671449e-01
$ lfortran a.f90 
5.50825894e-01
$ lfortran a.f90 
4.01341110e-01
$ lfortran a.f90 
2.66168296e-01
```

**Comment by certik** [comment]
For me it doesn't work:
```
$ cat a.f90 
real :: z
call random_number(z)
print *, z
call random_number(z)
print *, z
call random_number(z)
print *, z
end
```
gives:
```
$ lfortran a.f90
5.61876714e-01
5.61876714e-01
5.61876714e-01
```
These are not random.

**Comment by HarshitaKalani** [comment]
Yes, on running the above example, I also get non-random numbers
```console
$ lfortran a.f90
4.44132984e-01
4.44132984e-01
4.44132984e-01
```
I see, this is because there's no time gap between the generation of two random numbers, so for this
```fortran
real :: z
call random_number(z)
print *, z
end
```
if I run it very quickly, I get
```console
$ lfortran a.f90
5.04776001e-01
$ lfortran a.f90
5.04776001e-01
$ lfortran a.f90
3.61989588e-01
$ lfortran a.f90
3.61989588e-01
$ lfortran a.f90
2.19870627e-01
$ lfortran a.f90
2.19870627e-01
```

**Comment by certik** [comment]
It doesn't matter if there is a time gap, each invocation must return a new number. There is a bug somewhere, either in the interface, or casting, or somewhere else.
