### ISSUE TITLE
dftatom: Running conv_lda to all iterations

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2601]
It runs up to about 7 iterations but the 8th iteration gets killed. We do not know yet exactly why it fails, but we have noticed that things improve by giving it more stack via `ulimit -s`. However we also suspect it is running out of memory, so there are memory leaks.

We know about the following issues that we have to fix anyway:

* heap arrays
* memory leaks:
  * allocatable arrays in structs
  * `intent(out), allocatable`
  * strings
  * ... (maybe other cases too)

However something else might also be causing the dftatom problem, so for dftatom fixing the above bugs is neither necessary nor sufficient. For LFortran however it is necessary, so we might as well fix them to eliminate these classes of bugs.

**Comment by Shaikh-Ubaid** [comment]
It seems we now run `conv_lda` to all the iterations. I think this issue is complete? @czgdp1807 @certik

**Comment by Shaikh-Ubaid** [comment]
I am closing this for now. Workarounds like using cycle with a label is noted at https://github.com/lfortran/lfortran/issues/2386.
