### ISSUE TITLE
Should derived type pointer components be freed after usage?

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lfortran/lfortran#2616]
Program:
```fortran
program expr2
implicit none
type t
    integer, pointer :: x(:)
end type t
type(t) :: t_1
integer, target :: x(3)
x = 342
t_1%x => x
print *, t_1%x
end program
```
```console
$ memusage ./expr2.out
342 342 342 

Memory usage summary: heap total: 1044, heap peak: 1044, stack peak: 0
         total calls   total memory   failed calls
 malloc|          3           1044              0
realloc|          0              0              0  (nomove:0, dec:0, free:0)
 calloc|          0              0              0
   free|          0              0
Histogram for block sizes:
    0-15              2  66% ==================================================
 1024-1039            1  33% =========================
```

Also, I wonder how gfortran deallocates the memory, they also don't call `free`:
```console
$ memusage ./a.out   
         342         342         342

Memory usage summary: heap total: 13584, heap peak: 13584, stack peak: 240
         total calls   total memory   failed calls
 malloc|         10           1416              0
realloc|          0              0              0  (nomove:0, dec:0, free:0)
 calloc|         11          12168              0
   free|          0              0
Histogram for block sizes:
    0-15              3  14% ==============================
   16-31              1   4% ==========
   32-47              3  14% ==============================
   96-111             3  14% ==============================
  256-271             1   4% ==========
  512-527             2   9% ====================
  752-767             5  23% ==================================================
 1984-1999            1   4% ==========
 2032-2047            1   4% ==========
 4096-4111            1   4% ==========
```

**Comment by kargl** [comment]
Can you explain what you mean?  The pointer assign to the component of the derived type should not require dynamic memory allocation; and, if you look at gfortran's intermediate representation, you see this.

PS: A Fortran derive type does not have _members_.  It has _components_.

**Comment by Thirumalai-Shaktivel** [comment]
Instead of dynamic allocation, what happens?
Does it store the memory addresses?
Or just point to the array?

**Comment by kargl** [comment]
It seems that you have gfortran.  Try the -fdump-tree-original option with your code.  You'll see
```
  t_1.x.span = 4;
  t_1.x.dtype = {.elem_len=4, .rank=1, .type=1};
  t_1.x.dim[0].lbound = 1;
  t_1.x.dim[0].ubound = 3;
  t_1.x.dim[0].stride = 1;
  t_1.x.data = (void *) &x[0];
  t_1.x.offset = -1;
```
Part of the above is setting up the dope vector.  The salient line is `t_1.x.data = (void*)&x[0]`, i.e., the derived type component points at the statically declared target `x(3)`.  There is no memory allocation.  What you meant to ask is "Should the derived type pointer component free its target?"  The answer is _no_.  A better question would have been should the derived type pointer component be disassociated after usage.  The answer for the given go is either _no_ or _why?_.  The latter concerns the fact the program is exiting so it does not matter.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, got it!
Thanks for the detailed explanation!

**Comment by Thirumalai-Shaktivel** [comment]
I will try to create another MRE for memory leak; this doesn't seem to be an issue.

**Comment by Thirumalai-Shaktivel** [comment]
I'm not sure if leaks would be helpful, but here is the output for the above code
```console
$ leaks --atExit -- ./expr2.out
...
Process:         expr2.out [50291]
Path:            /Users/USER/*/expr2.out
Load Address:    0x1020d8000
Identifier:      expr2.out
Version:         0
Code Type:       ARM64
Platform:        macOS
Parent Process:  leaks [50290]

...

Physical footprint:         3585K
Physical footprint (peak):  3585K
Idle exit:                  untracked
----

leaks Report Version: 4.0, multi-line stacks
Process 50291: 187 nodes malloced for 14 KB
Process 50291: 0 leaks for 0 total leaked bytes.
```

**Comment by Thirumalai-Shaktivel** [comment]
@kargl do you know any other tool to detect memory leak in the program execution?

**Comment by certik** [comment]
Thanks @kargl for the explanation.

@Thirumalai-Shaktivel yes, the derived type does not deallocate any pointer components (members), but it deallocates allocatable array components (recursively if needed) when it goes out of scope. However, if it is in the main program, then it doesn't need to.

Regarding tools for memory leaks: we should create our own Debug runtime malloc implementation that will track this for us, so we will know exactly what got leaked. The compiler can even cooparate with it and give it the precise location information. I believe valgrind does something similar, so you can try using it.

The other sources of memory leaks can come from LLVM if we execute "alloca" inside a do loop, say in the main program or some long running function. It's not technically a leak, since it gets deallocated on function exit, but we can run out of stack easily that way. This is similar to allocating arrays on stack, we can run out of stack that way.

**Comment by Thirumalai-Shaktivel** [comment]
Yup, I came across Valgrind; I will give it a try.
Thanks for the detailed explanation.
