### ISSUE TITLE
Implement & & line concatenation

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#263]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/194

The & at the end of the line works, but & at the end and & at the new line doesn't yet: it should concatenate the lines and connect tokens together. As such this might need to be a pre-processing stage before tokenizer.

**Comment by lucifer1004** [comment]
This should have been fixed. @certik

**Comment by certik** [comment]
Yes, this is fixed as well, thanks!
