### ISSUE TITLE
SciPy: Quadpack

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2714]
With the workarounds mentioned here: https://github.com/certik/scipy/commits/quadpack_01, LFortran passes all the tests of quadpack.

**Comment by Pranavchiku** [comment]
You may not need the workarounds after #2716 is merged.

**Comment by certik** [comment]
@HarshitaKalani go ahead and see which workarounds can be removed here.

**Comment by HarshitaKalani** [comment]
These are the workarounds to compile and pass all the tests of `quadpack` package with the latest main: https://github.com/certik/scipy/commits/quadpack_02

**Comment by HarshitaKalani** [comment]
```fortran
recursive subroutine dqc25c()
external dqwgtc 
call dqk15w(dqwgtc)
end

program main
      call dqc25c()
end
```
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ gfortran a.f90 && ./a.out
/usr/bin/ld: /tmp/ccwoL9Uq.o: in function `dqc25c_':
a.f90:(.text+0x7): undefined reference to `dqwgtc_'
/usr/bin/ld: a.f90:(.text+0xf): undefined reference to `dqk15w_'
collect2: error: ld returned 1 exit status
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran a.f90  --implicit-typing --implicit-interface --generate-object-code --use-loop-variable-after-loop  --legacy-array-sections
Internal Compiler Error: Unhandled exception
^C
```
This is some issue with use of `external dqwgtc` in subroutine but I'm not sure why is it so.

**Comment by HarshitaKalani** [comment]
After #2800 gets merged, we'll be able to pass all the tests for `Quadpack` without any workaround/ patches.
I've pushed the latest commits here: https://github.com/certik/scipy/commits/quadpack_03

**Comment by certik** [comment]
It's merged. Great job!

**Comment by Pranavchiku** [comment]
Can we close the packages we test and compile correctly?

**Comment by HarshitaKalani** [comment]
Closing with reference to: #2811
