### ISSUE TITLE
Syntax error with DATA statement

### ISSUE THREAD

**Issue by rikardn** [lfortran/lfortran#2727]
The following short module:

```fortran
      MODULE VERSION
        CHARACTER(LEN=80) :: LEV
        DATA LEV/'1.0 '/
      END MODULE VERSION
```

gives the following syntax error when trying to compile with lfortran:

```
syntax error: Token 'DATA' (of type 'data') is unexpected here
 --> module.f90:3:9
  |
3 |         DATA LEV/'1.0 '/
  |         ^^^^ 
```

gfortran can compile this without issues.

**Comment by Thirumalai-Shaktivel** [comment]
Thanks @rikardn for the bug report!
I can see that we didn't support data statements in the module scope.

**Comment by certik** [comment]
Ha, a syntax error! Thanks @rikardn for finding it, it's quite rare to find a syntax error.

**Comment by gxyd** [comment]
This was fixed in https://github.com/lfortran/lfortran/pull/4667. So, closing this issue.

**Comment by gxyd** [comment]
Yes please. Kindly let us know if you encounter any other issue :)
