### ISSUE TITLE
[asr->fortran] visit symbols in Module visitor

### ISSUE THREAD

**Issue by khushi-411** [lfortran/lfortran#2737]
> I think we need to visit the symbols present in a module.

> https://github.com/lfortran/lfortran/blob/34e92d66f0323f0792dc1d6ae8c924d3442117eb/src/libasr/codegen/asr_to_fortran.cpp#L253-L265

> Currently, we skip visiting those symbols and therefore in the fortran code, we did not get the definition of "repeati32/i64" generated.

Originally posted by @Shaikh-Ubaid in https://github.com/lfortran/lfortran/pull/2630#discussion_r1373904339

**Comment by khushi-411** [comment]
I'll work on this.

**Comment by Thirumalai-Shaktivel** [comment]
I needed this fix, so I would work on this issue.

**Comment by Thirumalai-Shaktivel** [comment]
This issue seems to be fixed here: https://github.com/lfortran/lfortran/pull/2747
