### ISSUE TITLE
Several templates bugs

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2771]
```fortran
requirement bin_op(T, U, V, op)
  type, deferred :: T, U, V
  interface
    elemental function op(a, b)
      type(T), intent(in) :: a
      type(U), intent(in) :: b
      type(V) :: op
    end function
  end interface
end requirement

template axpy_tmpl(T, U, V, W, plus, times)
  private
  public :: axpy
  requires bin_op(V, W, V, plus)
  requires bin_op(T, U, W, times)
  interface axpy
    procedure axpy_
  end interface
contains
  subroutine axpy_(a, x, y)
    type(T), intent(in) :: a
    type(U), intent(in) :: x(:)
    type(V), intent(inout) :: y(:)

    y = plus(y, times(a,  x))
  end subroutine
end template

integer, parameter :: sp = kind(1.0), dp = kind(1.d0)
instantiate axpy_tmpl( &
    real(sp), integer, real(dp), real(sp), operator(+), operator(*))
real(sp) :: a
integer :: x(3)
real(dp) :: y(3)
a = 0.5
x = 2
y = 0
call axpy(a, x, y)
print *, y
end
```

Currently it gives:
```console
$ lfortran a.f90 
syntax error: Token 'bin_op' (of type 'identifier') is unexpected here
 --> a.f90:1:13
  |
1 | requirement bin_op(T, U, V, op)
  |             ^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by certik** [comment]
There are several bugs, after workarounds, the following compiles and runs:
```fortran
module M

requirement bin_op(T, U, V, op)
  type, deferred :: T
  type, deferred :: U
  type, deferred :: V
  interface
    elemental function op(a, b)
      type(T), intent(in) :: a
      type(U), intent(in) :: b
      type(V) :: op
    end function
  end interface
end requirement

template axpy_tmpl(T, U, V, W, plus, times)
  private
  public :: axpy
  require :: bin_op(V, W, V, plus)
  require :: bin_op(T, U, W, times)
contains
  subroutine axpy(a, x, y)
    type(T), intent(in) :: a
    type(U), intent(in) :: x(:)
    type(V), intent(inout) :: y(:)

! Does not work yet:
!    y = plus(y, times(a,  x))
    integer :: i
    do i = 1, size(x)
        y(i) = plus(y(i), times(a, x(i)))
    end do
  end subroutine
end template

contains

subroutine f()
integer, parameter :: sp = kind(1.0), dp = kind(1.d0)
instantiate axpy_tmpl(real, real, real, real, operator(+), operator(*))
real :: a
real :: x(3)
real :: y(3)
a = 0.5
x = 2
y = 0
call axpy(a, x, y)
print *, y
end subroutine

end module

program xx
use M, only: f
call f()
end program
```
This gives:
```console
$ lfortran a.f90
1.00000000e+00 1.00000000e+00 1.00000000e+00 
```

**Comment by certik** [comment]
Of these, the highest priority is the type handling `real(sp), integer, real(dp)`, etc. Everything else I think is cosmetic and low priority.

**Comment by ansharlubis** [comment]
@certik I'm a bit confused about changing the parser for `Instantiate`. Currently it's
```
    | Instantiate(identifier name, use_symbol* args, use_symbol* symbols)
```
And we need to have `real(4)` in the args. But there is no corresponding construct in `use_symbol`.

**Comment by certik** [comment]
We will need to change the AST to accommodate this.

**Comment by ansharlubis** [comment]
Do you have any suggestions on what type of construct I should use? By the looks of this, it feels like using `decl_attribute` like the one I showed you last week is the best option.

**Comment by certik** [comment]
I would recommend to first fix https://github.com/lfortran/lfortran/issues/2780 and just use "real" and "integer". That will work with the current AST. I think that's the highest priority.

The refactoring of AST is a separate issue, and it might take us some time to get right. The `decl_attribute` is one option, but if I remember there was a fundamental limitation in your PR of not working with keywords. Let's think.

* We need to accept any type. It can be arbitrarily complicated, such as `real(dp=int(sin(0.5)**3 + x * ...))`. This is handled by `AttrType`. So `decl_attribute` is a good one to use for that.
* We need to accept `operator(+)`.  That's handled by `IntrinsicOperator` which is a `use_symbol`.
* We also need to accept any function name, such as `real_add`, but it can be any keyword too, like `final`. That's `identifier` in AST, and typically that would be `Name`, which is an `expr`.

So we need to refactor the AST, or add some node, that can be a combination of `AttrType`, `IntrinsicOperator` and `Name`, so in the current design a combination of `decl_attribute`, `use_symbol` and `expr`.

At the AST level, it could be done by something like:
```
--- a/grammar/AST.asdl
+++ b/grammar/AST.asdl
@@ -69,7 +69,7 @@ unit_decl2
     | Template(identifier name, identifier* namelist, unit_decl2* decl,
         program_unit* contains)
     | Enum(decl_attribute* attr, trivia? trivia, unit_decl2* items)
-    | Instantiate(identifier name, use_symbol* args, use_symbol* symbols)
+    | Instantiate(identifier name, instantiate_symbol* args, use_symbol* symbols)
     | Requirement(identifier name, identifier* namelist, unit_decl2* decl,
         program_unit* funcs)
     | Require(unit_require* reqs)
@@ -455,4 +455,9 @@ pragma_type
 unit_require
     = UnitRequire(identifier name, identifier* namelist)
 
+instantiate_symbol
+    = InstantiateType(decl_attribute type) -- AttrType
+    | InstantiateOperator(use_symbol op) -- IntrinsicOperator
+    | InstantiateFunctionName(expr name) -- Name
+
 }
```
Note that if it just says `real`, we do not know if it is `InstantiateType` (type `real`) or `InstantiateFunctionName` (function name `real`), since this can only be determined by semantics. So we would just choose one, and then in semantics we would determine if it is a type or a function and act accordingly.

I think the above could work.


Now we need to figure out how to parse it. We need to do something similar in the parser, and ensure that it can parse all the cases above.

**Comment by ansharlubis** [comment]
Thanks for the suggestion. I'll start with the type mixing first before the parser.

**Comment by certik** [comment]
Here is a TODO list to fix this issue:

* [x] https://github.com/lfortran/lfortran/issues/2780
* [ ] `real(dp)`, `real(sp)`, will be fixed by https://github.com/lfortran/lfortran/pull/2803
* [ ] `type, deferred :: T, U, V`
* [ ] `y = plus(y, times(a,  x))`
* [ ] `interface axpy`
* [ ] templates in the main program (currently I think it only works in a module)
* [ ] main program without "program" and templates (we have some heuristics to tackle this, and I think it might not work for a template)

**Comment by certik** [comment]
@everythingfunctional as of the latest master almost everything works now, see the previous comment for the remaining issues to fix. Here is the code that now works, the only fixes I made to it are for each of the "unfixed" point above:
```fortran
program test_templates
requirement bin_op(T, U, V, op)
  type, deferred :: T
  type, deferred :: U
  type, deferred :: V
  interface
    elemental function op(a, b)
      type(T), intent(in) :: a
      type(U), intent(in) :: b
      type(V) :: op
    end function
  end interface
end requirement

template axpy_tmpl(T, U, V, W, plus, times)
  private
  public :: axpy
  require :: bin_op(V, W, V, plus)
  require :: bin_op(T, U, W, times)
contains
  subroutine axpy(a, x, y)
    type(T), intent(in) :: a
    type(U), intent(in) :: x(:)
    type(V), intent(inout) :: y(:)

    integer :: i
    do i = 1, size(x)
        y(i) = plus(y(i), times(a, x(i)))
    end do
  end subroutine
end template

integer, parameter :: sp = kind(1.0), dp = kind(1.d0)
instantiate axpy_tmpl( &
    real(sp), integer, real(dp), real(sp), operator(+), operator(*))
real(sp) :: a
integer :: x(3)
real(dp) :: y(3)
a = 0.5
x = 2
y = 0
call axpy(a, x, y)
print *, y
end
```
