### ISSUE TITLE
CI flaky test: `Binary content is not handled by write(..)`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2776]
https://github.com/lfortran/lfortran/actions/runs/6729033405/job/18289267264
```
+ /home/runner/work/lfortran/lfortran/modern_minpack_01/../src/bin/lfortran ./examples/example_lmder1.f90 --legacy-array-sections
Binary content is not handled by write(..)
```

It looks like this is a real bug that only manifests sometimes. We need to investigate and fix.

**Comment by Thirumalai-Shaktivel** [comment]
I think we have to initialise the flag there.

**Comment by certik** [comment]
Another one: https://github.com/lfortran/lfortran/actions/runs/6735922977/job/18310181593?pr=2782
