### ISSUE TITLE
library not found for -lgfortran

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#2828]
```console
$ cat examples/expr2.f90 
program expr2
implicit none

integer :: x

x = (2+3)*5
print *, x

end program
$ lfortran examples/expr2.f90 --backend fortran
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o expr2.out expr2.out.tmp.o  -L"/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/ubaid/Desktop/OpenSource/lfortran/src/bin/../runtime" -llfortran_runtime -lm -L"$CONDA_PREFIX/lib" -Wl,-rpath,"$CONDA_PREFIX/lib/" -lgfortran' failed.
```

If we install `gfortran` in the conda environment using `conda install -c conda-forge gfortran`, the `lfortran` project itself fails to build.

```console
...
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/iosfwd:236:14: error: use of undeclared identifier 'mbstate_t'
typedef fpos<mbstate_t>    u32streampos;
             ^
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/cstdint:157:9: error: no member named 'uint8_t' in the global namespace
using ::uint8_t _LIBCPP_USING_IF_EXISTS;
      ~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
In file included from /Users/ubaid/Desktop/OpenSource/using ::size_t _LIBCPP_USING_IF_EXISTS;
      ~~^
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/cstddef:53:9: error: no member named 'max_align_t' in the global namespace
using ::max_align_t _LIBCPP_USING_IF_EXISTS;
      ~~^
lfortran/src/libasr/pass/nested_vars.cpp:1:
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/../libasr/asr.h:6:
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/../libasr/alloc.h:4:
In file included from /Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/algorithm:664:
In file included from /Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/__debug:15:
In file included from /Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/type_traits:420:
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/cstddef:49:9: error: no member named 'ptrdiff_t' in the global namespace
using ::ptrdiff_t _LIBCPP_USING_IF_EXISTS;
      ~~^
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/cstddef:50:9: error: no member named 'size_t' in the global namespace
using ::size_t _LIBCPP_USING_IF_EXISTS;
      ~~^
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/cstddef:53:9: error: no member named 'max_align_t' in the global namespace
using ::max_align_t _LIBCPP_USING_IF_EXISTS;
      ~~^
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/pass/nested_vars.cpp:1:
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/../libasr/asr.h:6:
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/../libasr/alloc.h:4:
In file included from /Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/algorithm:664:
In file included from /Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/__debug:15:
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/type_traits:1472:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, 0> {};
                               ^
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/type_traits:1472:38: error: expected expression
    : public integral_constant<size_t, 0> {};
                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/codegen/asr_to_julia.cpp:1:
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/../libasr/asr.h:6:
In file included from /Users/ubaid/Desktop/OpenSource/lfortran/src/libasr/../libasr/alloc.h:4:
In file included from /Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/algorithm:664:
In file included from /Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/__debug:15:
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/type_traits:1472:32: error: use of undeclared identifier 'size_t'; did you mean 'sizeof'?
    : public integral_constant<size_t, 0> {};
                               ^
/Users/ubaid/conda_root/envs/lf/bin/../include/c++/v1/type_traits:1472:38: error: expected expression
    : public integral_constant<size_t, 0> {};
                                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:230: src/libasr/CMakeFiles/asr.dir/codegen/wasm_utils.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:146: src/libasr/CMakeFiles/asr.dir/codegen/x86_assembler.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/tests/CMakeFiles/doctest.dir/build.make:76: src/tests/CMakeFiles/doctest.dir/doctest.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:395: src/tests/CMakeFiles/doctest.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:188: src/libasr/CMakeFiles/asr.dir/codegen/wasm_to_wat.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:216: src/libasr/CMakeFiles/asr.dir/codegen/wasm_to_x64.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:132: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_py.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:202: src/libasr/CMakeFiles/asr.dir/codegen/wasm_to_x86.cpp.o] Error 1
[ 16%] Linking C shared library ../liblfortran_runtime.dylib
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:160: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_x86.cpp.o] Error 1
ld: warning: -pie being ignored. It is only used when linking a main executable
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:174: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_wasm.cpp.o] Error 1
[ 17%] Linking C static library liblfortran_runtime_static.a
[ 17%] Built target lfortran_runtime
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:244: src/libasr/CMakeFiles/asr.dir/pass/nested_vars.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:104: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_julia.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:118: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_fortran.cpp.o] Error 1
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:76: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_cpp.cpp.o] Error 1
[ 17%] Built target lfortran_runtime_static
20 errors generated.
make[2]: *** [src/libasr/CMakeFiles/asr.dir/build.make:90: src/libasr/CMakeFiles/asr.dir/codegen/asr_to_c.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:369: src/libasr/CMakeFiles/asr.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by Shaikh-Ubaid** [comment]
We do not experience the above build issue at the CI, because at the CI we create a new environment for testing as follows:

https://github.com/lfortran/lfortran/blob/c10d8a6fce5344327fcb8dae4061eb04ee073a98/.github/workflows/CI.yml#L756-L761

**Comment by Shaikh-Ubaid** [comment]
Do we need to create a new environment to test the `integration_tests` with the Fortran backend?

**Comment by Thirumalai-Shaktivel** [comment]
Yup, I have a separate conda environment to test Fortran.

**Comment by Shaikh-Ubaid** [comment]
>I have a separate conda environment to test Fortran.
 
Got it. Thank you for sharing.

Is it a good approach to have a separate environment for testing the fortran backend? Like should we not have a single environment for building as well as testing the `lfortran` compiler?

**Comment by Thirumalai-Shaktivel** [comment]
I had couple of problems like
1. Warnings while building
```
[...]
ld: warning: direct access in function 'ltmp3' from file '../libasr/libasr.a(llvm_utils.cpp.o)' to global weak symbol 'LCompilers::ASRUtils::extract_dimensions_from_ttype(LCompilers::ASR::ttype_t*, LCompilers::ASR::dimension_t*&)' from file '../libasr/libasr.a(asr_verify.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
[...]
```
2. Integration tests Error
```
CMake Error at /Users/thirumalai/mambaforge/envs/lf_1/share/cmake-3.25/Modules/CMakeTestFortranCompiler.cmake:62 (message):
  The Fortran compiler

    "/Users/thirumalai/bin/lfortran"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /Users/thirumalai/Open_Source/lfortran/integration_tests/test-llvm/CMakeFiles/CMakeScratch/TryCompile-AROFqw
[...]
```
I'm not sure if we can fix these issue. If we can then we can install gfortran and test in the same environment.

**Comment by Shaikh-Ubaid** [comment]
I think building and testing in the same `lf` environment used to work for me until https://github.com/lfortran/lfortran/pull/2805. Since https://github.com/lfortran/lfortran/pull/2805, it seems we now need to link `-lgfortran` which when installed via conda causes issues during build of `lfortran`.

**Comment by Thirumalai-Shaktivel** [comment]
Wait a minute, can you share the output of `which gfortran`? or Do you use `conda gfortran` or `/bin/gfortran`?

**Comment by Shaikh-Ubaid** [comment]
I think I use `/bin/gfortran`. Similarly for `clang`.

**Comment by Thirumalai-Shaktivel** [comment]
I use `conda gfortran`,  so I didn't came across the issue.
Can you try fixing it?
Here is the line responsible for linking `-lgfortran`: https://github.com/lfortran/lfortran/blob/c10d8a6fce5344327fcb8dae4061eb04ee073a98/src/bin/lfortran.cpp#L1583-L1585

**Comment by Shaikh-Ubaid** [comment]
>I use conda gfortran, so I didn't came across the issue.

Are you able to build `lfortran` in your conda environment where you have `gfortran` installed?

If we do `conda install -c conda-forge gfortran`, then the `lfortran` build fails for me like I mentioned in the description of this issue.

**Comment by Shaikh-Ubaid** [comment]
I suspect the changes in https://github.com/lfortran/lfortran/pull/2805 might not be accurate if we require to build and test `lfortran` in different environments. But I think the changes are fine if building and testing `lfortran` in different environments is expected/desired.

**Comment by certik** [comment]
Let me test this later today, but must likely we'll have to revert https://github.com/lfortran/lfortran/pull/2805. I suspected it will break things.

**Comment by certik** [comment]
For me `./run_tests.py -b fortran` still works. 

@Shaikh-Ubaid how do you install gfortran?

**Comment by Shaikh-Ubaid** [comment]
>@Shaikh-Ubaid how do you install gfortran?

I install `gfortran` using `conda install -c conda-forge gfortran`, after which I am unable to build `lfortran`.

**Comment by Shaikh-Ubaid** [comment]
>For me ./run_tests.py -b fortran still works.

For me `./integration_tests/run_tests.py -b fortran` fails in the default/regular `lf` environment with the error that `library not found for -lgfortran` (minimum reproducible example here https://github.com/lfortran/lfortran/issues/2828#issue-1982852997).

**Comment by Thirumalai-Shaktivel** [comment]
> For me `./run_tests.py -b fortran` still works.
> 
> @Shaikh-Ubaid how do you install gfortran?

It seems to work for @certik, I think @certik uses `/bin/gfortran`.
I think `clang` is not able to find the `libgfortran` in your `/lib`. Can you try debugging it?

**Comment by Shaikh-Ubaid** [comment]
The issue here is that `lfortran examples/expr2.f90 --backend fortran` fails as shown here https://github.com/lfortran/lfortran/issues/2828#issue-1982852997.

Now to fix it, we install `gfortran` using `conda install -c conda-forge gfortran` inside the `lf` environment. After this the lfortran project itself fails to build.

**Comment by Shaikh-Ubaid** [comment]
>I think clang is not able to find the libgfortran in your /lib. Can you try debugging it?

@Thirumalai-Shaktivel I am unsure if we are both on the same line. Could you post the outputs of the following commands on your system:

```console
git clean -dfx
conda deactivate
conda activate lf 
which gfortran
./build1.sh
lfortran examples/expr2.f90 --backend fortran
```

NOTE: Please do not change the conda environment between the execution of commands in the above.

**Comment by Shaikh-Ubaid** [comment]
> I had a couple of problem like
> 
> 1. Warnings while building
> 
> ```
> [...]
> ld: warning: direct access in function 'ltmp3' from file '../libasr/libasr.a(llvm_utils.cpp.o)' to global weak symbol 'LCompilers::ASRUtils::extract_dimensions_from_ttype(LCompilers::ASR::ttype_t*, LCompilers::ASR::dimension_t*&)' from file '../libasr/libasr.a(asr_verify.cpp.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.
> [...]
> ```
> 
> 2. Integration tests Error
> 
> ```
> CMake Error at /Users/thirumalai/mambaforge/envs/lf_1/share/cmake-3.25/Modules/CMakeTestFortranCompiler.cmake:62 (message):
>   The Fortran compiler
> 
>     "/Users/thirumalai/bin/lfortran"
> 
>   is not able to compile a simple test program.
> 
>   It fails with the following output:
> 
>     Change Dir: /Users/thirumalai/Open_Source/lfortran/integration_tests/test-llvm/CMakeFiles/CMakeScratch/TryCompile-AROFqw
> [...]
> ```
> 
> I'm not sure if we can fix these issues. If we can, then we should definitely install GFortran and test in the same environment.

I think you face some issues when building and testing in the same environment (like you shared https://github.com/lfortran/lfortran/issues/2828#issuecomment-1801271520). I think the PR https://github.com/lfortran/lfortran/pull/2833 would hopefully solve it.
