### ISSUE TITLE
Implement identification and version macros (needed for good cmake support)

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2859]
https://gitlab.kitware.com/cmake/cmake/-/issues/25419#note_1446778

```
#define __lfortran__ 1
#define __lfortran_major__ 0
#define __lfortran_minor__ 29
#define __lfortran_patchlevel__ 0
```

Then release.

**Comment by junghans** [comment]
Isn't there already `__LFORTRAN__` and `__VERSION__`?
https://github.com/lfortran/lfortran/blob/ab2ea0d1a68aca171a32af09972184c06f27e82c/src/lfortran/parser/preprocessor.re#L15-L17

**Comment by certik** [comment]
I think it is. I think CMake wants a lower case and also the other major/minor macro definitions.

**Comment by junghans** [comment]
When you look at https://github.com/Kitware/CMake/tree/master/Modules/Compiler, 75% have all caps.
We should add `__LFORTRAN_{MAJOR,MINOR,PATCHLEVEL}__`, but that should be enough.

**Comment by certik** [comment]
Perfect!
