### ISSUE TITLE
Format `(i0,*(1x,es15.8e2))` segfaults

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2861]
This is used in:

https://github.com/modern-fortran/tsunami/blob/70b5702aed42bbea0733335d50e0eb70cb159e08/src/ch02/tsunami.f90

And it segfaults. Commenting out the format works. Here is a minimal reproducible example:
```fortran
program tsunami
implicit none
integer :: n
integer, parameter :: grid_size = 3
real :: h(grid_size)
character(*), parameter :: fmt = '(i0,*(1x,es15.8e2))'
h = 1
print fmt, n, h
end program tsunami
```
This behaves as follows:
```console
$ lfortran tsunami.f90 -o a.out
$ ./a.out 
zsh: segmentation fault  ./a.out
$ gfortran tsunami.f90 -o a.out
$ ./a.out 
2  1.00000000E+00  1.00000000E+00  1.00000000E+00
```

**Comment by Pranavchiku** [comment]
I investigated and this happens because `dot_pos` is nullptr

```diff
% git diff
diff --git a/src/libasr/runtime/lfortran_intrinsics.c b/src/libasr/runtime/lfortran_intrinsics.c
index 3ad73c58f..1d2e1d1bf 100644
--- a/src/libasr/runtime/lfortran_intrinsics.c
+++ b/src/libasr/runtime/lfortran_intrinsics.c
@@ -292,6 +292,7 @@ void handle_decimal(char* format, double val, int scale, char** result, char* c)
     int integer_length = (integer_part == 0) ? 1 : (int)log10(llabs(integer_part)) + 1;
 
     char *num_pos = format ,*dot_pos = strchr(format, '.');
+    if (dot_pos == NULL) return;
     decimal_digits = atoi(++dot_pos);
     while(!isdigit(*num_pos)) num_pos++;
     width = atoi(num_pos);
```

**Comment by certik** [comment]
@Pranavchiku do you know how to fix it?

**Comment by Pranavchiku** [comment]
I am not exactly sure, I'll have to understand how the formatting works. I'll give it a shot.

**Comment by gptsarthak** [comment]
The issue here is that `*` inside the formatting has not been implemented yet. To know this we can check the `parse_fortran_format` function does not have something like `case '*' :`.
The other issue is that `e` after a decimal point like in `es15.8e2` is not implemented yet, again we can just check the parse function for its implementation.
I have a fix almost ready and will push in an hour.

**Comment by certik** [comment]
The example now compiles, but the formatting is still incorrect. I opened up an issue for it at: https://github.com/lfortran/lfortran/issues/2878.
