### ISSUE TITLE
Repeated use of `ASR verify :`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#2863]
```
program expr2
    implicit none
    print*, min("string_var", "hello")
end program
```
```console
$ lfortran a.f90
ASR verify pass error: ASR verify: ASR Verify: Arguments to min0 must be of real or integer type
 --> a.f90:3:13
  |
3 |     print*, min("string_var", "hello")
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ failed here


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
The `ASR verify` repeats twice as in the error above
`ASR verify pass error: ASR verify: ASR Verify: Arguments to min0 must be of real or integer type`

Remove `ASR verify: ` from everywhere.

**Comment by Rucha-Ambaliya** [comment]
hello ma'am, i'm a new contributor here and would like to solve this issue...so if possible can you guide me which file needs to be rectified in order to solve this... In my research I could find two files having similar information. 1. diagnostics.cpp and 2.intrinsic_function_registry.h

I would appreciate it if you can guide me with this.Thank you.

![Capture1](https://github.com/lfortran/lfortran/assets/148620892/52cece1c-dcaf-4dcd-a4ba-2b0b536e9169)
![Capture2](https://github.com/lfortran/lfortran/assets/148620892/48037e98-e721-4f4b-99c1-c45533a2de18)

**Comment by HarshitaKalani** [comment]
Hey @Rucha-Ambaliya, the `src/libasr/pass/intrinsic_function_registry.h` file contains the error messages with `ASR Verify: <msg>` written. You just need to remove `ASR Verify:` from them. 
I hope this helps!

**Comment by Rucha-Ambaliya** [comment]
sure i'll look into it...thank you ma'am.

**Comment by Rucha-Ambaliya** [comment]
Hello ma'am! Sorry for disappearing like this... Actually I was setting up my laptop for lfortran development environment and there was one issue with the compatibility which I have reported here as well after confirming in the forum. I wanted to know how did you compile this code as I'm having different massage in my command prompt after compiling it... I have done the changes in my local repository but would like to test it before sending pull request. I know this issue might not need to be checked after doing the changes but it will help me in knowing the workflow here... 

![Capture15](https://github.com/lfortran/lfortran/assets/148620892/82ae76e2-cde9-4da6-a9cf-841c34cf25da)

**Comment by HarshitaKalani** [comment]
Can you tell me the steps that you followed? That way it would be easier.

**Comment by Rucha-Ambaliya** [comment]
I have installed lfortran with the conda environment. and then I executed the command "lfortran a.f90" inside the directory my code was in...

program expr2
    implicit none
    print*, min("string_var", "hello")
end program

I copied this code inside the file named a.f90, and then executed the command with conda environment...
![Capture19](https://github.com/lfortran/lfortran/assets/148620892/1ec6c1a4-6a34-4084-a42a-a94bf0f0ea5a)

There was a issue when I made lf conda environment so I made a new one and I created a.f90 file both, inside the lfortran repository and inside the another separate folder, but the output came same...

**Comment by HarshitaKalani** [comment]
I guess you're not up-to-date with the latest main
Do a `git pull origin main` in the main branch
Then try to run this program.

Also, you can try the following program and let me know if you're getting some error 
```
program expr2
implicit none
print*, min(3, 7)
end program
```

**Comment by Rucha-Ambaliya** [comment]
![Capture20](https://github.com/lfortran/lfortran/assets/148620892/44e6cb9b-49be-459a-8145-dd06cd7f8e4a)

I am getting this massage...I got the same massage when I tried using integers as arguments in min before...There seems to be issue in linking the file "a.out.tmp.o"...

**Comment by Rucha-Ambaliya** [comment]
hello, ma'am...Sorry for disturbing again. Actually  I got a new laptop recently and have installed all the needed packages  as well. I can now work on interactive command line of lfortran too. Yet I'm getting the same output...

`Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: Arguments to min0 must be of real or integer type`

Although now it is not throwing any error if I pass integers as arguments...

**Comment by Pranavchiku** [comment]
I feel you shall try performing clean build once
```
git clean -dfx
git checkout main
```

then put the example in `a.f90` and run it. There may have been some issue because of it.

**Comment by Rucha-Ambaliya** [comment]
I'm still getting same result

![capture](https://github.com/lfortran/lfortran/assets/148620892/c38f2b18-597a-47af-902f-ddb3eecb04e1)

**Comment by Pranavchiku** [comment]
This works with latest main, @HarshitaKalani can you verify it?

```console
% cat a.f90 
program expr2
    implicit none
    print*, min("string_var", "hello")
end program
% lfortran a.f90 
hello
% gfortran a.f90 && ./a.out
 hello     
```

**Comment by Rucha-Ambaliya** [comment]
Hello! I made a new file a.f90 in lfortran folder and after running the command output came "hello" and it was same when i passed string "hllo" instead of "hello"... It means my system is configured perfectly now as I can now build lfortran properly as well, right?

**Comment by gxyd** [comment]
@Pranavchiku for me also, I get the same output. But I'm not really sure if that's what `lfortran` should be doing.

When I look at what GFortran does, I see that it doesn't return anything at all (nor raise an error). In the documentation for it, https://gcc.gnu.org/onlinedocs/gfortran/intrinsic-procedures/min.html I see that `min` only expects numeric values (not strings). I feel it's a regression in LFortran, since atleast earlier it used to report:
```
Arguments to min0 must be of real or integer type
```

for string arguments to `min`.

**Comment by gxyd** [comment]
I guess I'm wrong in understanding, I see that it's all done intentionally: https://github.com/lfortran/lfortran/pull/2869. Sorry.

**Comment by shivimathur** [comment]
```fortran
program expr2
    implicit none
    print*, min("string_var", "hello")
end program
```
```console
$ lfortran a.f90
hello
```
Looks like this issue is resolved now.

**Comment by certik** [comment]
Yes, the error is fixed, but this issue is about changing the ASR verify error:
```
ASR verify pass error: ASR verify: ASR Verify: Arguments to min0 must be of real or integer type
```
to
```
ASR verify pass error: Arguments to min0 must be of real or integer type
```
We still throw this error when the ASR is incorrect (it just happens to be correct now for the above case).

**Comment by captainhaddock18** [comment]
I am able to find "ASR verify:" in these 2 files "src/libasr/pass/intrinsic_functions.h" and "src/libasr/asr_verify.cpp". should we remove ASR Verify from one of these or both of them?

![Screenshot from 2024-11-29 19-55-12](https://github.com/user-attachments/assets/36fc80a2-4b95-4d75-a883-fcf2cb0ac18d)

![Screenshot from 2024-11-29 19-55-55](https://github.com/user-attachments/assets/a51d58bc-caf5-4e1f-8c84-150aad58c653)

**Comment by kmr-srbh** [comment]
@captainhaddock18 yes please remove the text `ASR Verify: `. We add it already when the diagnostic stage is `Stage::ASRVerify`. The `ASRUtils::require_impl()` uses `Stage::ASRVerify` too, so it is safe to remove from there also.

**Comment by captainhaddock18** [comment]
@kmr-srbh Thanks a lot! . I have made the changes in these files.  Should I run any tests before raising a PR or directly raise a PR for this issue?
