### ISSUE TITLE
Compile the tsunami tutorial

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#2877]
The first example: https://github.com/modern-fortran/tsunami/blob/70b5702aed42bbea0733335d50e0eb70cb159e08/src/ch02/tsunami.f90

Has two issues:

* [ ] do concurrent does not compile (for now we should just compile it serially)
* [x] the formatting prints, but incorrectly formats: https://github.com/lfortran/lfortran/issues/2878

**Comment by certik** [comment]
I can now compile ch02, ch03 and ch04. The next one after that is ch07, but that requires coarrays.

**Comment by Pranavchiku** [comment]
Let's add tsunami tutorial as a test, I opened issue at https://github.com/lfortran/lfortran/issues/2884
