### ISSUE TITLE
Case insensitivity violated with overloaded procedure

### ISSUE THREAD

**Issue by difference-scheme** [lfortran/lfortran#2897]
The following example fails to compile, because LFortran appears to possibly parse it incorrectly, being sensitive to "camelCase" in this instance:
```
module overloading

   interface func
      procedure specialFunc
   end interface func

contains
   
   function specialFunc() result(value)
      logical :: value 
      value = .false.
   end function specialFunc

end module overloading
```
Here's LFortran's output:
```
semantic error: Symbol 'specialFunc' not declared
 --> overloading.f90:1:2
  |
1 | module overloading
  |  ^ 
```
Switching the name `specialFunc` to all-lower case works as expected.

**Comment by Pranavchiku** [comment]
I am able to reproduce it. Let me see, I feel it will be a easy fix.

**Comment by difference-scheme** [comment]
@Pranavchiku @Shaikh-Ubaid Great, thanks! 

We are making good progress. Right now we are at around 50% of the underlying Fortran 2008 code base compiling, if I work around those bugs (that I submitted a few days ago) that are still open.

**Comment by certik** [comment]
Thanks @difference-scheme. We'll keep working on this. 50% is very close, since the progress is exponential. There might be just a few bugs left.

**Comment by difference-scheme** [comment]
Yes, please fix the reported bugs soon, so that we can try to get this code to compile out of the box, and run. 

By working around these bugs (and a few other, minor, ones that I haven't managed to report so far), I now got 99% of this code base to compile.

The only thing that still stubbornly refuses to compile, due to two or three remaining bugs that I haven't been able to pinpoint yet, is the main program unit.

**Comment by certik** [comment]
I forgot about one thing: this only compiles your code to ASR. Then once you start compiling the main program, it compiles ASR to LLVM and that's where most of the work will be for us, if I remember well from compiling `fpm`. From experience, even when the whole thing compiles, it typically produces wrong results, and it takes some time to fix the remaining bugs so that everything works correctly. So we might not be as close as I initially thought, but we are definitely making good progress. We'll keep fixing all these bugs. It will eventually start working.

**Comment by difference-scheme** [comment]
@certik 

So you mean that it hasn't done any code generation yet, and would do so all at once upon compiling the main program? Doesn't LFortran support separate compilation yet?

**Comment by certik** [comment]
> So you mean that it hasn't done any code generation yet, and would do so all at once upon compiling the main program? 

Yes.

> Doesn't LFortran support separate compilation yet?

We do, with the `--generate-object-code` option, but so far it only works for old F77 style codes (such as in SciPy) that require it. It doesn't work for modules yet.
