### ISSUE TITLE
Intrinsic procedure system_clock is apparently not recognized

### ISSUE THREAD

**Issue by difference-scheme** [lfortran/lfortran#2909]
It seems that the `system_clock` intrinsic procedure is either not yet supported, or that there is a bug concerning the argument type(s) that it expects. Here's a simple test code, and the corresponding LFortran error message:
```
module system_clock_test
   
   integer :: arg = 0

contains
   
   subroutine test()
      call system_clock(arg)
   end subroutine test

end module system_clock_test
```
LFortran's output:
```
semantic error: Arguments do not match for any generic procedure, system_clock
 --> test.f90:8:7
  |
8 |       call system_clock(arg)
  |       ^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by certik** [comment]
I think it only works for floats for now. Thanks for the bug report.

**Comment by difference-scheme** [comment]
@certik  I just checked the Standard, and the GNU Fortran documentation (https://gcc.gnu.org/onlinedocs/gfortran/SYSTEM_005fCLOCK.html), because I wasn't absolutely sure what this routine actually expects.  

According to both, `system_clock` should have three optional arguments, where the first is an `integer` scalar, and where only the second can be a `real` scalar.

Calling it with only a single (positional, i.e. non-keyword) argument should thus require an` integer` to be passed in.

**Comment by certik** [comment]
I think I mistook it for `cpu_time` which accepts a real. We might not support `system_clock` at all. This should not be difficult to fix.
