### ISSUE TITLE
Add __LFORTRAN__ / __LFORT__ predefined macro

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#292]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/261

This seems like the best path forward to be supported in https://gitlab.kitware.com/cmake/cmake/blob/5025b568433d6b7027b81822f1782defb80be74a/Modules/CMakeFortranCompilerId.F.in. (This relates to https://gitlab.com/lfortran/lfortran/-/issues/150.)

For comparison, `gcc` / `gfortran` has: https://gcc.gnu.org/onlinedocs/gcc-4.4.7/cpp/Common-Predefined-Macros.html

(I am a little unsure of the current level of support for preprocessor directives in `lfortran`, based on reading of https://github.com/fortran-lang/stdlib/issues/35.)

E.g. a relevant section for `flang`

```
#elif defined(__FLANG)
        PRINT *, 'INFO:compiler[Flang]'
# define COMPILER_VERSION_MAJOR DEC(__FLANG_MAJOR__)
# define COMPILER_VERSION_MINOR DEC(__FLANG_MINOR__)
# if defined(__FLANG_PATCHLEVEL__)
#  define COMPILER_VERSION_PATCH DEC(__FLANG_PATCHLEVEL__)
# endif
```

**Comment by junghans** [comment]
Fixed in #2859
