### ISSUE TITLE
Include man pages in release tarball

### ISSUE THREAD

**Issue by junghans** [lfortran/lfortran#2923]
Could you please include a man page for each binary in the release tarball?

**Comment by certik** [comment]
Should the man page be in the groff format, or already compiled? What is the modern practice?

**Comment by junghans** [comment]
`groff` format. 
One can do:
```
sphinx-build -b man doc/src man
```
even though the release tarball do not have the `doc` folder included, plus one would need all the sphinx deps as well.
So having them pre-compiled would be better.

**Comment by junghans** [comment]
Do you have an GitHub action to do releases or do you do them manually?
