### ISSUE TITLE
chkder.f from legacy minpack fails - syntax error

### ISSUE THREAD

**Issue by ettaka** [lfortran/lfortran#2926]
I was able to compile the modernized minpack.
I cloned also the [legacy minpack](https://github.com/scipy/scipy/tree/f797ac7721310c7bd98bae416be1bed9975b4203/scipy/optimize/minpack)
And I tried to compile, but it failed. For example:
```
(lf) ➜  minpack git:(main) lfortran chkder.f -c
syntax error: Token '*' is unexpected here
 --> chkder.f:2:6
  |
2 |      *subroutine chkder(m,n,x,fvec,fjac,ldfjac,xp,fvecp,mode,err)
  |      ^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by ettaka** [comment]
> For legacy minpack you need to enable many legacy options. This is tested at the CI here:
> 
> https://github.com/lfortran/lfortran/blob/c38578079fcc7264265a1a36b95a8a237543b683/.github/workflows/CI.yml#L427
> 
> , and the relevant cmake file is here: https://github.com/certik/minpack/blob/409ba02a107f47ee835f3976952bbc64dd46de8a/src/CMakeLists.txt, so you need to use "--generate-object-code --fixed-form --implicit-typing --implicit-interface".

Thanks!

However, if there are files with a mixture of `.f90` and `.f`, then one has to switch between `--fixed-form` flag and omitting it. Would it be possible to implement a feature for `lfortran` detecting whether the source file is of fixed or free form and then add the needed flag? Otherwise this can lead to issues in build automation, for example at `cmake` side https://stackoverflow.com/questions/44679904/cmake-to-handle-f77-and-f90-files-differently

**Comment by certik** [comment]
> Would it be possible to implement a feature for `lfortran` detecting whether the source file is of fixed or free form and then add the needed flag implicitly?

We already implemented it, use the `--fixed-form-infer`. It should infer the type from the file extension.

Let me know if it works for you.

**Comment by ettaka** [comment]
> > Would it be possible to implement a feature for `lfortran` detecting whether the source file is of fixed or free form and then add the needed flag implicitly?
> 
> We already implemented it, use the `--fixed-form-infer`. It should infer the type from the file extension.
> 
> Let me know if it works for you.

I confirm this works! Sorry, I should have read the help more carefully!

**Comment by certik** [comment]
@ettaka awesome, I am glad it works!
