### ISSUE TITLE
Intrinsic index() function is returning wrong result

### ISSUE THREAD

**Issue by etempel** [lfortran/lfortran#3004]
I tried to use intrinsic index() function to find a location of substring within a string and it returns a wrong value. An example: index('abc', 'b') should return 2 but it returns 1. Actually, any single character as second argument returns a value 1.

Additional point. Fortran standard specifies that you can include an extra argument back to look for substrings from back to forward. The optional back argument is not supported in lfortran.

**Comment by certik** [comment]
Thanks for the bug report!
