### ISSUE TITLE
ENH: support `back` parameter for intrinsic `index`

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3008]
Requested in #3004

```fortran
program main
logical :: back
back = .true.
print *, index('abcd', 'b', back)
end program
```

```console
% gfortran a.f90 && ./a.out
           2
```

Refer: https://gcc.gnu.org/onlinedocs/gfortran/INDEX-intrinsic.html#:~:text=Description%3A,occurrence%20rather%20than%20the%20first

File: https://github.com/lfortran/lfortran/blob/main/src/runtime/pure/lfortran_intrinsic_string.f90#L33

Add new function `integer elemental function index(string_, substring_, back) result(idx)` and apply logic correctly.

**Comment by HarshitaKalani** [comment]
Rather than creating a new function, I've added 'back' as an optional argument in the same function. Refer: #3010
