### ISSUE TITLE
 lfortran binaries

### ISSUE THREAD

**Issue by andriish** [lfortran/lfortran#3044]
Hi all,

it is great to see the developments of `lfortran`.
Would you also consider to provide binaries for the major Linux distros? 
It would be nice to have an official lfortran releases for Fedora/RHEL/SUSE in e.g. COPR https://copr.fedorainfracloud.org/

Of course there are alredy some unofficial builds, e.g. https://copr.fedorainfracloud.org/coprs/fed500/lfortran/, but it would be nice to have a blessed version from the developers.

Best regards,

Andrii

**Comment by certik** [comment]
I think this is similar to https://github.com/lfortran/lfortran/issues/1524. We currently support conda as our official binary distribution that we guarantee to work. We could support a Linux binary tarball that you download and unpack, and it works on all Linux distributions. We are looking for contributors willing to maintain such a binary.

I personally want to focus on getting lfortran to beta. Once we reach beta, we can spend more time with distribution issues like this one.

**Comment by andriish** [comment]
Hi @certik, 

thank you for the quick reply. I think that what I suggest is quite different from #1524 and has much wider use case.
Will try to elaborate a bit.

Having some conda binaries is, probably, a good thing. But conda is *not* a thing for many-many Fortran users for many reasons. The way the binaries of  Fortran compilers are shipped traditionally is either 1)RPM/DEB repository for specific distros (GNU, Intel, XL, NVHPC, AOCC) or 2)a huge tarball (NAG, Oracle). More recently -- also 3)containers (NVHPC).

Having a tarball that one can download-unpack-run is a great thing. But preparing such a tarball would require substantial efforts, especially for testing and most likely will be hard to automate -- e.g. one would require to have LLVM that works on many distributions. Totally understandable that some manpower would be needed for the maintenance and getting a beta is obviously more important.

So my suggestion is to look at the first traditional option -- a repository for specific distros. This is a *low-maintenance* option, in fact it could take  less than an hour to prepare a spec and repository for Fedora+RHEL+SUSE and also script a lot of appropriate automation.

Having such a repository would allow a painless usage of lfortran in  containers an in CI for many small and medium size projects ad will probably generate a lot of feedback. This is not an option now. 
The one-liner 
```
dnf -y enable copr/lfortran && dnf -y install lfortran
```
is much easier to put into CI, container or deploy on a real machine than the monstrous conda or a labour intense compilation from sources. 

And then the CI: a standard container + repository/tarball is much  *faster*  and cleaner  to start than conda.

Best regards,

Andrii

**Comment by certik** [comment]
Those are great points.

Where can you host a repository for Fedora+RHEL+SUSE, Debian and Ubuntu? 

Note that it is not enough to just build the package. We also have to carefully test it, in each of these distributions that we would claim to support. That can all be setup at a CI, but it requires some work. However if you think it can be done in 1h, you can send us a PR, that would be very useful.

**Comment by andriish** [comment]
Hi @certik,

>Where can you host a repository for Fedora+RHEL+SUSE, Debian and Ubuntu?

Fedora+RHEL+SUSE+Madriva+.. -- COPR does it, same as similar services from SUSE.
Debian and Ubuntu -- I'm not a user, but https://launchpad.net/ubuntu/+ppas should do the job. However I cannot give an estimation how much work is that.


>  if you think it can be done in 1h

No, that is not what I think or ever claimed. What I say is that one can setup a COPR repository with some automation in 1h. You are of course right, those builds will not have testing beyond 
```
%check
%ctest
```
but that is already something.
And concerning the  claims of support -- nothing prevents having binary builds with "experimental"  or "Tier II support" status. 

In any case -- you are aware about the idea and that was the goal of opening this issue. It is up to you to accept or reject it. This issue can be closed in either of cases.  


Thank you for the discussion.
Best regards,

Andrii

**Comment by andriish** [comment]
Oh, https://github.com/lfortran/lfortran/issues/2981 -- it seems @junghans already tries to package lfortran on for RHEL/Fedora/SUSE.

**Comment by junghans** [comment]
openSUSE is done: https://build.opensuse.org/request/show/1136961

fedora has a review request:
https://bugzilla.redhat.com/show_bug.cgi?id=2229349
@andriish can you review this?

Debian - I pinged @amckinstry about that a while back.

**Comment by andriish** [comment]
Hi @junghans,

great!

> Review

I have no rights to push the package, all I can do is to actually comment on it.
And from what I see the spec is OK. 
Just a minor thing  -- it would make sense to have slightly different set of packages: 
- compiler
- headers. Depend on compiler.
- shared lib runtime, i.e. similar to `libgfortran` package, which contains just one file. This should be  a dependency for compiler.
-  static lib runtime, i.e. similar to `libgfortran-static` package, which contains just one file. 
-  Jupiter file.  This would also require listing some Jupiter dependencies. Depends on compiler.

Best regards,

Andrii

**Comment by junghans** [comment]
/CC @bkmgit as he started the whole fedora package.

**Comment by junghans** [comment]
> * compiler
> * headers. Depend on compiler.
> * shared lib runtime, i.e. similar to `libgfortran` package, which contains just one file. This should be  a dependency for compiler.
> * static lib runtime, i.e. similar to `libgfortran-static` package, which contains just one file.
> * Jupiter file.  This would also require listing some Jupiter dependencies. Depends on compiler.

I am not a huge fan of splitting things into too many sub-packages, especially if it is for a single file. openSUSE requires shared libraries to be in separate packages, but fedora does not - I think.

For static libraries, they should be separate if package builds static and shared libraries:
https://docs.fedoraproject.org/en-US/packaging-guidelines/#_packaging_static_libraries

**Comment by certik** [comment]
Yes, the fewer packages, the better. We also plan to redesign our runtime library anyway, so things might change too.

**Comment by junghans** [comment]
@certik what are the plans for the runtime library?

**Comment by certik** [comment]
See here: https://github.com/lfortran/lfortran/issues/3034 and then also the runtime library related points here: https://github.com/lfortran/lfortran/issues/1303

**Comment by andriish** [comment]
Hi @junghans,

I do agree that less packages is better. But that is almost minimal number of packages ( e.g. no separation of docs).
Any serious compiler should have separate compiler binary  and runtime library^1. Then + one static library.
And then there is Jupiter file, which will require a lot of dependencies^2 not needed for non-Jupyter users. 
However, the headers could be combined with the compiler binary. Means just four packages. Quite good, as for me.

Best regards,

Andrii

^1 Single file is needed because that is *the only* runtime dependence for the executables compiled with `lfortran` and such a package would not depend on anything.  While the compiler binary requires  20+ other shared libraries.
^2 Maybe this example https://src.fedoraproject.org/rpms/root/blob/rawhide/f/root.spec  with packaging Jupyter subpackage can be useful.

**Comment by certik** [comment]
I recommend to start with just one binary package, and let LFortran reach version 1.0. By then we'll figure out (also based on packaging experience!) how to structure the various pieces, and then we can figure out how to split the packaging.

**Comment by bkmgit** [comment]
Packaging differs by linux distribution.  GCC for example has many sub packages which enables choosing the minimal set of components for a use case.  At the moment, having LFortran in distros allows people to try it out.  However, as the ecosystem develops, the main concern is how software built with LFortran will be packaged.and whether interoperability with software produced by other Fortran compilers will be an LFortran development consideration.  Being able to not have Jupyter dependencies if they are not needed by an application would be nice and is a good suggestion. Will we need to have GFortran, Flang and LFortran versions of compiled software?

**Comment by certik** [comment]
> Will we need to have GFortran, Flang and LFortran versions of compiled software?

We have a prototype GFortran module file parser, and in the past I tested a prototype of linking Intel Fortran and GFortran module files together, and it does work. So there is a path forward. But right now our focus is to deliver beta. Once we deliver, we can focus on interoperability.

**Comment by bkmgit** [comment]
Ok. It is helpful to have LFortran packaged.  Anyone that packages software built with LFortran will probably need to make future adjustments, but can give useful feedback.

**Comment by junghans** [comment]
We will just package it how the Fedora Reviewer wants it.

**Comment by andriish** [comment]
Hi @junghans, yeap, I saw it and subscribed. Good job! Could you, please, make builds for EPEL as well? RHEL/Alma are quite popular among the potential users.

Best regards,

Andrii

**Comment by certik** [comment]
Thanks @junghans for packaging it!

**Comment by junghans** [comment]
> Could you, please, make builds for EPEL as well? RHEL/Alma are quite popular among the potential users.

I had quick look, but EPEL9 doesn't have a zstd package, so unless somebody pushed for that we are out of luck.

**Comment by certik** [comment]
We don't depend on `zstd` directly, but LLVM depends on it. I assume EPEL9 has some way to package LLVM, so as long as we can link to it, we are fine. We can modify our cmake to make this work.

**Comment by junghans** [comment]
> We don't depend on `zstd` directly, but LLVM depends on it. I assume EPEL9 has some way to package LLVM, so as long as we can link to it, we are fine. We can modify our cmake to make this work.

See #3157

**Comment by junghans** [comment]
However there is another linking error on EPEL9, see #3158

**Comment by junghans** [comment]
Debian is done, package in sid/testing. Thanks @amckinstry !!!!

I will close this issue as only EPEL9/RHEL/Alma is left and that is tracked in #3158.

**Comment by certik** [comment]
Thank you @junghans and @amckinstry!!
