### ISSUE TITLE
Kind 16 is not supported for Integer

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3071]
```fortran
program main
	integer*16 x
end
```
```console
$ lfortran a.f90
style suggestion: Use integer(8) instead of integer*8
 --> a.f90:2:2
  |
2 |  integer*16 x
  |  ^^^^^^^^^^ help: write this as 'integer(8)'


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
Internal Compiler Error: Unhandled exception
^C
```
There should rather be an error message saying `semantic error: Kind 16 is not supported for Integer`. 
Also the warning is incorrect here. It should be `style suggestion: Use integer(16) instead of integer*16`

**Comment by parth121101** [comment]
@HarshitaKalani Can you please brief it?

**Comment by HarshitaKalani** [comment]
You can search for the warning. It'll be present in `semantics.h` file I believe.
In case different from `integer*4` and `integer*8`, we can throw an error saying this kind is not supported yet.
I think this should work.

Try this, submit a PR and will review then.
