### ISSUE TITLE
Add correct keywords for intrinsic functions

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3076]
In the `name2signature` vector in `src/lfortran/semantics/ast_common_visitor.h` file, we need to put correct kwargs.
For example
```cpp
{"repeat", {IntrinsicSignature({"string", "ncopies"}, 2, 2)}},
```
Here, the keyword args for `repeat` are "string" and "ncopies" (reference: https://gcc.gnu.org/onlinedocs/gfortran/REPEAT.html)
We need to do it for all the other intrinsic functions.

**Comment by Baitato** [comment]
@HarshitaKalani I'm sorry for the trouble, but I'm not sure what I'm doing wrong. I don't know why the tests are failing, can I have some help?

**Comment by HarshitaKalani** [comment]
Hey @Baitato, thanks for working on this!

This issue is dependent on https://github.com/lfortran/lfortran/pull/3075. Once it gets merged, I believe the errors will be resolved.
Let's just wait for some time. Till then you can explore some other issues :)

**Comment by HarshitaKalani** [comment]
@Baitato you can give it a try now and let me know if you face any issue.

**Comment by Kishan-Ved** [comment]
Please check my PR, I started with a clean build and made changes. All the checks passed.

**Comment by certik** [comment]
We need to move to this design: https://github.com/lfortran/lfortran/issues/3090.

**Comment by Kishan-Ved** [comment]
Working on it.
