### ISSUE TITLE
implement intrinsic `ishftc`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3083]
```fortran
program main
    integer(8) :: st(4) = [1, 2, 3, 4]
    print*, ishftc(st(2) * 5, 2)
end
```
```console
$ gfortran b.f90 && ./a.out
                   40
$ lfortran b.f90
semantic error: Function 'ishftc' not found or not implemented yet (if it is intrinsic)
 --> b.f90:3:13
  |
3 |     print*, ishftc(st(2) * 5, 2)
  |             ^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
Ref: https://github.com/lfortran/lfortran/issues/3052#issuecomment-1886572426

**Comment by khushi-411** [comment]
I'll work on this! Just commenting for visibility :-)

**Comment by HarshitaKalani** [comment]
Hey @khushi-411 , are you working on this?

**Comment by khushi-411** [comment]
Hey, @HarshitaKalani! Yeah, I'd work on this today! Will send the PR soon. Thanks!

**Comment by HarshitaKalani** [comment]
Perfect, thank you.

**Comment by Pranavchiku** [comment]
@khushi-411 if you are not working on it, @parth121101 may give it a shot?

**Comment by khushi-411** [comment]
Sure, @Pranavchiku! @parth121101, feel free to pick it up; I'm working on a different issue right now.
