### ISSUE TITLE
ASR intrinsics design improvements

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3129]
Currently in `intrinsic_function_registry.h` we have:
```c++
enum class IntrinsicScalarFunctions : int64_t {
    Kind, // if kind is reordered, update `extract_kind` in `asr_utils.h`
    Sin,
    Cos,
    Tan,
    Asin,
    Acos,
    Atan,
    Sinh,
    Cosh,
    Tanh,
    Atan2,
    Gamma,
    LogGamma,
...
```
And then we have there code like this:
```c++
namespace Sign {

     static inline void verify_args(const ASR::IntrinsicScalarFunction_t& x, diag::Diagnostics& diagnostics) {
        ASRUtils::require_impl(x.n_args == 2,
            "ASR Verify: Call to sign must have exactly two arguments",
            x.base.base.loc, diagnostics);
        ASR::ttype_t *type1 = ASRUtils::expr_type(x.m_args[0]);
        ASR::ttype_t *type2 = ASRUtils::expr_type(x.m_args[1]);
        ASRUtils::require_impl((is_real(*type1) || is_integer(*type2)),
            "ASR Verify: Arguments to sign must be of real or integer type",
            x.base.base.loc, diagnostics);
        ASRUtils::require_impl((ASRUtils::check_equal_type(type1, type2)),
            "ASR Verify: All arguments must be of the same type",
            x.base.base.loc, diagnostics);
    }
...
    static inline ASR::asr_t* create_Sign(Allocator& al, const Location& loc,
            Vec<ASR::expr_t*>& args,
            const std::function<void (const std::string &, const Location &)> err) {
        if (args.size() != 2) {
            err("Intrinsic sign function accepts exactly 2 arguments", loc);
        }
        ASR::ttype_t *type1 = ASRUtils::expr_type(args[0]);
        ASR::ttype_t *type2 = ASRUtils::expr_type(args[1]);
        if (!ASRUtils::is_integer(*type1) && !ASRUtils::is_real(*type1)) {
            err("Argument of the sign function must be Integer or Real",
                args[0]->base.loc);
        }
        if (!ASRUtils::check_equal_type(type1, type2)) {
            err("Type mismatch in statement function: "
                "the second argument must have the same type "
                "and kind as the first argument.", args[1]->base.loc);
        }
        ASR::expr_t *m_value = nullptr;
        if (all_args_evaluated(args)) {
            Vec<ASR::expr_t*> arg_values; arg_values.reserve(al, 2);
            arg_values.push_back(al, expr_value(args[0]));
            arg_values.push_back(al, expr_value(args[1]));
            m_value = eval_Sign(al, loc, expr_type(args[0]), arg_values);
        }
        return ASR::make_IntrinsicScalarFunction_t(al, loc,
            static_cast<int64_t>(IntrinsicScalarFunctions::Sign),
            args.p, args.n, 0, ASRUtils::expr_type(args[0]), m_value);
    }
```

Let's create a Python script that has definitions of all these ASR intrinsic functions and the argument types, and it generates the above list automatically, as well as the `verify_args`.  There are no optional arguments and no implicit semantics in ASR, so this should be quite straightforward and explicit. The script can then also generate documentation for all intrinsics, etc.

The `create_Sign` design is that the frontend should figure out the argument order (based on keyword names, which is front-end language specific), and convert them to ASR, and then we can check that they have the correct type in `create_Sign` (and correct number of arguments), in a front-end language independent manner.

Here is an example of the definition that the Python script will use to generate the above automatically:
```python
["Sign", (["real", "integer"], ["real", "integer"]), equal_types=True)],
["FloorDiv", (["real", "integer", "unsigned", "logical"], ["real", "integer", "unsigned", "logical"]), get_past_const=True, equal_types=True)]
```
Obviously we need to figure out what other checks are required.

**Comment by certik** [comment]
The old compile time evaluation can also be removed: https://github.com/lfortran/lfortran/issues/3169

**Comment by Thirumalai-Shaktivel** [comment]
I had this in mind for the past couple of months, but I didn't know whether to do it using C++ or Python. As you have suggested and Ubaid already implemented for `verify_args`, I think we need to implement the same for `create_*` as well.

@Shaikh-Ubaid, I have some ideas in mind and would like to try. Can I work on this issue?
If you have already started working on it, ping me once you are done, or let me know if you need any help.

**Comment by Shaikh-Ubaid** [comment]
Go ahead. If you need any help, feel free to get in touch. Also some plans I had in mind that you can try:

- supporting the trigonometry functions
- supporting unary functions
- supporting symbolic functions
- support for specifying kinds in the python script
- return types for different intrinsic functions also need to be checked

**Comment by certik** [comment]
You can both work on it. This requires a lot of small iterative improvements, moving more and more things into the Python script and generate the C++ code. @Thirumalai-Shaktivel we need this quite urgently now, since we are implementing more and more intrinsic functions and we need to lower the amount of work we need to do for each new function, so abstracting this out is needed. I recommend you both work on it.

**Comment by certik** [comment]
Thanks, great job @Shaikh-Ubaid !

I created a new issue for the remaining tasks: https://github.com/lfortran/lfortran/issues/3383
