### ISSUE TITLE
Implement `lshift`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3137]
```fortran
program main
   print*, lshift(4, 2)
end
```
```console
$ gfortran a.f90 && ./a.out
          16
$ lfortran a.f90
semantic error: Function 'lshift' not found or not implemented yet (if it is intrinsic)
 --> a.f90:2:12
  |
2 |    print*, lshift(4, 2)
  |            ^^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
Refer: https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gfortran/LSHIFT.html'
Follow: https://github.com/lfortran/lfortran/pull/3134

**Comment by HarshitaKalani** [comment]
There's another function which looks similar to me - `shiftl`: https://gcc.gnu.org/onlinedocs/gcc-4.4.7/gfortran/LSHIFT.html

**Comment by gxyd** [comment]
Could I maybe take this issue, as noone else is working on it yet?

**Comment by HarshitaKalani** [comment]
Yes please go ahead.
