### ISSUE TITLE
implement intrinsic `pack`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3155]
Towards: #3052 
```fortran
PROGRAM test_pack_1
    INTEGER :: m1(6)
    INTEGER :: m2(4)
    m1 = (/ 1, 0, 0, 0, 5, 0 /)
    m2 = (/ 1, 0, 0, 2 /)
    WRITE(*, FMT="(6(I0, ' '))") pack(m1, m1 /= 0)  ! "1 5"
    WRITE(*, FMT="(4(I0, ' '))") pack(m2, m2 /= 0, (/ 0, 0, 3, 4 /))
END PROGRAM
```
```console
$ gfortran b.f90 && ./a.out
1 5 
1 2 3 4 
$ lfortran b.f90
Internal Compiler Error: Unhandled exception
^C
```

**Comment by gxyd** [comment]
So the issue is with regards to the ASR->LLVM stage for `ArrayPack` node of ASR. I might like to try to implement it.

**Comment by HarshitaKalani** [comment]
I guess @Pranavchiku is already working on this issue: https://github.com/lfortran/lfortran/pull/3464

**Comment by gxyd** [comment]
Thanks for letting me know. I see that this issue seems to well handled there. Weird, that PR doesn't make any change in asr_to_llvm.cpp, I guess it's probably being done as another pass now.

**Comment by HarshitaKalani** [comment]
With the implementation of `pack` here https://github.com/lfortran/lfortran/pull/3464, I'm getting the following difference in output with GFortran and LFortran. 
```console
$ gfortran a.f90 && ./a.out
1 5 
1 2 3 4 
$ lfortran a.f90
1 5 0 0 0 0 
1 2 3 4 
```

**Comment by Pranavchiku** [comment]
Yes, this is intentional. I have added a TODO to remove this, for now we will fill it with zeros.

**Comment by HarshitaKalani** [comment]
Closing as works perfect with the latest main.
