### ISSUE TITLE
fix string slicing

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3183]
```fortran
program string_slice
    implicit none
    character :: s = "lfortran"
    print*, len(s)
    print*, s(1:1)
end program 
```
```console
$ lfortran b.f90
8
l
(lf) harshita@harshita-linux:~/Desktop/lfortran$ gfortran b.f90 && ./a.out
           1
 l
```

```fortran
program string_slice
    implicit none
    character :: s = "lfortran"
    print*, len(s)
    print*, s(1:2)
end program 
```
```console
(lf) harshita@harshita-linux:~/Desktop/lfortran$ lfortran b.f90
8
lf
(lf) harshita@harshita-linux:~/Desktop/lfortran$ gfortran b.f90 && ./a.out
b.f90:5:14:

    5 |     print*, s(1:2)
      |              1
Error: Substring end index at (1) exceeds the string length
```

**Comment by certik** [comment]
The length of the `character :: s` is 1. Assigning a string to it I guess only assigns what fits? The whole string handling in Fortran is not very intuitive. In ASR we need to add verify checks to ensure that assigning strings have exactly the correct length, and then in AST->ASR we can insert explicit casts or slices as appropriate.

**Comment by satyam4484** [comment]
I Found something that might help you 

`Program string_slice
    implicit none
    character(len=8) :: s = "lfortran"
    
    ! Print the length of the string
    print*, "Length of s:", len(s)
    
    ! Print the whole string
    print*, "Whole string:", s(1:len(s))
    
    ! Print a slice of the string (e.g., characters 2 to 5)
    print*, "Slice of string (2:5):", s(2:5)
    
end program string_slice`
