### ISSUE TITLE
Consider lines starting from C or * comments.

### ISSUE THREAD

**Issue by andriish** [lfortran/lfortran#3184]
That would be great to implement this feature.
It would be extremely useful for the compilation of the old codes.

**Comment by certik** [comment]
I think that's already implemented. Use `--fixed-form`. Can you check that it works for you?

**Comment by andriish** [comment]
Hi @certik,

my fault. Just updated to 0.31 on Fedora and the issue is solved.
Will report other issues.

Best regards,

Andrii

**Comment by andriish** [comment]
Thanks!
