### ISSUE TITLE
Throw error if end index exceeds in length while slicing string

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3196]
```fortran
program string_slice
   implicit none
   character(len=8) :: s = "lfortran"

   print*, "Length of s:", len(s)
   print*, s(1: 9)

end program
```
```console
$ gfortran a.f90 && ./a.out
a.f90:6:13:

    6 |    print*, s(1: 9)
      |             1
Error: Substring end index at (1) exceeds the string length
$ lfortran a.f90
Length of s:8
lfortran
```

**Comment by s3luu** [comment]
Hi! Can I pick up this issue? I have never contributed to an open source project before :)

**Comment by rjgadonniex** [comment]
Hello! Could I be assigned to this issue? I believe I can identify the fix.

**Comment by certik** [comment]
Just submit a PR, no need to ask. You can both work on it.

**Comment by darango3002** [comment]
I would also like to work on this if possible. This would be my first open source contribution.

**Comment by Kishan-Ved** [comment]
Fixed in this PR: https://github.com/lfortran/lfortran/pull/3233
