### ISSUE TITLE
implement intrinsic `floor`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3255]
Implement in `intrinsic_function_registry.h`.
Hint: Take idea from `floor` implementation in `comptime_eval.h`, `ast_common_visitor.h` and `src/runtime/pure/lfortran_intrinsic_trig.f90` and finally remove them.

**Comment by HarshitaKalani** [comment]
```fortran
program main
	real :: x
	x = 4.5
	print*, floor([4.9, 4.5])
end
```
```console
$ lfortran a.f90
semantic error: floor must have one real argument
 --> a.f90:1:1
  |
1 | program main
  | ^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
$ gfortran a.f90 && ./a.out
           4           4
```

here, the location of error is wrong too.

**Comment by Pranavchiku** [comment]
Although this example works with LFortran, for easy understanding:

```fortran
program main
    real :: x = 5.8
    print *, floor(x)
end program
```

Refer: https://gcc.gnu.org/onlinedocs/gfortran/FLOOR.html

**Comment by HarshitaKalani** [comment]
Following this, one can then implement ceiling too.

**Comment by parth121101** [comment]
I am working on this. Will open PR soon

**Comment by Kishan-Ved** [comment]
> Following this, one can then implement ceiling too.

I'll work on implementing ceiling.

**Comment by parth121101** [comment]
Since I have already implemented floor it would be easy for me to implement ceil.

**Comment by Kishan-Ved** [comment]
Ok cool, you can go ahead with it.
