### ISSUE TITLE
Implement `adjustl`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#3256]
Implement in `intrinsic_function_registry.h`
Hint: Take idea from `adjustl` implementation in `comptime_eval.h`, `ast_common_visitor.h` and `src/runtime/pure/lfortran_intrinsic_string.f90` and finally remove them.

Ref: https://gcc.gnu.org/onlinedocs/gfortran/ADJUSTL.html

**Comment by HarshitaKalani** [comment]
Following this, one can then implement `adjustr`.

**Comment by Kishan-Ved** [comment]
> Implement in `intrinsic_function_registry.h` Hint: Take idea from `adjustl` implementation in `comptime_eval.h`, `ast_common_visitor.h` and `src/runtime/pure/lfortran_intrinsic_string.f90` and finally remove them.
> 
> Ref: https://gcc.gnu.org/onlinedocs/gfortran/ADJUSTL.html

I believe `ast_common_visitor.h` doesn't have adjustl.

**Comment by Kishan-Ved** [comment]
Working on this.
