### ISSUE TITLE
add topic fortran-compiler

### ISSUE THREAD

**Issue by Beliavsky** [lfortran/lfortran#3271]
I suggest adding the topic `fortran-compiler` in the About section.

**Comment by certik** [comment]
Which about section? I don't see one in the documentation.

**Comment by Beliavsky** [comment]
The place at https://github.com/lfortran/lfortran where you list [library](https://github.com/topics/library) [jupyter](https://github.com/topics/jupyter) [compiler](https://github.com/topics/compiler) [fortran](https://github.com/topics/fortran) [interactive](https://github.com/topics/interactive) [repl](https://github.com/topics/repl) [jupyter-notebook](https://github.com/topics/jupyter-notebook) [jupyter-kernels](https://github.com/topics/jupyter-kernels)

**Comment by certik** [comment]
Ah I see, I just put it there, does it look good now?

**Comment by Beliavsky** [comment]
yes
