### ISSUE TITLE
linking a shared library

### ISSUE THREAD

**Issue by junghans** [lfortran/lfortran#3281]
I am trying to link a shared library.
```
lfortran -v -fPIC --generate-object-code --implicit-interface -shared -Wl,-soname,libworld.so -o libworld.so world.f.o
```

We don't have `-shared` option, as this needs to go to `clang`, I thought
```
lfortran -v -fPIC --generate-object-code --implicit-interface -W,-shared -Wl,-soname,libworld.so -o libworld.so world.f.o
```
but that fails with:
```
lfortran -v -fPIC --generate-object-code --implicit-interface -W,-shared -Wl,-soname,libworld.so -olibworld.so world.f.o
clang -o libworld.so world.f.o  -L"/usr/bin/../lib64" -Wl,-rpath,"/usr/bin/../lib64" -llfortran_runtime -lm
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-redhat-linux/13/../../../../lib64/crt1.o: in function `_start':
(.text+0x1b): undefined reference to `main'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
For some reason, the `-shared` is missing in the `clang` call.

Running:
```
clang -o libworld.so world.f.o  -L"/usr/bin/../lib64" -shared -Wl,-rpath,"/usr/bin/../lib64" -llfortran_runtime -lm
```
works, so somewhere there is a bug in the `-W` option parsing....

**Comment by certik** [comment]
The linking will be done by Clang, so I think we just need to get the options passed through correctly. We do link external libraries via cmake and LFortran here for example:

https://github.com/certik/fastGPT/blob/c2148fbd909c82ec72eaccc00d8ddc51e9106144/CMakeLists.txt#L76

and it works, so there shouldn't be a big roadblock to this.

**Comment by junghans** [comment]
Looking at the clang invocation from `-v` is seems all `-W` options are ignored. 

External libraries are different as they start with `-l`.

**Comment by junghans** [comment]
I am a bit confused by this code:
https://github.com/lfortran/lfortran/blob/0ac37572d74b173871d5c54fe88bf6c01b87eae2/src/bin/lfortran.cpp#L2085-L2090

We throw away everything, but the first option, then we extract the `rpath` value and then re-assemble it, the paths are used no where else. I guess it would be better to just pass them through like `-L` and `-l`.

**Comment by certik** [comment]
It looks like it is hackish and we should clean it up.

**Comment by certik** [comment]
Hopefully it's not difficult to fix it properly and pass through the proper options.

**Comment by junghans** [comment]
Here is my plan: For `-l`, `-L`, `-shared`, other files just hand them through to the linker. Clean up `-W` be a pass through as well, no more `rpath` parsing.

**Comment by certik** [comment]
Yes, we can do that.
