### ISSUE TITLE
CI: Only hashes for reference tests are checked

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3306]
which means one can commit any reference stdout/stderr/output file as long as he committed the hash corresponding to the correct stdout/stderr/output.

>The reference outputs still update. I investigated the issue. I think in one of the previous PRs, updated `json` reference files were committed, but the updated stdout/stderr/output were not committed. It seems at the CI we do not check/verify if the `stdhash` in the json reference file corresponds to the committed stdout/stderr/output file or not. In other words, we simply check if the committed hash and generated hash for reference files are the same or not. We do not check if the committed hash belongs to the committed stdout/stderr/output file or not.

_Originally posted by @Shaikh-Ubaid in https://github.com/lfortran/lfortran/pull/3290#discussion_r1477143047_

**Comment by certik** [comment]
Thanks @Shaikh-Ubaid for fixing this!
