### ISSUE TITLE
Implementing -rdynamic?

### ISSUE THREAD

**Issue by junghans** [lfortran/lfortran#3310]
Last thing for #3208, what are we doing about the `-rdynamic` option? Implement or ignore?

GNU does:
```
       -rdynamic
           Pass  the  flag  -export-dynamic  to  the  ELF linker, on targets that support it. This instructs the linker to add all
           symbols, not only used ones, to the dynamic symbol table. This option is needed for some uses of "dlopen" or  to  allow
           obtaining backtraces from within a program.
```

**Comment by certik** [comment]
If anybody needs it, we can implement it. I don't remember ever using it. If any of your projects need it, then let's implement it.

**Comment by junghans** [comment]
Ok, looking at this again, I think on can achieve the same thing with `-Wl,-export-dynamic`, so I think this is not needed.
