### ISSUE TITLE
compiling stdlib linalg

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3323]
Using [lf-linalg](https://github.com/Pranavchiku/stdlib-fortran-lang/tree/lf-linalg) branch, gfortran works well.

With LFortran

```script
set -ex
FC=lfortran cmake .
make fortran_stdlib
cp src/*.mod example/linalg
make VERBOSE=1

./example/linalg/example_eye1		
./example/linalg/example_is_symmetric
./example/linalg/example_cross_product	
./example/linalg/example_eye2		
./example/linalg/example_is_triangular
./example/linalg/example_diag1		
./example/linalg/example_is_diagonal		
./example/linalg/example_kronecker_product
./example/linalg/example_diag2		
./example/linalg/example_is_hermitian	
./example/linalg/example_outer_product
./example/linalg/example_diag3		
./example/linalg/example_is_hessenberg	
./example/linalg/example_trace
./example/linalg/example_diag4		
./example/linalg/example_is_skew_symmetric

git clean -dfx
```

```console
[..,]
Scanning dependencies of target example_diag1
make[2]: Leaving directory '/Users/pranavchiku/repos/stdlib'
make  -f example/linalg/CMakeFiles/example_diag1.dir/build.make example/linalg/CMakeFiles/example_diag1.dir/build
make[2]: Entering directory '/Users/pranavchiku/repos/stdlib'
[ 36%] Building Fortran object example/linalg/CMakeFiles/example_diag1.dir/example_diag1.f90.o
cd /Users/pranavchiku/repos/stdlib/example/linalg && /Users/pranavchiku/repos/lfortran/src/bin/lfortran  -I/Users/pranavchiku/repos/stdlib/src/mod_files  -c /Users/pranavchiku/repos/stdlib/example/linalg/example_diag1.f90 -o CMakeFiles/example_diag1.dir/example_diag1.f90.o
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2372
    LCompilers::print_stack_on_segfault();
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 2304
    return compile_to_object_file(arg_file, outfile, false,
  File "/Users/pranavchiku/repos/lfortran/src/bin/lfortran.cpp", line 949
    res = fe.get_llvm3(*asr, lpm, diagnostics, infile);
  File "/Users/pranavchiku/repos/lfortran/src/lfortran/fortran_evaluator.cpp", line 360
    compiler_options, run_fn, infile);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/codegen/asr_to_llvm.cpp", line 9561
    pass_manager.apply_passes(al, &asr, co.po, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 302
    apply_passes(al, asr, _passes, pass_options, diagnostics);
  File "/Users/pranavchiku/repos/lfortran/src/libasr/pass/pass_manager.h", line 166
    throw LCompilersException("Verify failed in the pass: "
LCompilersException: Verify failed in the pass: subroutine_from_function
make[2]: *** [example/linalg/CMakeFiles/example_diag1.dir/build.make:75: example/linalg/CMakeFiles/example_diag1.dir/example_diag1.f90.o] Error 1
make[2]: Leaving directory '/Users/pranavchiku/repos/stdlib'
make[1]: *** [CMakeFiles/Makefile2:979: example/linalg/CMakeFiles/example_diag1.dir/all] Error 2
make[1]: Leaving directory '/Users/pranavchiku/repos/stdlib'
make: *** [Makefile:146: all] Error 2
```

---

Workarounds:

* [x] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/c9b4090da37dd3aae824d433aa5fc6e689207f0b #3407 #3415
* [x] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/8b90459bf17d6547ca268e2a4d8bb8071a5497ef ( submodule error )
* [x] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/96641b4a5113ed03c3fb34e7dfc1bbb41eb641d9 ( --realloc-lhs )
* [ ] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/c126687bbc3d6f7d0f7873aaf81dca1b7e045909
* [ ] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/c6733dd3d521939e059fb8cab8be7871cc2c0aa2
* [ ] https://github.com/Pranavchiku/stdlib-fortran-lang/commit/a2449ee5897bcf9ba042e7482c01261a5bcbd732

---

Examples:

* [ ] example_eye1		
* [ ] example_is_symmetric
* [ ] example_eye2		
* [ ] example_is_triangular
* [ ] example_diag1		
* [ ] example_is_diagonal		
* [ ] example_diag2		
* [ ] example_is_hermitian	
* [ ] example_outer_product
* [ ] example_diag3		
* [ ] example_is_hessenberg	
* [ ] example_trace
* [ ] example_diag4		
* [ ] example_is_skew_symmetric

---

Issues to fix:

* [ ] example_diag1
    * [x] #3366
* [ ] stdlib_linalg
    * [x] #3337

**Comment by Pranavchiku** [comment]
Branch: https://github.com/Pranavchiku/stdlib-fortran-lang/commits/lf-linalg4
With this we have entire `stdlib_linalg` compiled and aligned ( 2 case fails ) with GFortran.  There are a few workarounds which are listed in issue description.

**Comment by czgdp1807** [comment]
Let's close this and open a new issue because everything listed here is complete. What we need is to compile ``stdlib/test/linalg/test_linalg``.

**Comment by Pranavchiku** [comment]
In my opinion let's populate this only, else it will make it difficult to keep track.

**Comment by Pranavchiku** [comment]
Also, examples few examples do not align with GFortran yet.

**Comment by czgdp1807** [comment]
This issue has outdated information. 

> Also, few examples do not align with GFortran yet.

Can you point which examples?
