### ISSUE TITLE
Rename `Reserve` to `ListReserve` in intrinsic function registry

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3346]

**Comment by rajeshkotaru** [comment]
working on it

**Comment by Shaikh-Ubaid** [comment]
>working on it

Sure, go ahead. Looking forward to your PR. Feel free to reach out if you need any help.

**Comment by rajeshkotaru** [comment]
there are 90+ with "reserve" and around 10 with "Reserve" in (intrinsic_function_registry.h)
 would u want we to change only Reserve or both ?

**Comment by Shaikh-Ubaid** [comment]
See where all `ListReverse` is used. Similar to it the `Reserve` should be `ListReserve` at appropriate places.

If `ListReverse` at some place is `list.reverse`, then `reserve` should be `list.reserve`.

**Comment by rajeshkotaru** [comment]
ok

**Comment by rajeshkotaru** [comment]
Opened a pull request

**Comment by Shaikh-Ubaid** [comment]
Can you post a link to the PR here?

**Comment by rajeshkotaru** [comment]
sorry bymistake opened PR in lpython

**Comment by rajeshkotaru** [comment]
pull request passed all 22 CI checks,can u please review it.

**Comment by Shaikh-Ubaid** [comment]
Closing as completed in https://github.com/lfortran/lfortran/pull/3360.

**Comment by Shaikh-Ubaid** [comment]
Thanks @rajeshkotaru! Amazing work!
