### ISSUE TITLE
ASR: inconsistent Const handling

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3374]
We have a `Const` ttype ASR node. We also have a `expr? value` member of a `Variable` node. The documentation says:
```
`value` the optional constant expression holding the compile time value
(e.g. `5`, or `5.5`), it is a compile time constant.
```

So we have two ways to represent constants. It seems removing the Const node would simplify things.

**Comment by Shaikh-Ubaid** [comment]
There is also another way. Setting the storage type as `storage_typeType::Parameter` also implies a constant.

**Comment by Shaikh-Ubaid** [comment]
It seems we have some redundant ways to represent the same thing.

**Comment by certik** [comment]
Yes. One option: `storage_type == Parameter` implies `value != nullptr`. If `value == nullptr`, then  `storage_type != Parameter`. Enforced by Verify. Get rid of Const.
