### ISSUE TITLE
Add ToLowerCase elemental intrinsic

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3550]
It will convert a string to lower case. This is needed directly in LPython, and it is needed for LFortran as well to do case insensitive string comparison at runtime.

Discussed at https://lfortran.zulipchat.com/#narrow/stream/197339-general/topic/ToLowerCase.20Elemental.20Intrinsic.

**Comment by Pranavchiku** [comment]
Implemented in #3556, closing it.
