### ISSUE TITLE
Change the ASR representation of ArrayConstant

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3581]
Currently ArrayConstant contains a list of individual constants, like RealConstant.

Instead, it should contain a type (that includes kind) of the element, shape, and then a pointer to contiguous data. This will be fast, and automatically enforce all the things we care about:

* That ArrayConstant only contains constants
* That all constants it contains have the same type and kind
* That it doesn't point to any other node by a mistake

**Comment by Pranavchiku** [comment]
I am not exactly sure of how ASR definition shall look like, if you can post it, it will be really helpful.

**Comment by certik** [comment]
Maybe something like this:
```diff
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -139,7 +139,7 @@ expr
     | Var(symbol v)
     | FunctionParam(int param_number, ttype type, expr? value)
     | ArrayConstructor(expr* args, ttype type, expr? value, arraystorage storage_format)
-    | ArrayConstant(expr* args, ttype type, arraystorage storage_format)
+    | ArrayConstant(ttype type, int* data, arraystorage storage_format)
     | ArrayItem(expr v, array_index* args, ttype type, arraystorage storage_format, expr? value)
     | ArraySection(expr v, array_index* args, ttype type, expr? value)
     | ArraySize(expr v, expr? dim, ttype type, expr? value)
```
This should generate `n_data` and `m_data` pointer. Although we might not support `int*`. So maybe we need to introduce a new intrinsic type in asdl for this.

At the C++ side, it should be length and pointer to data. Maybe we can use `ArrayConstant(ttype type, string data, arraystorage storage_format)`, which might work, as I think strings are represented by a length and a pointer to data, which is exactly what we need here. We can have 0 in there, but I think it might work.

**Comment by certik** [comment]
Once this works, we can then do: https://github.com/lfortran/lfortran/issues/3203#issuecomment-2015804152

**Comment by certik** [comment]
@Pranavchiku I forgot about this issue: I think now is a good time to get this fixed. Let's wrap up stdlib, and then fix this.

**Comment by Pranavchiku** [comment]
Yes, perfect.

**Comment by Pranavchiku** [comment]
I have a small question ( maybe things are not clear to me yet ), how are we going to represent `ASR::expr_t** args` using `char*`?

**Comment by certik** [comment]
Are you asking how to implement ArrayConstant for an array of strings?

**Comment by Pranavchiku** [comment]
I think I have it, `char* data = (char *) args;` will do the trick.

**Comment by Pranavchiku** [comment]
This issue affects a wide range of codebase thus I wish to be sure before I start making changes ( I did give few shots, missed )

> Grammar

```diff
diff --git a/src/libasr/ASR.asdl b/src/libasr/ASR.asdl
index f61430d06..c96911943 100644
--- a/src/libasr/ASR.asdl
+++ b/src/libasr/ASR.asdl
@@ -140,7 +140,7 @@ expr
     | Var(symbol v)
     | FunctionParam(int param_number, ttype type, expr? value)
     | ArrayConstructor(expr* args, ttype type, expr? value, arraystorage storage_format)
-    | ArrayConstant(expr* args, ttype type, arraystorage storage_format)
+    | ArrayConstant(string data, ttype type, arraystorage storage_format)
     | ArrayItem(expr v, array_index* args, ttype type, arraystorage storage_format, expr? value)
     | ArraySection(expr v, array_index* args, ttype type, expr? value)
     | ArraySize(expr v, expr? dim, ttype type, expr? value)
```

> Populating values

Assuming it is an `integer` array constant, we will do something like

```cpp
        int *values = new int[n_args];
        for (size_t i = 0; i < n_args; i++) {
            ASR::expr_t* a_value = ASRUtils::expr_value(a_args[i]);
            values[i] = ASR::down_cast<ASR::IntegerConstant_t>(a_value)->m_n;
        }
        char* data = (char*)values;
```

> Fetch array size

Assuming `ASR::ArrayConstant_t* x`, `int size = ASRUtils::get_fixed_size_of_array(x->m_type)`.

> Fetch array element

To fetch `ith` element i.e., `x->m_args[i]` will now be `((ASR::expr_t*) data->m_data) + i`.
