### ISSUE TITLE
The main branch has been rebased (hashes changed)

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#3589]
About a month ago we merged a PR that contained a large binary. We removed it from history using `git filter-repo`, which changed all hashes after January 31, 2024. The details of the binary removal process are in https://github.com/lfortran/lfortran/pull/3577.

## Summary:

* Old main was moved to `old-main` (we will keep this branch for some time for reference; once everybody moved to the new main, we will remove it and close this issue)
* The main branch has been replaced with the fixed branch.
* The latest commit in old main (now part of `old-main`) was bd8e83cbd9d85034eb1a9474d8d26a51bfb35117 (CI: https://github.com/lfortran/lfortran/actions/runs/8162236398)
* The equivalent commit of the new main (now part of `main`) is aafa829bb6bf942f90ea7911660933f2e6c2b9c6 (CI: https://github.com/lfortran/lfortran/actions/runs/8162696884)
* The last common shared (good) commit in both branches is dca110d46606d068dbca0fb334b4bf612ab4011d, after which both branches diverge
* No tags nor releases were affected (we didn't tag any commit since the last good commit)
* `old-main` branch (after `git gc`) is 45MB, `main` branch is 25MB.

### Update your main

```
git checkout main
git checkout -b main-old
git fetch origin +main:main
```

### Rebase your branches

```
git checkout my_branch
git rebase bd8e83cbd9d85034eb1a9474d8d26a51bfb35117
git rebase --onto aafa829bb6bf942f90ea7911660933f2e6c2b9c6 bd8e83cbd9d85034eb1a9474d8d26a51bfb35117
git rebase main
```

This first rebases your branch on top of the latest `old-main`, you must resolve conflicts as usual. Then it transplants only your commits from the latest `old-main` on top of the equivalent commit in `main` (using `rebase --onto`), which should just work (no conflicts), since the code is identical except the missing binary. Finally, it rebases on top of the latest main, you must resolve conflicts as usual.

**Comment by Shaikh-Ubaid** [comment]
It seems that now the commits that we have in the new `main` and the commits (of the `old-main`) that were committed in the PRs in the last month do not match. A consequence of this could be that we cannot link-to or obtain the PR in which a specific commit of the new `main` belonged.

For example, this commit https://github.com/lfortran/lfortran/commit/fb2b8e5505be099bee3400fdb34f68bdc460737a belongs to the new `main`, but github is unable to link/understand which PR it was committed.

**Comment by certik** [comment]
@Shaikh-Ubaid, yes, that's an unfortunate side effect of this change, but probably not much we can do about it. The PR number is still present in the merge commit message, so one can figure it out that way.

Anyone has any issue with this change? I think we can probably move the `old-main` into my fork soon.

**Comment by certik** [comment]
I pushed the `old-main` here: https://github.com/certik/lfortran/tree/old-main, where it can remain for a long time.

**Comment by certik** [comment]
I removed `old-main` from this main repository, so I am going to close this issue now.

**Comment by certik** [comment]
For reference:
```console
$ git clone https://github.com/lfortran/lfortran
$ cd lfortran
$ git show
commit 755ad600e9ff89c80883ed4755b07505987f4c24 (HEAD -> main, origin/main, origin/HEAD)
...
$ du -sh .git
 35M	.git
$ git gc --prune=now --aggressive
$ du -sh .git                    
 25M	.git
```

So the default downloaded git repository is 35MB, but when we run `gc`, it gets down to 25MB. So I think the binary has been removed and things look good.
