### ISSUE TITLE
ENH: Refactor `ToLowerCase` to define and use macros

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3618]
Introduced in #3556, we can define a macro or call `Ichar` intrinsic in here.

https://github.com/lfortran/lfortran/blob/755ad600e9ff89c80883ed4755b07505987f4c24/src/libasr/pass/intrinsic_functions.h#L3173-L3184

**Comment by Pranavchiku** [comment]
@parth121101 if you don't mind, I have a sample idea on how to refactor this, may I pick this up?

**Comment by parth121101** [comment]
> @parth121101 if you don't mind, I have a sample idea on how to refactor this, may I pick this up?

sure @Pranavchiku
