### ISSUE TITLE
CI: Flaky tests/jobs

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3619]
I think something somewhere is flaky. Many a times I am needing to rerun the CI just because some test either an integration test or a reference test fails in one of the jobs. The same failed test later easily passes in the next run.

Example: 
- https://github.com/lfortran/lfortran/actions/runs/8231069708 (failed in a reference test but passed in the next attempt).
- https://github.com/lfortran/lfortran/actions/runs/8349229152/attempts/1.
- https://github.com/lfortran/lfortran/actions/runs/8416999752/job/23044644284?pr=3704
- https://github.com/lfortran/lfortran/actions/runs/8483191078/attempts/1?pr=3389

**Comment by certik** [comment]
I think we have a bug somewhere, but we'll need to investigate. Let's link this issue to all flaky tests and let's figure out some pattern of what fails.

**Comment by Shaikh-Ubaid** [comment]
Another fake failure https://github.com/lfortran/lfortran/actions/runs/8349229152/attempts/1.

**Comment by Shaikh-Ubaid** [comment]
Another failure https://github.com/lfortran/lfortran/actions/runs/8483191078/attempts/1?pr=3389.

**Comment by certik** [comment]
The last failure is the same as https://github.com/lfortran/lfortran/issues/3736#issuecomment-2027256877.

**Comment by Pranavchiku** [comment]
One more https://github.com/lfortran/lfortran/actions/runs/8488767668/job/23258122870

**Comment by Pranavchiku** [comment]
Same again https://github.com/lfortran/lfortran/actions/runs/8488966919/job/23258555259
