### ISSUE TITLE
Use macro for variables cast in intrinsic functions pass

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3634]
One may use inbuilt macros like `i2r`, `r2r`, or define macros if needed instead of doing things like:

https://github.com/lfortran/lfortran/blob/b141da8ff8ce77bc583c60cce2cf7895cdddb8c3/src/libasr/pass/intrinsic_functions.h#L1765-L1768

**Comment by parth121101** [comment]
Thanks @Pranavchiku I used this cast while implementing floor function. I would use macros instead of cast variables and will soon open a new PR for the same.
