### ISSUE TITLE
Remove `compare` macro from ASRBuilder

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3644]
Towards #3277, reference PR: #3643.

One has to remove the following macros, add inline functions and perform consequent changes as done in reference PR.

https://github.com/lfortran/lfortran/blob/e7a1e2ee7cde90c3d298b01c489a8fd232d0597c/src/libasr/asr_builder.h#L337-L374

**Comment by Pranavchiku** [comment]
@parth121101 you may go ahead and open PR for this.

**Comment by parth121101** [comment]
Thanks @Pranavchiku , working on this, will open a PR soon

**Comment by Pranavchiku** [comment]
Any updates here?

**Comment by parth121101** [comment]
> Any updates here?

Opened a pr for the same.
#3657
