### ISSUE TITLE
Math: Implement `sqrt`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#367]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/468

Needed for https://gitlab.com/lfortran/lfortran/-/issues/401.

## Definition
As per J3/18-007r1 (the F2018 Interpretation Document):
![image](/uploads/f9a14d5145002ce499a292841d99ac7a/image.png)

## Example
Simple sample:
```fortran
program intrinsics_08
real :: x

x = sqrt(0.76159416)
print *, x

end
```
## Standard
Note that the relevant standard can be found here: [18-007r1.pdf](/uploads/973db2bfcc64cd2a397f823c32718b39/18-007r1.pdf)

**Comment by konradha** [comment]
I tested this a little, this can be considered done, right @certik ?

**Comment by certik** [comment]
Yes, sqrt works. Although it should be ported to use IntrinsicFunction.
