### ISSUE TITLE
Stdlib: Unformatted write() not supported

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3678]
```console
% cat examples/expr5.f90        
program expr2
    implicit none

    open(1, form="unformatted", file="tmp.txt")
    write(1) "hi"
    close(1)

end program
% gfortran examples/expr5.f90        
% ./a.out                            
% cat tmp.txt                   
hi%                                                                                        
% lfortran_in_main examples/expr5.f90
Binary content is not handled by write(..)
% echo $?
1
```

**Comment by gxyd** [comment]
I'll try to see if I can fix this issue.

**Comment by Shaikh-Ubaid** [comment]
@gxyd are you working on this?

**Comment by gxyd** [comment]
Yes, I am, I might take a little time to understand it's code, but definitely onto it.

**Comment by gxyd** [comment]
> Ok. It is one of the issue that other issues depend on for solving derived_io in stdlib and is a blocker for me. Try it for a day or two. Until then I will focus on formatted read/write.

I'm sorry, I missed your message. You can pick it up then, sorry to keep you waiting.
