### ISSUE TITLE
parser(fixed form): missing empty line termination raises syntax error

### ISSUE THREAD

**Issue by gnikit** [lfortran/lfortran#3738]
Missing a new line character when using the Fixed Form parser raises `syntax error: End of file is unexpected here`. I suspect this is a bug. BTW gfortran, ifx and legacy ifort compile okay.

## MWE

```fortran
      PROGRAM MWE1_MAIN
      END PROGRAM MWE1_MAIN
```

### Output

```sh
lfortran mwe.F --fixed-form
syntax error: End of file is unexpected here
 --> discourse_thread.F:2:28
  |
2 |       END PROGRAM MWE1_MAIN
  |                            ^^^^ 
```

## Additional Info

LFortran version: 0.33.1
Platform: Linux
Default target: x86_64-conda-linux-gnu

**Comment by gxyd** [comment]
I tried the above example with LFortran on main, I get a different error:
```bash
> lfortran mew.F --fixed-form
tokenizer error: ICE: Cannot recognize global scope entity
 --> mew.F:1:1
  |
1 | PROGRAM MWE1_MAIN
  | ^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
