### ISSUE TITLE
ICE for nonexistent program file

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#3796]
Having heard many times that internal compiler errors should always be reported to those responsible for compilers whether the program is valid or not, I give lfortran's otherwise correct response when it was asked to compile a nonexistent file.
```
(lf2) john:~/Jfh$ lfortran Foobar.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
  Binary file "/home/john/conda_root/envs/lf2/bin/lfortran", local address: 0x726858
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", local address: 0x29e3f
  Binary file "/lib/x86_64-linux-gnu/libc.so.6", local address: 0x29d8f
LCompilersException: File does not exist: Foobar.f90
(lf2) john:~/Jfh$
```

**Comment by certik** [comment]
Thanks! Yes, this needs to be a proper error message.

**Comment by certik** [comment]
Fixed by https://github.com/lfortran/lfortran/pull/5289.
