### ISSUE TITLE
`abs(X-mean)**2` throws error 

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#3809]
https://github.com/czgdp1807/stdlib/commit/5c54bef7165591d2bf79aac940ed2a2aa36e5faf

**Comment by HarshitaKalani** [comment]
This is completed with https://github.com/lfortran/lfortran/issues/3749. @Pranavchiku can you please confirm?
```fortran
program main
  real :: x(5) = [1, 2, 3, 4, 5]
  integer:: mean 
  mean = sum(x) / 5
  print*, sum(abs(x - mean)**2) / (5 - merge(1, 0, .true.))
end
```
```console
$ gfortran a.f90 && ./a.out
   2.50000000    
$ lfortran a.f90
2.50000000e+00
```

**Comment by Pranavchiku** [comment]
Yes, this works with latest main.

To close this
* [ ] add an integration test
* [ ] remove workaround from stdlib
* [ ] setup CI
