### ISSUE TITLE
Tiny can only return one type

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#381]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/493

`tiny()` currently always returns `real(4)`. But depending on the input argument, it should return `real(4)` or `real(8)`. We have to figure out how to make that work.

**Comment by HarshitaKalani** [comment]
This now works as expected.
```fortran
program main
   real(4) a
   real(8) b
   print*, tiny(a)
   print*, tiny(b)
   print*, kind(tiny(a))
   print*, kind(tiny(b))
end
```
```console
$ lfortran a.f90
1.17549435e-38
2.22507385850720138e-308
4
8
$ gfortran a.f90 && ./a.out
   1.17549435E-38
   2.2250738585072014E-308
           4
           8
```
