### ISSUE TITLE
lfortran seems to be missing iso_fortran_env module

### ISSUE THREAD

**Issue by kargl** [lfortran/lfortran#3881]
%  ../work/bin/lfortran --version
LFortran version: 0.35.0-11-g1ce45f421-dirty
Platform: FreeBSD
Default target: x86_64-portbld-freebsd15.0

% make
semantic error: Module 'iso_fortran_env' not declared in the current source and the modfile was not found
  --> mk_m90types.f90:12:4
   |
12 |    use iso_fortran_env
   |    ^^^^^^^^^^^^^^^^^^^ 

Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
*** Error code 1

% find ${HOME}/lfortran -name iso\*
<nada>

**Comment by kargl** [comment]
Ugh.  It seems that lfortran cannot find its modules, which isn't too surprise as it seems to not install the files.

% find . -name \*.mod
./lfortran/src/runtime/lfortran_intrinsic_kind.mod
./lfortran/src/runtime/lfortran_intrinsic_iso_fortran_env.mod
./lfortran/src/runtime/lfortran_intrinsic_builtin.mod
./lfortran/src/runtime/lfortran_intrinsic_math3.mod
./lfortran/src/runtime/lfortran_intrinsic_ieee_arithmetic.mod
./lfortran/src/runtime/lfortran_intrinsic_iso_c_binding.mod
./lfortran/src/runtime/lfortran_intrinsic_optimization.mod
./lfortran/src/runtime/lfortran_intrinsic_trig.mod
./lfortran/src/runtime/lfortran_intrinsic_bit.mod
./lfortran/src/runtime/lfortran_intrinsic_string.mod
./lfortran/src/runtime/lfortran_intrinsic_math2.mod
./lfortran/src/runtime/lfortran_intrinsic_math.mod
./lfortran/src/runtime/lfortran_intrinsic_sin.mod

`make install` should have installed the *.mod under ./work.

**Comment by kargl** [comment]
Curiouser and curiouser!

The *.mod are no longer built with the current git sources.

% cd src/runtime
% make
CMake Error at CMakeLists.txt:61 (install):
  install FILES given no DESTINATION!


-- Configuring incomplete, errors occurred!
*** Error code 1
% tail -12 CMakeLists.txt
  FILES
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_builtin.mod
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_custom.mod
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_iso_fortran_env.mod
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_ieee_arithmetic.mod
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_iso_c_binding.mod
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_math.mod
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_sin.mod
  ${CMAKE_Fortran_MODULE_DIRECTORY}/lfortran_intrinsic_string.mod
  DESTINATION ${CMAKE_INSTALL_LIBDIR}
  )

% find $HOME}/lfortran -name Makefile | xargs grep CMAKE_INSTALL_LIBDIR

Hmmm, so CMAKE_INSTALL_LIBDIR is unset?

**Comment by certik** [comment]
Weird. I just checked, the lfortran 0.35.0 conda package contains the `.mod` files in:
```console
$ ls share/lfortran/lib/
lfortran_intrinsic_builtin.mod          lfortran_intrinsic_iso_fortran_env.mod  liblfortran_runtime.so
lfortran_intrinsic_custom.mod           lfortran_intrinsic_math.mod             liblfortran_runtime.so.0
lfortran_intrinsic_ieee_arithmetic.mod  lfortran_intrinsic_sin.mod              liblfortran_runtime.so.0.35.0
lfortran_intrinsic_iso_c_binding.mod    lfortran_intrinsic_string.mod           liblfortran_runtime_static.a
```
They are installed using cmake. So at least sometimes they get installed.

I think you are on FreeBSD? Maybe the defaults behave differently there. You can consult the `build1.sh` script that shows how to build it on Linux/macOS:
```console
$ cat build1.sh
#!/usr/bin/env bash

set -e
set -x

cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -DWITH_LLVM=yes \
    -DLFORTRAN_BUILD_ALL=yes \
    -DWITH_STACKTRACE=yes \
    -DWITH_RUNTIME_STACKTRACE=yes \
    -DCMAKE_PREFIX_PATH="$CMAKE_PREFIX_PATH_LFORTRAN;$CONDA_PREFIX" \
    -DCMAKE_INSTALL_PREFIX=`pwd`/inst \
    -DCMAKE_INSTALL_LIBDIR=share/lfortran/lib \
    .
cmake --build . -j16 --target install
```
It seems it sets `CMAKE_INSTALL_LIBDIR`, so I think you should set it as well. Here is a minimal cmake run:
```
cmake \
    -DCMAKE_BUILD_TYPE=Debug \
    -DWITH_LLVM=yes \
    -DCMAKE_PREFIX_PATH="$CONDA_PREFIX" \
    -DCMAKE_INSTALL_PREFIX=`pwd`/inst \
    -DCMAKE_INSTALL_LIBDIR=share/lfortran/lib \
    .
```
I think you at least want to set these. For the `CMAKE_PREFIX_PATH` just put the root directory where LLVM is installed. Modify the install prefix. the libdir I think you can keep, so that lfortran knows where to find it, it's a relative path.

**Comment by kargl** [comment]
Yes. FreeBSD is my OS.  I have been using build0.sh, then doing
(note I use tcsh)

% cmake  -DCMAKE_BUILD_TYPE=Debug \
         -DWITH_LLVM=yes \
         -DCMAKE_INSTALL_PREFIX=~/lfortran/work \
         -DWITH_RUNTIME_LIBRARY=no \
         ../lfortran/CMakeLists.txt

by hand (it's a copy and paste from my crib sheet).  I tried adding  -DCMAKE_INSTALL_LIBDIR=~/lfortran/work/lib.
I guess the absolute path is causing issues. 

I have no idea what conda is.

**Comment by kargl** [comment]
The problem with `dl_phdr_info` is due to the use of `-DWITH_STACKTRACE=yes` and `-DWITH_RUNTIME_STACKTRACE=yes`.   One of these defines HAVE_LFORTRAN_LINK, and it seems that lfortran is trying to redefine internals on how the linker works.  I tried commenting out the offending lines in lfortran_intrinsics.c near line 35.  This leads to other issues with FreeBSD's `dl_pthr_info` not matching what lfortran wants.

**Comment by kargl** [comment]
With the addition of building with a customization to build0.sh and build1.sh.  The build issue can be split into individual issues.  Closing this one.

**Comment by certik** [comment]
Thanks. For reference, here are the two issues:

* https://github.com/lfortran/lfortran/issues/3895
* https://github.com/lfortran/lfortran/issues/3896
