### ISSUE TITLE
lfortran_intrinsic_custom module not declared?

### ISSUE THREAD

**Issue by kargl** [lfortran/lfortran#3882]
After replacing, `use iso_fortran_env` with `integer, parameter :: real_kinds(2) = [4, 8]` in mk_m90types.f90,
I now see

% make
semantic error: Module 'lfortran_intrinsic_custom' not declared in the current source and the modfile was not found
  --> mk_m90types.f90:18:4
   |
18 |    open(newunit=fd, file = 'm90types.f90', status='replace')
   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
*** Error code 1

**Comment by kargl** [comment]
Ugh.  It seems that lfortan cannot find its modules.    Whoops.  This should not happen.

% make
/usr/home/sgk/lfortran/work/bin/lfortran -g /usr/home/sgk/include -I. -o mk_m90types mk_m90types.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
LCompilersException: File does not exist: /usr/home/sgk/include

Note the typo in `${HOME}/include` (i.e., no `-I`).

**Comment by certik** [comment]
Not sure what is going on. If you need help debugging, let me know.
