### ISSUE TITLE
bug: external module's integer array element value is always 0

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#3897]
```fortran
module test
    implicit none
    integer(4), dimension(2) :: arr = [105, 109]
end module test

program a
    use test, only: arr
    implicit none
    integer :: i
    i = 1
    print *, arr(i)
end program a
```

the above program gives an output of '0' via LFortran, it should be '105'.

The issue is in `ASR->LLVM`, I found this issue while trying to fix https://github.com/lfortran/lfortran/issues/2969.

I've spent sometime trying to fix this issue, and would love to be the one to fix it.

**Comment by certik** [comment]
The `init_arr` can look like:
```
        subroutine init_arr
            arr = [105, 109]
        end subroutine init_arr
```

**Comment by certik** [comment]
I think we can start with having a global pass at the end which will go into every module and transform all module variable initializations into an init subroutine, and then call this init subroutine from the main program.
