### ISSUE TITLE
Problem while using --visualize flag

### ISSUE THREAD

**Issue by AkhilAkkapelli** [lfortran/lfortran#3916]
Command: (lf) C:\Users\akhil> `lfortran --visualize FortranTest.F90`
ERROR: 'link' is not recognized as an internal or external command, operable program or batch file.
The command 'link /NOLOGO /OUT: FortranTest.out FortranTest.out.temp.o C:\Users\akhil\miniconda3\envs\lf\Library\bin/../lib\lfortran_runtime_static.lib' failed.

**Comment by Shaikh-Ubaid** [comment]
The `--visualize` works with `--show-ast` and `--show-asr`. You need to provide both together, for example:

```console
lfortran examples/expr2.f90 --show-ast --visualize
```
