### ISSUE TITLE
`--backend` flag is not mentioned in the docs

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#3956]
There is no mention of `--backend` flag in the docs https://docs.lfortran.org/en/usage/#invoking-lfortran. Reported here https://fortran-lang.discourse.group/t/fortran-on-web-using-lfortran/7957/3.

**Comment by anushatomar13** [comment]
Hi @Shaikh-Ubaid ,
I would like to work on this issue. It would be great if you could assign it to me!
Thanks

**Comment by Shaikh-Ubaid** [comment]
Sure. I am glad you are interested in working on this. I assigned it to you.

Feel free to reach out of you need any help.

**Comment by anushatomar13** [comment]
Thank you @Shaikh-Ubaid 
Could you please clarify the usage and supported values for the `--backend` flag when invoking LFortran? I'd like to understand:

1. The list of supported backends/targets, especially for Windows and FreeBSD.
2. Whether it can be combined with flags like `--target`, `-c`, `-o`, or `--static`.
3. The appropriate section to include this documentation.
4. Any guidelines for contributing the documentation update.

This information will help me accurately document the `--backend` flag functionality for LFortran users. Please let me know if you need any additional details.

**Comment by Shaikh-Ubaid** [comment]
Let's start with what all info we have handy now and we can update/extend/improve it later.

- check `src/bin/lfortran.cpp` to understand about the combinations. 
- `-o` can be combined with any other command. It's just used to name the output file. 
- For `-c`, check the above mentioned `lfortran.cpp` file. It also contains info about the  `--backend` flag.
- See https://fortran-lang.discourse.group/t/fortran-on-web-using-lfortran/7957/5?u=ubaid-shaikh for info about `--target`.
- I think the above information should be mentioned as a part of https://docs.lfortran.org/en/usage/#invoking-lfortran.

**Comment by anushatomar13** [comment]
@Shaikh-Ubaid 
Please let me know if this looks fine to you or if any additional information is required.
