### ISSUE TITLE
Linking Error : Calling external function throws undefined refernce error  

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#4008]
Calling a **function** or **subroutine** from another file throws error.

> func.f90

```Fortran
function f() result(d) 
    implicit none 
    integer :: d 
    d = 9
end function f
```

>prog.f90
```Fortran
program a
    implicit none
    integer :: c
    integer  :: f 
    external :: f
    c = f()
    print *, c
end program a
```

```shell
assem@assem-PC:~/Desktop/fortran/test_05$ ../../../lfortran/src/bin/lfortran --implicit-interface  -c func.f90 
assem@assem-PC:~/Desktop/fortran/test_05$ ../../../lfortran/src/bin/lfortran --implicit-interface  -c prog.f90 
assem@assem-PC:~/Desktop/fortran/test_05$ ../../../lfortran/src/bin/lfortran --implicit-interface  -o mmm func.o prog.o 
/usr/bin/ld: prog.o: in function `main':
LFortran:(.text+0x7): undefined reference to `f'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o mmm func.o prog.o  -L"/home/assem/lfortran/src/bin/../runtime" -Wl,-rpath,"/home/assem/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
assem@assem-PC:~/Desktop/fortran/test_05$ 
```

**Comment by assem2002** [comment]
same as in #4009

**Comment by kmr-srbh** [comment]
@assem2002 the above error occurs because there is no function `f()` defined inside `prog.f90`. I think this might be the correct way to do what you wished to achieve.

> prog.f90
```fortran
program a
   implicit none
   integer :: c
   interface f1
      integer function f() result(d)
      end function
   end interface f1
   c = f()
   print *, c
end program a

function f() result(d)
   integer :: d
   d = 9
end function f
```

This gives the required output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
9
```

**Comment by kmr-srbh** [comment]
For loading the function from an external module, we can do

> func.f90
```fortran
module func
   implicit none
contains
   function f() result(d)
      integer :: d
      d = 9
   end function f
end module func
```

> prog.f90
```fortran
program a
   use func
   implicit none
   integer :: c
   c = f()
   print *, c
end program a
```

Which gives the output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
9
```

**Comment by assem2002** [comment]
Yeah you're right about your suggested code.but we should be able to call an external function that's defined in another file using `external` keyword.
gfortran compiles [these files ](https://github.com/lfortran/lfortran/issues/4008#issue-2299271520) normally with no issue.
We have to support such a thing because **lapack** uses this way to build its own library . (Note that lapack uses Fortran 77 style which doesn't support `module`)

**Comment by kmr-srbh** [comment]
@assem2002 could you please share the steps you followed to compile this using GFortran?

**Comment by assem2002** [comment]
@kmr-srbh 

```shell
assem@assem-PC:~/Desktop/fortran/test_05$ gfortran -c func.f90 
assem@assem-PC:~/Desktop/fortran/test_05$ gfortran -c prog.f90 
assem@assem-PC:~/Desktop/fortran/test_05$ gfortran -o mmm func.o prog.o 
assem@assem-PC:~/Desktop/fortran/test_05$ ./mmm 
           9

```

I think it just compiles `prog.f90` and the object file waits for the undefined variables to be found in linking phase. for sure it doesn't have the advantages that mod file offers so that is why LFortran requires `--implicit-interface` flag to be used if we call an external function in our code.

**Comment by kmr-srbh** [comment]
Looks like we are dealing with legacy code here.

**Comment by assem2002** [comment]
as @Pranavchiku mentioned it would compile normally with `--generate-object-code` flag.
`-c` flag in gfortran handles this issue with no problem. should we do the same in LFortran? If not just let's close this issue.

**Comment by Pranavchiku** [comment]
Here is how you should do it, I hope this now makes more sense. Let me know if you need any help,

```console
% rm -rf *.o
% lfortran a.f90 -c 
% lfortran b.f90 -c --implicit-interface
% lfortran a.o b.o
Undefined symbols for architecture arm64:
  "_f", referenced from:
      _main in b.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
The command 'clang -o a.out a.o b.o  -L"/Users/pranavchiku/repos/lfortran/src/bin/../runtime" -Wl,-rpath,"/Users/pranavchiku/repos/lfortran/src/bin/../runtime" -llfortran_runtime -lm' failed.
% rm -rf *.o
% lfortran a.f90 -c --generate-object-code
% lfortran b.f90 -c --implicit-interface  
% lfortran a.o b.o
9
```

**Comment by Pranavchiku** [comment]
We have `f` in `a` so we generate its object code i.e. `a.o`. Now for `b`, `f` is implicit and thus we enable `--implicit-interface`.
