### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#401]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/526

`gfortran` treats inputs as case insensitive; we should too.

Sample:
```fortran
program main
   integer, parameter :: R=10
   print*, r
end program
```
Fails for us, with `input:3:12 semantic error: Variable 'r' not declared` while `gfortran` has no complaints.

**Comment by HarshitaKalani** [comment]
This works fine with the latest main!

**Comment by certik** [comment]
Indeed, this works now.
