### ISSUE TITLE
Bug: Expressions in `DIMENSION` attribute of arrays inside a `SUBROUTINE` lead to an `ASR verify pass error`

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4013]
#### Minimum Reproducible Example (MRE)

> m.f90
```fortran
MODULE m
   IMPLICIT NONE
   INTEGER :: nx = 2
END MODULE m
```
> example.f90
```fortran
MODULE example
   USE m
   IMPLICIT NONE
CONTAINS
   SUBROUTINE sub (n)

      INTEGER, DIMENSION(nx-1) :: n
      
   END SUBROUTINE sub
END MODULE example

PROGRAM test
   use example
END PROGRAM test
```
#### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
 --> ./examples/example.f90:5:4 - 9:21
  |
5 |       SUBROUTINE sub (n)
  |       ^^^^^^^^^^^^^^^^^^...
...
  |
9 |       END SUBROUTINE sub
  | ...^^^^^^^^^^^^^^^^^^^^^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

The bug was caught when trying to compile file `expxs.f90` of the SNAP package.<br><br>

The subroutine `expxs_slgg ( scat, map, cs )` causes the above error due to the parameter `cs` which is declared as `REAL(r_knd), DIMENSION(cmom-1,nx), INTENT(OUT) :: cs`. On further analysis, we find that the expression `cmom-1` is the cause of the issue. Other similar expressions like `cmom+1`, `cmom * 2`, etc also lead to the above error. We can simplify the issue to the MRE provided above.

**Comment by assem2002** [comment]
Do you think it's due to the dimension-shape not being a constant at compile time?

**Comment by kmr-srbh** [comment]
> Do you think it's due to the dimension-shape not being a constant at compile time?

Thank you @assem2002 , I had missed the module part of the issue. I have updated the code. The previous code failed due to the reason you stated. :+1:

**Comment by kmr-srbh** [comment]
> It's still the same problem though. If you figure out any fix inform me, I will look up this issue too and I'll keep updated.

The code compiles and executes properly with GFortran. It compiles with LFortran when we replace `nx-1` with `nx`. Also, the issue does not occur outside of a subroutine. Could you please explain why you think this could be the reason?

**Comment by assem2002** [comment]
it got confusing when found out it works with `nx` but not with `nx - 1`. I'll dig into it and let you know.

**Comment by kmr-srbh** [comment]
> it got confusing when found out it works with `nx` but not with `nx - 1`. I'll dig into it and let you know.

Yes! The previous code I had provided was incorrect. The issue here has a module in the picture too. The above is the correct code.

**Comment by certik** [comment]
I think a variation of this bug was fixed by @Pranavchiku in https://github.com/lfortran/lfortran/pull/3962. Maybe the fix does not work if the module is compiled separately?

**Comment by kmr-srbh** [comment]
> I think a variation of this bug was fixed by @Pranavchiku in #3962. Maybe the fix does not work if the module is compiled separately?

I tried the MRE provided in #3962. From what I have observed, setting array dimension works with module variables, but not when we convert it to an expression. So, doing `real, dimension(nx), intent(in) :: cs` works, but `real, dimension(nx-1), intent(in) :: cs` fails.

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
 --> ./examples/example.f90:5:1 - 9:14
  |
5 |    subroutine a(cs)
  |    ^^^^^^^^^^^^^^^^...
...
  |
9 |    end subroutine
  | ...^^^^^^^^^^^^^^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

Given that we already have a fix for it's base case in #3962, I think this should be easy to fix. I am trying to fix this.

**Comment by kmr-srbh** [comment]
@certik got this. This is an issue with handling binary integer operations inside the dimension attribute. I am pushing a fix in a while.

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
integer binop
ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.
 --> ./examples/example.f90:5:1 - 9:14
  |
5 |    subroutine a(cs)
  |    ^^^^^^^^^^^^^^^^...
...
  |
9 |    end subroutine
  | ...^^^^^^^^^^^^^^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by Pranavchiku** [comment]
Yes, handling binary operation will do the job. Just transfer it to something like INTEGER, DIMENSION(get_nx()-1) :: n

**Comment by Pranavchiku** [comment]
An approach to fix this is to create a `BaseExprReplacer` with special handling for `Var_t`,`IntegerBinOp_t`, etc. Apply same logic on `visit_Var` and then we can expand it.

**Comment by kmr-srbh** [comment]
> An approach to fix this is to create a `BaseExprReplacer` that visits passed expression with special handling for `Var_t`,`IntegerBinOp_t`, etc. Apply same logic on `visit_Var` and then we can expand it.

Let me have a look into it! :+1:

**Comment by Pranavchiku** [comment]
> Let me have a look into it! 👍

i’ll ask you to get current PR to finish line.
