### ISSUE TITLE
Support compile time reduction of kind argument for intrinsic functions

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4058]
```fortran
program main
  print*, maskl(1, kind=kind(0.0d0))
end
```
```console
$ lfortran a.f90 
semantic error: `kind` argument of the `Maskl` function must be a scalar Integer constant
  --> a.f90:20:25
   |
20 |   print*, maskl(1, kind=kind(0.0d0))
   |                         ^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
$ gfortran a.f90 && ./a.out
 -9223372036854775808
```

**Comment by kmr-srbh** [comment]
This should be easy to fix. @HarshitaKalani are you working on this?

**Comment by HarshitaKalani** [comment]
If you wish to work on this, please go ahead @kmr-srbh

**Comment by HarshitaKalani** [comment]
@kmr-srbh lmk if you're working on this. I've a fix ready for this, I can push that if you haven't started this yet.
PS: one of my PRs need this.

**Comment by kmr-srbh** [comment]
> @kmr-srbh lmk if you're working on this. I've a fix ready for this, I can push that if you haven't started this yet. PS: one of my PRs need this.

@HarshitaKalani please go ahead and push the changes. I had tried the fix I had in mind, but it had not worked. I am excited to see how the changes look like. I think this will be a learning experience for me!
