### ISSUE TITLE
Fix: for array input in intrinsic elemental functions, return array output

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4059]
```fortran
program main
    real :: i(2) = [1.0, 2.0]
    print*, sum(sngl(i))
end
```
```console
$ lfortran b.f90
ASR verify pass error: Input to Sum intrinsic must always be an array
 --> b.f90:3:13
  |
3 |     print*, sum(sngl(i))
  |             ^^^^^^^^^^^^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
$ gfortran b.f90 && ./a.out
   3.00000000    
```

**Comment by HarshitaKalani** [comment]
I just checked that this works for `aint`.
```fortran
program main
    real :: i(2) = [1.0, 2.0]
    print*, sum(aint(i))
end
```

And realised that the reason is that the automatic python script does not handle arrays as return type. 
```py
"Sngl": [
        {
            "args": [("real",)],
            "return": "real32"
        }
    ],
```
```py
 "Aint": [
        {
            "args": [("real",)],
            "ret_type_arg_idx": 0,
            "kind_arg": True
        }
    ],
```
So when it is ret_type_arg_idx: 0 which means the return type would be same as the first arg which is array whereas in case we write return: real32, it makes the return_type as real instead of an array of type real.

**Comment by parth121101** [comment]
> I just checked that this works for `aint`.
> 
> ```fortran
> program main
>     real :: i(2) = [1.0, 2.0]
>     print*, sum(aint(i))
> end
> ```
> 
> And realised that the reason is that the automatic python script does not handle arrays as return type.
> 
> ```python
> "Sngl": [
>         {
>             "args": [("real",)],
>             "return": "real32"
>         }
>     ],
> ```
> 
> ```python
>  "Aint": [
>         {
>             "args": [("real",)],
>             "ret_type_arg_idx": 0,
>             "kind_arg": True
>         }
>     ],
> ```
> 
> So when it is ret_type_arg_idx: 0 which means the return type would be same as the first arg which is array whereas in case we write return: real32, it makes the return_type as real instead of an array of type real.

In this case do you think precision intrinsic would be able to handle arrays??
```
"Precision": [
        {
            "args": [("real",), ("complex",)],
            "return": "int32"
        }
    ],
```
