### ISSUE TITLE
Intrinsic `Kind` is a TypeInquiry function and not Elemental function

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4067]
```fortran
program main
    real :: i(2) = [1, 2]
    print*, kind(i)
end program 
```
```console
$ lfortran a.f90 
4 4 
$ gfortran a.f90 && ./a.out
           4
```

**Comment by Shaikh-Ubaid** [comment]
I am just curious. Why are we refactoring this into TypeInquiry and what benefit does it bring us?

**Comment by HarshitaKalani** [comment]
Yes. Also, in the above example, we can see that kind (when an elemental intrinsic) gives output for every element of the array which is not the expected behaviour. As an inquiry function, it gives the kind of array which is correct.
