### ISSUE TITLE
bug: arguments do not match for any generic procedure, `bcast`

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4149]
### Minimum Reproducible Example
```fortran
MODULE input_module

   INTERFACE bcast
      MODULE PROCEDURE bcast_i_1d
   END INTERFACE bcast

CONTAINS

   SUBROUTINE bcast_i_1d ( value, ilen )

      INTEGER, INTENT(IN) :: ilen

      INTEGER, DIMENSION(ilen), INTENT(IN) :: value

   END SUBROUTINE bcast_i_1d


   SUBROUTINE input_var_bcast

      INTEGER :: ilen

      INTEGER, DIMENSION(30) :: ipak

      CALL bcast ( ipak, ilen )

   END SUBROUTINE input_var_bcast

END MODULE input_module
```
### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ lfortran -c input.f90
semantic error: Arguments do not match for any generic procedure, bcast
  --> input.f90:24:7
   |
24 |      CALL bcast ( ipak, ilen)
   |      ^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by kmr-srbh** [comment]
This is a derivative of #4131. I am trying to fix this.

**Comment by kmr-srbh** [comment]
This is a derivative of #4131.

**Comment by kmr-srbh** [comment]
The cause of the issue is that inside subroutine `bcast_i_1d`, the dimension of parameter `value` is a variable `ilen`, but while calling it inside `input_var_bcast` the dimension of argument `ipak` is an integer 30. This comparison of types fails and leads to above error.

**Comment by kmr-srbh** [comment]
@certik In the above case, we have a comparison between a value of type `Integer_t` and `IntegerConstant_t`. Should we allow the expressions to be treated as equal in these type of comparisons? The result of `ASRUtils::check_equal_type(ASRUtils::expr_type(x), ASRUtils::expr_type(y))` is `true` for this. I see that GFortran also does not raise an error here.

**Comment by certik** [comment]
Here is a minimal example:
```fortran
module input_module

interface bcast
    module procedure bcast_i_1d
end interface

contains

    subroutine bcast_i_1d(n, A)
    integer, intent(in) :: n, A(n)
    end subroutine

    subroutine input_var_bcast()
    integer, dimension(5) :: A
    call bcast(5, A)
    end subroutine

end module input_module

program test
use input_module
call input_var_bcast()
end program
```

**Comment by kmr-srbh** [comment]
> We might have a bug inside check_equal_type that somehow these two expressions do not compare equal. 

Yes, we have a bug inside the `ASRUtils::expr_equal()` function. It is an incorrect type check logic. 

```c++
if (x->type != y->type) {
    return false;
}
```

The output of `ASRUtils::check_equal_type(ASRUtils::expr_type(x), ASRUtils::expr_type(y))` returns `true` for the above case and you are right about these being equal as the basis for the comparison here is their `kind`.

I found the issue in the way we were comparing the expressions later in the `ASR::expr_equal()` function. This is dependent on the incorrect logic we discussed above.

We compare the expressions using a `switch` statement. As the above check was incorrect, it had outright returned `false` for this comparison. After we fix it using the `ASRUtils::check_equal_type()` function, the below case fails. 

```c++
case ASR::exprType::IntegerConstant: {
    ASR::IntegerConstant_t* intconst_x = ASR::down_cast<ASR::IntegerConstant_t>(x);
    ASR::IntegerConstant_t* intconst_y = ASR::down_cast<ASR::IntegerConstant_t>(y);
    return intconst_x->m_n == intconst_y->m_n;
}
```

We use the value of `x->type` in the `switch` statement and are sure that `x` is an `IntegerConstant_t`, but we cannot say whether `y` is an `Integer_t` or `IntegerConstant_t`. The same is the case for real numbers.


I changed this to the following which works:
```c++
case ASR::exprType::IntegerConstant: {
   ASR::IntegerConstant_t* intconst_x = ASR::down_cast<ASR::IntegerConstant_t>(x);
   if (ASR::is_a<ASR::IntegerConstant_t>(*y)) {
       ASR::IntegerConstant_t* intconst_y = ASR::down_cast<ASR::IntegerConstant_t>(y);
       return intconst_x->m_n == intconst_y->m_n;
   } else {
       // if `y` is not `IntegerConstant_t`, it must be `Integer_t`
       return true;
   }
}
case ASR::exprType::RealConstant: {
   ASR::RealConstant_t* realconst_x = ASR::down_cast<ASR::RealConstant_t>(x);
   if (ASR::is_a<ASR::RealConstant_t>(*y)) {
       ASR::RealConstant_t* realconst_y = ASR::down_cast<ASR::RealConstant_t>(y);
       return realconst_x->m_r == realconst_y->m_r;
   } else {
       // if `y` is not `RealConstant_t`, it must be `Real_t`
       return true;
   }
}
```

**Comment by kmr-srbh** [comment]
With the above change in place, the above two examples compile successfully and no tests fail.

```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran -c ./examples/example.f90
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ 
```

**Comment by Pranavchiku** [comment]
This fails when it checks if `dimensions_equal`, and reason it fails is different kind of `30` and `ilen`. We need to bypass it and this should work.

**Comment by kmr-srbh** [comment]
> This fails when it checks if `dimensions_equal`, and reason it fails is different kind of `30` and `ilen`. We need to bypass it and this should work.

The issue is not with `kind` actually.
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
kind_a: 4
kind_b: 4
semantic error: Arguments do not match for any generic procedure, bcast
  --> ./examples/example.f90:24:7
   |
24 |       CALL bcast ( ipak, ilen )
   |       ^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

The flow of execution is:
`dimension_expr_equal`-->`expr_equal`-->`if (x->type != y->type)`-->`false`

Digging deeper into the result of `if (x->type != y->type)`, I recalled that `Integer_t` and `Real_t` are **_types_** whereas here the complete issue is related to the comparison of **_expressions_**.

Also, the logic for comparing dimensions needs to be improved as we check for compile-time values before we can know whether the expressions are equal.

Replacing `INTEGER, DIMENSION(ilen), INTENT(IN) :: value` with `INTEGER, DIMENSION([1, 2, 3, 4]), INTENT(IN) :: value` and `INTEGER, DIMENSION(30) :: ipak` with `INTEGER, DIMENSION("hello") :: ipak` compiles without any issues. 

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran -c ./examples/example.f90
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ 
```

The generated ASR for both arrays has the dimension:
```clojure
[((IntegerConstant 1 (Integer 4))
(IntegerConstant -1 (Integer 4)))]
```
It matches and the code compiles.


At the heart of the issue is the comparison of dimensions solely on the basis of their `exprType`, which does not happen in case the value is compile-time as the extracted values are compared for equality then.

I think the fix might be to compare the dimensions based on their `ttypeType`. This will hugely simplify the comparison as even for expressions like `Var_t` and `IntegerBinOp_t`, we will have a type.

Thoughts @certik @Pranavchiku?

**Comment by certik** [comment]
For now I would do the generic function resolution simply based on equal number of dimensions, and each dimension already has to be an integer, so you don't even have to check the type I think.

A step after that is to check if the integer expressions are compatible, for example if one is 5 and one is 8, maybe it's not compatible for the generic function resolution, however, we need to investigate this more. 

So for now I think we just check the array element type, and the number of dimensions. We don't check the dimensions. That should unblock us.

**Comment by kmr-srbh** [comment]
Another derivative of this issue. Found in file `output.f90`.

### MRE
```fortran
MODULE output_module
   IMPLICIT NONE

   INTEGER :: nx=4

   INTERFACE psend
      MODULE PROCEDURE psend_d_2d
   END INTERFACE psend

CONTAINS

   SUBROUTINE psend_d_2d ( d1, value )
      INTEGER, INTENT(IN) :: d1
      REAL, DIMENSION(d1), INTENT(IN) :: value
   END SUBROUTINE psend_d_2d


   SUBROUTINE output_send ( fprnt )
      REAL, DIMENSION(nx), INTENT(IN) :: fprnt
      CALL psend ( nx, fprnt )
   END SUBROUTINE output_send

END MODULE output_module
```
### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
dimension expressions not equal
x type: integer
y type: integer
semantic error: Arguments do not match for any generic procedure, psend
  --> ./examples/example.f90:20:7
   |
20 |       CALL psend ( nx, fprnt )
   |       ^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by Pranavchiku** [comment]
I think the code here will transformed to the following and thus it is derivative but not directly related to this PR.

```fortran
   SUBROUTINE output_send ( fprnt )
      REAL, DIMENSION(get_nx()), INTENT(IN) :: fprnt
      CALL psend ( nx, fprnt )
   END SUBROUTINE output_send
```

**Comment by kmr-srbh** [comment]
> I think the code here will transformed to the following and thus it is derivative but not directly related to this PR.

You are right. I will try to handle the base case for this issue. Let's see if that fixes this one also.

**Comment by assem2002** [comment]
Apparently, When we check for dimensions equality we use `dimension_expr_equal()` to check for the equality of values for both `dimension->m_length` `dimension->m_start` . that's good approach and the right one to follow. 
```Fortran
if (ASRUtils::extract_value(ASRUtils::expr_value(dim_a), dim_a_int) &&
        ASRUtils::extract_value(ASRUtils::expr_value(dim_b), dim_b_int)) {
        return dim_a_int == dim_b_int;
    }
```

The problem raises when we compare `variable` (_that's not a parameter - doesn't have constant value at compile time_) against any other type(_not variable - as `expr_equal()` would bypass that_) . 
The value returning from `expr_value()` for `variable` type would be `nullptr` and it get compared with the other argument which results in the error that we encounter here.

> Possible Solution
- As I noticed, GFortran follows the practice of accepting any array when it comes to the similar situation mentioned in this issue (where the dimension type is a variable - not known at compile time) even when using flag`-fcheck=bound`. Maybe we can follow the same practice.

- Maybe we can think of a way to test the size of arrays in the backend.

@certik @Pranavchiku : What approach should we take for now? If you have any thoughts on that, it'd be great help.

**Comment by certik** [comment]
We should follow the approach described here: https://github.com/lfortran/lfortran/issues/4149#issuecomment-2153083833.

**Comment by assem2002** [comment]
Okay that should be easy to do. I'll push a PR for it.
