### ISSUE TITLE
enh: implement subroutine `EXIT`

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4151]
```console
(base) saurabh-kumar@Awadh:~/Projects/Packages/SNAP/src$ lfortran -c utils.f90 --no-warnings --no-style-warnings



semantic error: Function 'exit' not found or not implemented yet (if it is intrinsic)
   --> utils.f90:237:5
    |
237 |     CALL EXIT ( 0 )
    |     ^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

Reference: https://gcc.gnu.org/onlinedocs/gcc-4.7.4/gfortran/EXIT.html

**Comment by gxyd** [comment]
Is this a duplicate of https://github.com/lfortran/lfortran/issues/3439 ?

**Comment by kmr-srbh** [comment]
Thanks a lot for this @gxyd! From the thread it turns out that this is a low priority issue. We can have #3429 for it. Closing this one.

**Comment by gxyd** [comment]
You tagged this issue as "SNAP", so if it's needed to compile "SNAP", I'm not if I would tag the other issue as "low-priority". Maybe we should re-consider?

**Comment by kmr-srbh** [comment]
According to Ondrej's comment https://github.com/lfortran/lfortran/issues/3439#issuecomment-1983691259 he plans to implement this along with other GFortran extensions. Also, this is used only 2 times in the whole SNAP code-base. I think we can defer this until beta.

**Comment by certik** [comment]
You can put "error stop" as a workaround in the code for now. If we implement `exit`, it needs to be behind a compiler flag, since it is an extension.
