### ISSUE TITLE
bug: remove symbol from old parent symbol table when imported from a new module

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4165]
### Minimum Reproducible Example

```fortran 
MODULE one
   IMPLICIT NONE
   INTEGER :: nx = 1
END MODULE one

MODULE two
   USE one, ONLY: nx
   IMPLICIT NONE
END MODULE two

PROGRAM test
   USE two
   USE one, ONLY: nx

   PRINT *, nx
END PROGRAM test
```
### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
semantic error: Variable already defined
  --> ./examples/example.f90:13:4
   |
13 |    USE one, ONLY: nx
   |    ^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

This bug was caught when trying to compile the file `snap_main.f90` of the SNAP package. In there, `utils_module` defined inside file `utils.f90` imports the symbol `iproc` from `plib_module`. Inside the file `snap_main.f90`, `utils_module` is imported completely. After a few lines, some selected symbols are imported from `plib_module` which includes `iproc`. This leads to the above error. Another instance of this error occurs in the same file when importing `swp_typ` from `control_module` fails because `utils_module` already imports it.

GFortran does not throw an error here. While it is not very clear from the output of `-fdump-tree-all` how it handles this case, but I am guessing it might be removing the old symbol from the parent symbol table and re-declaring it in the new one.

**Comment by certik** [comment]
Great catch. It needs to shadow the previous declaration --- so it needs to I think just replace the old symbol in the symbol table. Since `use` is done first, I think it can't be used by any statement/declaration, so it is safe to remove.
