### ISSUE TITLE
Call to EXIT not implemented

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#4181]
Compiling 'utils.f90' in the SNAP package raises this error.

```shell
semantic error: Function 'exit' not found or not implemented yet (if it is intrinsic)
   --> utils.f90:237:5
    |
237 |     CALL EXIT ( 0 )
    |     ^^^^^^^^^^^^^^^ 
```

I could just bypass it by using `error stop` as we discussed before.
If it's important to the beta version I think we should wrap `EXIT()` around `error stop` to handle this.
Notice : we don't encounter the call to `EXIT` that much in the package

**Comment by Pranavchiku** [comment]
Workaround is to use `error stop` instead.

**Comment by kmr-srbh** [comment]
We have an issue for this at #3439. `EXIT` is not part of the Fortran standard and is an extension of GFortran. I had opened an issue regarding this a few days ago too and it seems this is low priority until beta.

**Comment by assem2002** [comment]
I'll just close this issue with reference to https://github.com/lfortran/lfortran/issues/3439 .
Thank you all.
