### ISSUE TITLE
How to Extract Lexer Tokens and Parse Tree Using LFortran?

### ISSUE THREAD

**Issue by AkhilAkkapelli** [lfortran/lfortran#4182]
Can you please provide instructions or examples on how to extract lexer tokens and the parse tree from a Fortran source file using LFortran? Any guidance on the relevant commands would be appreciated.

**Comment by Pranavchiku** [comment]
You can use `--show-tokens` for extracting tokens and `--show-ast` for abstract syntax tree or say parse tree
