### ISSUE TITLE
bug: struct::m_derived_type cannot point outside of its symbol table

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#4192]
### Minimum Reproducible Example

```fortran
MODULE geom_module

   TYPE diag_type
      INTEGER :: len
   END TYPE diag_type

   TYPE(diag_type), DIMENSION(1) :: diag

END MODULE geom_module

PROGRAM test_program
    USE geom_module, ONLY: diag

   PRINT *, diag(1)

END PROGRAM test_program
```

### Output
```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran -c ./examples/example.f90
ASR verify pass error: ASR verify: The symbol table was not found in the scope of `symtab`.
 --> ./examples/example.f90:3:4 - 6:1
  |
3 |       TYPE diag_type
  |       ^^^^^^^^^^^^^^...
...
  |
6 |    
  | ...^ failed here

ASR verify pass error: Struct::m_derived_type 'diag_type' cannot point outside of its symbol table, owner: geom_module
 --> ./examples/example.f90:7:4
  |
7 |    TYPE(diag_type), DIMENSION(1) :: diag
  |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ failed here


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

This bug was caught when trying to compile file `mkba_sweep.f90` of the SNAP package.

**Comment by Pranavchiku** [comment]
When you `--dump-all-passes`, you'll find:

```console
(Print
                        [(ArrayItem
                            (Var 8 diag)
                            [(()
                            (IntegerConstant 1 (Integer 4))
                            ())]
                            (Struct
                                6 diag_type
                            )
                            ColMajor
                            ()
                        )]
                        ()
                        ()
                    )
```

Here type points to symtab 6, it should point to `8 diag_type`, I believe somewhere `symbol_get_past_external` is used  while fetching symbol type. One will have to look at `visit_FuncCallOrArray` and debug where `ArrayItem` is created.

```console
                            (Struct
                                6 diag_type
                            )
```

**Comment by certik** [comment]
We have to refactor StructType. It should contain a list of types of the members. And everything else is in the Struct symbol, in the symbol table.

**Comment by certik** [comment]
@tanay-man will port the StructType refactoring from LPython. After that we can tackle this issue.

**Comment by certik** [comment]
Here is the PR to update Struct: https://github.com/lfortran/lfortran/pull/4598

**Comment by certik** [comment]
Remember: if the full fix will take a lot of time, then let's find some quicker fix with the existing ASR, so that we can remove the workaround in SNAP to unblock us. After that we can work on the full fix.

**Comment by certik** [comment]
This test passes for me. Let's create a new MRE using the latest LFortran from SNAP that reproduces this bug: https://github.com/certik/SNAP/commit/d82b86772758258c7e783ef7402c0ef1240171d9.

**Comment by kmr-srbh** [comment]
The MRE above fails for me with the latest main on Linux.

**Comment by gxyd** [comment]
I get the same error on macOS as well, as is originally reported in the MRE of the issue.
