### ISSUE TITLE
Implement opaque pointers for LLVM 17

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4210]
The follwing PRs show how to do it:

* https://github.com/lfortran/lfortran/pull/4206
* https://github.com/lfortran/lfortran/pull/4209
* https://github.com/lfortran/lfortran/pull/4252

**Comment by gxyd** [comment]
I'll try looking into this issue, here's the link to the release notes from LLVM: https://releases.llvm.org/17.0.1/docs/ReleaseNotes.html#changes-to-the-llvm-ir talking about migration instructions.

**Comment by certik** [comment]
See also https://github.com/lfortran/lfortran/pull/4206, which implemented the foundation.

**Comment by certik** [comment]
I raised this to high priority, because the conda-forge osx-arm64 package upgraded to Clang 17 and does not seem to allow to install llvmdev=16. As a workaround I downgraded compilers there, but that will only work temporarily. Eventually things will break. We need to be able to use the default compilers and default LLVM version on all systems. I spent several hours today dealing with this issue at conda-forge, to figure out a workaround.

So it's time to get LLVM 17, then 18, and then 19 (to be released next moth) working. It's technical debt that will be costing us more and more time going forward, as well as our users who need newer LLVM support.

**Comment by junghans** [comment]
+1 as we need this for the Fedora packages as well.

**Comment by junghans** [comment]
From https://koji.fedoraproject.org/koji/taskinfo?taskID=122565175 building with llvm-17:
```
/3 Test #1: test_cwrapper ....................   Passed    0.00 sec
2/3 Test #3: test_lfortran ....................Subprocess aborted***Exception:   0.10 sec
[doctest] doctest version is "2.4.8"
[doctest] run with "--help" for options
{"type":"BinOp","op":"Mul","left":{"type":"Num","n":2},"right":{"type":"Name","id":"x"}}
{"type":"BinOp","op":"Mul","left":{"type":"Num","n":2},"right":{"type":"Name","id":"x"}}
{"type":"BinOp","op":"Mul","left":{"type":"Num","n":2},"right":{"type":"BinOp","op":"Pow","left":{"type":"Name","id":"x"},"right":{"type":"Name","id":"y"}}}
double free or corruption (out)
===============================================================================
/builddir/build/BUILD/lfortran-0.40.0-build/lfortran-0.40.0/src/lfortran/tests/test_llvm.cpp:23:
TEST CASE:  llvm 1
/builddir/build/BUILD/lfortran-0.40.0-build/lfortran-0.40.0/src/lfortran/tests/test_llvm.cpp:23: FATAL ERROR: test case CRASHED: SIGABRT - Abort (abnormal termination) signal
===============================================================================
[doctest] test cases: 16 | 15 passed | 1 failed | 78 skipped
[doctest] assertions: 52 | 52 passed | 0 failed |
[doctest] Status: FAILURE!
3/3 Test #2: test_stacktrace ..................   Passed    0.25 sec
```

**Comment by certik** [comment]
Yes, we can build with LLVM 17, but only run very few tests that we managed to port so far. We still have about 100 places in the LLVM backend that use typed pointers and we need to port them to use opaque pointers.

**Comment by Thirumalai-Shaktivel** [comment]
Currently, I'm working on a fix for allocatable.
I have started with:
```fortran
program main
  integer, allocatable :: x(:)
  allocate(x(1))
  deallocate(x)
end program
```

I will try to complete this by tomorrow.

**Comment by Thirumalai-Shaktivel** [comment]
To start, I would suggest to clone or create a new conda env with LLVM 17.
Clean build the lfortran project:
```console
$ git clean -dfx
$ ./build1.sh
$ cd integration_tests; ./run_tests.sh
```
Now, you can see the tests start failing. I took the print_arr_03.f90 test and reduced the code (by commenting out) to the simplest until I'm able to reproduce the same issue. So, I will try to handle all the issues related to allocatable.

Commenting out the tests related to allocatable, you will able to generate or see other tests failing. You can start from there.

Mostly, the issue seems to be related to GEP or Load.

**Comment by certik** [comment]
One idea I had was to create a dictionary of LLVM pointers and their types when we create them. Then when we "load" them, consult the dictionary and find the associated type, so that we can type it. If we can use the pointer to the LLVM IR pointer node and if it doesn't change, this might work! If so, that might quickly unblock us. We can then refactor this later to use the dictionary less and less.

**Comment by Thirumalai-Shaktivel** [comment]
I feel the same, we use GEP and Load APIs everywhere. And sometimes it hard to pass the Type of the Value.

**Comment by certik** [comment]
Yes. Ultimately we know the type in ASR, but the way the LLVM backend is structured sometimes we don't have this information because we have tons of utility functions that assumed LLVM would give us this information. In other words, we created "wrong abstractions", that we now need to redo.

**Comment by Thirumalai-Shaktivel** [comment]
Everything related to LLVM 17 seems to be fixed.

**Comment by certik** [comment]
Thank you @Thirumalai-Shaktivel, this was a huge help!

We just need to fix the interactive mode (ctest) and we can close this issue.

**Comment by certik** [comment]
So everything works at the CI now, I am going to close this issue now.

I am sure there will be bugs, so let's just open new issues for each bug that we find.

I made a new release: https://github.com/lfortran/lfortran/releases/tag/v0.41.0, so we'll check conda and other packaging.

@junghans you can try it in Fedora now, LLVM 10 - 19 should all work. If anything breaks, please report it.

**Comment by junghans** [comment]
I will test that soon!

**Comment by junghans** [comment]
LLVM-19 is still broken: [build.log.txt.zip](https://github.com/user-attachments/files/17396706/build.log.txt.zip)
(from https://koji.fedoraproject.org/koji/taskinfo?taskID=124888084)

**Comment by certik** [comment]
@junghans thanks for trying it! I reported the failure at https://github.com/lfortran/lfortran/issues/5072. It seems unrelated.
