### ISSUE TITLE
Duplicate functions in interface not raising error

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#4222]
related to https://github.com/lfortran/lfortran/issues/4007

```Fortran
MODULE input_module
    implicit none
    INTERFACE test_interface
       MODULE PROCEDURE test_01, test_01, test_01
    END INTERFACE test_interface
 CONTAINS
 
    SUBROUTINE test_01 (x)
        implicit none
        integer , intent(in):: x 
    END SUBROUTINE test_01

 END MODULE input_module

```
This should raise an error as there are 3 modules with the same name.
there's no harm in duplicating it, but it's not a good practice. 
If we raise an ambiguity error when issue https://github.com/lfortran/lfortran/issues/4007 is resolved, then this error should be a must.

**Comment by mohitdhingra22** [comment]
I have created a new test for the duplicate module procedure names and registered it in tests.toml. The PR is ready for review. Here is the link to the PR:[mohitdhingra22:fix_duplicate_procedures](url)

**Comment by NishantBansal2003** [comment]
I was using `std::set<ASR::symbol_t*> symbols_set;` (following this https://github.com/lfortran/lfortran/pull/4732#pullrequestreview-2275807890) to find unique symbols and throwing an error like this:

```cpp
throw SemanticError("Entity " + correct_pname + " is already present in the interface", x->base.loc);
```
However, the error message for the test appears as follows:

```vbnet
semantic error: Entity test_01 is already present in the interface
  --> duplicate.f90:8:5 - 12:26
   |
 8 |        SUBROUTINE test_01 (x)
   |        ^^^^^^^^^^^^^^^^^^^^^^...
...
   |
12 |        END SUBROUTINE test_01
   | ...^^^^^^^^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```
Is there a way I can get the error location to appear more like the following `gfortran` error format?

```vbnet
duplicate.f90:4:41:

    4 |        MODULE PROCEDURE test_01, test_01, test_01
      |                                         1
Error: Entity 'test_01' at (1) is already present in the interface
```
cc: @kmr-srbh

**Comment by assem2002** [comment]
@NishantBansal2003. I think you can push a PR, It'd be more convenient to see where you've made the changes in the codebase.

**Comment by NishantBansal2003** [comment]
Hey @assem2002, I was trying to push the changes, but after I added the modifications and attempted to run:

```bash
ctest
./run_tests.py -u
```
I encountered the following error:

```error
LCompilersException: Incompatible format: LFortran Modfile was generated using version '0.41.0-30-g74e7180b5', but the current LFortran version is '0.41.0-30-g74e7180b5-dirty'.
Command failed.
```
In this section:

```error
UPDATE TEST: string2.f90
+ lfortran -c tests/string1.f90
Internal Compiler Error: Unhandled exception
Traceback (most recent call last):
```
Could you please assist me with this issue?

**Comment by assem2002** [comment]
use `git clean -dfx` then build again. but make sure to stage your changes, if you have untracked files they we'll get removed after running `git clean -dfx`.
