### ISSUE TITLE
Stacktraces on Ubuntu take a long time

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4236]
For some reason, the stacktraces for exceptions / errors inside LFortran take a very long time to print in Ubuntu. This didn't used to be the case, but now it is. 

I suggest we move to use llvm based stacktraces on all platforms including linux, and remove the binutils dependency.

**Comment by assem2002** [comment]
I have Ubuntu. and yeah it takes so long, I though it was normal for stack trace unwinding.

**Comment by certik** [comment]
No, on macOS it is immediate. And in Ubuntu it used to be immediate.

**Comment by kmr-srbh** [comment]
Fixed in #4697.
