### ISSUE TITLE
support array initialisation example in openmp ASR pass

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#4247]
Towards #3777.

With #4246, we get #4031 working. Now we need to support it in ASR pass.

Example: https://github.com/lfortran/lfortran/issues/4031#issue-2303897390

**Comment by Pranavchiku** [comment]
I have design ready, I'll work on it tomorrow morning, this will have slightly more changes. I will work on this tomorrow morning ( IST ).

**Comment by Pranavchiku** [comment]
To handle arrays we need to changed variable declaration from `real, dimension(n) :: a` to `real(c_float), dimension(:), pointer :: a` whereas for scalar variables we just had to `real :: x` to `real(c_float) :: x` and both are equivalent in ASR so it was easy to handle.

Now let's take the following example:

```fortran
subroutine initialize_array(n, a)
use omp_lib
implicit none
integer, intent(in) :: n
real, dimension(n), intent(out) :: a

integer :: i

!$omp parallel shared(a) private(i, n)
!$omp do
do i = 1, n
  a(i) = 12.91
end do
!$omp end do
!$omp end parallel
end subroutine

program openmp
integer, parameter :: n = 1000000
real, dimension(n) :: a

print *, a(2)

call initialize_array(n, a)

print *, a(1), a(n)
end program
```

As we hit `DoConcurrentLoop`:
* change declaration of `a` to `real(c_float), dimension(:), intent(inout), pointer :: a` i.e. update symbol table
* Thereafter if it was not a pointer initially then we need to allocate it `allocate(a(data%n))`
* Then set it's pointer to `a` of `data` i.e. `data%a = c_loc(a)`
* Thereafter in `lcompilers_function` we need to `call c_f_pointer(tdata%a, a, [n])`, here we need to tell compiler what `n` is which needs to be passed from `initialise_array`
* Then we get back to `initialise_array` and after call to `GOMP_parallel`, if there are any usage of `a` then we need to update it because of change made in step 1, so basically we'll have a `ArrayVisitor` pass similar to `ReductionVariableVisitor` that will handle it.
* Real trick begins now, as we updated `a` which is a function argument, we need to track all function / subroutine calls to `initialise_array`, update `a` there and reuse `ArrayVisitor` to update any usage of `a`, not only that we may need to allocate `a` there if it was not pointer initially. 
* There can be cases where `f1` -> `f2` -> `f3` -> `f4` ->`f-openmp-pragma` we have a chain of functions and `a` is passed from `f1` all the way to `f-openmp-pragma`, then we need to update all these functions accordingly.
* To do this we'll have a separate pass which will be `BaseWalkVisitor`, with special handling for `Program`, and `Function`. We'll iterate over body and see if there are any function calls to target (`f-openmp-pragma `) function, if any we need to update `a`, allocate if necessary and then call `ArrayVisitor` on each statement.
* If `a` is argument in this function, then we recursively do same job for `f4` all the way to `f1`.
* If everything works fine, we are done!

**Comment by Pranavchiku** [comment]
I have made progress and last 4 steps are remaining.

**Comment by Pranavchiku** [comment]
It is tricky, I am trying to figure it out.

**Comment by certik** [comment]
I would do the following:
```fortran
subroutine initialize_array(n, a)
use omp_lib
implicit none
integer, intent(in) :: n
real, dimension(n), intent(out) :: a

integer :: i

!$omp parallel shared(a) private(i, n)
!$omp do
do i = 1, n
  a(i) = 12.91
end do
!$omp end do
!$omp end parallel
end subroutine

program openmp
integer, parameter :: n = 1000000
real, dimension(n) :: a

print *, a(2)

call initialize_array(n, a)

print *, a(1), a(n)
end program
```
Gets transformed into:
```fortran
subroutine initialize_array_kernel_1(n, a) bind(c)
integer(c_int), intent(in) :: n
real(c_double), intent(out) :: a(n)
integer :: i
!$omp parallel shared(a) private(i, n)
!$omp do
do i = 1, n
  a(i) = 12.91
end do
!$omp end do
!$omp end parallel
end subroutine

subroutine initialize_array(n, a)
use omp_lib
implicit none
integer, intent(in) :: n
real, dimension(n), intent(out) :: a
integer :: i
call initialize_array_kernel_1(n, a)
end subroutine

program openmp
integer, parameter :: n = 1000000
real, dimension(n) :: a

print *, a(2)

call initialize_array(n, a)

print *, a(1), a(n)
end program
```
Now the function `initialize_array_kernel_1` is `bind(c)` and we might end up implementing it completely separately, for example via our future ASR->MLIR backend, that offloads it to a GPU.

For the canonical OpenMP implementation via LLVM and your pass, I would then transform the kernel `initialize_array_kernel_1`. All we need to figure out are the proper types of all entities. For arrays, I would use `real(c_double), intent(out) :: a(n)`. At the C (or LLVM) side, this is just a pointer to an array data.

As a first step, why don't you post here the full Fortran program, that works for arrays. Let's test it, get it merged. Only then let's worry about the ASR->ASR pass.

**Comment by Pranavchiku** [comment]
We have it, I'll open PR soon.
