### ISSUE TITLE
openmp1 test fails on intel mac

### ISSUE THREAD

**Issue by KGB99** [lfortran/lfortran#4288]
After building LFortran with Git all tests except for the openmp1 test fail on my intel mac. The steps I did for building are the following:
```
git clean -dfx
git pull origin main
./build0.sh
./build1.sh
./run_tests.py
```

After running the following to update the tests:
```
rm -rf ./tests/reference/*
./run_tests.py -u
```
The following changes occur in the repo:
- `tests/reference/run_dbg-runtime_stacktrace_01-dcc746e.json` contents are:
```
{
    "basename": "run_dbg-runtime_stacktrace_01-dcc746e",
    "cmd": "lfortran {infile} -g --debug-with-line-column --no-color",
    "infile": "tests/errors/runtime_stacktrace_01.f90",
    "infile_hash": "3e65758e10744eea8d101be6437af3724c0ec32c832e29da968fc22d",
    "outfile": null,
    "outfile_hash": null,
    "stdout": "run_dbg-runtime_stacktrace_01-dcc746e.stdout",
    "stdout_hash": "3bb54d94e2d111c5ecb9eb370562d40ff2806b07b914f3f3fa45f3ce",
    "stderr": null,
    "stderr_hash": null,
    "returncode": 6
}
```
- `tests/reference/run_dbg-runtime_stacktrace_01-dcc746e.stdout` contents are:
```
The stack address was not found in any shared library or the main program, the stack is probably corrupted.
Aborting...
```

**Comment by certik** [comment]
Is this an openmp1 test? The failure is coming from the `stacktrace_01` test, which, as we discussed at https://github.com/lfortran/lfortran/pull/4276#issuecomment-2173780563, we need to fix for Intel Mac, of it does not work.

**Comment by KGB99** [comment]
Yes exactly, sorry i had understood that you wanted me to open an issue for it. Did I understand wrong?

**Comment by certik** [comment]
You mentioned here: https://github.com/lfortran/lfortran/pull/4276#issuecomment-2174210742, that an openmp test in integration_tests is failing for you. So I asked if you could please report it, as that we definitely need to fix.

All integration_tests must fully run on all platforms.
