### ISSUE TITLE
Throw error when `dim` is provided non integer value in `sum` intrinsic

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4305]
```fortran
program main
	print *, sum([1, 2, 3], dim = 1.1)
end program
```
```console
$ gfortran a.f90 && ./a.out
a.f90:2:31:

    2 |         print *, sum([1, 2, 3], dim = 1.1)
      |                                      1
Error: ‘dim’ argument of ‘sum’ intrinsic at (1) must be INTEGER
$ lfortran a.f90
6
```

**Comment by karanziie1990** [comment]
Hi @HarshitaKalani,

I am interested in solving this issue but am finding it difficult to know where to start. Could you please provide some guidance? I have already set up the project locally on my Windows laptop using WSL.

**Comment by HarshitaKalani** [comment]
Hi @karanziie1990 ,
Thanks for your interest.
You may look into the intrinsic_array_function_registry.h file, you'll find sum intrinsic implemented. Just explore the right place to give the error. Feel free to open a PR with some changes and we can discuss more there.

**Comment by karanziie1990** [comment]
Thank you @HarshitaKalani for your quick response and guidance.

I'll look into the `intrinsic_array_function_registry.h`  file and update you soon.

**Comment by karanziie1990** [comment]
I have a question regarding the workflow. Whenever I make some small code changes to the `intrinsic_array_function_registry.h `file, I have to run the command
> `make -j8`

 to see it's effects on the end LFortran code(.f90 files). Is it necessary to build the entire project every time I make a small change, or am I possibly doing something wrong?
