### ISSUE TITLE
Add Wasm backend

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#441]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/583

The Wasm backend can just use LLVM which I think can emit Wasm. The pure Fortran part of the runtime library should translate. The C part of the runtime library might translate with Clang, we need to investigate.

We need to add the proper option to enable Wasm into the main `lfortran` driver, and make sure everything works. Add a demo for something simple.

I have asked about some of these details here: https://github.com/pyodide/pyodide/issues/549#issuecomment-926915889

**Comment by Shaikh-Ubaid** [comment]
Currently, in `lfortran`, we have a `wasm` which (hopefully) emits `wasm` and `wat`. 

>Add a demo for something simple.

We also have a demo at https://dev.lfortran.org/

---

With the current `wasm` backend there are few simple things noted at https://github.com/lfortran/lfortran/issues/597 as future prospects.

**Comment by Shaikh-Ubaid** [comment]
Please, could someone possibly share if this issue is safe to close?

**Comment by certik** [comment]
We can close it I think.
