### ISSUE TITLE
bug : Getter functions doesn't get imported from mod files

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#4435]
related to #4371 
**MRE**
```fortran 
module c
    integer ::j=20
end module c

module a
    use c
    contains
    subroutine fdf()
        integer :: o(j,2)
        print *,j
        print *, size(o)
    end subroutine
end module a

program g1
    use a
    call fdf()
end program g1

```
This code compiles normally with no errors.
The error occurs when we move `program g1` into another file, the getter function `_lcompilers_get_ j` doesn't get imported into the ASR.

**Comment by Pranavchiku** [comment]
I see, this one is tricky to create. Thanks @assem2002 !

**Comment by assem2002** [comment]
I'm trying to figure out a fix for this, but apparently we don't serialize standalone functions and subroutines. so the solution I'm handling now is wrapping a module around `getter_functions` so we can serialize the `getter_function`.

**Does that seem a good approach ?** notice that we would be creating .mod files for each getter function we build.
