### ISSUE TITLE
Improve an error message for an array expression with derived types

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4437]
From "Two or more part references with non-zero rank must not be specified" to "Only one array can be used in an expression with derived types" or something like that.

https://github.com/lfortran/lfortran/pull/4423#discussion_r1663030187

**Comment by NishantBansal2003** [comment]
It looks like this issue has been fixed and can be closed.

**Comment by certik** [comment]
Which PR fixed it?

**Comment by NishantBansal2003** [comment]
https://github.com/lfortran/lfortran/pull/4912

**Comment by certik** [comment]
Awesome, thanks!
