### ISSUE TITLE
Equivalence error when arguments are array elements

### ISSUE THREAD

**Issue by KGB99** [lfortran/lfortran#4442]
I have the following MRE:
```
      PROGRAM ERROR

      REAL               CI( 2, 2 ), CIV( 4 ), CR( 2, 2 ), CRV( 4 )

      EQUIVALENCE        ( CI( 1, 1 ), CIV( 1 ) ),
     $                   ( CR( 1, 1 ), CRV( 1 ) )


      END
```
which throws an error when compiling with LFortran but compiles with gfortran. The failing step is from AST to ASR.
Equivalence is implemented so the following code for example does work:
```
      PROGRAM ERROR2

      REAL               A, B, C, D

      EQUIVALENCE        ( A, B ), ( C, D )

      END
```

EDIT:
The `--fixed-form` flag must be used to get the appropriate error.

**Comment by KGB99** [comment]
This is discussed in #2523

**Comment by KGB99** [comment]
I think this error arises in the tokenizer. The syntax of using a `,` followed by a `$` for equivalence is accepted in gfortran but not implemented for lfortran. I will start an attempt at fixing this.

**Comment by KGB99** [comment]
From what I understand typing:
```
      EQUIVALENCE        ( CI( 1, 1 ), CIV( 1 ) ),
     $                   ( CR( 1, 1 ), CRV( 1 ) )
```
is semantically the same as 
```
      EQUIVALENCE        ( CI( 1, 1 ), CIV( 1 ) )
      EQUIVALENCE        ( CR( 1, 1 ), CRV( 1 ) )
```
and when looking at the Tokens and AST:
```
(KEYWORD "equivalence")
(TOKEN "(")
(TOKEN "identifier" ci)
(TOKEN "(")
(TOKEN "integer" 1)
(TOKEN ",")
(TOKEN "integer" 1)
(TOKEN ")")
(TOKEN ",")
(TOKEN "identifier" civ)
(TOKEN "(")
(TOKEN "integer" 1)
(TOKEN ")")
(TOKEN ")")
(TOKEN ",")
(TOKEN "(")
(TOKEN "identifier" cr)
(TOKEN "(")
(TOKEN "integer" 1)
(TOKEN ",")
(TOKEN "integer" 1)
(TOKEN ")")
(TOKEN ",")
(TOKEN "identifier" crv)
(TOKEN "(")
(TOKEN "integer" 1)
(TOKEN ")")
(TOKEN ")")
(NEWLINE)
```
```
[(AttrEquivalence
                [([(FuncCallOrArray
                    ci
                    []
                    [(()
                    1
                    ()
                    0)
                    (()
                    1
                    ()
                    0)]
                    []
                    []
                    []
                )
                (FuncCallOrArray
                    civ
                    []
                    [(()
                    1
                    ()
                    0)]
                    []
                    []
                    []
                )])
                ([(FuncCallOrArray
                    cr
                    []
                    [(()
                    1
                    ()
                    0)
                    (()
                    1
                    ()
                    0)]
                    []
                    []
                    []
                )
                (FuncCallOrArray
                    crv
                    []
                    [(()
                    1
                    ()
                    0)]
                    []
                    []
                    []
                )])]
            )]
```
We see that this is not reflected. Therefore I think it would make sense to transform the code to replace the `,` with another `equivalence` in either the tokenization or ast phase. What do you think? @certik

**Comment by certik** [comment]
Here is the definition of `AttrEquivalence`:
```
    | AttrEquivalence(equi* args)
...
equi = (expr* set_list)
```
So it accepts a list of pairs (I don't know if it is allowed to have more than a pair, such as a triple, but it seems that's not being used in lapack). Above the first pair in AST is `(ci, civ)` and the second pair is `(cr, crv)`. So this seems correct to me? It is representing it as `AttrEquivalence([(ci,civ), (cr,crv)])`.

You are right that one could also put two equivalence statements separately, as:
```
AttrEquivalence([(ci,civ)])
AttrEquivalence([(cr,crv)])
```
But that's the same issue as `integer :: a, b` vs:
```
integer :: a
integer :: b
```
And we allow both and represent both in AST and in AST->ASR we loop over all declarations (`a`, `b`) in the same statement. In the same way we would loop over all pairs in a single equivalence statement.
