### ISSUE TITLE
shape not implemented

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#446]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/589

It appears that the shape intrinsic is not implemented, since `lfortran shape3.f90` for
```
program main
integer :: vec(2)
print*,shape(vec)
end program main
```
gives
```
input:3:8 semantic error: Function or array 'shape' not declared
print*,shape(vec)
```

**Comment by HarshitaKalani** [comment]
Shape is implemented in the latest main. This issue can be closed.

**Comment by certik** [comment]
Indeed, the example now works:
```
$ lfortran a.f90 
2 
```
