### ISSUE TITLE
subroutine array argument size mismatch

### ISSUE THREAD

**Issue by KGB99** [lfortran/lfortran#4488]
I have the following MRE made up of two files derived from LAPACK's `src/sgees.f` and `src/shseqr.f`:
- err.f
```
      PROGRAM SGEES

      REAL               WORK( 4 )

      INTEGER            IWRK

      EXTERNAL           SHSEQR

      CALL SHSEQR( WORK )

      CALL SHSEQR( WORK( IWRK ) )

      RETURN

      END
```
- err2.f
```
      SUBROUTINE SHSEQR ( WORK )

      REAL WORK( * )
      
      PRINT *, "X"

      RETURN 
      END
```
gfortran prints out:
```
X
X
```
Whereas Lfortran returns a type mismatch error for the subroutine call during the code generation phase.

(Honestly, I don't understand the semantics of passing a scalar argument to a subroutine expecting an array, but this is how it is done in the code.)

**Comment by Pranavchiku** [comment]
You must use `--legacy-array-sections` compiler flag, it allows you to pass

```
      CALL SHSEQR( WORK )

      CALL SHSEQR( WORK( IWRK ) )
```

as

```
      CALL SHSEQR( WORK )

      CALL SHSEQR( WORK( IWRK: ) )
```

```console
% lfortran b.f90 --generate-object-code -c
% lfortran a.f90 --implicit-interface --generate-object-code -c --legacy-array-sections
% lfortran a.o b.o 
X
X
```
