### ISSUE TITLE
do-loop inside a do-while loop

### ISSUE THREAD

**Issue by KGB99** [lfortran/lfortran#4489]
The command to reproduce error is `lfortran --fixed-form err.f` where err.f is the program containing the following MRE derived from LAPACK's `src/sbbcsd.f`:
```
      PROGRAM SBBCSD
      INTEGER I, IMIN, IMAX

      IMIN = 0
      IMAX = 2

      DO WHILE( IMAX .GT. 1 )
         DO I = IMIN, IMAX - 1
            PRINT *, IMAX
            IMAX = IMAX - 1
         END DO
      END DO
      RETURN

      END
```
Gfortran prints out a countdown from IMAX to 1. 
LFortran returns the following error when converting from the tokens to the AST:
```
syntax error: Token ',' is unexpected here
 --> err.f:8:21
  |
8 |          DO I = IMIN, IMAX - 1
  |                     ^ 
```

When the do while loop is removed LFortran is able to compile the program.

**Comment by gxyd** [comment]
Are all of LAPACK's files parsed via a fixed form parser? Is that the default setting?

**Comment by KGB99** [comment]
There is both `.f` and `.f90` files in the [LAPACK repo](https://github.com/Reference-LAPACK/lapack/tree/master). I use the cmake command from #1232 which uses `--fixed-form-infer`, so both the fixed form parser as well as the regular parser are used, but a majority of the files are in fixed form.

**Comment by gxyd** [comment]
Understood, thanks for pointing me to that issue as well.

**Comment by KGB99** [comment]
Sorry i notice now that I omitted that the `--fixed-form` flag is needed to reproduce the error, i added that now.

**Comment by KGB99** [comment]
If #4516 gets merged then the program compiles, however the result is still wrong.
Gfortran prints:
```
2
1
```
Whereas Lfortran prints:
```
2
```

**Comment by KGB99** [comment]
#4516 fixes the current error, however afterwards Lfortran prints `2` instead of
```
2
1
```
like gfortran

**Comment by KGB99** [comment]
im closing this issue to open a new one for the incorrect result.
