### ISSUE TITLE
Nested if-do-do causes compilation to hang

### ISSUE THREAD

**Issue by KGB99** [lfortran/lfortran#4493]
I have the following MRE derived from LAPACK's `src/sgebal.f`. The command to reproduce the error is `lfortran --fixed-form err.f` where err.f is the file containing the following code:
```
      PROGRAM SGEBAL

      LOGICAL            X
      INTEGER            I
      
      X = .TRUE.
      IF( .TRUE. ) THEN
         DO WHILE( X )
            DO I = 1, 1, -1
                  PRINT *, "X"
            END DO
            X = .FALSE.
         END DO
      END IF

      RETURN

      END
```
When compiling without the `--fixed-form` flag the program compiles correctly and outputs `X`, the same as gfortran. However, when compiling with the fixed form flag LFortran is unable to parse the file, therefore I assume it is a bug in the fixed-form-parser.

**Comment by gxyd** [comment]
Can I maybe try to fix this issue?

**Comment by KGB99** [comment]
Yes, go for it:)

**Comment by KGB99** [comment]
closing as this has been solved meanwhile.
