### ISSUE TITLE
Bug : getter functions do hard code assignment

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#4498]
**MRE**

```Fortran
module A
    IMPLICIT NONE
    integer :: i = 4
    integer :: arr_mod(4,4)
    contains
    subroutine sub (arr)
        integer , INTENT(OUT):: arr(4,i)
        print *,size(arr)            ! This prints 16 while it should print 20000
    end subroutine sub
end module A


program mainnn
    use A
    i = 5000
    call sub(arr_mod)
end program
```

The getter function gets created with the variable hard coded to the initial value at compile time, then if the value gets changed in the compile time the function becomes usless.
normally getter function works normally when it tries to get an external variable, but when it tries to access a variable that's isn't an external one the described issue occurs.

**Comment by assem2002** [comment]
I think it could be handled easily with two approaches :
- make sure we wrap the variable in an `ExternalSymbol` node (if it's not already wrapped).
- Avoid using `lcompilers_getter_ ...()` in such case _(accessing variable that's already in your module)_ .

I think the second approach with this case won't result in `ASR verify pass error: ASR::ttype_t in ASR::FunctionType cannot be tied to a scope.` error, right ?

**Comment by kmr-srbh** [comment]
I think this is the same as #4125.

**Comment by kmr-srbh** [comment]
#4130 is the related PR.

**Comment by assem2002** [comment]
Yeah that's exactly the issue in https://github.com/lfortran/lfortran/issues/4125.
I'm working on a fix now. we should've fixed that earlier, I've been debugging the package from array to another and eventually this bug was the reason. I think we shouldn't proceed with such a bug as it hurts so many computations in the package so debugging now would be waste of time.
