### ISSUE TITLE
implied do loops cause in segementation fault with `format`

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#4507]
MRE
```Fortran
program A
    integer ::i
    10 FORMAT (5A,I100)
    write (*,10) ('*',i=1,5), 12345678
end program A
```

It specifically happens when using format character `I` after an implied do loop (As I've tested it so far).

**Comment by kmr-srbh** [comment]
It seems we have a bunch of things to handle with `StringFormat` and implied do loops. If there is a workaround let's use it for now, else we will have to fix it.

**Comment by assem2002** [comment]
Yeah you're right. It also has a workaround so we can leave it for now.

**Comment by kmr-srbh** [comment]
Here is a workaround:

```fortran
program A
    integer :: i
    character(1), dimension(5) :: arr
    arr = (/ ('*',i=1,5) /)
    10 FORMAT (5A,I100)
    write (*,10) arr, 12345678
end program A
```
