### ISSUE TITLE
Array constructor such as [4,9] not implemented

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#460]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/604

`(base) /mnt/c/fortran/test$ cat constarr.f90`
```
program main
print*,[4,9]
end program main
```
`(base) /mnt/c/fortran/test$ lfortran constarr.f90`
```
Traceback (most recent call last):
LFortranException: visit_ConstantArray() not implemented
```

**Comment by Beliavsky** [comment]
At https://dev.lfortran.org/ the program above now gives output of

`208`

It is better to a get compiler message that a feature is not implemented than to compile a code and give wrong results.

**Comment by certik** [comment]
And locally it gives some kind of a random number:
```
$ lfortran a.f90
1829222120
```
We need to investigate what is going on.

I agree it's always better to give an error message than a wrong result.
