### ISSUE TITLE
Reading into an allocatable array sometimes fail

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#4617]
See https://github.com/lfortran/lfortran/pull/4615#issuecomment-2276108195.

This bug happens when we execute the file by hand, but not when run via ctest, due to another bug: https://github.com/lfortran/lfortran/issues/4616.

**Comment by certik** [comment]
We need to pass in correct length of how much data to read. It's broken for allocatable arrays, so we just need to fix it.

**Comment by assem2002** [comment]
I think it's not quite related to allocatable arrays, It's somthing related to how we do the `close` statement.
Notice this exact test `file_09.f90` :
```fortranprogram file_09
    implicit none

    integer :: u = 11, i, j,m=12
    character :: arr(2, 2)
    character, allocatable :: alloc_arr(:, :)

    open(u, file="file_01_data.txt", form="unformatted", access="stream", status="old")
    read(u) arr
    ! close(u)

    if (arr(1, 1) /= '1' .or. arr(1, 2) /= '1') error stop
    print *, arr

    open(u, file="file_01_data.txt", form="unformatted", access="stream", status="old")
    allocate(alloc_arr(2, 2))
    read(u) alloc_arr
    close(u)

    if (alloc_arr(2, 1) /= '0' .or. alloc_arr(2, 2) /= '3') error stop
    print *, alloc_arr
end program file_09
```

I just used commented out the `close()` statement and used another unit number `m` and it reads normally.

**Comment by kmr-srbh** [comment]
I had tested it this way. If we comment out `read(u) arr` and leave `close (u)` uncommented, it still works correctly. In fact, if we comment out both the `read` and close` statements, it still works. I think the issue requires both these reads and is something related to memory maybe.
