### ISSUE TITLE
intrinsic sign not implemented

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#462]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/606

`$ cat lfbug_sign.f90`
```
program main
print*,sign(1.0,-2.0)
end program main
```
`(base) /mnt/c/fortran/2015$ lfortran lfbug_sign.f90`
```
semantic error: Function 'sign' not found or not implemented yet (if it is intrinsic)
 --> lfbug_sign.f90:2:8
  |
2 | print*,sign(1.0,-2.0)
  |        ^^^^^^^^^^^^^^ 
```
`(base) /mnt/c/fortran/2015$ gfortran lfbug_sign.f90 && ./a.out`
`  -1.00000000  `

**Comment by HarshitaKalani** [comment]
This can be closed as intrinsic sign is now implemented.
```console
$ gfortran a.f90 && ./a.out
  -1.00000000    
$ lfortran a.f90
-1.00000000e+00
```
