### ISSUE TITLE
digits(n) fails if integer n is of kind 1 or 2

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#4622]
This program shows that ```digits(n)``` fails with lfortran if ```n``` is an integer of kind ```int8```. Judicious commenting out will show that it also fails for kind ```int16``` but it runs correctly with ```int32``` and ```int64```. The program:
```
program ndigits
  use iso_fortran_env, only: int8,int16,int32,int64 
  implicit none
  integer:: n
  print *,digits(1_int8 )
  print *,digits(1_int16)
  print *,digits(1_int32)
  print *,digits(1_int64)
end program ndigits
```
Output from gfortran:
```
           7
          15
          31
          63
```
Output from lfortran:
```
semantic error: Kind 1 not supported for type Integer
 --> ndigits.f90:5:11
  |
5 |   print *,digits(1_int8 )
  |           ^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by kmr-srbh** [comment]
Thanks for this! Yes, it seems we currently support only kind 4 and 8 for integers.

https://github.com/lfortran/lfortran/blob/93ae4ec6709427aec5dbbd16ca1be7eb4206d7dc/src/libasr/pass/intrinsic_functions.h#L4326-L4350

**Comment by HarshitaKalani** [comment]
I think we do support kind = 1 and 2 but it is not handled while implementing digits. I'll just fix that up.
