### ISSUE TITLE
achar not implemented

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#466]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/610

The achar box in the [roadmap](https://gitlab.com/lfortran/lfortran/-/issues/272) is filled in, implying that it is implemented, but it appears not to be.

`(base) /mnt/c/fortran/2015/lfortran$ cat achar.f90`
```
program main
print*,achar(10)
end program main
```
`(base) /mnt/c/fortran/2015/lfortran$ lfortran achar.f90`
```
semantic error: Function 'achar' not found or not implemented yet (if it is intrinsic)
 --> achar.f90:2:8
  |
2 | print*,achar(10)
  |        ^^^^^^^^^ 
```

**Comment by HarshitaKalani** [comment]
For the above example, it is:
```console
$ gfortran a.f90 && ./a.out
 

$ lfortran a.f90


$
```

And, 

```fortran
program test_achar
   character c
   c = achar(32)
   print*, c
 end program test_achar
```
```console
$ gfortran a.f90 && ./a.out
  
$ lfortran a.f90
 
$ 
```
