### ISSUE TITLE
count not implemented

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#467]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/611

I don't see `count` listed in the Fortran Features roadmap. It is not implemented.

`(base) /mnt/c/fortran/2015/lfortran$ cat count.f90`

```
program main
print*,count([.false.,.true.,.false.])
end program main
```
`(base) /mnt/c/fortran/2015/lfortran$ lfortran count.f90`
```
semantic error: Function 'count' not found or not implemented yet (if it is intrinsic)
 --> count.f90:2:8
  |
2 | print*,count([.false.,.true.,.false.])
  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 
```

**Comment by HarshitaKalani** [comment]
```console
$ lfortran a.f90
1
$ gfortran a.f90 && ./a.out
           1
```
Closing as count is implemented in the latest main.
