### ISSUE TITLE
`gfortran` treats the next logical arg as `mask` instead of `dim`

### ISSUE THREAD

**Issue by HarshitaKalani** [lfortran/lfortran#4679]
RESULT = FINDLOC(ARRAY, VALUE, DIM [, MASK] [,KIND] [,BACK])

```fortran
program main
    logical :: x(3) = [.true., .false., .true.], y = .true., back = .true.
    print *, findloc(x, y, back)
end program
```
```console
$ gfortran a.f90 && ./a.out
           1
$ lfortran a.f90
semantic error: `dim` should be a scalar integer type
 --> a.f90:3:14
  |
3 |     print *, findloc(x, y, back)
  |              ^^^^^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by kargl** [comment]
It seems that you're not looking at F2023 or F2018 documentation.  gfortran's behavior is correct.  See F2023.

16.9.88 FINDLOC (ARRAY, VALUE, DIM [, MASK, KIND, BACK]) or
              FINDLOC (ARRAY, VALUE [, MASK, KIND, BACK])

**Comment by certik** [comment]
I am guessing the logic is that if the 3rd argument is logical, it's a mask and the `FINDLOC (ARRAY, VALUE [, MASK, KIND, BACK])` overload applies, if it is an integer, it's a dim and the first `FINDLOC (ARRAY, VALUE, DIM [, MASK, KIND, BACK])` overload applies.

**Comment by HarshitaKalani** [comment]
>gfortran's behavior is correct.

With the subject, I didn't mean gfortran's behavior is wrong. The purpose rather was to follow that :)
