### ISSUE TITLE
I format should not allow a character variable

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#4704]
The Fortran 2023 standard 13.7.2.2 paragraph 1 requires that I format be used only if the effective item is of integer, enum or enumeration type.  Lfortran 0.40.0 compiled and ran this program with an effective item of character type.
```
program badint
  print "(I0)",'int?'
end program badint
```
Lfortran 0.40.0 output:
```
103715652427789
```
Every other compiler I tried gave a compile-time error.

**Comment by kmr-srbh** [comment]
@assem2002

**Comment by assem2002** [comment]
Yeah We have the backend ready for tackling such errors in the runtime, for now it either segfaults or print some random data. I think if you run the same MRE multiple it would segfault.

**Comment by harperjf** [comment]
Glad it didn't segfault. When that happens with other programs at run time how do I discover which Fortran statement caused it? But my badint.f90 program just printed a different large integer each time I ran it with lfortran.

**Comment by assem2002** [comment]
It's undefined behaviour, but for this case it works with random numbers id you fliped the situation, this should segfault at some point
```
program badint
  print "(A)",1111
end program badint
```
I'll try to implement the format checker, it should be easy to do.
