### ISSUE TITLE
`min` and `max` intrinsics are not properly elemental

### ISSUE THREAD

**Issue by milancurcic** [lfortran/lfortran#4745]
```fortran
! max.f90
real :: x(2)
x = [1.2, 2.3]
print *, max(0., x) ! doesn't work
!print *, max([0., 1.], x) ! works
end
```

```
$ lfortran max.f90 
semantic error: All arguments to max0 must be of the same type
 --> max.f90:3:10
  |
3 | print *, max(0., x) ! doesn't work
  |   
```

Intrinsic `max` is elemental, so passing scalars and arrays should be allowed.

Same with intrinsic `min`.

**Comment by certik** [comment]
Thanks for reporting it, I can reproduce it with the latest main as well.

**Comment by milancurcic** [comment]
Great news, thanks. Will LFortran build via conda-forge include latest changes to `main` or do I need to give it a special instruction to pick up this change?

**Comment by certik** [comment]
Right now this is fixed in `main`, so you need to build the latest git. Once we make a release and update conda, it will be available at conda-forge.
