### ISSUE TITLE
Problem mixing lfortran and clang++ compilation

### ISSUE THREAD

**Issue by mottelet** [lfortran/lfortran#4779]
Hello,

I have a problem trying to test a simplified calling sequence C++ -> Fortran -> C++ testing exception reporting through a a Fortran subroutine (it work e.g. when using the g++/gfortran pair) with clang++ and lfortran. Tests have been done on a M1 mac with latest miniforge-conda and clang, clang++ from cxx-compiler package and lfortran package.

The fortran subroutine in `testf.f` source file is:
```
      subroutine testf(simul)
      external simul
      call simul(0)
      end
```
and the c++ part (main and function) is in `main.cpp` source file:
```
#include <iostream>
using namespace std;

typedef void (*fun_t)(int *ind);
extern "C" void testf_(fun_t);
void cppsimul(int *i);

int main() {
    cout << "in main\n";
    try
    {
        testf_(cppsimul);        
    }
    catch (int e)
    {
        cout << "Caught exception\n";
    }
  return 0;
}

void cppsimul(int *i)
{
    cout << "in cppsimul\n";
    throw 0;
}
```
Compilation is done with:
```
lfortran -c --implicit-interface  testf.f 
clang++ main.cpp testf.o -o main
```
and the first step is OK and yields `testf.o` but for the c++ compilation and link i get
```
% clang++ main.cpp testf.o -o main         
Undefined symbols for architecture arm64:
  "_testf(void (*)(int*))", referenced from:
      _main in main-73c7ba.o
ld: symbol(s) not found for architecture arm64
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
Which flags are needed for the lfortran call ?

In fact, when I look into the `testf.o` object file, I get
```
 % objdump -t testf.o                      

testf.o:	file format mach-o arm64

SYMBOL TABLE:
0000000000000000 l     F __TEXT,__text ltmp0
```
which shows that no symbol is exported.

Thanks for help

**Comment by kmr-srbh** [comment]
Please use the `--generate-object-code` option to generate the object file for external subroutines using `lfortran`:

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran/examples$ lfortran -c testf.f testf.o --implicit-interface --generate-object-code
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran/examples$ clang++ testf.o main.cpp -o main.o
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran/examples$ ./main.o
in main
in cppsimul
Caught exception
```

**Comment by mottelet** [comment]
> ```
> in main
> in cppsimul
> Caught exception
> ```

Thanks ! And I see that the exception is correctly propagated, the couple clang/lfortran does it right !

S.

**Comment by kmr-srbh** [comment]
I am not sure if we have a compiler option to do this. @certik could you please help?

**Comment by certik** [comment]
See the `--mangle-underscore` and related options. We can generate the same output as gfortran if required.

**Comment by kmr-srbh** [comment]
Thanks for helping @certik!

We can achieve the same results as GFortran using:

```console
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran/examples$ lfortran -c testf.f testf.o --implicit-interface --all-mangling --mangle-underscore --generate-object-code
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran/examples$ objdump -t testf.o

testf.o:     file format elf64-x86-64

SYMBOL TABLE:
0000000000000000 l    df *ABS*  0000000000000000 LFortran
0000000000000000 l    d  .text  0000000000000000 .text
0000000000000000 g     F .text  0000000000000015 testf_


(base) saurabh-kumar@Awadh:~/Projects/System/lfortran/examples$ clang++ testf.o main.cpp -o main.o
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran/examples$ ./main.o
in main
in cppsimul
Caught exception
```

**Comment by mottelet** [comment]
OK, the two switches `--all-mangling --mangle-underscore` together are needed.

Thanks.
