### ISSUE TITLE
Call parameter type does not match function signature! when trying to build arpack

### ISSUE THREAD

**Issue by mottelet** [lfortran/lfortran#4782]
Hello,

The following file in arpack https://github.com/opencollab/arpack-ng/blob/master/SRC/snaitr.f does not compile with
```
lfortran --generate-object-code --std legacy --implicit-typing --implicit-interface --implicit-argument-casting  snaitr.f
```
but yields  bunch of errors such as 
```
code generation error: asr_to_llvm: module failed verification. Error:
Call parameter type does not match function signature!
```
S.

**Comment by certik** [comment]
Awesome, thanks for the report!

**Comment by Pranavchiku** [comment]
This works with https://github.com/lfortran/lfortran/pull/4515

**Comment by mottelet** [comment]
I am using lfortran release 0.40 from conda-forge, I suppose that the above PR is in the master branch ?

**Comment by Pranavchiku** [comment]
No it is still not released. It is not even in master branch, you need to do `gh pr checkout 4515` and do `lfortran` build by yourself if this is urgent. Else, will make a release once the PR is merged.

**Comment by mottelet** [comment]
Great ! Can you tell me why cmake is complaining ?
```
% cmake ..
CMake Error at CMakeLists.txt:14 (file):
  file STRINGS file "/Users/mottelet/git/lfortran/version" cannot be read
```

**Comment by certik** [comment]
Yes, you have to run `build0.sh` first to create the `version` file.
