### ISSUE TITLE
Spread intrinsic raises semantic error for scalar first argument

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#4801]
## Minimal reproducible example

```f90

PROGRAM test_spread
  INTEGER :: a = 1
  WRITE(*,*) SPREAD(A, 1, 2)
END PROGRAM
```

the above fortran program, taken from https://gcc.gnu.org/onlinedocs/gfortran/SPREAD.html. On compilation with LFortran raises the below error:
```bash
semantic error: The argument `source` in `spread` must be of type Array
   --> test.f90:280:23
    |
280 |     WRITE(*,*) SPREAD(A, 1, 2)
    |                       ^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

I think this issue is also needed for compilation of `IO` of `stdlib`, see: https://github.com/lfortran/lfortran/issues/3406#issue-2133452997

**Comment by jinangshah21** [comment]
```
 if(is_integer(*type_source)){
            Vec<ASR::expr_t*> args_temp;
            args_temp.reserve(al, 1);
            args_temp.push_back(al, source);
            source = ASRUtils::EXPR(ASRUtils::make_ArrayConstructor_t_util(al, source->base.loc,
                                    args_temp.p, args_temp.n, type_source, ASR::arraystorageType::ColMajor));
            type_source = ASRUtils::expr_type(source);
```
I have converted scalar to Array in `create_Spread` But output is random number for first value.
For above example I am having output : 725262921  1
For Spread(a, 1, 3) I am having output : -1922029  1   1 
So only first value Is Wrong, what can be reason for that?

**Comment by HarshitaKalani** [comment]
Do you mean the following?
```fortran
PROGRAM test_spread
  INTEGER :: a(1) = 1
  WRITE(*,*) SPREAD(A, 1, 3)
END PROGRAM
```
This is generating the correct output for me though. I'm working on linux
```console
$ gfortran b.f90 && ./a.out
           1           1           1
$ lfortran b.f90
1    1    1
```
