### ISSUE TITLE
code generation error: Type mismatch in subroutine call

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#4852]
For the below Fortran program in fixed-form:
```f77
      SUBROUTINE func( real_arr )
        REAL               real_arr( * )
        INTEGER            num
        EXTERNAL           ext
        CALL ext( real_arr )
        CALL ext( real_arr( num ) )
        RETURN

      END

      PROGRAM MAIN
        IMPLICIT NONE
      END PROGRAM MAIN

```

On compiling it with LFortran as below:
```
$ lfortran test.f --fixed-form --implicit-interface
code generation error: Type mismatch in subroutine call, expected `f32[:]`, passed `f32`
 --> test.f:6:19
  |
6 |         CALL ext( real_arr( num ) )
  |                   ^^^^^^^^^^^^^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by gxyd** [comment]
I'll try to reduce the program further, I don't know why I didn't do that before I created the issue. 😞

**Comment by gxyd** [comment]
Didn't know that the below is actually a valid Fortran program:
```f90
PROGRAM main
    IMPLICIT NONE
    REAL :: array(5)
    INTEGER :: i, num

    DO i = 1, 5
        array(i) = REAL(i)
    END DO

    num = 3

    CALL ext(array) ! first call

    CALL ext(array(num)) ! second call

END PROGRAM main

SUBROUTINE ext(B)
    REAL :: B(*)
    INTEGER :: i

    PRINT *, 'Inside subroutine'
END SUBROUTINE ext

```

In the second call (`CALL ext(array(num))`), the single element `array(3)` is passed to `ext`, and Fortran treats the scalar value as a 1-element array, and the subroutine call is successfully executed.

**Comment by gxyd** [comment]
I'll try to see if I can come up with a solution to the above problem.

**Comment by gxyd** [comment]
Interestingly, compiling the below program with GFortran, raises an error:
```f90
PROGRAM main
    IMPLICIT NONE
    REAL, PARAMETER :: array(3) = [1, 2, 3]
    INTEGER :: i, num

    CALL ext(array)

    CALL ext(array(2))

END PROGRAM main

SUBROUTINE ext(B)
    REAL :: B(*)
    INTEGER :: i

    PRINT *, 'Inside subroutine'
END SUBROUTINE ext
```

the only difference above being, that I made `array` as a parameter. I even tried explicitly specifying the intent as `intent(in)`  of `B` in subroutine, and still I get the same error.

On compiling it with GFortran, I get the below error:
```bash
test.f90:8:13:

    8 |     CALL ext(array(2))
      |             1
Error: Rank mismatch in argument 'b' at (1) (rank-1 and scalar)
```

**Comment by gxyd** [comment]
It makes sense that if the above array `arr` here: https://github.com/lfortran/lfortran/issues/4852#issuecomment-2363578074, was defined as a `PARAMETER`, then it will need to raise an error instead.

**Comment by gxyd** [comment]
@certik @Pranavchiku , is there an existing compiler option to make program present here: https://github.com/lfortran/lfortran/issues/4852#issuecomment-2363578074 to work?

**Comment by certik** [comment]
Yes, it's called `--legacy-array-sections`.

**Comment by gxyd** [comment]
Ah, understood. That makes sense:
```
--legacy-array-sections: "Enables passing array items as sections if required"
```

**Comment by gxyd** [comment]
I'll close the issue, as I think by using the compiler option `--legacy-array-sections` would be the right way.

**Comment by certik** [comment]
Yes, you have to use this option for legacy codes.
