### ISSUE TITLE
Make run_tests.py run in parallel

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#491]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/641

Currently they run in serial. On my Apple M1 they run in 8.4s. We should run them in parallel, I am hoping we can get some nice speedups that way.

**Comment by konradha** [comment]
Done [here](https://gitlab.com/lfortran/lfortran/-/merge_requests/1749

**Comment by certik** [comment]
Thanks!
