### ISSUE TITLE
Array Reference with vector indices are not supported

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5117]
Towards #4397.

MRE : 
```fortran
program linalg_mod
implicit none
real :: B(2,2) = reshape([2,3,4,5],[2,2])
integer :: x(2) = [2,1]
B = B(:,x)
print *, B
end program
```

LFortran Error : 
```
(lf) jinu2110@JNSLAP:/mnt/c/lfortran$ lfortran a.f90 
semantic error: Incompatible ranks 2 and 1 in assignment
 --> a.f90:5:1
  |
5 | B = B(:,x)
  | ^^^^^^^^^^ 
```

GFortran Output : 
```
(lf) jinu2110@JNSLAP:/mnt/c/lfortran$ gfortran a.f90 && ./a.out
   4.00000000       5.00000000       2.00000000       3.00000000  
```

**Comment by certik** [comment]
I see, it's because `x` is a vector index, so it's actually a 2D array on the RHS. I don't know if we support vector indices yet.

**Comment by kmr-srbh** [comment]
I think this is a duplicate of #4405. We have a draft PR for it at #4446. I think using the general ASR tools to create the `do` loop will help us resolve the questions I had posted on the thread.

**Comment by jinangshah21** [comment]
Closing it as it is a duplicate of #4405.
