### ISSUE TITLE
Design for array expressions

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5201]
The type for each node in an array expression (like `x = a(:2) + b(:2)`) contains dimensions with the size of the array (and lower bound, typically `1`). For things like `x = f(a)`, we need to go into the function signature, and extract the dimension of the result as an expression / function of the arguments, and then substitute using the actual arguments in the expression. 

So in the end we end up with each node in the array expression having an expression for each dimension as a function of the parent variables in the expression, and it does *not* call any user function. 

The simplifier pass can then take these expressions and allocate a temporary array on stack, as needed.

(There is a corner case when the user function `f` calls another pure user function `g` to calculate the size of the return array; in that case that pure function has to be called; but by virtue of being pure, it has no side effects, so it can be called multiple times.)

**Comment by certik** [comment]
A temporary solution might be to expose FunctionParam (https://github.com/lfortran/lfortran/pull/5157) and then substitute it in the simplifier pass.

But the full solution is to not expose any FunctionParam, but always compute the correct expression already in AST->ASR. The simplifier pass will just use it.

**Comment by czgdp1807** [comment]
I think I will go with temporary solution first in order to check whether it fixes the ballooning problem or not.

**Comment by certik** [comment]
Regarding the corner case when the function result array size is computed using an expensive user function `g()`:
```
function f() result(r)
real :: r(g())
end function
```
the function has to be side-effects-free ("Fortran pure"), so we can call it more than once (or not at all) without any side effects. Consequently, at first we can simply duplicate it and call it more than once in expressions like "x + f()". This will get everything working.

Later, to optimize the performance, we should refactor the expression "z = x + f()" into:
```
allocate(y(g()))
y = f()
z = x + y
```
And then to:
```
n = g()
allocate(y(n))
y = fn(n)
z = x + y
```
and change `f` to `fn` as follows:
```
function f(n) result(r)
integer, intent(in) :: n
real :: r(n)
end function
```


This transformation can be done even if `g()` depends on the arguments: we know the argument sizes before calling `f()`, so we can compute `n` using them, and pass `n` into `fn()`. This only require calling `g()` once, so it will be high performance.

So the door is open to maximum performance with this approach. Let's worry about this corner case later, for now we simply duplicate the expression and call `g()` twice.

**Comment by czgdp1807** [comment]
All of this is good and happens in `simplifier` pass. The question is how to represent `z = x + f(a)` in ASR before all the passes? Like, `Assignment(Var(z), IntegerBinOp(x, FunctionCall(f, [a]))`. What would be the type of `FunctionCall(f, [a])`? `Array(IntegerConstant(1), FunctionCall(g, [a]))`? Also what about `f(f(a(1, 2:ub)))`? Just after AST to ASR, how things would like? That's something we need an answer to.

**Comment by certik** [comment]
This must be assigned right away in AST->ASR, *before* any ASR passes. In the first example you posted the type of `FunctionCall(f, [a])` will be `Array(IntegerConstant(1), ArraySize(a))` assuming the function `f` is declared as:
````
function f(a) result(r)
real :: r(size(a))
end function
```
You simply go in, examine the type of the result and substitute it from the arguments. Specifically, you do *not* call the function.

Regarding your second example it will follow exactly the same approach, so the size of the final array will be `ArraySize(a(1, 2:ub))` assuming the same function `f`, which can be further simplified to just `ub-1` I think. Again, you do *not* call `f`.

**Comment by czgdp1807** [comment]
Well, so that's what I meant in our Zulip chat. In a function call argument there can be any expression present. So you need to compute array size of any ASR expression.
