### ISSUE TITLE
tokenizer error with format 'tr1' 

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5212]
## Minimal Reproducible Example

for the below fortran program in fixed-form, with a `format` statement

```f90
      subroutine f ()
      implicit none

  1   format (tr1,a)

      end
```

on execution of the above program with lfortran as below:
```console
$ lfortran test.f --fixed-form --cpp
tokenizer error: Token 't' is not recognized in `format` statement
 --> test.F:1:8
  |
1 |       subroutine f ()
  |        ^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

## Other information

We need the fix to be able to move forward with compilation of [POT3D](https://github.com/lfortran/lfortran/issues/2862). Please see the below comment https://github.com/lfortran/lfortran/issues/5212#issuecomment-2446428446, that the issue isn't restricted to fixed-form programs

**Comment by gxyd** [comment]
Seems like this issue exists even free-form as well:
```f90
      subroutine f ()
      implicit none

  1   format (tr1,a)

      end

      program main
        implicit none
      end program main

```

on it's execution with lfortran as below:
```console
> lfortran test.F
tokenizer error: Token 't' is not recognized in `format` statement
 --> test.F:1:2
  |
1 |       subroutine f ()
  |  ^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by certik** [comment]
We might not support the "t" token in the format. I am not sure what it does, so we need to look it up, and then improve the tokenizer.
