### ISSUE TITLE
CI: Test fastGPT ( macos-latest ) job under 'Test LLVM' doesn't run

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5231]
## Description

Let's look at the `Test LLVM` CI job here: https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L878-L879, where it explicitly mentions:
```yml
runs-on: ubuntu-latest
```

and under that we've `Test fastGPT ( macos-latest)` here: https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L1163, which will probably never run because of the main job already requiring the os to be `ubuntu-latest`.

I'm not really sure if that's intentional or not, if it is intentional, then maybe we can have a comment describing that it's there just for the sake of repeating the code repeated from https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L496 (i.e. `Check Third Party Code Compilation - OS (${{ matrix.os }}), LLVM (${{ matrix.llvm-version }})`) or the other is we actually test it on macOS as well.

**Comment by gxyd** [comment]
I went through a few of the PR's where `Test LLVM` CI job is run, e.g.; https://github.com/lfortran/lfortran/actions/runs/11645376083/job/32428340408?pr=5230

there's nothing which runs under:
* `Test fastGPT (ubuntu-latest)` 
* `Test fastGPT (macos-latest)`
* `Test fpm`

under none of them there is any console output (see attached screenshot as well), which I think indicates that they aren't actually being run.

![Screenshot 2024-11-03 at 10 27 14 AM](https://github.com/user-attachments/assets/31b9b241-33a2-4719-8131-e231bf224a6f)

**Comment by Pranavchiku** [comment]
There is separate mac-os job for FastGPT

**Comment by gxyd** [comment]
> There is separate mac-os job for FastGPT

I'm sorry, I don't understand. Are you saying that we do run the macOS job for fastGPT at the CI correctly? The links in the issue description suggest otherwise to me.

**Comment by Pranavchiku** [comment]
Yes, refer: https://github.com/lfortran/lfortran/pull/5232#discussion_r1826917386

**Comment by Pranavchiku** [comment]
> The links in the issue description suggest otherwise to me.

We made a choice not to run third party test on all llvm version but only 11 and 19, both on mac and ubuntu.

**Comment by Pranavchiku** [comment]
> and under that we've Test fastGPT ( macos-latest) here: https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L1163, which will probably never run because of the main job already requiring the os to be ubuntu-latest.

Refer: https://github.com/lfortran/lfortran/actions/runs/11643270291/job/32423821353

**Comment by Pranavchiku** [comment]
To close this  issue one has to remove the following code sections:

* https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L1163

**Comment by gxyd** [comment]
Why do we *not* want to test only `fastGPT` and `fpm` with all the LLVM versions, but test all the other third party packages?

**Comment by Pranavchiku** [comment]
> Why do we not want to test only fastGPT and fpm with all the LLVM versions

We do test it. https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L1038 and https://github.com/lfortran/lfortran/blob/main/.github/workflows/CI.yml#L1194.

I think you are confused here

* We test all third party checks under `third_party_code_compile`.
    * This tests both ubuntu and macos, with LLVM 11 and 19, so 2x2, 4 test combinations
* We test all integration test, third party test to assure everything works across all llvm version under `Test LLVM:`
    * Why not test on mac-os latest? Testing on LLVM 19 would suffice not completely though, not scalable
    * Hence, if it works on ubuntu-latest for all LLVM version, and on macos for LLVM 19, we can be assured that it will work for intermediate versions.

**Comment by certik** [comment]
@gxyd thanks for the catch! It's amazing that we all missed it. CI is really hard to get right.
