### ISSUE TITLE
'no implicit return type' error for an external function

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5238]
## Minimal Reproducible Example

For the below fortran program:
```f90
subroutine map_xi_to_c (cs, cv)
    USE iso_fortran_env
    implicit none
    real(REAL32), dimension(2), intent(in) :: cs
    real(REAL32), intent(out) :: cv
    real(REAL32), external :: fold
    cv=fold(cs(1))
    return
end

function fold (x0)
    use iso_fortran_env
    implicit none
    real(REAL32) :: fold
    real(REAL32) :: x0
end

program main
end program main

```

on it's execution with LFortran as below:
```console
$ lfortran --version
LFortran version: 0.41.0-184-g30e8beb84-dirty
Platform: macOS ARM
LLVM: 11.0.1
Default target: arm64-apple-darwin23.6.0

$ lfortran test.f90 --implicit-interface --implicit-typing
semantic error: No implicit return type available for `fold`
  --> test.f90:11:1 - 16:3
   |
11 |    function fold (x0)
   |    ^^^^^^^^^^^^^^^^^^...
...
   |
16 |    end
   | ...^^^ 


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

I've tried using the different LFortran compiler options i.e. `--implicit-interface` and `--implicit-typing`, and none of them work.

**Comment by certik** [comment]
Yes, that should work. The return type is `real(REAL32) :: fold`.

**Comment by Pranavchiku** [comment]
We have handled cases where variable defines return type of external function, let me check.

**Comment by Pranavchiku** [comment]
The fact that it works with `--implicit-interface` and not with `--implicit-typing --implicit-interface`. I am pushing fix with `--impilcit-interface` because considering `implicit none` we shall not be using `--implicit-typing`
