### ISSUE TITLE
Return non-zero exit code for --continue-compilation if there are errors

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5248]
https://github.com/lfortran/lfortran/pull/5230/files#r1827993610

**Comment by certik** [comment]
To fix this issue, lfortran itself must return a non-zero exit code when there are errors. Then our runtests will automatically pick it up.

**Comment by Pranavchiku** [comment]
I’ll try to fix it tomorrow morning, @AnshMehta1 till then you can continue supporting other examples

**Comment by AnshMehta1** [comment]
> I’ll try to fix it tomorrow morning, @AnshMehta1 till then you can continue supporting other examples, or if you wish to try it you, you need to find suitable place in lfortran.cpp where ast_to_asr is called and return non zero exit code if option is turned on and diagnostics have error message.

I will also be able to try it by tomorrow morning only as currently I am travelling.
