### ISSUE TITLE
Symbol cannot be found in module when using Fortran 77 style PARAMETER

### ISSUE THREAD

**Issue by rikardn** [lfortran/lfortran#5251]
Compiling the following fortran code:

```fortran
MODULE FIRST
  PARAMETER (X=90)
END MODULE FIRST

MODULE SECOND
  USE FIRST, ONLY: X
END MODULE SECOND
```

gives the following error:

```
semantic error: The symbol 'x' not found in the module 'first'
 --> SIZ.f90:6:3
  |
6 |   USE FIRST, ONLY: X
  |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ 

```

I have tested it to work fine with gfortran.

Replacing the `PARAMETER (X=90)` with the more modern ` INTEGER, PARAMETER :: X = 90` works. The older `PARAMETER` statement should still be valid Fortran 2018.

**Comment by certik** [comment]
Good catch! Thanks. We'll fix it.

**Comment by rikardn** [comment]
Thanks!

For extra context: I am trying to compile NONMEM (https://www.iconplc.com/solutions/technologies/nonmem) which is a proprietary software and the gold standard software for modeling in the field of pharmacometrics. It was originally written in Fortran 77, but has partially been updated to Fortran 95. As soon as this bug has been fixed I will retry the compilation and report my findings.

**Comment by Pranavchiku** [comment]
As suspected, we don't have type information in `PARAMETER (X=90)` so you need to handle `--implicit-typing`, full example:

```fortran
MODULE FIRST
  PARAMETER (X=90)
END MODULE FIRST

MODULE SECOND
  USE FIRST, ONLY: X
CONTAINS
  SUBROUTINE PRINT_X
    PRINT *, X
  END SUBROUTINE PRINT_X
END MODULE SECOND

PROGRAM MAIN
  USE SECOND
  CALL PRINT_X
END PROGRAM MAIN
```

```console
% lfortran a.f90 --implicit-typing
0.00000000e+00
```

Which is a real bug because `x` has not attributed to it's value:

```clojure
                            x:
                                (Variable
                                    2
                                    x
                                    []
                                    Local
                                    ()
                                    ()
                                    Default
                                    (Real 4)
                                    ()
                                    Source
                                    Public
                                    Required
                                    .false.
                                )
```

I have fix for this ready, pushing in a while, comes from the following diff:
```diff
diff --git a/src/lfortran/semantics/ast_common_visitor.h b/src/lfortran/semantics/ast_common_visitor.h
index d65030a11..6db11dc5e 100644
--- a/src/lfortran/semantics/ast_common_visitor.h
+++ b/src/lfortran/semantics/ast_common_visitor.h
@@ -1048,7 +1048,7 @@ public:
     }
 
     ASR::symbol_t* declare_implicit_variable(const Location &loc,
-            const std::string &var_name, ASR::intentType intent) {
+            const std::string &var_name, ASR::intentType intent, ASR::expr_t* value = nullptr) {
         ASR::ttype_t *type;
         char first_letter = var_name[0];
         // The default implicit typing is:
@@ -1060,12 +1060,25 @@ public:
             // it is a real
             type = ASRUtils::TYPE(ASR::make_Real_t(al, loc, 4));
         }
+        if ( value != nullptr ) {
+            // infer type from value
+            ASR::ttype_t* value_type = ASRUtils::expr_type(value);
+            if ( ASRUtils::is_integer(*value_type) ) {
+                type = ASRUtils::TYPE(ASR::make_Integer_t(al, loc, compiler_options.po.default_integer_kind));
+            } else if ( ASRUtils::is_real(*value_type) ) {
+                type = ASRUtils::TYPE(ASR::make_Real_t(al, loc, 4));
+            } else if ( ASRUtils::is_complex(*value_type) ) {
+                type = ASRUtils::TYPE(ASR::make_Complex_t(al, loc, 4));
+            } else if ( ASRUtils::is_logical(*value_type) ) {
+                type = ASRUtils::TYPE(ASR::make_Logical_t(al, loc, 4));
+            }
+        }
         SetChar variable_dependencies_vec;
         variable_dependencies_vec.reserve(al, 1);
         ASRUtils::collect_variable_dependencies(al, variable_dependencies_vec, type);
         ASR::symbol_t *v = ASR::down_cast<ASR::symbol_t>(ASR::make_Variable_t(al, loc,
             current_scope, s2c(al, var_name), variable_dependencies_vec.p,
-            variable_dependencies_vec.size(), intent, nullptr, nullptr,
+            variable_dependencies_vec.size(), intent, value, value != nullptr ? ASRUtils::expr_value(value) : value,
             ASR::storage_typeType::Default, type, nullptr,
             current_procedure_abi_type, ASR::Public,
             ASR::presenceType::Required, false));
@@ -2425,7 +2438,12 @@ public:
                                 ASR::symbol_t* sym_ = current_scope->resolve_symbol(sym);
                                 if (!sym_ && compiler_options.implicit_typing && sa->m_attr != AST::simple_attributeType
                                                         ::AttrExternal) {
-                                    sym_ = declare_implicit_variable(x.m_syms[i].loc, sym, ASR::intentType::Local);
+                                    ASR::expr_t* value = nullptr;
+                                    if (sa->m_attr == AST::simple_attributeType::AttrParameter) {
+                                        this->visit_expr(*s.m_initializer);
+                                        value = ASRUtils::EXPR(tmp);
+                                    }
+                                    sym_ = declare_implicit_variable(x.m_syms[i].loc, sym, ASR::intentType::Local, value);
                                 }
                             }
                         }
```

**Comment by rikardn** [comment]
Thanks for having a look.

I believe that the Fortran standard stipulates implicit typing so having it off by default is surprising (and perhaps non-conformant). This is mentioned in https://github.com/lfortran/lfortran/issues/243

**Comment by certik** [comment]
@rikardn yes, we do not allow implicit typing by default, but you can always enable it for backwards compatibility or strict standard compliance.

**Comment by rikardn** [comment]
Thanks for the fix. I'll retest.

Thanks @certik for clarifying. My feeling is that this design choice makes lfortran harder to use and trust. So by default lfortran compiles some non-standard version of Fortran. In this case it alters the implicit typing. This makes me worried that there are other changes that lfortran does to the standard Fortran that might change the behaviour of the compilation or worse the actual function of the generated code? Are these documented somewhere? I would be less anxious if the default was to compile standard Fortran (perhaps the latest version) and that non-standard changes would be opt-in or optionally have one single option to make the compiler be as standards compliant as possible. Take this as just my humble opinion as a user. I fully sympathize with not wanting to have implicit typing by default.

**Comment by certik** [comment]
@rikardn good points.

> or optionally have one single option to make the compiler be as standards compliant as possible.

We have that option: `--std=f23`. With it, it will be exactly Fortran 2023 compliant. If not, please report it and we'll fix it. 

Given your comment I think you should probably just use it.


Until we reach version 1.0, we can change the default behavior. We need to see what the community wants, right now I still think more people would prefer the implicit typing to not be allowed by default. We'll only know by doing it, so I appreciate your feedback on this.

Note that my understanding is that every compiler deviates from the standard in some way. There is no compiler that is strictly standards conforming.

> This makes me worried that there are other changes that lfortran does to the standard Fortran that might change the behaviour of the compilation or worse the actual function of the generated code?

Yes, it changes the behavior, mostly by being more strict and give extra error messages, warnings and hints.

> Are these documented somewhere?

Right now it's documented by the code itself:

https://github.com/lfortran/lfortran/blob/9f1b9c6631049f3036965c5db3965bbc5e6621ed/src/bin/lfortran.cpp#L2294

Should be quite descriptive I think.

**Comment by rikardn** [comment]
Thanks @certik! I think `--std=f23` is what I am looking for. I'll give it a try.
