### ISSUE TITLE
MAINT,CHORE: Apply for GitLab FOSS tier

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#526]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/684

![image](/uploads/26763e602a81027f42fe682ff3bc9603/image.png)

There appears to be a new tier for GitLab's open source projects:
- https://about.gitlab.com/blog/2022/02/04/ultimate-perks-for-open-source-projects/

The application process consists of filling [out this form](https://about.gitlab.com/solutions/open-source/join/#application).

**Comment by lucifer1004** [comment]
Now that the project has been moved here, I think this issue can be closed. @certik

**Comment by certik** [comment]
Yes, this can be closed. I applied for the FOSS Tier, but never heard back from GitLab. We fixed it by moving to GitHub.
