### ISSUE TITLE
ICE on missing file

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5286]
Trying to run 
```sh
src/bin/lfortran no_such_file.f90
```
where `no_such_file.f90` doesn't exist results in:
```sh
Internal Compiler Error: Unhandled exception
```
on `main` branch, SHA 2d0376d42c22b5b026

**Comment by pjh40** [comment]
`main` is catching the `LCompilers::LCompilersException("File does not exist: " + arg_file)` exception thrown in `main_app`, but the ICE message is way too "scary" for a missing input file.

**Comment by harperjf** [comment]
This bug was reported in #3796 in April and I thought it had been fixed. It hasn't.

**Comment by certik** [comment]
Fixed by https://github.com/lfortran/lfortran/pull/5289.
