### ISSUE TITLE
LCOMPILERS_ASSERT on missing variable decl

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5287]
Attempting to compile the program:
```f90
program foo
  parameter(foo=1)
  integer bar
  bar = foo
end program
```
leads to the error:
```sh
LCOMPILERS_ASSERT failed: [...]/lfortran/src/libasr/../libasr/asr.h
function expr_type0(), line number 53287 at 
false
ERROR MESSAGE:
0
```
on `main` SHA 2d0376d42c22b5b.  Adding an `INTEGER FOO` declaration allows the program to compile correctly.

**Comment by certik** [comment]
With https://github.com/lfortran/lfortran/pull/5291 the above code now gives:
```console
$ lfortran a.f90
semantic error: Symbol 'foo' must be a variable or a function
 --> a.f90:4:9
  |
4 |   bar = foo
  |         ^^^ 'foo' is a 'Program', not a variable or a function
```
That was the main bug.

There is also a separate bug that if you use `parameter(foo=1)` but not actually declare it, it will not say anything, I made this: https://github.com/lfortran/lfortran/issues/5292.
