### ISSUE TITLE
Implement `include`

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#529]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/687

Here is an example (https://github.com/gnikit/fortls/blob/master/test/test_source/test_inc.f90):
```fortran
$ cat test_inc.f90 
MODULE test_mod

include "subdir/test_inc2.f90"

REAL(8) :: val1

CONTAINS

SUBROUTINE test_sub

val2
END SUBROUTINE test_sub
include 'mpi.f'

END MODULE test_mod
```
Currently it fails with:
```console
$ lfortran --show-ast test_inc.f90 
syntax error: Newline is unexpected here
  --> test_inc.f90:11:5
   |
11 | val2
   |     ^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by lucifer1004** [comment]
Duplicate of #762. Maybe we can close this old issue and discuss the solution in the new one. @certik

**Comment by certik** [comment]
#762 is a PR that once finished should close this issue. So we can keep both open.

**Comment by lucifer1004** [comment]
I put the wrong link, the duplicate issue is #777

**Comment by certik** [comment]
Closing, we'll keep tracking #777.
