### ISSUE TITLE
Design enumerations properly

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5314]
See https://github.com/lfortran/lfortran/pull/5310#issuecomment-2466309316.

The big problem is that enumerators are both part of the enumeration as well as global.

The old design was almost correct. We need to use either ExternalSymbol or an equivalent feature to store enumerators globally, but make them point inside the enumeration. So we use regular lookups in the symbol table to find them.

A relatively clean design could be:

* Introduce EnumeratorLink symbol, which would point to the actual enumeration. Then we look it up as usual, and use in expressions.
* We have a choice:
  * Either we always go into the enumeration and pull the actual enumerator
  * Or we use EnumeratorLink in expressions via Var. But it would be quite painful I think, so probably always following up might not be a bad idea; this would happen at the same place where the old code in #5310 was, but we simply check if the symbol is EnumeratorLink, and if so, follow up through and use the enumerator from enumeration's symbol table.

When an enumeration is declared in Fortran, then the frontend (AST->ASR) will bring all enumerators into the current scope via EnumeratorLink. In LPython and other frontends we usually don't want to do that and let users reference the enumeration explicitly, but since Fortran is designed this way, then we can implement this global feature via EnumeratorLink.

**Comment by Pranavchiku** [comment]
> Either we always go into the enumeration and pull the actual enumerator

Which we cannot do as it will cause `symbol out of current scope` ASR verify error, scope of `asr_owner` of the statement below is `6` 

```clojure
(Print
    (StringFormat
        ()
        [(Var 7 red)
        (Var 8 green)]
        FormatFortran
        (String -1 0 () PointerString)
        ()
    )
)
```

> Or we use EnumeratorLink in expressions via Var

We have to use it, else it will always throw ASR Verify Error as explained above.

**Comment by Pranavchiku** [comment]
With this simple diff, we can get the job done:

```diff
diff --git a/src/lfortran/semantics/ast_symboltable_visitor.cpp b/src/lfortran/semantics/ast_symboltable_visitor.cpp
index f1d888aa2..b2712b1c3 100644
--- a/src/lfortran/semantics/ast_symboltable_visitor.cpp
+++ b/src/lfortran/semantics/ast_symboltable_visitor.cpp
@@ -3488,6 +3488,12 @@ public:
             s2c(al, sym_name), nullptr, 0, m_members.p, m_members.n, abi_type,
             dflt_access, enum_value_type, type, nullptr);
         parent_scope->add_symbol(sym_name, ASR::down_cast<ASR::symbol_t>(tmp));
+        for (auto it: current_scope->get_scope()) {
+            ASR::Variable_t* var = ASR::down_cast<ASR::Variable_t>(it.second);
+            parent_scope->add_symbol(var->m_name, ASR::down_cast<ASR::symbol_t>(ASR::make_ExternalSymbol_t(al,
+                        var->base.base.loc, parent_scope, s2c(al, var->m_name), it.second,
+                        s2c(al, sym_name), nullptr, 0, var->m_name, var->m_access)));
+        }
         current_scope = parent_scope;
     }
 
```

Instead of creating `ExternalSymbol` inside `resolve_variable`, create it rightaway in `visit_Enum`.
