### ISSUE TITLE
Syntax errors now print all errors

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5332]
It seems we now print all syntax errors, so we often get hundreds of error messages.

Instead, by default let's only print exactly one error message and exit. Only with `--continue-compilation` let's print all of them. We can also later control how many to print with a compiler option, but for now I think a good default is to print just one error message and exit.

Also, as a user, I don't think I want to run the code if there are errors. But I still might want to print all errors. We should figure out the CompilerOptions flags how to control this well.

**Comment by kmr-srbh** [comment]
> Also, as a user, I don't think I want to run the code if there are errors. But I still might want to print all errors. We should figure out the CompilerOptions flags how to control this well.

The following diff helps us report errors and not continue to linking:

```diff
diff --git a/src/bin/lfortran.cpp b/src/bin/lfortran.cpp
index 24714ca45..f96357fc4 100644
--- a/src/bin/lfortran.cpp
+++ b/src/bin/lfortran.cpp
@@ -2660,7 +2660,7 @@ int main_app(int argc, char *argv[]) {
             // assume it's an object file
             tmp_o = arg_file;
         }
-        if (err && !compiler_options.continue_compilation) return err;
+        if (err) return err;
         err_ = err;
         object_files.push_back(tmp_o);
     }
```

**Comment by Pranavchiku** [comment]
The deleted code is working as we wish, if `--continue-compilation` is on, don't throw error and continue. If it is not, throw error right away. This was added in one of the recent PRs.
