### ISSUE TITLE
Possibly incorrect way of data initialization

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5341]
## Minimal Reproducible Example

The below fortran program is derived from [tests/fixedform_doloop3.f](https://github.com/lfortran/lfortran/blob/main/tests/fixedform_doloop3.f), which I think has an incorrect initialization:
```f90
SUBROUTINE START1()
    IMPLICIT NONE
    INTEGER :: L
    INTEGER :: N
    REAL F, ONE=1, TWO=2
END

program main
end program main

```

the original line in the program `tests/fixedform_doloop3.f` is:
```f90
        REAL F(L), ONE=1, TWO=2
```
here: https://github.com/lfortran/lfortran/blob/main/tests/fixedform_doloop3.f#L7

## GFortran output
```console
> gfortran test.f90 -o a.out && ./a.out
test.f90:5:16:

    5 |     REAL F, ONE=1, TWO=2
      |                1
Error: Syntax error in data declaration at (1)
```

## Concern

The concern of this issue *isn't* the **error not reported** bug, but rather the fact that this allows an incorrect way to initialize variables and hence might disturb other correct fixes to the parser. With this issue the main concern is to correct the `tests/fixedform_doloop3.f`, below is a screenshot from https://bayanbox.ir/view/3820206914900746365/StatLab-Applied-Statistics-Algorithms.pdf, where the program `tests/fixedform_doloop3.f` comes from:

![Screenshot 2024-11-11 at 6 14 28 PM](https://github.com/user-attachments/assets/16ed9290-fb07-4715-9129-cfe595d7881b)

**Comment by harperjf** [comment]
Is this the same bug as #3945 ?

**Comment by pjh40** [comment]
As @harperjf said, I would guess that it is the same as #3945... I don't see any incorrect initialization apart from the missing `::`.

**Comment by gxyd** [comment]
The underlying issue is the same here, i.e. we shouldn't allow a syntax like `REAL ONE = 1`, which wasn't necessarily the intention of this issue to fix it. The focus of this issue was to rectify the wrong test case in our test-suite where a bad syntax like `REAL ONE = 1` was there and instead use a correct syntax.

So, I think we can still keep the issue #3945 open, as even after closing this issue we don't raise an error for the incorrect syntax yet.

**Comment by certik** [comment]
Everything should be fixed now.
