### ISSUE TITLE
Infinite loop in FixedFormRecursiveDescent

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5350]
Trying to parse:
```fortran
      CHARACTER*10 FUNCTION CF716(IVD001)
      END                               
```
LFortran SHA 4068df32ee4 enters an infinite loop in `LCompilers::LFortran::FixedFormRecursiveDescent`. It appears that the `FixedFormRecursiveDescent::is_declaration` function is trying to match against an input string of `0functioncf716(`.  This seems to point to two issues:

1. The `CHARACTER*<N>` parser is not greedy enough getting the repeat count (1 instead of 10?); and
2. There doesn't seem to be a non-match exit criterion from `is_declaration`.

**Comment by certik** [comment]
Good catch. The declaration parsing in the fixed-form tokenizer is a bit tricky and currently is not robust enough, I found another bug there today: https://github.com/lfortran/lfortran/pull/5362. The ultimate fix is probably to figure out how to generate the parser (https://github.com/lfortran/lfortran/issues/5365), likely after we reach beta. Until then we just need to fix these bugs in our current parser, it's relatively clean, just hard to "prove" that there are no bugs like this one.
