### ISSUE TITLE
IMPLICIT statement parsing error

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5352]
Attempting to parse:
```f90
subroutine foo
  implicit integer(Y, V-X), real(M)
end subroutine foo
```
with LFortran SHA 4068df32e leads to the error:
```
syntax error: Token ',' is unexpected here
 --> func.f90:2:27
  |
2 |   implicit integer(Y, V-X), real(M)
  |                           ^ 
```
I'd guess that the grammar doesn't accept an _implicit-spec-list_, as is specified in the standard.

Also, _kind-selector_ inputs that aren't an `id` or `KW_INTEGER` are improperly rejected:
```f90
implicit real(4+4)(q-s)
implicit integer(kind=2)(i)
```

**Comment by certik** [comment]
I think this is similar to https://github.com/lfortran/lfortran/issues/3113. We need to fix it.

**Comment by pjh40** [comment]
I am on vacation for the next week, but I would happy to look at this and other issues when I get back online.

**Comment by certik** [comment]
Awesome, we'll leave these to you. :) Thank you.

**Comment by pjh40** [comment]
FYI: The #5536 PR doesn't address the issues with KIND... I'll open a new issue for that.
