### ISSUE TITLE
Failure in master, cmake inserts "-g"

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5395]
https://github.com/lfortran/lfortran/actions/runs/11859220707/job/33051652014?pr=5394

I have fixed this somewhere, but can't remember where. We need to downgrade cmake, or ensure cmake does not insert "-g".

**Comment by certik** [comment]
Found it, I fixed this exact issue in https://github.com/lfortran/lfortran/pull/5322.

**Comment by certik** [comment]
The solution is to use "cmake=3.29.1" for now.

If we decide to upgrade cmake, we need to make it not use "-g", but that's a separate issue. For CI robustness, we need to control all versions, so let's simply pin the version.

**Comment by certik** [comment]
The PR https://github.com/lfortran/lfortran/pull/5396 should fix this.

**Comment by Pranavchiku** [comment]
Thanks for fixing this!
