### ISSUE TITLE
Need command-line option to contextually rename symbols

### ISSUE THREAD

**Issue by dylon** [lfortran/lfortran#5419]
For our LSP integration, we will need a command-line option to contextually rename symbols. It would best if we could rename them across a project rather than just the current file, but we must be able to rename them within at least the current file.

Support for this will require indexing a symbol's locations within the current file and possibly within its project. We may then use that same index for LSP's various symbol reference functionalities.

Requirements:
1. Need a command-line option, named `--rename-symbol` or the like.
2. It will accept the following parameters:
    1. `--line` := line on which the symbol to rename appears (accepts int param; must be within the respective range)
    2. `--column` := column on which the symbol to rename appears (accepts int param; must be within the respective range)
    3. `--new-name` (or something like that) := what to replace the symbol with (accepts string param; must be valid identifier)
    4. The final, positional parameter will be the path to the file whose symbol should be renamed (as is the current behavior).

**Comment by certik** [comment]
What should be the output --- should it modify the file in-place, or rather return all locations to rename and VSCode does the actual renaming?

**Comment by Pranavchiku** [comment]
Irrespective of the answer we get above, we'll need to identify all the locations to rename, so naive design goes as 

- From `line` and `column` information, using `--lookup-name` we get the name of `symbol`
- Then we iterate over the ASR tree, and store location and symbol table of the places where the name string matches

This solves one part of collecting locations. Now if we wish to replace it in-place:

- To do this, we need to iterate over the stored location and symbol table, change name of existing symbol i.e. delete old name and add new name with same `ASR::symbol_t*`
- Get the asr_owner and iterate over body
- override `visit_Var` to check if symbol name matches with old symbol, if yes replace it with new one

This way we can replace it.

**Comment by dylon** [comment]
> What should be the output --- should it modify the file in-place, or rather return all locations to rename and VSCode does the actual renaming?

Per [this issue](https://github.com/microsoft/language-server-protocol/issues/879), [the specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_rename), and [the VSCode rename event handler](https://github.com/microsoft/vscode-languageserver-node/blob/main/server/src/common/server.ts#L1295), LSP and VSCode expect the server to respond with a list of ranges (starting and ending coordinates, where each coordinate consists of a line and column) consisting of every occurrence of the symbol to rename, including the text to replace each occurrence with; they do not expect the server to edit the document, probably so the changes can be undone by the client. Each instance should adhere to [the TextEdit specification](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textEdit).
