### ISSUE TITLE
ASR: Unify Subroutine/Function

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#543]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/703

There is a lot of code duplication for Function/Subroutine in the LLVM backend, as well as the AST->ASR frontend. I think we should have just one ASR node, called `Function`, and make the `expr? return_var`, if it is not present, it's a subroutine.

**Comment by lucifer1004** [comment]
This seems to have been fixed? @certik 

In C/C++/Julia backends, they are already unified. Searching `visit_Subroutine` in the whole repo gives 

- `ast_to_openmp.cpp`
- `ast_to_src.cpp`
- `ast_body_visitor.cpp`
- `ast_symboltable_visitor.cpp`

I think these are not related to this issue.

**Comment by certik** [comment]
Yes, this has been fixed, now we just use Function.
