### ISSUE TITLE
Continue Compilation flag fails for some errors

### ISSUE THREAD

**Issue by parth121101** [lfortran/lfortran#5463]
I will keep on modifying this list that contains the error tests that does not skip error statements despite of continue-compilation flag.

- [x] tests/errors/int_01.f90
- [x] tests/errors/integer16.f90
- [x] tests/errors/common1.f90
- [x] tests/errors/kind_float_of_int.f90
- [x] tests/errors/kind_invalid_int_of_complex.f90
- [x] tests/errors/kind_invalid_int_of_int.f90
- [x] tests/errors/kind_invalid_int_of_logical.f90
- [x] tests/errors/kind_star_of_complex.f90
- [x] tests/errors/kind_star_of_int.f90
- [x] tests/errors/kind_star_of_logical.f90
- [x] tests/errors/kind_string_of_int.f90
- [x] tests/errors/kind_var_of_int.f90
- [x] tests/errors/kind1.f90
- [x] tests/errors/kind2.f90
- [x] tests/errors/type_casting_01.f90
- [x] tests/errors/type_conflict1.f90
- [x] tests/errors/init1.f90
- [x] tests/errors/program_without_line_01.f90
- [x] tests/errors/program_without_line_02.f90
- [x] tests/errors/program_without_line_03.f90
- [x] tests/errors/program_without_line_04.f90

**Comment by Pranavchiku** [comment]
Nice, if you can send a PR at the same time to fix that would be awesome!

**Comment by parth121101** [comment]
All the tasks of this issue are solved. Closing the issue
