### ISSUE TITLE
Fix the `--continue-compilation` behavior

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#5480]
There are two use cases:
* Report all errors, produce usable ASR (very common, for example for the LSP application)
* continue compilation despite errors (maybe you want to use the ASR to run some passes despite errors, or even create a binary or run it); this might bre useful for LSP as well, maybe you want to be able to run the code even if you are editing some line; this use case is very rare though I think.

I think our `--continue-compilation` option is a good one, as it will simply report an error and continue; so this option will cover both use case above.

Here is how it should behave:
* it should simply continue compilation if there are errors
* it should not imply or change any other option. Currently it implies `--show-asr`, but it should not. If the user requested to run the code, then it should run it, despite errors.

In addition, irrespective of `--continue-compilation`, we need options to:
* [x] just show AST (`--showast`)
* [x] just show ASR (`--showasr`)
* [ ] just do parsing and semantics, report all errors, but do not continue beyond that; do not print AST or ASR; if everything passes without errors, then do not print anything, and return 0 exit code; if there are errors, return non-zero exit code; this option can perhaps be called `--semantics-only`.

In our tests for multiple error messages, we should use `--semantics-only`.

TODO:
* [ ] implement `--semantics-only` and use it in tests
* [ ] make `--continue-compilation` a purely additive option that makes the compilation continue

So we should revert to the original behavior of `--continue-compilation`, however we need the additional `--semantics-only` option to stop the compilation after producing ASR.

**Comment by Pranavchiku** [comment]
I’ll do this. Thanks for opening this!
