### ISSUE TITLE
bug: do not allow declaration of `parameter` variables with `allocatable`/`pointer` attribute

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#5531]
### Minimum Reproducible Example

```fortran
program main
   implicit none
   integer, allocatable, parameter :: v=1
end program
```

### Output
```console
(lf) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran ./examples/example.f90
; ModuleID = 'LFortran'
source_filename = "LFortran"

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  %v = alloca i32*, align 8
  store i32* null, i32** %v, align 8
  store i32 1, i32** %v, align 4
  call void @_lpython_free_argv()
  br label %return

return:                                           ; preds = %.entry
  ret i32 0
}

declare void @_lpython_call_initial_functions(i32, i8**)

declare void @_lpython_free_argv()
asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store i32 1, i32** %v, align 4
 i32*
code generation error: asr_to_llvm: module failed verification. Error:
Stored value type does not match pointer operand type!
  store i32 1, i32** %v, align 4
 i32*


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by kmr-srbh** [comment]
The same issue is also with the `pointer` attribute.

**Comment by kmr-srbh** [comment]
Hello @dsaw! Please go ahead.

If we look at the AST generated by this code using the `--show-ast` option:

```clojure
(base) saurabh-kumar@Awadh:~/Projects/System/lfortran$ lfortran test.f90 --show-ast
(TranslationUnit
    [(Program
        main
        ()
        []
        [(ImplicitNone
            []
            ()
        )]
        [(Declaration
            (AttrType
                TypeInteger
                []
                ()
                ()
                None
            )
            [(SimpleAttribute
                AttrAllocatable
            )
            (SimpleAttribute
                AttrParameter
            )]
            [(v
            []
            []
            ()
            1
            Equal
            ())]
            ()
        )]
        []
        []
    )]
)
```

we notice that `AttrAllocatable` and `AttrParameter` are present together. We need to detect this during variable declaration and throw a semantic error. See `visit_DeclarationUtil()` inside `ast_common_visitor.h` and try to handle this for both `AttrAllocatable` and `AttrPointer`.

Here is the test case for `pointer`:
```fortran
program main
    implicit none
    integer, pointer, parameter :: v => null()
 end program
```

We can consider adding a verification to ASR Verify like we do for `allocatable`, `pointer` conflict, but maybe we can do that later.

**Comment by devsawgrad** [comment]
thanks. I had a query, how can we generate a test reference json like this https://github.com/lfortran/lfortran/pull/1907/files#diff-27f6ba94fff6be69d16b55d5591bac19e551bc664fb70f0d21d1aa6699a167af?  once a test is added that is, would really like to understand the process.

**Comment by dsaw** [comment]
thanks. I had a query. how can we generate a test reference json for comparison like this https://github.com/lfortran/lfortran/pull/1907/files#diff-27f6ba94fff6be69d16b55d5591bac19e551bc664fb70f0d21d1aa6699a167af ? would be helpful to know the process.

**Comment by kmr-srbh** [comment]
Please do `./run_tests.py -u` to create the references.
