### ISSUE TITLE
read for character array

### ISSUE THREAD

**Issue by Euler37** [lfortran/lfortran#5545]
- `lfortran` version
```
LFortran version: 0.42.0
Platform: Linux
LLVM: 19.1.1
Default target: x86_64-conda-linux-gnu
```
lfortran will exceed the character len
- code
```fortran
program main
   implicit none
    character(len=1)::s(2)
    read(*,*)s
    print*,s(1)
    print*,s(2)
end program main
```
``` sh
$ gfortran 1.f90 && ./a.out
ab cd
a
c
$lfortran 1.f90
ab cd
ab
cd
```
 if use `character(len=1)::s` ,it is right

**Comment by kmr-srbh** [comment]
This is the same issue as #4015, but for character arrays. The fix is the same as #4021.

**Comment by kmr-srbh** [comment]
Thanks for reporting this @Euler37. This is the same issue as #4015, but for character arrays. The fix is the same as #4021.

**Comment by Euler37** [comment]
when read from file or keyboard, the len of character will change. If read same variable twice, It will cutoff. Maybe It is related to this issue
```
program main
   implicit none
   character(len=100)::s
   read(*,"(A)")s
   print*,s,len(s)
   read(*,"(A)")s
   print*,s,len(s)
end program main
```
``` sh
$ lfortran 1.f90
123
123    3
1234
12    2
```

**Comment by kmr-srbh** [comment]
> ```fortran
> program main
>    implicit none
>    character(len=100)::s
>    read(*,"(A)")s
>    print*,s,len(s)
>    read(*,"(A)")s
>    print*,s,len(s)
> end program main
> ```
> 
> ```shell
> $ lfortran 1.f90
> 123
> 123    3
> 1234
> 12    2
> ```

Thanks for this @Euler37. This is indeed an issue with formatted read.

> and for previous example
> 
> ```fortran
> program main
>    implicit none
>     character(len=1)::s(2)
>     read(*,*)s
>     print*,s(1),len(s(1))
>     print*,s(2),len(s(2))
> end program main
> ```
> 
> it will show
> 
> ```shell
> ab cd
> ab    2
> cd    2
> ```

This example now works with the changes is #5547.
