### ISSUE TITLE
WASM: Runtime Library

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#555]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/720

Continued from https://gitlab.com/lfortran/lfortran/-/issues/706 

Related to https://gitlab.com/lfortran/lfortran/-/issues/700 

For the `LFortran` `WebAssembly` Backend, we need to get the `runtime library` working, so that one can use functions like sin/cos, etc.

The `runtime library` has two parts:
1. [x] `pure`  part  (we have to package the `.mod` files together with the emscripten compiled LFortran. (https://github.com/lfortran/lfortran/pull/643, https://github.com/lfortran/lcompilers_frontend/pull/37)
2. [x] `impure` part (Implemented in `C`)
    - [x] Add support for `print` function (https://gitlab.com/lfortran/lfortran/-/merge_requests/1794)
    - [x] Add support for `cpu_time` (https://github.com/lfortran/lfortran/pull/641)

**Comment by Shaikh-Ubaid** [comment]
I tried the test cases for 
- `integration_tests/abs_01.f90`
- `integration_tests/abs_02.f90`
- `integration_tests/abs_03.f90`
- `integration_tests/intrinsics_21.f90` // for `modulo()` and `mod()`
- `integration_tests/intrinsics_23.f90` // for `huge()`
- `integration_tests/floor_01.f90`
- `integration_tests/floor_02.f90`
- `integration_tests/floor_03.f90`

at the current live site https://dev.lfortran.org/

They all seem to work. Thus, it seem the `runtime` library works at https://dev.lfortran.org/

Please, could someone possibly share if it is safe to close this issue?

**Comment by certik** [comment]
Nice, great job!

Try this: use the default example and change `dp=8` to `dp=kind(0.d0)`. I get:

<img width="1541" alt="Screen Shot 2022-08-22 at 11 16 25 PM" src="https://user-images.githubusercontent.com/20568/186010955-6d198388-7720-45a1-a259-87fce4b00c8c.png">

Kind of good, but not quite. :)

**Comment by Shaikh-Ubaid** [comment]
Thank you for sharing the bug, Ondrej Sir. We merged a `PR` https://github.com/lfortran/lfortran/pull/657 which should (hopefully) fix the issue. I also submitted a `PR` at https://github.com/lfortran/lcompilers_frontend/pull/40 to update the `lfortran` version/commit.

**Comment by Shaikh-Ubaid** [comment]
>Try this: use the default example and change dp=8 to dp=kind(0.d0). I get:

With the fixes in https://github.com/lfortran/lfortran/pull/657 and https://github.com/lfortran/lcompilers_frontend/pull/40, the latest `lfortran` at https://dev.lfortran.org/ seems to now support it.
![image](https://user-images.githubusercontent.com/43722035/186198654-be80f984-7269-4729-965f-7137484736f2.png)

**Comment by Shaikh-Ubaid** [comment]
>integration_tests/abs_01.f90
integration_tests/abs_02.f90
integration_tests/abs_03.f90
integration_tests/intrinsics_21.f90 // for modulo() and mod()
integration_tests/intrinsics_23.f90 // for huge()
integration_tests/floor_01.f90
integration_tests/floor_02.f90
integration_tests/floor_03.f90


I tested these examples again at https://dev.lfortran.org/. They all seem to work. Thus, it seems the runtime library works at https://dev.lfortran.org/

Please, could someone possibly share if this issue is safe to close?

**Comment by certik** [comment]
I tested this by hand as well and I think everything is indeed fixed! Amazing.

The parts of the runtime library that do not work are all calls into C, however I am guessing just providing the appropriate JavaScript implementations might fix it. We will eventually use pure Fortran implementations of trigonometric functions like sin(x). But for now we can either implement them in JavaScript, or figure out how to compile the C part of the runtime library using Clang and somehow link it.
