### ISSUE TITLE
Pass location information of function / subroutine / program / module name to ASR

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5558]
With `--rename-symbol` we intend to return all occurrences of a symbol and when it comes to `Unit` i.e. `function / subroutine / program / modules / etc ` the location information contains entire start line and end line but we only need the `id`. This was discussed as a problem before and raised at https://github.com/lfortran/lfortran/issues/5524. A potential solution is to pass location information of `id` to ASR, for example:

```fortran
function xyz
...
end function xyz
```

We can store location of `xyz` in AST and then pass it to ASR.

**Comment by certik** [comment]
@Pranavchiku what needs to be done to finish this?

**Comment by Pranavchiku** [comment]
I think we can close this with reference to #5602
