### ISSUE TITLE
Fixed Form END statement parsing bug

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#558]
*Original issue*: https://gitlab.com/lfortran/lfortran/-/issues/725

I think this might be a bug with the Fixed Form parser of LFortran.

### Source
```fortran
C { This is comment }
       END
```

### Command
```sh
lfortran --fixed-form --show-ast --indent tmp.f
```

### Output
```log
input:1:5 syntax error: end of file is unexpected here
 END
    ^
Parsing error: syntax error
```

## Additional Comments

I think the `.f` is not automatically associated with Fixed Form, thus removing `--fixed-form` will cause the source file to be parsed by the Free Form part of lfortran. 

## Info

LFortran version: 0.14.0
Platform: Linux
Default target: x86_64-unknown-linux-gnu

**Comment by konradha** [comment]
This works fine now.
