### ISSUE TITLE
(PRIMA) use actual function instead of its type in `m_type_declaration` of Variable

### ISSUE THREAD

**Issue by jinangshah21** [lfortran/lfortran#5603]
It is just one step ahead of #5500 

MRE : 
```fortran
module procedure_07_module
contains
    subroutine cb(x)
        implicit none
        integer, intent(in), optional :: x(:)
    end subroutine cb

    subroutine calfun(x)
        implicit none
        integer, intent(in), optional :: x(:)
        logical :: y
        y = present(x)
        if (y) error stop
    end subroutine calfun
end module procedure_07_module

program procedure_07
    use procedure_07_module
    call temp(calfun)
contains
    subroutine temp(call_back)
        implicit none
        procedure(cb) :: call_back
        call call_back()   
    end subroutine temp
end program procedure_07
```

LFortran Error : 
```console
code generation error: Subroutine code not generated for 'cb'
Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
```

**Comment by jinangshah21** [comment]
ASR :
```fortran
call_back:
        (Variable
        14
        call_back
        []
        Unspecified
        ()
        ()
        Default
        (FunctionType
        [(Array
        (Integer 4)
        [(()
        ())]
        DescriptorArray
        )]
        ()
        Source
        Implementation
        ()
        .false.
        .false.
        .false.
        .false.
        .false.
        []
        .false.
        )
        13 cb            !!! Here instead of cb it should be calfun as we are using m_type_declaration in function call
        Source
        Public
        Required
        .false.
        )
```

**Comment by Pranavchiku** [comment]
Do you know how to fix it?

**Comment by jinangshah21** [comment]
I want to if we have to store 'cb' Or `calfun` in `m_type_declaration`.
If we want cb to store then in ASR we need to add ExternalSymbol for cb which is currently not present as it is only used in type declaration.

**Comment by Pranavchiku** [comment]
Let's drill down, if you look at `pass_18_array_op`, you'll find `cb` as an `ExternalSymbol` ( will refer as `cb_program_es` ) pointing to `cb` present inside module ( will refer as `cb_module` ) and `call_back` in `temp` having `cb_program_es` as `m_type_declaration`

After, `pass_array_by_data` on looking at `pass_19_array_by_data`

- `cb_module` is removed and inplace `cb_integer____0` is added
- As a consequence `cb_program_es` is removed ( Note: it should have not removed it, instead pointed to `cb_integer____0`)
- The reason it fails is because `call_back` in `temp` still points to old `cb_program_res` which is there in memory but not rendered as it is removed from `SymbolTable` map. So you can access the pointer hence it does not segfault but can't see it. 


If you fix the second point in `pass_array_by_data`, this issue will be fixed.

**Comment by jinangshah21** [comment]
Ok I will look into it. Thanks!

**Comment by jinangshah21** [comment]
I have done changes and now no error is popping. But there is one issue : `call call_back()` makes a function call to `cb` but it should be made to `calfun` as calfun is passed in argument. `cb` is just type of `calfun`.

**Comment by Pranavchiku** [comment]
I think `cb` will be an `ExternalFunction`, you then just need to get past external. I have not looked at ASR though.

**Comment by jinangshah21** [comment]
> I think `cb` will be an `ExternalFunction`, you then just need to get past external. I have not looked at ASR though.

What I want to say is in above example when we do call `call_back()` `calfun` should be called instead of `cb`. But currently `cb` is called.

**Comment by Pranavchiku** [comment]
```diff
diff --git a/src/libasr/pass/transform_optional_argument_functions.cpp b/src/libasr/pass/transform_optional_argument_functions.cpp
index 049cadf95..84bced39e 100644
--- a/src/libasr/pass/transform_optional_argument_functions.cpp
+++ b/src/libasr/pass/transform_optional_argument_functions.cpp
@@ -336,6 +336,9 @@ bool fill_new_args(Vec<ASR::call_arg_t>& new_args, Allocator& al,
     ASR::symbol_t* func_sym = ASRUtils::symbol_get_past_external(x.m_name);
     if (ASR::is_a<ASR::Variable_t>(*x.m_name)) {
         // possible it is a `procedure(cb) :: call_back`
+
+        // check if `cb` is changed
+        // if yes, just change the FunctionType ( type modified by this pass ) as type
         ASR::Variable_t* v = ASR::down_cast<ASR::Variable_t>(x.m_name);
         LCOMPILERS_ASSERT(ASR::is_a<ASR::FunctionType_t>(*v->m_type));
         func_sym = ASRUtils::symbol_get_past_external(v->m_type_declaration);
```

**Comment by jinangshah21** [comment]
> ```diff
> diff --git a/src/libasr/pass/transform_optional_argument_functions.cpp b/src/libasr/pass/transform_optional_argument_functions.cpp
> index 049cadf95..84bced39e 100644
> --- a/src/libasr/pass/transform_optional_argument_functions.cpp
> +++ b/src/libasr/pass/transform_optional_argument_functions.cpp
> @@ -336,6 +336,9 @@ bool fill_new_args(Vec<ASR::call_arg_t>& new_args, Allocator& al,
>      ASR::symbol_t* func_sym = ASRUtils::symbol_get_past_external(x.m_name);
>      if (ASR::is_a<ASR::Variable_t>(*x.m_name)) {
>          // possible it is a `procedure(cb) :: call_back`
> +
> +        // check if `cb` is changed
> +        // if yes, just change the FunctionType ( type modified by this pass ) as type
>          ASR::Variable_t* v = ASR::down_cast<ASR::Variable_t>(x.m_name);
>          LCOMPILERS_ASSERT(ASR::is_a<ASR::FunctionType_t>(*v->m_type));
>          func_sym = ASRUtils::symbol_get_past_external(v->m_type_declaration);
> ```

I think our current logic is correct because we need to fill args of SubroutineCall with `__libasr_created_variable_`. Also FunctionType is also correct in subsequent passes. Now we need to figure out how `calfun` can be called in runtime instead of `cb`.  I think we used `m_type_declaration` for function variable where we need to look.

**Comment by jinangshah21** [comment]
```program
module procedure_07_module

contains
    subroutine calfun(x)
        implicit none
        integer, intent(in), optional :: x(:)
        logical :: y
        y = present(x)
        if (y) error stop
        print *, y
    end subroutine calfun
end module procedure_07_module

program procedure_07
    use procedure_07_module
    call temp(calfun)
contains
    subroutine cb(x)
        implicit none
        integer, intent(in), optional :: x(:)
    end subroutine cb
    subroutine temp(call_back)
        implicit none
        procedure(cb) :: call_back
        call call_back()   
    end subroutine temp
end program procedure_07
```

Consider Above program here I just made cb as direct Function instead of ExternalSymbol and for this program calfun which we want.

**Comment by jinangshah21** [comment]
I have figured out solution. Will open PR soon.
