### ISSUE TITLE
Bug : calculating the size for array based on kind=8 variable fails

### ISSUE THREAD

**Issue by assem2002** [lfortran/lfortran#5646]
MRE 
```fortran
PROGRAM subroutines_12

    IMPLICIT NONE
    
    INTEGER(8) :: nang = 2
    
    CALL my_subroutine
    
    CONTAINS
    
        SUBROUTINE my_subroutine
    
            INTEGER, DIMENSION(nang) :: fxhv
    
        END SUBROUTINE my_subroutine
    
    END PROGRAM subroutines_12
    
```

```console
; ModuleID = 'LFortran'
source_filename = "LFortran"

@subroutines_12.nang = internal global i64 2

define i32 @main(i32 %0, i8** %1) {
.entry:
  call void @_lpython_call_initial_functions(i32 %0, i8** %1)
  call void @my_subroutine()
  call void @_lpython_free_argv()
  br label %return

return:                                           ; preds = %.entry
  ret i32 0
}

define void @my_subroutine() {
.entry:
  %0 = load i64, i64* @subroutines_12.nang, align 4
  %1 = mul i32 1, i64 %0
  %2 = mul i32 %1, 4
  %3 = call i8* @_lfortran_malloc(i32 %2)
  %4 = bitcast i8* %3 to i32*
  br label %return

return:                                           ; preds = %.entry
  call void @_lfortran_free(i8* %3)
  ret void
}

declare i8* @_lfortran_malloc(i32)

declare void @_lfortran_free(i8*)

declare void @_lpython_call_initial_functions(i32, i8**)

declare void @_lpython_free_argv()
asr_to_llvm: module failed verification. Error:
Both operands to a binary operator are not of the same type!
  %1 = mul i32 1, i64 %0

code generation error: asr_to_llvm: module failed verification. Error:
Both operands to a binary operator are not of the same type!
  %1 = mul i32 1, i64 %0



Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.

```

**Comment by saikarna913** [comment]
@assem2002, could you please clarify where this issue is originating from? I'm interested in understanding where the code generation takes place. I'd also like to learn about the file structure of this repo, including the lexer, parser, and semantic analysis components. Additionally, I would appreciate guidance on how to debug in LFortran, as I'd like to get a strong start as a new contributor.

**Comment by assem2002** [comment]
@saikarna913  refer to this comment https://github.com/lfortran/lfortran/issues/5646#issuecomment-2536547615. also watch this tutorial it's a good video to watch for a start off.
For the current issue we have incompatible LLVM `mul` operation because of the types of the operands, to know where does that results from you have to trace the LLVM IR resulting, and try to minimze the source code or even comment and uncomment pieces till you find the piece that results in the error. You then go to `asr_to_llvm.cpp` to fix the issue, may be you can first use print statement if you're not sure about the function that results in the error.
This issue actually has a fix in this PR https://github.com/lfortran/lfortran/pull/5648
