### ISSUE TITLE
address comments left for '_lfortran_formatted_read' in #5583

### ISSUE THREAD

**Issue by gxyd** [lfortran/lfortran#5664]
## Description

There were a [few review comments left](https://github.com/lfortran/lfortran/pull/5583#pullrequestreview-2486963113), and all of those comments should be addressed and the conversation be resolved.

I'm opening the issue, so we don't forget about those comments

cc: @certik @kmr-srbh

**Comment by kmr-srbh** [comment]
@gxyd thanks for opening up an issue. I have been unable to devote time this week, I will try to address this soon.

**Comment by gxyd** [comment]
Yup, I know you are unavailable this week, that's why opened this issue, feel free to assign this to yourselves 😃
