### ISSUE TITLE
Fix a issue with Print in MLIR backend

### ISSUE THREAD

**Issue by Thirumalai-Shaktivel** [lfortran/lfortran#5693]
There is a issue here in `builder->getStringAttr(fmt))`,

Consider an example:
```fortran
program expr2
integer :: x

x = (2+3)*5
print *, x
write(*,*) x

end program
```
For which, I get the output as,
```console
$ lfortran examples/expr2.f90 --backend=mlir  
 25
 25
 -28655536
```
Where, ` -28655536` shouldn't be printed

The reason is, the global string `printf_fmt_2` and `printf_fmt_1` value doesn't have a null char `\00` at the end.
```mlir
module @LFortran {
  llvm.mlir.global private @printf_fmt_2(" %d\0A")
  llvm.func @printf(!llvm.ptr<i8>, ...)
  llvm.mlir.global private @printf_fmt_1(" %d\0A")
  llvm.func @main(%arg0: !llvm.ptr<i8>, ...) -> i32 {
  // [...]
  }
}
```

I will submit a new PR to fix this.

_Originally posted by @Thirumalai-Shaktivel in https://github.com/lfortran/lfortran/pull/5691#discussion_r1884870787_

**Comment by saikarna913** [comment]
@Thirumalai-Shaktivel can i work on this issue

**Comment by Thirumalai-Shaktivel** [comment]
Thank you, but I already started working this.
Please choose some other issue.
