### ISSUE TITLE
bug: declaring a variable with initial value makes it a `save` variable

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#5714]
### Minimal Reproducible Example

```fortran
program main
   integer :: x=2
end program
```

### ASR

```clojure
(TranslationUnit
    (SymbolTable
        1
        {
            main:
                (Program
                    (SymbolTable
                        2
                        {
                            x:
                                (Variable
                                    2
                                    x
                                    []
                                    Local
                                    (IntegerConstant 2 (Integer 4) Decimal)
                                    (IntegerConstant 2 (Integer 4) Decimal)
                                    Save
                                    (Integer 4)
                                    ()
                                    Source
                                    Public
                                    Required
                                    .false.
                                )
                        })
                    main
                    []
                    []
                )
        })
    []
)
```

This happens during AST -> ASR as the AST for this program does not contain the `AttrSave` attribute.

**Comment by gxyd** [comment]
I referred the J3 documentation for `SAVE` attribute, which says:
> The SAVE attribute specifies that a local variable of a BLOCK construct retains its association status, allocation status, definition status, and value after termination of the construct unless it is a pointer and its target becomes undefined (19.5.2.5(7)). If the BLOCK construct is within a subprogram the variable is shared by all instances (15.6.2.4) of the subprogram.

in the MRE you provided, we've:
* the variable x is a global variable.
* variable `x` is allocated for it's lifetime, meaning that it retains it's state until the end of the program, and it retains it's value throughout the execution of the program.

So, *implicitly* it should behave like a variable with *SAVE* attribute enabled, and I don't see this to be an issue.

**Comment by kmr-srbh** [comment]
@gxyd @Pranavchiku thanks for the clarification.
