### ISSUE TITLE
test: fix flaky behavior of integration test `matrix_02_matmul.f90` with `--fast` on `fortran` backend

### ISSUE THREAD

**Issue by kmr-srbh** [lfortran/lfortran#5749]
```shell
50/383 Test  #50: matrix_02_matmul_FAST ............***Failed    0.00 sec
Note: The following floating-point exceptions are signalling: IEEE_DENORMAL
ERROR STOP 
```

As seen at: https://github.com/lfortran/lfortran/actions/runs/12375675421/job/34541033706?pr=5745#annotation:11:4138

**Comment by gxyd** [comment]
It's reported once here as well: https://github.com/lfortran/lfortran/issues/5724, maybe have a single issue with all the information?

**Comment by kmr-srbh** [comment]
@gxyd yes let's have only one issue. Closing this as duplicate.
