### ISSUE TITLE
LFortran returns the location of a symbol's declaration instead of its definition

### ISSUE THREAD

**Issue by dylon** [lfortran/lfortran#5760]
For variables, LFortran returns the locations of their declarations instead of their definitions. Consider the following snippet:

```fortran
program expr2
  implicit none

  integer :: program

  program = (2+3)*5
  print *, program

end program

```

LFortran returns the following:

```shell
lfortran --show-document-symbols /var/tmp/expr2.f90 | jq
[
  {
    "kind": 12,
    "location": {
      "range": {
        "start": {
          "character": 1,
          "line": 0
        },
        "end": {
          "character": 11,
          "line": 8
        }
      },
      "uri": "uri"
    },
    "name": "expr2"
  },
  {
    "kind": 13,
    "location": {
      "range": {
        "start": {
          "character": 14,
          "line": 3
        },
        "end": {
          "character": 20,
          "line": 3
        }
      },
      "uri": "uri"
    },
    "name": "program"
  }
]
```

If you consider the location of the `program` symbol, it gives the range of characters representing its identifier in its declaration. Instead, it would be preferable if it would return the range of characters representing its definition `program = (2+3)*5`:

```json
  {
    "kind": 13,
    "location": {
      "range": {
        "start": {
          "character": 3,
          "line": 5
        },
        "end": {
          "character": 19,
          "line": 5
        }
      },
      "uri": "uri"
    },
    "name": "program"
  }
```

We could consider returning the locations of both a symbol's declaration and definition. That would be useful information, too.

**Comment by certik** [comment]
The symbol `program` is declared on the line `integer :: program`, which it seems to return, so this seems correct?

If you want it to return all usage of the `program` variable, then it would return the two lines:
```
  program = (2+3)*5
  print *, program
```

**Comment by Pranavchiku** [comment]
The reason `--show-document-symbols` give is:
- `program` is symbol inside `TranslationUnit`
- `program` is integer variable inside `expr2`

**Comment by certik** [comment]
I think the current behavior is correct, so I am going to close this issue for now. @dylon reopen it if you think this LFortran should change.
