### ISSUE TITLE
LSP with modules

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5772]
With https://github.com/lfortran/lfortran-lsp/pull/44

* [ ] LSP shall generate a `.mod` file as soon as we open a module file so that it can be used by other programs ( https://github.com/lfortran/lfortran-lsp/pull/44 )
* [ ] Fix the location information, currently it points to line 1, column 1

> a.f90

```fortran
subroutine add()
end subroutine
program expr2
use module_expr2
implicit none
integer :: x
x = (2+3)*5
print *, x, xy
call sub()
call add()
end program

```

> b.f90

```fortran
module module_expr2
    implicit none
    integer :: xy, yz
contains
subroutine sub()
    implicit none
end subroutine
subroutine sub2()
    implicit none
end subroutine
end module module_expr2
```

Ideally, if I click on `b.f90`, it shall generate `module_expr2.mod` file which then opening `a.f90` shall be linked automatically  (https://github.com/lfortran/lfortran-lsp/pull/44)

Right now, I need to first do `lfortran -c b.f90` and then open `a.f90`

On hover to elements of module, it returns `line=1, column=1` location

<img width="405" alt="image" src="https://github.com/user-attachments/assets/8e1ede88-10f4-460b-8cb6-3047ad8d74a0" />

**Comment by certik** [comment]
The automatic generation of `.mod` file and automatic linking is problematic, see my comments in https://github.com/lfortran/lfortran-lsp/pull/44. Let's not do that right now. The right solution there is to teach LFortran how to build the project, but that has to be done differently. For pure Fortran projects it might be enough to generate `.mod` files for every compiled file (whether a module or not) and record all compiler options. However, for mixed complex projects that might not be enough if the build system does some operation that we can't see.

But the location information we definitely have to fix.

**Comment by Pranavchiku** [comment]
If I use the following diff:

```diff
diff --git a/src/libasr/lsp.cpp b/src/libasr/lsp.cpp
index 374fc734f..725be8568 100644
--- a/src/libasr/lsp.cpp
+++ b/src/libasr/lsp.cpp
@@ -158,6 +158,9 @@ void populate_symbol_lists(T* x, LCompilers::LocationManager lm, std::vector<LCo
         uint32_t first_column;
         uint32_t last_column;
         std::string filename;
+        std::cout<<"sym: "<<a.first<<std::endl;
+        std::cout<<"loc.first: "<<a.second->base.loc.first<<std::endl;
+        std::cout<<"loc.last: "<<a.second->base.loc.last<<std::endl;
         lm.pos_to_linecol(a.second->base.loc.first, first_line,
             first_column, filename);
         lm.pos_to_linecol(a.second->base.loc.last, last_line,
```

and run `a.f90`, I get:

```console
% lfortran a.f90 --show-document-symbols
....
sym: sub
loc.first: 0
loc.last: 0
sym: sub2
loc.first: 0
loc.last: 0
sym: xy
loc.first: 0
loc.last: 0
sym: yz
loc.first: 0
loc.last: 0
sym: module_expr2
loc.first: 0
loc.last: 0
sym: sub
loc.first: 0
loc.last: 0
sym: sub2
loc.first: 0
loc.last: 0
sym: xy
loc.first: 0
loc.last: 0
....
```

It is evident that we do not `deserialize` the location information correctly.

**Comment by Pranavchiku** [comment]
This is weird, even after storing location information and deserializing it correctly, it gives `0`.

**Comment by certik** [comment]
We need to debug it.

**Comment by Pranavchiku** [comment]
Woah, here you go:

```cpp
    asr_t* deserialize_Module() {
        size_t n_dependencies; // Sequence
        Location loc;
        loc.first = self().read_int64();
        loc.last = self().read_int64();
        loc.first = 0; ------------------------------- !!!
        loc.last = 0; ------------------------------- !!!
        uint64_t m_symtab_counter = self().read_int64();
```

**Comment by Pranavchiku** [comment]
I am using this to write down and iterate on design:

Brief: struct `LocationManager` contains all information we need, and in case of multiple files we wish to serialise `LocationManager` which contains `strings`, `boolean` and `vectors` of `uint32_t` which can be serialised and loaded during deserialisation. After deserialisation we need to fetch existing `LocationManager` struct and merge new one with this. To merge we need to set `offset` which is nothing but `pos + 1` of last file.

Detailed:

- Pass `LCompilers::LocationManager lm` to `save_mod_files` and pass it to `save_asr` where before writing `Full ASR:` write entire `LocationManager`.
- By step 1, we have location manager in a serialized format, next is to deserialize it
-  Pass `lm` to `ast_to_asr` and with every `ASRUtils::load_module`, we invoke `find_and_load_module` and eventually `load_modfile`, in `load_serialised_asr`, deserialize `lm` struct and merge it with existing `LocationManager` passed as arguments. We need not to worry about duplication, as `load_module` only loads module once. 


With this we will have the two structs merged. Now the next question is for `call sub()` the `pos` will be corresponding to file `a.f90`, and thereby `index = bisection(file_ends, pos)` gives us index corresponding to `a.f90` and not module file. Even if we have information, we are not able to identify if `sub()` belongs to which `index`.

```fortran
subroutine add()
end subroutine
program expr2
use module_expr2
implicit none
integer :: x
x = (2+3)*5
print *, x, xy
call sub()
call add()
end program
```

cc @certik

**Comment by certik** [comment]
Yes, that's the right design. There will be some corner cases, like big project reusing modules, but we can probably just keep duplicating the files in the location manager for now, that should work (I think). We'll iron out this issues as we go.
