### ISSUE TITLE
ES format misbehaving

### ISSUE THREAD

**Issue by harperjf** [lfortran/lfortran#5793]
This 2-line program compiles and runs with ifx or ifort,  printing 3.333333333333333+199 which I believe is correct. But it gives wrong output from gfortran and a strange error message from lfortran 0.42.0:
```
  print "(ES0.15)", 1/3.0d-200
  end program
```
Output from lfortran:
```
*** stack smashing detected ***: terminated
Aborted (core dumped)
```
Output from gfortran, which should have omitted the letter E:
```
3.333333333333333E+199
```

**Comment by certik** [comment]
This was closed in favor of https://github.com/lfortran/lfortran/issues/5794.
