### ISSUE TITLE
location information of `Var` in `RealBinOp`  is incorrect

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#5833]
```fortran
module time_module_xx
  IMPLICIT NONE
  PUBLIC
  REAL :: tparset_ = 0.0
  REAL :: wtime_ = 0.0
END module time_module_xx


module plib_module_xx
use time_module_xx, only: wtime_
PUBLIC
INTEGER :: iproc = 0
INTEGER :: root = 0
INTEGER :: pinit = 0
INTEGER :: pcomm_set = 0
end module

PROGRAM snap_main
  USE time_module_xx, ONLY: tparset_

  USE plib_module_xx, ONLY: pinit,         &
    pcomm_set
  tparset_ = tparset_ + 1.0
END PROGRAM snap_main
```

```console
% lfortran a.f90 --line=23 --column=17 --lookup-name
[]
```

If I use the following diff it works:

```diff
diff --git a/a.f90 b/a.f90
index a8a3493a2..0e060bda8 100644
--- a/a.f90
+++ b/a.f90
@@ -18,7 +18,6 @@ end module
 PROGRAM snap_main
   USE time_module_xx, ONLY: tparset_
 
-  USE plib_module_xx, ONLY: pinit,         &
-pcomm_set
+  USE plib_module_xx, ONLY: pinit, pcomm_set
   tparset_ = tparset_ + 1.0
 END PROGRAM snap_main
```

**Comment by Pranavchiku** [comment]
Is this related to parser? @certik

**Comment by certik** [comment]
I see. The `&` causes there to be an extra remapping in the LocationManager, which maybe you are not calling when converting from linear location to file+line+column? You can check if the parser is working correctly by making a typo and see if you get the correct error message. I think it works, so I am guessing maybe a bug in LSP.

**Comment by Pranavchiku** [comment]
Here is a spelling mistake causing `Variable xx not declared` error:

<img width="615" alt="image" src="https://github.com/user-attachments/assets/05684ef0-a6c1-4365-952d-a825e58ca862" />

**Comment by Pranavchiku** [comment]
```fortran
  USE plib_module_xx, ONLY: pinit,         &
    pcomm_set
```
creates gives incorrect location information. I think this is related to parser parsing loc information.

**Comment by Pranavchiku** [comment]
I think this has to do something with `input` and `output` mapping.
