### ISSUE TITLE
Unable to run integration_tests

### ISSUE THREAD

**Issue by pjh40** [lfortran/lfortran#5865]
On main (SHA b99ee2dd97d5207ce), I get a bunch of errors in the integration tests of the form:
```
[  0%] Building Fortran object CMakeFiles/program_cmake_01.dir/program_cmake_01.f90.o
semantic error: The `emit_debug_line_column` is not enabled; please use the `--debug-with-line-column` option to get the correct location information


Note: Please report unclear, confusing or incorrect messages as bugs at
https://github.com/lfortran/lfortran/issues.
make[2]: *** [CMakeFiles/program_cmake_01.dir/build.make:78: CMakeFiles/program_cmake_01.dir/program_cmake_01.f90.o] Error 5
make[1]: *** [CMakeFiles/Makefile2:3966: CMakeFiles/program_cmake_01.dir/all] Error 2
make: *** [Makefile:101: all] Error 2
Command failed.
```

Did I miss an environment change?  macOS build.

**Comment by Thirumalai-Shaktivel** [comment]
I think it's the problem with CMake. It adds `-g` to the default option.
Which version, do you have?

**Comment by pjh40** [comment]
cmake version 3.31.2

**Comment by Thirumalai-Shaktivel** [comment]
In the CI, we use the version: cmake=3.29.1
and I have `cmake version 3.26.4`

So, try to downgrade the version. Maybe that would fix the issue?

**Comment by pjh40** [comment]
Yes, downgrading to 3.29.1 allowed me to run the tests again.  Thank you!

**Comment by certik** [comment]
We'll have to figure out how to do it, I opened up an issue for it: https://github.com/lfortran/lfortran/issues/5867.
