### ISSUE TITLE
WASM: Future Prospects

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lfortran/lfortran#597]
- We are currently building `lfortran` to `wasm` in `debug` type.
    - As previously discussed, ideally it should be in `release` type (for speed). https://github.com/lfortran/lfortran/issues/1240
- ~Currently, the `runtime` library is not supported at `dev.lfortran.org`~ (https://github.com/lfortran/lfortran/pull/643, https://github.com/lfortran/lfortran/pull/657)
- CI: Testing NodeJS version compare fix/make-robust
    - The statement `string(COMPARE GREATER_EQUAL "${WASM_EXEC_VERSION}" "v16.0.0" IS_NODE_ABOVE_16)` in `integration_tests/CMakeLists.txt` can/might return wrong/undesired result when the `node` version is between (around) `v2.0.0` to `<=` `v9.x.x`.
- ~Add Bitwise operators~
- Use passes (ImpliedDoLoop and others) for arrays (https://github.com/lcompilers/lpython/issues/1483)
    - This could hopefully support operations involving arrays.
- ~Verify preamble in wasm decoding~ (https://github.com/lfortran/lfortran/pull/631)
    - ~During `wasm` to `wat` conversion, we currently skip the first eight bytes of `wasm` (as they contain the `magic` number and `wasm` version). Ideally, we should check/verify these eight bytes and return/exit with an error.~
- Auto-generating `wasm_to_wat.h` using script
- Pass `wasm_bytes` stream from `C++` to `JavaScript` using Heap. That is Heap Method for accessing `uint8_t* wasm_bytes`.
    - To pass bytes from `lfortran.wasm` to the `JavaScript` frontend for execution, we construct a string from the bytes (since, few attempts to pass bytes directly did not succeed, where as passing strings was successful).
- The current `wasm_to_wat.cpp`  might/can parse `wasm` with sections in any (random) order. https://github.com/lcompilers/lpython/issues/1486
    - As per the `wasm` docs, it seems that the different sections in `wasm` should/must appear as per the increasing order of their section ids (I guess, custom sections might be an exception). We should possibly try to generate error if the sections in the `wasm` are not in proper/expected order.
- Use/Provide `WASI` Environment for executing generated `wasm` (https://github.com/lcompilers/lpython/issues/1461)
- Support `C` `runtime` library in the `LLVM` based `WASM` Backend. https://github.com/lcompilers/lpython/issues/1413
- WASM: RuntimeError: memory access out of bounds (https://github.com/lfortran/lfortran/issues/658).

**Comment by Shaikh-Ubaid** [comment]
Related: https://github.com/lfortran/lfortran/issues/589

**Comment by certik** [comment]
Closing in favor of https://github.com/lcompilers/lpython/issues/1485. All items are either fixed, or we created issues for them (in either LPython or LFortran) and are tracking it in #1485.
