### ISSUE TITLE
`include` is not supported

### ISSUE THREAD

**Issue by kargl** [lfortran/lfortran#605]
make
~/tmp/junk/bin/lfortran -c --no-warnings pfftm/pfftm.f90
semantic error: Dummy argument 'trigs' not defined
  --> pfftm/pfftm.f90:43:7 - 47:1
   |
43 |          subroutine sinitpfft(trigs, n, n2, n3, n5)
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^...
...
   |
47 |    
   | ...^ 

The relevant code is 

      subroutine sinitpfft(trigs, n, n2, n3, n5)
         integer, parameter :: knd = m90_sngl
         include 'initpfft.inc'
      end subroutine sinitpfft

where the first few lines of `initpfft.inc` are

`integer, intent(in) :: n, n2, n3, n5`
`real(knd), intent(out) :: trigs(2*(2**n2+3**n3+5**n5))`

So, trigs is declared.

**Comment by certik** [comment]
Thanks @kargl for reporting it. I think we just fixed it.

**Comment by kargl** [comment]
Thanks.  I keep an eye of lfortran progress.  This is good step forward in compiling my math library.  I'll give it a spin in the next few weeks.

**Comment by certik** [comment]
Perfect. LFortran should be able to parse your project to AST now, and it will probably still have some issues with semantics, but if you report all errors that you encounter, we'll eventually fix it.
