### ISSUE TITLE
Semantic error : Function 'alnorm' was not found or not implemented yet( if it is intrinsic)

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#607]
while compiling ```spearman.f``` using lfortran, I got the following semantic error, I can try to solve this if provide the stack trace, but it is currently not working on my device.
```
(lf) pranavchiku@pranavchiku-Yoga-Slim-7-14IIL05:~/lfortran$ ./src/bin/lfortran --show-asr --fixed-form --implicit-typing ~/scipy/scipy/stats/statlib/spearman.f --show-stacktrace
Traceback (most recent call last):
semantic error: Function 'alnorm' not found or not implemented yet (if it is intrinsic)
  --> /home/pranavchiku/scipy/scipy/stats/statlib/spearman.f:75:33
   |
75 |       prho = u / exp(y / two) + alnorm(x, .true.)
   |                                 ^^^^^^^^^^^^^^^^^ 


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by certik** [comment]
See also https://github.com/lfortran/lfortran/pull/154#issuecomment-1214289747.

For `alnorm`, we have to:

* [ ] add `--allow-implicit-interface` lfortran flag
* [ ] with this flag, create an implicit interface (that is, explicit in ASR, but not present in the source code) to `alnorm` from the way it is called, so it will be something like `real function alnorm(x, l)`, where `x` is real and `l` is logical. I am guessing the result is `real`, possibly using the fact that `alnorm` is implicitly typed, so it starts with `a` so it's a real.

We can figure out the details as we go. If we do the interface, then I think that will already work with our LLVM backend.

**Comment by Pranavchiku** [comment]
I should, execute it 
```
./src/bin/lfortran --show-asr --fixed-form --implicit-typing --allow-implicit-interface ~/scipy/scipy/stats/statlib/spearman.f 
```
like this right?

**Comment by Pranavchiku** [comment]
On executing this I get the following error
```
The following argument was not expected: --allow-implicit-interface
Run with --help for more information.
```

**Comment by certik** [comment]
@Pranavchiku yes, we have to implement this according to the TODO list at https://github.com/lfortran/lfortran/issues/607#issuecomment-1217960923.

**Comment by Pranavchiku** [comment]
okay, how can I add that flag, I mean any particular file associated to it wherein I can perform that?

**Comment by certik** [comment]
You have to open `src/bin/lfortran.cpp` and see how other compiler options are handled, and just add this one. Add it to `CompilerOptions` (just see how `--implicit-typing` is handled and do exactly the same). But then the hard part is to go into the appropriate place in AST->ASR which is returning the above error, and then check if this compiler option is set. If it is, then you create that interface as described above. If it is not set, then you return an error as it does now.

**Comment by Pranavchiku** [comment]
on it!

**Comment by Pranavchiku** [comment]
@certik , the error will be returned from ```src/bin/lfortran.cpp``` file right?

**Comment by certik** [comment]
You keep the error as is, but you add a branch that does not fail if `----allow-implicit-interface` is passed.

**Comment by Pranavchiku** [comment]
I am actually trying to print, some manual output to check if it is coming to this line or not, any suggestions?

**Comment by Pranavchiku** [comment]
Okay, so ig ```alnorm``` is not implemented in the file ```src/bin/lfortran/sematics/comptime_eval.h```

[comptime_eval.h](https://github.com/lfortran/lfortran/blob/main/src/lfortran/semantics/comptime_eval.h#L64)
