### ISSUE TITLE
Translation of documentation on docs.lfortran.org

### ISSUE THREAD

**Issue by awvwgk** [lfortran/lfortran#613]
I haven't found any useful resources to provide localized documentation using mkdocs so far. There is the possibility to translate themes, as well as cross-linking between localized versions of the documentation:

- https://www.mkdocs.org/user-guide/localizing-your-theme/
- https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/

It explicitly states

> Translations only apply to text contained within a theme's template, such as "next" and "previous" links. The Markdown content of a page is not translated. If you wish to create multilingual documentation, you need to combine theme localization with a third-party internationalization/localization plugin.

There is a discussion from 2015 at https://github.com/mkdocs/mkdocs/issues/617, which resolved recently for mkdocs. The recommended way for localizing pages is to find a suitable plugin, which is quite similar to the situation we had at the Fortran-lang webpage (see https://github.com/fortran-lang/fortran-lang.org/issues/197).

A list of localization plugins is available at https://github.com/mkdocs/mkdocs/wiki/MkDocs-Plugins#internationalization--localization, here is a selection:

- https://github.com/mondeja/mkdocs-mdpo-plugin (po files, early stage)
- https://gitlab.com/mkdocs-i18n/mkdocs-i18n (full page replacement)
- https://github.com/ultrabug/mkdocs-static-i18n (full page replacement)

---

If it turns out to be unfeasible to keep mkdocs and support translations (as with jekyll and i18n support for the fortran-lang.org), there seems to be a material based sphinx theme (https://bashtage.github.io/sphinx-material/) which would be similar to the currently used theme with mkdocs. Thanks to @henilp105's great work on the [Fortran-lang webpage](https://fortran-lang.github.io/webpage/en/index.html), we already have a showcase what is possible with sphinx and MyST markdown.

**Comment by certik** [comment]
Yes, we can move to Sphinx + MyST.
