### ISSUE TITLE
docs.lfortran.org missing style sheets

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#624]
Here is how it looks like to me:

<img width="1058" alt="Screen Shot 2022-08-18 at 7 02 50 PM" src="https://user-images.githubusercontent.com/20568/185453509-bd010c67-0c76-443f-ab49-f7f986de01d2.png">

**Comment by certik** [comment]
I think I know what it is --- it's missing the `.nojekyll` thing.

**Comment by certik** [comment]
Trying to fix it with https://github.com/lfortran/docs.lfortran.org/commit/e3c3a03b823e6140403e27391284fb63cf2dea38

**Comment by certik** [comment]
Did not work, but also trying 231a6e3f8528c4f69caab24ae6c7801d80f56d7f.

**Comment by Shaikh-Ubaid** [comment]
I guess, the `.nojekyll` should be inside the `docs` directory.

**Comment by certik** [comment]
One more try: https://github.com/lfortran/docs.lfortran.org/commit/33654d299add037bbb925a3c5594c08412d8ce03

**Comment by Shaikh-Ubaid** [comment]
It looks great!
![image](https://user-images.githubusercontent.com/43722035/185456962-95dd2365-a839-4e01-8e6d-a801388217fb.png)

**Comment by certik** [comment]
Thanks @Shaikh-Ubaid !
