### ISSUE TITLE
build: static zlib option in cmake 3.24

### ISSUE THREAD

**Issue by gnikit** [lfortran/lfortran#644]
FYI in CMake v3.24 a flag has been added that effectively does what `FindStaticZLIB.cmake` does.
Should this be included in PR #69 ?

See https://cmake.org/cmake/help/latest/module/FindZLIB.html

> New in version 3.24: Set ZLIB_USE_STATIC_LIBS to ON to look for static libraries. Default is OFF.

**Comment by certik** [comment]
We would have to update all our scripts to use this new cmake. I would wait some time, until this version is more widely used, assuming our current approach works well.

**Comment by awvwgk** [comment]
Is there any advantage from the new zlib finder, which currently doesn't work with our custom wrapper? In this case we could have a version check on the CMake version and use the new finder if available, otherwise our custom one.

**Comment by gnikit** [comment]
Sure, that makes sense. I would just note that in the current CMake scripts sometimes the current minimum version used is not correct. We implicitly use 3.19 but we enforce 3.12 or 3.16 if I recall.

-----

@awvwgk I don't think there is any difference for us. 

Do you happen to remember why you had to enforce zlib to be static?

**Comment by awvwgk** [comment]
> Do you happen to remember why you had to enforce zlib to be static?

I think there was an issue with the LLVM + zlib detection, see https://gitlab.com/lfortran/lfortran/-/issues/424.

**Comment by certik** [comment]
I can't remember why we used static, but LLVM essentially has to be linked statically, and it make it easier to distribute the LFortran binary if we link things statically. If this is a big problem, we can make it configurable.

**Comment by gnikit** [comment]
No it's okay @certik. I think everything works fine as it is. I'll leave this open (more like a TODO) for if/when you decide to implement this.
