### ISSUE TITLE
[SciPy]: tokenizer error: End of file inside a do loop 2

### ISSUE THREAD

**Issue by Smit-create** [lfortran/lfortran#673]
```
% lfortran --fixed-form --implicit-typing --show-asr scipy/optimize/cobyla/cobyla2.f
tokenizer error: End of file inside a do loop 2
   --> scipy/optimize/cobyla/cobyla2.f:267:7
    |
267 |       DO 240 K=1,MP
    |       ^^^^ 

```

**Comment by konradha** [comment]
This should be fixed with recent [6cf0d96](https://github.com/lfortran/lfortran/commit/6cf0d96205cf47fc6cc63909bb75bfc002f1694f) -- please ping me if this error occurs still.

**Comment by konradha** [comment]
@Smit-create if you encounter more of these cases, please add them to #679

**Comment by konradha** [comment]
Can be considered done as of 37492194ffc7517d8a3b3eec15f6c1571728ab02
