### ISSUE TITLE
[SciPy]: Missing intrinsic ```fpched```

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#689]
on executing ```lfortran --show-asr --fixed-form --implicit-typing ../scipy/scipy/interpolate/fitpack/concur.f```
results in 
```
semantic error: Function 'fpched' not found or not implemented yet (if it is intrinsic)
   --> /home/pranavchiku/scipy/scipy/interpolate/fitpack/concur.f:333:7
    |
333 |       call fpched(u,m,t,n,k,ib,ie,ier)
    |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

**Comment by Pranavchiku** [comment]
This looks similar to #615 , but it is throwing ```Segmentation fault (core dumped)```

**Comment by konradha** [comment]
For this, a stub should be created (implicit procedure ?) as it is _not_ an intrinsic (definition in ` scipy/interpolate/fitpack/fpched.f ` )
