### ISSUE TITLE
[SciPy]: Assign ```complex``` to ```integer```

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#701]
```
semantic error: Type mismatch in assignment, the types must be compatible
   --> /home/pranavchiku/scipy/scipy/linalg/src/id_dist/src/idzr_aid.f:105:9
    |
105 |         l = w(1)
    |         ^   ^^^^ type mismatch (integer and complex)
```
Here ```l``` is ```integer``` and ```w``` is ```complex*16``` defined as ```complex*16 w(k)```

**Comment by Pranavchiku** [comment]
Should we assign real part of complex number to integer?

**Comment by konradha** [comment]
- This is a double precision complex vector, I'm not sure this is supported at all.
- I guess this should either be `floor(complex_real_part)` or the integer of the magnitude.

**Comment by Pranavchiku** [comment]
Okay!

**Comment by Pranavchiku** [comment]
```
semantic error: Type mismatch in assignment, the types must be compatible
  --> /home/pranavchiku/scipy/scipy/linalg/src/id_dist/src/idzp_aid.f:79:9
   |
79 |         n2 = work(2)
   |         ^^   ^^^^^^^ type mismatch (integer and complex)

```

**Comment by konradha** [comment]
`COMPLEX` should be the more general type and we'd need to adhere to the Fortran standard -- would you mind chiming in @certik ?

**Comment by konradha** [comment]
gfortran has `__convert_c4_i4` or `__convert_c8_i4` in this case. While I'm not aware of the precise semantics, testing this with the following example

```fortran
program main
complex a
integer k

a = cmplx(1,2)
print *, a
k = a
print *, "convert to integer"
print *, k
end program
```
 yields 

```bash
             (1.00000000,2.00000000)
 convert to integer
           1
```

so we can assume that converting a complex variable to an integer will result in the integer of the real part of the number.

**Comment by konradha** [comment]
depends on #653

**Comment by konradha** [comment]
#828
