### ISSUE TITLE
[SciPy]: Token ```DOUBLE PRECISION``` unexpected

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#702]
```
syntax error: Token 'doubleprecision' is unexpected here
 --> /home/pranavchiku/scipy/scipy/optimize/cobyla/trstlp.f:4:16
  |
4 |       IMPLICIT DOUBLE PRECISION (A-H,O-Z)
  |                ^^^^^^^^^^^^^^^^ 
```

**Comment by konradha** [comment]
I would guess enabling the token as `DOUBLE PRECISION` (with a space) fixes this -- I can hardcode this but I'd need an example that does the error.

**Comment by Pranavchiku** [comment]
Ahh I forgot! Doing that

**Comment by Pranavchiku** [comment]
```

      SUBROUTINE TRSTLP (N,M,A,B,RHO,DX,IFULL,IACT,Z,ZDOTA,VMULTC,
     1  SDIRN,DXNEW,VMULTD,IPRINT)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      end
```

**Comment by Pranavchiku** [comment]
@konradha this produces the same error, I hope it helps :)

**Comment by konradha** [comment]
Ok I understood now -- we don't currently support this: `IMPLICIT DOUBLE PRECISION (A-H,O-Z)` makes all implicitly declared variables take double precision by default -- we'll have to enable this option within the ASR, I guess.

**Comment by Pranavchiku** [comment]
Okay

**Comment by konradha** [comment]
You would need to set a flag or general enum that identifies the implicit typing rule (e.g. default `real` but `double precision` as clarified above ...) and identify the places where implicit-typing needs to be adapted depending on this flag. Two references: https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn9v/index.html https://docs.oracle.com/cd/E19957-01/805-4939/z40007365fbc/index.html (obviously non-complete, but I think it's a good starting point).

**Comment by Pranavchiku** [comment]
Yeah sure! :)
