### ISSUE TITLE
[SciPy]: ```--show-asr``` halting on execution

### ISSUE THREAD

**Issue by Pranavchiku** [lfortran/lfortran#709]
File: ```scipy/linalg/src/id_dist/src/idd_frm.f```
Halts on executing to: ```/src/bin/lfortran --show-asr --implicit-typing --allow-implicit-interface --fixed-form /home/pranavchiku/scipy/scipy/linalg/src/id_dist/src/idd_frm.f```

**Comment by Smit-create** [comment]
I think the issue is with the `--show-ast`. `--show-ast` halts for me which means ASR won't be generated until we have AST.

**Comment by Pranavchiku** [comment]
Yeah!

**Comment by konradha** [comment]
No, that's unfortunately not the issue. The fixed form parser currently does not tokenize `STOP` -- should get fixed with #695

**Comment by Pranavchiku** [comment]
Ohh okay :)

**Comment by konradha** [comment]
This is fixed. We should verify the ASR generated for `scipy/linalg/src/id_dist/src/idd_frm.f` though.
