### ISSUE TITLE
Implement Julia backend

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#725]
It has been requested many times to be able to convert Fortran to Julia. We just need an ASR to Julia backend. To do that, we just need to generate Julia source code from ASR, similar how the C and C++ backends do that:

* https://github.com/lfortran/lfortran/blob/main/src/libasr/codegen/asr_to_c_cpp.h
* https://github.com/lfortran/lfortran/blob/main/src/libasr/codegen/asr_to_cpp.cpp
* https://github.com/lfortran/lfortran/blob/main/src/libasr/codegen/asr_to_c.cpp

But just one file `asr_to_julia.h/cpp` and it would generate nice readable Julia code.

**Comment by lucifer1004** [comment]
This would be awesome!

**Comment by lucifer1004** [comment]
@certik Maybe we can close this issue, or rename it and use it as a dashboard for Julia related issues?

**Comment by certik** [comment]
This has been fixed by https://github.com/lfortran/lfortran/pull/735. We can open up new issues for things to fix or improve.
