### ISSUE TITLE
LFortran CLI should check source file existence

### ISSUE THREAD

**Issue by lucifer1004** [lfortran/lfortran#740]
Currently, the CLI can run even when the specified file does not exist. I think it is better to report an error in that case, in order not to mislead the user.

For example, 

```
./lfortran --show-asr non-exist.f90
```

yields

```
(TranslationUnit (SymbolTable 1 {}) [])
```

instead of reporting an error.

**Comment by certik** [comment]
Yes! I've been burned by this too. Do you want to submit a PR? That should be easy to fix.

**Comment by lucifer1004** [comment]
@certik Can we use `std::filesystem::exists` (which requires C++17)?

**Comment by certik** [comment]
The `std::filesystem` failed on Windows for us last time we tried it.
