### ISSUE TITLE
Question: funding lfortran

### ISSUE THREAD

**Issue by adam-urbanczyk** [lfortran/lfortran#743]
lfortran.org or this repo do not mention anything about funding lfortran. Is it on purpose that this open collective is not mentioned https://opencollective.com/lfortran ? Are there other alternatives?

**Comment by certik** [comment]
We need to add it to our README and a webpage, thanks for the reminder. Here are the two main links:

* https://numfocus.org/donate-to-lfortran
* https://opencollective.com/lfortran
