### ISSUE TITLE
Implement DATA in the body of a function

### ISSUE THREAD

**Issue by certik** [lfortran/lfortran#778]
SciPy uses DATA in the body of a function, such as:
```fortran
 35         CONTINUE
 40         BY1=RP2*(EC*BJ1-1.0D0/X-0.25D0*X*CS1)
         ELSE
           DATA A/-.7031250000000000D-01,.1121520996093750D+00,
     &            -.5725014209747314D+00,.6074042001273483D+01,
     &            -.1100171402692467D+03,.3038090510922384D+04,
     &            -.1188384262567832D+06,.6252951493434797D+07,
     &            -.4259392165047669D+09,.3646840080706556D+11,
     &            -.3833534661393944D+13,.4854014686852901D+15/
```
LFortran can currently only parse it if the DATA is among the declarations.

**Comment by certik** [comment]
PR #799 allows to parse this, but currently ignores the DATA (and other) declarations inside the if statement. We have to decide how to include it in AST and add it to AST and to the fmt printer. After that this issue will be fixed. Until then we'll keep this issue open so that we do not forget.

**Comment by awvwgk** [comment]
Consider the following minimal example

```
❯ cat test.f90
real :: a(5)
print *, a
data a /1, 2, 3, 4, 5/
end
❯ gfortran test.f90 && ./a.out
   1.00000000       2.00000000       3.00000000       4.00000000       5.00000000
```

The `data` declaration should be collected with the rest of the declarations and initialized when entering the parent scope.

**Comment by certik** [comment]
This particular example works with LFortran also, as we collect DATA and put it into declarations. But not nested in IFs.

See https://github.com/lfortran/lfortran/pull/799#issuecomment-1261254674.

What is the semantics in an If statement -- does it only get executed when the if runs?

**Comment by awvwgk** [comment]
> What is the semantics in an `if` statement -- does it only get executed when the if runs?

The sematics remains unchanged from the `if` statement as it is the same scope. See https://github.com/lfortran/lfortran/pull/799#issuecomment-1261274317 for an example which should clarify things.
