### ISSUE TITLE
LCompilersException: `visit_Format()` not implemented

### ISSUE THREAD

**Issue by Smit-create** [lfortran/lfortran#826]
Example code:
```fortran
% cat a.f90 
SUBROUTINE CVOUT( LOUT, IFMT )
      INTEGER            LOUT
      CHARACTER          IFMT*( * )
      INTEGER            I, LLL
      CHARACTER*80       LINE
      WRITE( LOUT, 9999 )IFMT, LINE( 1: LLL )
 9999 FORMAT( / 1X, A / 1X, A )
END
```

Error:
```
void visit_Format(const Format_t & /* x */) { throw LFortran::LCompilersException("visit_Format() not implemented"); }
LCompilersException: visit_Format() not implemented
```

The example was originally taken from: `scipy/sparse/linalg/_eigen/arpack/ARPACK/UTIL/cvout.f`

**Comment by Smit-create** [comment]
This error is raised by most of the files under` scipy/sparse/linalg/_eigen/arpack/ARPACK/UTIL/*`

**Comment by certik** [comment]
Yes, format is not implemented yet. That is a bigger feature. For now we can just print a warning ("Format not implemented yet, we ignore it for now") and just ignore it. The write (todo) and print (done) we then implement without format for now.

**Comment by HarshitaKalani** [comment]
I believe it works with the latest main:
```console
$ gfortran a.f90 && ./a.out
$ lfortran a.f90
style suggestion: Use character(80) instead of character*80
 --> a.f90:5:7
  |
5 |       CHARACTER*80       LINE
  |       ^^^^^^^^^^^^ help: write this as 'character(80)'


Note: Please report unclear or confusing messages as bugs at
https://github.com/lfortran/lfortran/issues.`
```

**Comment by certik** [comment]
Yes, I think this is fixed and we have tests for this, so I am closing this.
