### ISSUE TITLE
I try compile 3rd party Fortran codes but no error message and no result

### ISSUE THREAD

**Issue by xichaoqiang** [lfortran/lfortran#873]
Hello,

Thanks for sharing this great package.

I install lfortran in CentOS7 from github.

test_lfortran_cmdline works well, all tests succeeded.

I want try lfortran to convert an .f code to .f90.

My .f file is download from https://github.com/miili/pysurf96/blob/master/src/surfdisp96.f   

This is a standalone code.

I have comment blank rows.

![image](https://user-images.githubusercontent.com/30900789/194731835-53794008-7c32-4055-ac77-c42b46f80acb.png)

I run the following command. I have been waiting for hours. But not result or error message show.

![image](https://user-images.githubusercontent.com/30900789/194731849-9b42c48d-a45b-45e2-8e90-f6bc135e6bc8.png)

Best regards,
Xi

**Comment by certik** [comment]
Thanks for the report! I noticed a few bugs:

* the fixed-form tokenizer can't handle `\r\n` line endings. Workaround: just convert your file to just use `\n` for now
* it can't handle implicit statements after parameter statements, I just manually swapped them

After the two workarounds, here is the f90 file that LFortran produces: https://gist.github.com/certik/3c0e17a1a8b9ec44747d44385e42696a

Let me know if it works.

Btw, LFortran should never hang like this, everything should be finished in a fraction of a second, so any hangs are bugs.

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.

**Comment by xichaoqiang** [comment]
@certik Sorry for my later reply.

The f90 can compile. But it seems the result will different sometimes. 

 There are two demos in the pysurf96 package.

The first demo result is correct. Upper is f90, lower is raw f77.
![image](https://user-images.githubusercontent.com/30900789/196074210-a1eda275-105d-4732-8c34-03b20c6cece5.png)

The second demo result is different. Upper is f90, lower is raw f77.

![image](https://user-images.githubusercontent.com/30900789/196074308-d01c5e69-580b-44b7-a282-e722bc4febd6.png)

**Comment by xichaoqiang** [comment]
@certik I  found the bug. The convert lost brackets. If I add the brackets. The results will become correct.

In the f77 file.

![无标题1](https://user-images.githubusercontent.com/30900789/196118327-fd72c846-6291-4342-ad90-ab9925141cd3.png)


But in the f90 file.

![image](https://user-images.githubusercontent.com/30900789/196117372-6b3eeb42-c8bf-4e78-a00d-29bfcd7b8d74.png)

**Comment by certik** [comment]
Ha, I think that's a bug! Thanks a lot for finding it. Here is a small reproducer:
```console
$ cat a.f90 
e = 1/(a*b)
$ lfortran --show-ast a.f90 
(TranslationUnit [(= 0 e (/ 1 (* a b)) ())])
$ lfortran fmt a.f90       
e = 1/a*b
```
The AST is correct, but the AST->SRC is incorrect.

**Comment by certik** [comment]
@xichaoqiang this should be fixed by https://github.com/lfortran/lfortran/pull/922. The rules for when to use parentheses are quite complex. Hopefully this fixes it. If you discover any other problem, please report it!

**Comment by certik** [comment]
I opened up issues for the two missing features:

* #924
* #925

That should be it.
