### ISSUE TITLE
lfortran always runs if `-o a.out`

### ISSUE THREAD

**Issue by meow464** [lfortran/lfortran#923]
Steps to reproduce:
```
lfortran hellow_world.f90 -o a.out
Hello World!
```

Seems to be caused by [line 1236 here](https://github.com/lfortran/lfortran/pull/854/files#diff-c0399703ff87e80a2de3aa22a1a199f6717cfdc00e7cfd997d981a3642fd54deR1236)

It would be good to document that -o disables auto run.

Suggestion: move arg_o inside CompilerOptions since emit_lang() functions already receive it anyways.

CC: @Thirumalai-Shaktivel

**Comment by certik** [comment]
Yes, `-o` should disable auto run. Thanks for noticing that.
