### ISSUE TITLE
Conjg breaks for huge numbers

### ISSUE THREAD

**Issue by sloorush** [lfortran/lfortran#980]
First, I don't know C++, so maybe I'm missing something.  But, how does this work with `x = cmplx(huge(x%re), 1.)`   The complex conjugate of `x` would be `cmplx(huge(x%re), -1.)`.  The multiplication of `2 * real(x)` overflows to +inf.

```
function conjgz64(x) result(r)
    complex(dp) :: x
   complex(dp) :: r
   r=-x+2*real(x)
end function
```

A correct implementation would be

```
function conjgz64(x) result(r)
    complex(dp) :: x
    complex(dp) :: r
    r=cmplx(x%re, -x%im)
end function
```

_Originally posted by @kargl in https://github.com/lfortran/lfortran/issues/964#issuecomment-1301647963_

**Comment by sloorush** [comment]
Using `cmplx(x%re, -x%im)` or `cmplx(real(x), -aimag(x))` both give the same result:
```
❯ lfortran integration_tests/complex_10.f90
code generation error: ComplexConstructor with runtime arguments not implemented yet.


Note: if any of the above error or warning messages are not clear or are lacking
context please report it to us (we consider that a bug that needs to be fixed).
```

@certik Any clue where I should look to perfectly fix this?

**Comment by certik** [comment]
@sloorush you would have to give me more context what you are trying to do. The latest LFortran can compile and run that example:
```console
$ lfortran integration_tests/complex_10.f90 
(3.000000,-4.000000) (3.000000,4.000000)
```

**Comment by certik** [comment]
@sloorush I fixed this in https://github.com/lfortran/lfortran/pull/986. But what you can do is implement `cmplx(real(x), -aimag(x))`, I think we now have all the pieces to get it done.

**Comment by sloorush** [comment]
> That gives you a full stacktrace where the error is coming from.

Got it! I'll look into this
